import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Pinned from Mobilize's official v1 API reference on 2026-07-18. */
export const MOBILIZE_OPERATIONS = [
  {
    id: "list_organizations",
    method: "GET",
    path: "/organizations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    omitAuthorization: true,
    description: "List active public Mobilize organizations",
  },
  {
    id: "list_promoted_organizations",
    method: "GET",
    path: "/organizations/{organization_id}/promoted_organizations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List organizations promoted by the connected organization",
  },
  {
    id: "get_public_event",
    method: "GET",
    path: "/events/{event_id}",
    pathParameters: ["event_id"],
    mutating: false,
    bodyAllowed: false,
    omitAuthorization: true,
    description: "Get one public event without privileged fields",
  },
  {
    id: "list_organization_events",
    method: "GET",
    path: "/organizations/{organization_id}/events",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List events owned or promoted by the connected organization",
  },
  {
    id: "get_organization_event",
    method: "GET",
    path: "/organizations/{organization_id}/events/{event_id}",
    pathParameters: ["event_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get one owned or promoted organization event",
  },
  {
    id: "list_deleted_organization_events",
    method: "GET",
    path: "/organizations/{organization_id}/events/deleted",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List deleted organization events",
  },
  {
    id: "list_organization_people",
    method: "GET",
    path: "/organizations/{organization_id}/people",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List people affiliated with the connected organization",
  },
  {
    id: "get_organization_attendance",
    method: "GET",
    path: "/organizations/{organization_id}/attendances/{attendance_id}",
    pathParameters: ["attendance_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get one organization attendance",
  },
  {
    id: "list_organization_attendances",
    method: "GET",
    path: "/organizations/{organization_id}/attendances",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List organization attendances",
  },
  {
    id: "list_event_attendances",
    method: "GET",
    path: "/organizations/{organization_id}/events/{event_id}/attendances",
    pathParameters: ["event_id"],
    mutating: false,
    bodyAllowed: false,
    description: "List attendances for one organization event",
  },
  {
    id: "get_enums",
    method: "GET",
    path: "/enums",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    omitAuthorization: true,
    description: "Get current public API enum values",
  },
  {
    id: "create_event",
    method: "POST",
    path: "/organizations/{organization_id}/events",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create an event for the connected organization",
  },
  {
    id: "update_event",
    method: "PUT",
    path: "/organizations/{organization_id}/events/{event_id}",
    pathParameters: ["event_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Replace editable fields on an organization event",
  },
  {
    id: "delete_event",
    method: "DELETE",
    path: "/organizations/{organization_id}/events/{event_id}",
    pathParameters: ["event_id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete an organization event",
  },
  {
    id: "create_event_attendance",
    method: "POST",
    path: "/organizations/{organization_id}/events/{event_id}/attendances",
    pathParameters: ["event_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create one or more event attendances for a person",
  },
  {
    id: "create_or_update_affiliation",
    method: "POST",
    path: "/organizations/{organization_id}/affiliations",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description:
      "Create an organization affiliation or update the matched person",
  },
  {
    id: "upload_event_image",
    method: "POST",
    path: "/images",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    bodyEncoding: "multipart_image_base64",
    description: "Upload one bounded event image",
  },
] as const satisfies readonly BoundedRestOperation[];

export const MOBILIZE_PUBLIC_READ_OPERATION_IDS = [
  "list_organizations",
  "list_promoted_organizations",
  "get_public_event",
  "get_enums",
] as const;

export const MOBILIZE_SENSITIVE_READ_OPERATION_IDS = [
  "list_organization_events",
  "get_organization_event",
  "list_deleted_organization_events",
  "list_organization_people",
  "get_organization_attendance",
  "list_organization_attendances",
  "list_event_attendances",
] as const;

export const MOBILIZE_MANAGE_OPERATION_IDS = MOBILIZE_OPERATIONS.filter(
  (item) => item.mutating,
).map((item) => item.id);

export const MOBILIZE_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "mobilize",
  name: "Mobilize",
  baseUrl: "https://api.mobilize.us/v1/",
  credentialName: "MOBILIZE_API_KEY",
  authorization: { headerName: "Authorization", prefix: "Bearer " },
  pathCredentials: [
    {
      placeholder: "organization_id",
      credentialName: "MOBILIZE_ORGANIZATION_ID",
    },
  ],
  operations: MOBILIZE_OPERATIONS,
  health: { operationId: "list_promoted_organizations" },
};
