import { safeConnectorFetch } from "../safe-connector-fetch";
import { Injectable } from "@nestjs/common"; import type { MarketplaceConnectorSafeErrorCode } from "../types";
type JsonObject = Record<string, unknown>; export type BrevoCredentials = { apiKey: string; senderBoundary: string };
export class BrevoApiError extends Error { constructor(public readonly code: MarketplaceConnectorSafeErrorCode, message: string, public readonly statusCode?: number) { super(message); } }
@Injectable() export class BrevoApiAdapter {
  health(credentials: BrevoCredentials) { return this.getAccount(credentials); }
  getAccount(credentials: BrevoCredentials) { return this.request(credentials, { method: "GET", path: "/account" }); }
  listSenders(credentials: BrevoCredentials) { return this.request(credentials, { method: "GET", path: "/senders" }); }
  listTemplates(credentials: BrevoCredentials, input: JsonObject) { return this.request(credentials, { method: "GET", path: "/smtp/templates", query: { limit: this.clamp(input.limit, 50, 1, 100), offset: this.clamp(input.offset, 0, 0, 10000), templateStatus: typeof input.templateStatus === "boolean" ? input.templateStatus : undefined } }); }
  sendTransactionalEmail(credentials: BrevoCredentials, input: JsonObject) { const message = this.object(input.message); if (!message) throw new BrevoApiError("provider_validation_error", "message is required"); this.assertMessage(message, credentials.senderBoundary); return this.request(credentials, { method: "POST", path: "/smtp/email", json: message }); }
  async request(credentials: BrevoCredentials, input: { method: string; path: string; query?: JsonObject; json?: JsonObject | unknown[] }) {
    const method = input.method.toUpperCase(); if (!/^(GET|POST|PUT|PATCH|DELETE)$/.test(method) || !input.path.startsWith("/") || input.path.startsWith("//") || input.path.includes("..") || input.path.includes("://") || input.path.startsWith("/v3/")) throw new BrevoApiError("provider_validation_error", "Brevo method or path is invalid."); this.rejectSecrets(input.query); this.rejectSecrets(input.json);
    if (method === "POST" && input.path.replace(/\/$/, "") === "/smtp/email") { const message = this.object(input.json); if (!message) throw new BrevoApiError("provider_validation_error", "Brevo transactional email must be an object."); this.assertMessage(message, credentials.senderBoundary); }
    const body = input.json === undefined ? undefined : JSON.stringify(input.json); if (body && Buffer.byteLength(body) > 25 * 1024 * 1024) throw new BrevoApiError("provider_validation_error", "Brevo request exceeds the bounded 25 MB envelope."); const url = new URL(`https://api.brevo.com/v3${input.path}`); this.append(url.searchParams, input.query); const response = await safeConnectorFetch(url, { method, headers: { "api-key": credentials.apiKey, Accept: "application/json", "Content-Type": "application/json" }, body }); const raw = await response.text(); const text = raw.slice(0, 512_000); let parsed: unknown = text; try { parsed = text ? JSON.parse(text) : null; } catch { parsed = text; } const safe = this.redact(parsed); if (!response.ok) throw new BrevoApiError(this.code(response.status), this.message(safe) ?? `Brevo returned ${response.status}`, response.status); return { status: response.status, data: safe, rateLimit: { limit: response.headers.get("x-sib-ratelimit-limit"), remaining: response.headers.get("x-sib-ratelimit-remaining"), reset: response.headers.get("x-sib-ratelimit-reset") }, truncated: raw.length > text.length };
  }
  private assertMessage(message: JsonObject, boundary: string) { const sender = this.object(message.sender); const email = this.string(sender?.email); if (!email || !this.allowed(email, boundary)) throw new BrevoApiError("sender_identity_not_approved", `An explicit sender matching ${boundary} is required, including for templates.`); const versions = Array.isArray(message.messageVersions) ? message.messageVersions : []; if (versions.some((entry) => { const object = this.object(entry); return !object || !Array.isArray(object.to) || object.to.length > 99; })) throw new BrevoApiError("provider_validation_error", "Each Brevo message version permits at most 99 recipients."); const base = [message.to, message.cc, message.bcc].reduce<number>((sum, value) => sum + (Array.isArray(value) ? value.length : 0), 0); const versionRecipients = versions.reduce<number>((sum, entry) => sum + ((this.object(entry)?.to as unknown[] | undefined)?.length ?? 0), 0); const total = versions.length ? versionRecipients : base; if (total < 1 || total > 2000) throw new BrevoApiError("provider_validation_error", "Brevo transactional email must contain 1 to 2000 recipients."); if (Buffer.byteLength(JSON.stringify(message)) > 25 * 1024 * 1024) throw new BrevoApiError("provider_validation_error", "Brevo email exceeds the bounded 25 MB envelope."); }
  private allowed(email: string, boundary: string) { const normalized = boundary.toLowerCase().replace(/^@/, ""); return normalized.includes("@") ? email.toLowerCase() === normalized : email.toLowerCase().endsWith(`@${normalized}`); }
  private rejectSecrets(value?: JsonObject | unknown[]) { if (!value) return; const walk = (entry: unknown) => { if (Array.isArray(entry)) return entry.forEach(walk); const object = this.object(entry); if (!object) return; for (const [key, child] of Object.entries(object)) { if (/(api.?key|partner.?key|password|secret|authorization|credential|token)/i.test(key)) throw new BrevoApiError("policy_blocked", `Credential-bearing field ${key} is not allowed.`); walk(child); } }; walk(value); }
  private append(params: URLSearchParams, value?: JsonObject) { if (!value) return; for (const [key, entry] of Object.entries(value)) if (entry !== undefined && entry !== null) params.append(key, String(entry)); }
  private redact(value: unknown): unknown { if (Array.isArray(value)) return value.slice(0, 500).map((entry) => this.redact(entry)); const object = this.object(value); if (!object) return value; const result: JsonObject = {}; for (const [key, entry] of Object.entries(object).slice(0, 500)) result[key] = /(^key$|api.?key|partner.?key|tracker.?key|password|secret|authorization|credential|token)/i.test(key) ? "[REDACTED]" : this.redact(entry); return result; }
  private message(value: unknown) { const object = this.object(value); return this.string(object?.message) ?? this.string(object?.error); } private code(status: number): MarketplaceConnectorSafeErrorCode { if (status === 401) return "credential_missing"; if (status === 403) return "insufficient_scope"; if (status === 429) return "provider_rate_limited"; if (status >= 500) return "provider_unavailable"; return "provider_validation_error"; } private string(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : null; } private object(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonObject : null; } private clamp(value: unknown, fallback: number, min: number, max: number) { const number = Number(value ?? fallback); return Number.isFinite(number) ? Math.min(Math.max(Math.floor(number), min), max) : fallback; }
}
