import { action, capability } from "../../catalog/marketplace-catalog.types"; import type { MarketplaceConnectorManifest } from "../types";
const reads = [action("brevo_read_account", "Read account", "Read bounded Brevo account and plan metadata."), action("brevo_read_senders", "Read senders", "List bounded sender metadata."), action("brevo_read_templates", "Read templates", "List bounded transactional template metadata.")];
const writes = [action("brevo_send_email", "Send transactional email", "Sending requires approval in Safe mode."), action("brevo_full_api", "Use full Brevo API", "Any other Brevo v3 operation requires approval in Safe mode.")];
export const BREVO_CONNECTOR_MANIFEST: MarketplaceConnectorManifest = {
  slug: "brevo", name: "Brevo", connectorType: "native_clawchat", providerDocsUrl: "https://developers.brevo.com/reference/getting-started-1", providerWebsiteUrl: "https://www.brevo.com",
  capabilities: [
    { ...capability("account", "Account", "Read bounded account and plan metadata.", true), platformCapability: "email_account_profile" },
    { ...capability("senders", "Senders", "List bounded verified sender metadata.", true), platformCapability: "email_sender_identities" },
    { ...capability("templates", "Templates", "List bounded transactional template metadata.", true), platformCapability: "email_templates" },
    { ...capability("send", "Transactional email", "Send through the bound verified sender.", true), platformCapability: "email_send" },
    { ...capability("full_api", "Full Brevo v3 API", "Use all Brevo endpoints authorized by the customer-owned API key.", false), platformCapability: "brevo_full_api" },
  ],
  auth: { type: "api_key", credentialSchema: [
    { name: "BREVO_API_KEY", label: "Brevo API key", required: true, secret: true, storedIn: "encrypted_secret", requiredForAuthTypes: ["api_key"], helpText: "Generate a customer-owned API key in Brevo SMTP & API settings." },
    { name: "BREVO_SENDER_BOUNDARY", label: "Verified sender boundary", required: true, secret: false, storedIn: "encrypted_secret", requiredForAuthTypes: ["api_key"], helpText: "An exact registered sender email or authenticated domain." },
  ] },
  tools: [
    { name: "brevo.getAccount", functionName: "brevo_get_account", aliases: ["brevo.getAccount", "brevo_get_account"], capability: "account", platformCapability: "email_account_profile", action: "read", approvalRequired: false, description: "Read bounded Brevo account and plan metadata; tracker/API secrets are redacted.", inputSchema: emptySchema() },
    { name: "brevo.listSenders", functionName: "brevo_list_senders", aliases: ["brevo.listSenders", "brevo_list_senders"], capability: "senders", platformCapability: "email_sender_identities", action: "read", approvalRequired: false, description: "List bounded Brevo sender metadata.", inputSchema: emptySchema() },
    { name: "brevo.listTemplates", functionName: "brevo_list_templates", aliases: ["brevo.listTemplates", "brevo_list_templates"], capability: "templates", platformCapability: "email_templates", action: "read", approvalRequired: false, description: "List bounded transactional template metadata.", inputSchema: { type: "object", properties: { limit: { type: "number", minimum: 1, maximum: 100, default: 50 }, offset: { type: "number", minimum: 0, default: 0 }, templateStatus: { type: "boolean" } }, additionalProperties: false } },
    { name: "brevo.sendTransactionalEmail", functionName: "brevo_send_transactional_email", aliases: ["brevo.sendTransactionalEmail", "brevo_send_transactional_email", "email_send"], capability: "send", platformCapability: "email_send", action: "write", approvalRequired: true, description: "Send through the bound verified sender with provider limits enforced.", inputSchema: { type: "object", properties: { message: { type: "object" }, approvalId: { type: "string" } }, required: ["message"], additionalProperties: false } },
    { name: "brevo.request", functionName: "brevo_request", aliases: ["brevo.request", "brevo_request", "brevo_full_api"], capability: "full_api", platformCapability: "brevo_full_api", action: "admin", approvalRequired: true, description: "Call a Brevo v3 endpoint at the fixed official origin; caller credentials are rejected.", inputSchema: { type: "object", properties: { method: { type: "string", enum: ["GET", "POST", "PUT", "PATCH", "DELETE"] }, path: { type: "string", pattern: "^/" }, query: { type: "object" }, json: { type: ["object", "array"] }, approvalId: { type: "string" } }, required: ["method", "path"], additionalProperties: false } },
  ], approvalProfiles: [{ id: "brevo_safe", label: "Safe", description: "Bounded reads run directly; sends and every other v3 API operation require approval.", defaultSelected: true, allowedActions: reads, approvalRequiredActions: writes, blockedActions: [] }], healthChecks: [{ id: "account", label: "Brevo API-key account check" }],
}; function emptySchema() { return { type: "object", properties: {}, additionalProperties: false }; }
