export const LEMON_SQUEEZY_ENDPOINT_FAMILIES = [
  { id: "auth", label: "API Authentication", docsUrl: "https://docs.lemonsqueezy.com/guides/developer-guide/getting-started", guidance: "Use Bearer API keys with JSON:API headers. Keep API keys and webhook signing secrets in ClawChat connections only." },
  { id: "stores_catalog", label: "Stores Products Variants Prices Files", docsUrl: "https://docs.lemonsqueezy.com/api", guidance: "Read stores, products, variants, prices, and files. Variant/file/download changes affect purchases and entitlements and require approval." },
  { id: "orders_customers", label: "Orders Customers Invoices", docsUrl: "https://docs.lemonsqueezy.com/api/orders/the-order-object", guidance: "Read orders and customers with minimized data. Order/subscription invoice refunds and invoice generation require approval." },
  { id: "subscriptions", label: "Subscriptions Usage", docsUrl: "https://docs.lemonsqueezy.com/guides/developer-guide/managing-subscriptions", guidance: "Read subscription lifecycle. Plan changes, cancellations, resumptions, pauses, prorations, invoice-immediate changes, and usage records require approval." },
  { id: "licenses", label: "Licenses License API", docsUrl: "https://docs.lemonsqueezy.com/api/license-api", guidance: "Read license keys and instances. Activation, validation, deactivation, activation limits, and entitlement changes require approval when they affect access." },
  { id: "checkouts_discounts", label: "Checkouts Discounts", docsUrl: "https://docs.lemonsqueezy.com/guides/developer-guide/taking-payments", guidance: "Checkout links and discounts are customer-facing commerce actions and require approval before creation or deletion." },
  { id: "webhooks", label: "Webhooks", docsUrl: "https://docs.lemonsqueezy.com/help/webhooks", guidance: "Use webhook events for orders, subscriptions, customers, and licenses. Webhook configuration changes require approval and secrets must never be exposed." },
  { id: "rate_limits_errors", label: "Rate Limits And Errors", docsUrl: "https://docs.lemonsqueezy.com/api", guidance: "JSON:API endpoints allow 300 calls/minute with rate-limit headers; License API allows 60 calls/minute." },
];
