import { Injectable } from "@nestjs/common";
import { request as httpsRequest } from "node:https";
import type { MarketplaceConnectorSafeErrorCode } from "../types";

type JsonObject = Record<string, unknown>;
export type TettraCredentials = { teamId: string; apiKey: string };
export class TettraApiError extends Error { constructor(public readonly code: MarketplaceConnectorSafeErrorCode, message: string, public readonly statusCode?: number) { super(message); } }

@Injectable()
export class TettraApiAdapter {
  async search(c: TettraCredentials, input: JsonObject = {}) { return this.call(c, "GET", "search", { query: this.optionalString(input.query, 2000) }); }
  async getCategoryItems(c: TettraCredentials, input: JsonObject) { return this.call(c, "GET", `categories/${this.id(input.categoryId, "categoryId")}`, {}); }
  async createPage(c: TettraCredentials, input: JsonObject) { return this.call(c, "POST", "pages", { title: this.str(input.title, "title", 500), body: this.str(input.body, "body", 200000), category_id: this.optionalId(input.categoryId), subcategory_id: this.optionalId(input.subcategoryId) }); }
  async updatePage(c: TettraCredentials, input: JsonObject) { const pageId = this.id(input.pageId, "pageId"); const body = this.compact({ owner_id: this.optionalId(input.ownerId), title: this.optionalString(input.title, 500), body: this.optionalString(input.body, 200000), category_id: this.optionalId(input.categoryId), subcategory_id: this.optionalId(input.subcategoryId) }); if (!Object.keys(body).length) throw new TettraApiError("provider_validation_error", "Tettra page update requires at least one changed field."); return this.call(c, "PATCH", `pages/${pageId}`, body); }
  async createSuggestion(c: TettraCredentials, input: JsonObject) { const pageId = this.optionalId(input.pageId); const title = this.optionalString(input.title, 500); if (!pageId && !title) throw new TettraApiError("provider_validation_error", "A new suggestion requires title; an update suggestion requires pageId."); return this.call(c, "POST", "suggestions", { update: Boolean(pageId), page_id: pageId, title, description: this.optionalString(input.description, 20000), category: this.optionalId(input.categoryId), assignable_id: this.optionalId(input.assignableId) }); }
  async createQuestion(c: TettraCredentials, input: JsonObject) { const ids = Array.isArray(input.assigneeIds) ? input.assigneeIds.slice(0, 50).map((v) => Number(this.id(v, "assigneeId"))) : undefined; return this.call(c, "POST", "questions", { title: this.str(input.title, "title", 500), details: this.optionalString(input.details, 20000), category_id: this.optionalId(input.categoryId), subcategory_id: this.optionalId(input.subcategoryId), assignees: ids }); }
  async createCategory(c: TettraCredentials, input: JsonObject) { const name = this.str(input.name, "name", 191); if (/[<>]/.test(name)) throw new TettraApiError("provider_validation_error", "Tettra category name cannot contain angle brackets."); return this.call(c, "POST", "categories", { name, description: this.optionalString(input.description, 20000) }); }

  private async call(c: TettraCredentials, method: "GET" | "POST" | "PATCH", suffix: string, input: JsonObject) {
    this.credentials(c); const path = `/api/teams/${c.teamId}/${suffix}`; if (!/^[a-z]+(?:\/\d+)?$/.test(suffix)) throw new TettraApiError("provider_validation_error", "Tettra path is invalid.");
    const body = JSON.stringify({ api_key: c.apiKey, ...this.compact(input) }); if (Buffer.byteLength(body) > 250000) throw new TettraApiError("provider_validation_error", "Tettra request exceeds 250 KB.");
    return await new Promise<unknown>((resolve, reject) => { const req = httpsRequest({ protocol: "https:", hostname: "app.tettra.co", port: 443, method, path, headers: { Accept: "application/json", "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body) }, timeout: 20000 }, (res) => { const chunks: Buffer[] = []; let size = 0; res.on("data", (chunk: Buffer) => { size += chunk.length; if (size > 5_000_000) { req.destroy(); reject(new TettraApiError("provider_validation_error", "Tettra response exceeds 5 MB.")); } else chunks.push(chunk); }); res.on("end", () => { try { resolve(this.parse(res.statusCode ?? 502, Buffer.concat(chunks).toString("utf8"))); } catch (e) { reject(e); } }); }); req.on("timeout", () => req.destroy(new Error("timeout"))); req.on("error", (e) => reject(e instanceof TettraApiError ? e : new TettraApiError("provider_unavailable", "Tettra could not be reached.", 502))); req.write(body); req.end(); });
  }
  private parse(status: number, raw: string) { let data: unknown = raw; try { data = raw ? JSON.parse(raw) : null; } catch { data = raw.slice(0, 5_000_000); } data = this.redact(data); if (status < 200 || status >= 300) throw new TettraApiError(this.safeCode(status), this.message(data) ?? `Tettra returned HTTP ${status}.`, status); return data; }
  private credentials(c: TettraCredentials) { this.id(c.teamId, "teamId"); if (!c.apiKey || c.apiKey.length > 1000) throw new TettraApiError("credential_missing", "Tettra team ID and API key are required.", 401); }
  private compact(v: JsonObject) { return Object.fromEntries(Object.entries(v).filter(([, x]) => x !== undefined && x !== null && x !== "")); }
  private id(v: unknown, name: string) { const s = String(v ?? "").trim(); if (!/^\d{1,20}$/.test(s)) throw new TettraApiError("provider_validation_error", `${name} is invalid.`); return s; }
  private optionalId(v: unknown) { return v === undefined || v === null || v === "" ? undefined : Number(this.id(v, "id")); }
  private str(v: unknown, name: string, max: number) { if (typeof v !== "string" || !v.trim() || v.length > max) throw new TettraApiError("provider_validation_error", `${name} is required and must be at most ${max} characters.`); return v.trim(); }
  private optionalString(v: unknown, max: number) { if (v === undefined || v === null || v === "") return undefined; if (typeof v !== "string" || v.length > max) throw new TettraApiError("provider_validation_error", `Tettra field must be at most ${max} characters.`); return v.trim(); }
  private redact(v: unknown, depth = 0): unknown { if (depth > 8) return "[truncated]"; if (typeof v === "string") return v.slice(0, 1_000_000); if (Array.isArray(v)) return v.slice(0, 1000).map((x) => this.redact(x, depth + 1)); if (!v || typeof v !== "object") return v; return Object.fromEntries(Object.entries(v as JsonObject).slice(0, 1000).map(([k, x]) => [k, /(api.?key|token|secret|password|cookie|authorization)/i.test(k) ? "[redacted]" : this.redact(x, depth + 1)])); }
  private message(v: unknown) { const o = v && typeof v === "object" && !Array.isArray(v) ? v as JsonObject : null; const x = o?.message ?? o?.error; return typeof x === "string" ? x.slice(0, 500) : null; }
  private safeCode(s: number): MarketplaceConnectorSafeErrorCode { if (s === 401) return "credential_missing"; if (s === 403) return "insufficient_scope"; if (s === 429) return "provider_rate_limited"; if (s >= 500) return "provider_unavailable"; return "provider_validation_error"; }
}
