import { action, capability } from "../../catalog/marketplace-catalog.types";
import type { MarketplaceConnectorManifest } from "../types";
const reads = [action("sparkpost_read_account", "Read account", "Read bounded account metadata."), action("sparkpost_read_events", "Read message events", "Search a bounded time window of message events."), action("sparkpost_read_metrics", "Read metrics", "Read bounded deliverability metrics.")];
const writes = [action("sparkpost_create_transmission", "Create transmission", "Creating a transmission requires approval in Safe mode."), action("sparkpost_full_api", "Use full SparkPost API", "Any other key-authorized API operation requires approval in Safe mode.")];
export const SPARKPOST_CONNECTOR_MANIFEST: MarketplaceConnectorManifest = {
  slug: "sparkpost", name: "SparkPost", connectorType: "native_clawchat", providerDocsUrl: "https://developers.sparkpost.com/api/", providerWebsiteUrl: "https://www.sparkpost.com",
  capabilities: [
    { ...capability("account", "Account", "Read bounded account metadata when the key grant permits it.", true), platformCapability: "email_account_profile" },
    { ...capability("events", "Message events", "Search bounded delivery and engagement events.", true), platformCapability: "email_delivery_activity" },
    { ...capability("metrics", "Deliverability metrics", "Read bounded deliverability summaries.", true), platformCapability: "email_delivery_metrics" },
    { ...capability("transmissions", "Transmissions", "Create transmissions through the bound sender domain.", true), platformCapability: "email_send" },
    { ...capability("full_api", "Full SparkPost API", "Use all endpoints authorized by the customer key within its region and subaccount.", false), platformCapability: "sparkpost_full_api" },
  ],
  auth: { type: "api_key", credentialSchema: [
    { name: "SPARKPOST_API_KEY", label: "SparkPost API key", required: true, secret: true, storedIn: "encrypted_secret", requiredForAuthTypes: ["api_key"], helpText: "Create a customer-owned key with only the required SparkPost grants." },
    { name: "SPARKPOST_REGION", label: "SparkPost region", required: true, secret: false, storedIn: "encrypted_secret", requiredForAuthTypes: ["api_key"], helpText: "US or EU. The two account regions are independent." },
    { name: "SPARKPOST_SENDER_DOMAIN", label: "Verified sender domain", required: true, secret: false, storedIn: "encrypted_secret", requiredForAuthTypes: ["api_key"], helpText: "The exact verified domain agents may transmit from." },
    { name: "SPARKPOST_SUBACCOUNT_ID", label: "Subaccount ID", required: false, secret: false, storedIn: "encrypted_secret", requiredForAuthTypes: ["api_key"], helpText: "Optional exact numeric subaccount boundary." },
  ] },
  tools: [
    { name: "sparkpost.getAccount", functionName: "sparkpost_get_account", aliases: ["sparkpost.getAccount", "sparkpost_get_account"], capability: "account", platformCapability: "email_account_profile", action: "read", approvalRequired: false, description: "Read bounded account metadata.", inputSchema: emptySchema() },
    { name: "sparkpost.listMessageEvents", functionName: "sparkpost_list_message_events", aliases: ["sparkpost.listMessageEvents", "sparkpost_list_message_events"], capability: "events", platformCapability: "email_delivery_activity", action: "read", approvalRequired: false, description: "Search at most 100 message events in an explicit seven-day-or-shorter UTC window.", inputSchema: { type: "object", properties: { from: { type: "string" }, to: { type: "string" }, events: { type: "string" }, campaignIds: { type: "string" }, limit: { type: "number", minimum: 1, maximum: 100, default: 100 }, cursor: { type: "string" } }, required: ["from", "to"], additionalProperties: false } },
    { name: "sparkpost.getDeliverabilityMetrics", functionName: "sparkpost_get_deliverability_metrics", aliases: ["sparkpost.getDeliverabilityMetrics", "sparkpost_get_deliverability_metrics"], capability: "metrics", platformCapability: "email_delivery_metrics", action: "read", approvalRequired: false, description: "Read bounded aggregate deliverability metrics.", inputSchema: { type: "object", properties: { from: { type: "string" }, to: { type: "string" }, metrics: { type: "string" }, campaigns: { type: "string" } }, required: ["from", "to"], additionalProperties: false } },
    { name: "sparkpost.createTransmission", functionName: "sparkpost_create_transmission", aliases: ["sparkpost.createTransmission", "sparkpost_create_transmission", "email_send"], capability: "transmissions", platformCapability: "email_send", action: "write", approvalRequired: true, description: "Create a SparkPost transmission through the bound sender domain.", inputSchema: { type: "object", properties: { transmission: { type: "object" }, approvalId: { type: "string" } }, required: ["transmission"], additionalProperties: false } },
    { name: "sparkpost.request", functionName: "sparkpost_request", aliases: ["sparkpost.request", "sparkpost_request", "sparkpost_full_api"], capability: "full_api", platformCapability: "sparkpost_full_api", action: "admin", approvalRequired: true, description: "Call a key-authorized SparkPost v1 endpoint at the configured official regional origin.", inputSchema: { type: "object", properties: { method: { type: "string", enum: ["GET", "POST", "PUT", "PATCH", "DELETE"] }, path: { type: "string", pattern: "^/" }, query: { type: "object" }, json: { type: ["object", "array"] }, approvalId: { type: "string" } }, required: ["method", "path"], additionalProperties: false } },
  ], approvalProfiles: [{ id: "sparkpost_safe", label: "Safe", description: "Bounded reads run directly; transmissions and every other API operation require approval.", defaultSelected: true, allowedActions: reads, approvalRequiredActions: writes, blockedActions: [] }], healthChecks: [{ id: "key", label: "SparkPost key check" }],
};
function emptySchema() { return { type: "object", properties: {}, additionalProperties: false }; }
