import { safeConnectorFetch } from "../safe-connector-fetch";
import { Injectable } from "@nestjs/common";
import type { MarketplaceConnectorSafeErrorCode } from "../types";
type JsonObject = Record<string, unknown>;
export type SparkPostCredentials = { apiKey: string; region: "US" | "EU"; senderDomain: string; subaccountId?: string };
export class SparkPostApiError extends Error { constructor(public readonly code: MarketplaceConnectorSafeErrorCode, message: string, public readonly statusCode?: number) { super(message); } }
@Injectable()
export class SparkPostApiAdapter {
  async health(credentials: SparkPostCredentials) { try { return { verified: true, data: await this.getAccount(credentials) }; } catch (error) { if (error instanceof SparkPostApiError && error.code === "insufficient_scope") return { verified: true, grantRestricted: true }; throw error; } }
  getAccount(credentials: SparkPostCredentials) { return this.request(credentials, { method: "GET", path: "/account" }); }
  listMessageEvents(credentials: SparkPostCredentials, input: JsonObject) { const range = this.range(input); return this.request(credentials, { method: "GET", path: "/events/message", query: { from: range.from, to: range.to, events: input.events, campaigns: input.campaignIds, per_page: this.clamp(input.limit, 100, 1, 100), cursor: this.string(input.cursor) ?? "initial" } }); }
  getDeliverabilityMetrics(credentials: SparkPostCredentials, input: JsonObject) { const range = this.range(input); return this.request(credentials, { method: "GET", path: "/metrics/deliverability", query: { from: range.from, to: range.to, metrics: this.string(input.metrics) ?? "count_targeted,count_sent,count_delivered,count_bounce,count_open,count_clicked", campaigns: input.campaigns } }); }
  createTransmission(credentials: SparkPostCredentials, input: JsonObject) { const transmission = this.object(input.transmission); if (!transmission) throw new SparkPostApiError("provider_validation_error", "transmission is required"); this.assertTransmission(transmission, credentials.senderDomain); return this.request(credentials, { method: "POST", path: "/transmissions", json: transmission }); }
  async request(credentials: SparkPostCredentials, input: { method: string; path: string; query?: JsonObject; json?: JsonObject | unknown[] }) {
    const method = input.method.toUpperCase(); if (!/^(GET|POST|PUT|PATCH|DELETE)$/.test(method) || !input.path.startsWith("/") || input.path.startsWith("//") || input.path.includes("..") || input.path.includes("://") || input.path.startsWith("/api/")) throw new SparkPostApiError("provider_validation_error", "SparkPost method or path is invalid.");
    this.rejectSecrets(input.query); this.rejectSecrets(input.json); if (method === "POST" && input.path.replace(/\/$/, "") === "/transmissions") { const transmission = this.object(input.json); if (!transmission) throw new SparkPostApiError("provider_validation_error", "SparkPost transmission must be an object."); this.assertTransmission(transmission, credentials.senderDomain); }
    const body = input.json === undefined ? undefined : JSON.stringify(input.json); if (body && Buffer.byteLength(body) > 22 * 1024 * 1024) throw new SparkPostApiError("provider_validation_error", "SparkPost request exceeds the bounded 22 MB envelope.");
    const origin = credentials.region === "EU" ? "https://api.eu.sparkpost.com/api/v1" : "https://api.sparkpost.com/api/v1"; const url = new URL(`${origin}${input.path}`); this.append(url.searchParams, input.query);
    const headers: Record<string, string> = { Authorization: credentials.apiKey, Accept: "application/json", "Content-Type": "application/json" }; if (credentials.subaccountId) headers["X-MSYS-SUBACCOUNT"] = credentials.subaccountId;
    const response = await safeConnectorFetch(url, { method, headers, body }); const raw = await response.text(); const text = raw.slice(0, 512_000); let parsed: unknown = text; try { parsed = text ? JSON.parse(text) : null; } catch { parsed = text; } const safe = this.redact(parsed); if (!response.ok) throw new SparkPostApiError(this.code(response.status), this.message(safe) ?? `SparkPost returned ${response.status}`, response.status); return { status: response.status, data: safe, rateLimit: { limit: response.headers.get("x-ratelimit-limit"), remaining: response.headers.get("x-ratelimit-remaining"), reset: response.headers.get("x-ratelimit-reset") }, truncated: raw.length > text.length };
  }
  private assertTransmission(value: JsonObject, domain: string) { const content = this.object(value.content); const override = this.object(value.override); const sender = this.sender(this.object(override?.from) ?? override?.from ?? this.object(content?.from) ?? content?.from); if (!sender || !sender.toLowerCase().endsWith(`@${domain}`)) throw new SparkPostApiError("sender_identity_not_approved", `Transmission sender must use ${domain}.`); const recipients = value.recipients; if (Array.isArray(recipients) && (recipients.length < 1 || recipients.length > 1000)) throw new SparkPostApiError("provider_validation_error", "Inline transmissions must contain 1 to 1000 recipients."); if (!Array.isArray(recipients) && !this.object(recipients)?.list_id) throw new SparkPostApiError("provider_validation_error", "Transmission requires inline recipients or a stored recipient list."); if (Buffer.byteLength(JSON.stringify(value)) > 22 * 1024 * 1024) throw new SparkPostApiError("provider_validation_error", "Transmission exceeds the documented 20 MB content envelope."); }
  private sender(value: unknown) { if (typeof value === "string") return this.email(value); return this.email(this.string(this.object(value)?.email)); }
  private email(value: string | null) { if (!value) return null; return (value.match(/<([^>]+)>/)?.[1] ?? value).trim(); }
  private range(input: JsonObject) { const from = new Date(this.required(input.from, "from")); const to = new Date(this.required(input.to, "to")); if (!Number.isFinite(from.valueOf()) || !Number.isFinite(to.valueOf()) || to <= from || to.valueOf() - from.valueOf() > 7 * 24 * 60 * 60 * 1000) throw new SparkPostApiError("provider_validation_error", "Use a valid UTC range no longer than seven days."); return { from: from.toISOString(), to: to.toISOString() }; }
  private required(value: unknown, field: string) { const result = this.string(value); if (!result) throw new SparkPostApiError("provider_validation_error", `${field} is required`); return result; }
  private rejectSecrets(value?: JsonObject | unknown[]) { if (!value) return; const walk = (entry: unknown) => { if (Array.isArray(entry)) return entry.forEach(walk); const object = this.object(entry); if (!object) return; for (const [key, child] of Object.entries(object)) { if (/(api.?key|password|secret|authorization|credential|token)/i.test(key)) throw new SparkPostApiError("policy_blocked", `Credential-bearing field ${key} is not allowed.`); walk(child); } }; walk(value); }
  private append(params: URLSearchParams, value?: JsonObject) { if (!value) return; for (const [key, entry] of Object.entries(value)) if (entry !== undefined && entry !== null) params.append(key, String(entry)); }
  private redact(value: unknown): unknown { if (Array.isArray(value)) return value.slice(0, 500).map((entry) => this.redact(entry)); const object = this.object(value); if (!object) return value; const result: JsonObject = {}; for (const [key, entry] of Object.entries(object).slice(0, 500)) result[key] = /(api.?key|password|secret|authorization|credential|token)/i.test(key) ? "[REDACTED]" : this.redact(entry); return result; }
  private message(value: unknown) { const object = this.object(value); const first = Array.isArray(object?.errors) ? this.object(object!.errors[0]) : null; return this.string(first?.message) ?? this.string(first?.description) ?? this.string(object?.message); }
  private code(status: number): MarketplaceConnectorSafeErrorCode { if (status === 401) return "credential_missing"; if (status === 403) return "insufficient_scope"; if (status === 420 || status === 429) return "provider_rate_limited"; if (status >= 500) return "provider_unavailable"; return "provider_validation_error"; }
  private string(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : null; } private object(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonObject : null; } private clamp(value: unknown, fallback: number, min: number, max: number) { const number = Number(value ?? fallback); return Number.isFinite(number) ? Math.min(Math.max(Math.floor(number), min), max) : fallback; }
}
