import { safeConnectorFetch } from "../safe-connector-fetch";
import { Injectable } from "@nestjs/common";
import type { MarketplaceConnectorSafeErrorCode } from "../types";

type JsonObject = Record<string, unknown>;
export type ResendCredentials = { apiKey: string; keyPermission: "SENDING" | "FULL"; domain: string };
export class ResendApiError extends Error { constructor(public readonly code: MarketplaceConnectorSafeErrorCode, message: string, public readonly statusCode?: number) { super(message); } }

@Injectable()
export class ResendApiAdapter {
  async health(credentials: ResendCredentials) {
    try { return { verified: true, data: await this.listDomains(credentials, { limit: 1 }) }; }
    catch (error) { if (credentials.keyPermission === "SENDING" && error instanceof ResendApiError && error.code === "insufficient_scope") return { verified: true, scopeRestricted: true }; throw error; }
  }
  listEmails(credentials: ResendCredentials, input: JsonObject) { return this.request(credentials, { method: "GET", path: "/emails", query: this.page(input) }); }
  listDomains(credentials: ResendCredentials, input: JsonObject) { return this.request(credentials, { method: "GET", path: "/domains", query: this.page(input) }); }
  sendEmail(credentials: ResendCredentials, input: JsonObject) { const message = this.object(input.message); if (!message) throw new ResendApiError("provider_validation_error", "message is required"); this.assertMessage(message, credentials.domain); return this.request(credentials, { method: "POST", path: "/emails", json: message, idempotencyKey: this.idempotency(input.idempotencyKey) }); }
  sendBatch(credentials: ResendCredentials, input: JsonObject) { const messages = Array.isArray(input.messages) ? input.messages : []; if (messages.length < 1 || messages.length > 100) throw new ResendApiError("provider_validation_error", "Resend batch requires 1 to 100 messages."); for (const message of messages) { const object = this.object(message); if (!object) throw new ResendApiError("provider_validation_error", "Every batch item must be an email object."); this.assertMessage(object, credentials.domain); if ("attachments" in object || "scheduled_at" in object) throw new ResendApiError("provider_validation_error", "Resend batch does not support attachments or scheduled_at."); } return this.request(credentials, { method: "POST", path: "/emails/batch", json: messages, idempotencyKey: this.idempotency(input.idempotencyKey) }); }
  async request(credentials: ResendCredentials, input: { method: string; path: string; query?: JsonObject; json?: JsonObject | unknown[]; idempotencyKey?: string }) {
    const method = input.method.toUpperCase();
    if (!/^(GET|POST|PUT|PATCH|DELETE)$/.test(method) || !input.path.startsWith("/") || input.path.startsWith("//") || input.path.includes("..") || input.path.includes("://")) throw new ResendApiError("provider_validation_error", "Resend method or path is invalid.");
    this.rejectSecrets(input.query); this.rejectSecrets(input.json);
    if (method === "POST" && input.path === "/emails") { const message = this.object(input.json); if (!message) throw new ResendApiError("provider_validation_error", "Resend /emails requires an email object."); this.assertMessage(message, credentials.domain); input.idempotencyKey = this.idempotency(input.idempotencyKey); }
    if (method === "POST" && input.path === "/emails/batch") { const messages = Array.isArray(input.json) ? input.json : []; if (messages.length < 1 || messages.length > 100) throw new ResendApiError("provider_validation_error", "Resend batch requires 1 to 100 messages."); for (const entry of messages) { const message = this.object(entry); if (!message) throw new ResendApiError("provider_validation_error", "Every batch item must be an email object."); this.assertMessage(message, credentials.domain); if ("attachments" in message || "scheduled_at" in message) throw new ResendApiError("provider_validation_error", "Resend batch does not support attachments or scheduled_at."); } input.idempotencyKey = this.idempotency(input.idempotencyKey); }
    const body = input.json === undefined ? undefined : JSON.stringify(input.json); if (body && Buffer.byteLength(body) > 42 * 1024 * 1024) throw new ResendApiError("provider_validation_error", "Resend request payload exceeds the bounded 42 MB envelope.");
    const url = new URL(`https://api.resend.com${input.path}`); this.append(url.searchParams, input.query);
    const headers: Record<string, string> = { Authorization: `Bearer ${credentials.apiKey}`, "Content-Type": "application/json", "User-Agent": "RelayConsole/1.0" };
    if (input.idempotencyKey) headers["Idempotency-Key"] = this.idempotency(input.idempotencyKey);
    const response = await safeConnectorFetch(url, { method, headers, body }); const raw = await response.text(); const text = raw.slice(0, 512_000); let parsed: unknown = text; try { parsed = text ? JSON.parse(text) : null; } catch { parsed = text; } const safe = this.redact(parsed);
    if (!response.ok) throw new ResendApiError(this.code(response.status, safe), this.message(safe) ?? `Resend returned ${response.status}`, response.status);
    return { status: response.status, data: safe, rateLimit: { limit: response.headers.get("ratelimit-limit"), remaining: response.headers.get("ratelimit-remaining"), reset: response.headers.get("ratelimit-reset"), retryAfter: response.headers.get("retry-after") }, quota: { daily: response.headers.get("x-resend-daily-quota"), monthly: response.headers.get("x-resend-monthly-quota") }, truncated: raw.length > text.length };
  }
  private assertMessage(message: JsonObject, domain: string) { const from = this.string(message.from); if (!from) throw new ResendApiError("sender_identity_not_approved", "A from sender is required."); const email = from.match(/<([^>]+)>/)?.[1] ?? from; if (!email.toLowerCase().endsWith(`@${domain}`)) throw new ResendApiError("sender_identity_not_approved", `Sender must use ${domain}.`); const count = [message.to, message.cc, message.bcc].flatMap((v) => Array.isArray(v) ? v : typeof v === "string" ? [v] : []).length; if (count < 1 || count > 50) throw new ResendApiError("provider_validation_error", "Resend email must contain 1 to 50 recipients."); if (Buffer.byteLength(JSON.stringify(message)) > 42 * 1024 * 1024) throw new ResendApiError("provider_validation_error", "Resend email exceeds the bounded attachment envelope."); }
  private page(input: JsonObject) { if (input.after && input.before) throw new ResendApiError("provider_validation_error", "Use either after or before, not both."); return { limit: Math.min(Math.max(Math.floor(Number(input.limit ?? 20)), 1), 100), after: input.after, before: input.before }; }
  private idempotency(value: unknown) { const key = this.string(value); if (!key || key.length > 256) throw new ResendApiError("provider_validation_error", "Idempotency key must contain 1 to 256 characters."); return key; }
  private rejectSecrets(value?: JsonObject | unknown[]) { if (!value) return; const walk = (entry: unknown) => { if (Array.isArray(entry)) return entry.forEach(walk); const object = this.object(entry); if (!object) return; for (const [key, child] of Object.entries(object)) { if (/(api.?key|password|secret|authorization|credential|token)/i.test(key)) throw new ResendApiError("policy_blocked", `Credential-bearing field ${key} is not allowed.`); walk(child); } }; walk(value); }
  private append(params: URLSearchParams, value?: JsonObject) { if (!value) return; for (const [key, entry] of Object.entries(value)) if (entry !== undefined && entry !== null) params.append(key, String(entry)); }
  private redact(value: unknown): unknown { if (Array.isArray(value)) return value.slice(0, 500).map((entry) => this.redact(entry)); const object = this.object(value); if (!object) return value; const result: JsonObject = {}; for (const [key, entry] of Object.entries(object).slice(0, 500)) result[key] = /(api.?key|password|secret|authorization|credential|token|download_url)/i.test(key) ? "[REDACTED]" : this.redact(entry); return result; }
  private code(status: number, body: unknown): MarketplaceConnectorSafeErrorCode { const name = this.string(this.object(body)?.name); if (name === "restricted_api_key" || status === 401 && name !== "missing_api_key") return "insufficient_scope"; if (status === 401 || status === 403 && name === "invalid_api_key") return "credential_missing"; if (status === 429) return "provider_rate_limited"; if (status >= 500) return "provider_unavailable"; return "provider_validation_error"; }
  private message(value: unknown) { const object = this.object(value); return this.string(object?.message) ?? this.string(object?.error); }
  private string(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : null; }
  private object(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as JsonObject : null; }
}
