export const CHARGEBEE_ENDPOINT_FAMILIES = [
  { id: "auth_site", label: "Authentication And Site Model", docsUrl: "https://apidocs.chargebee.com/docs/api/auth", guidance: "Use HTTP Basic Auth with API key as username and empty password against `{site}.chargebee.com/api/v2`. Verify test/live site and key before writes." },
  { id: "customers", label: "Customers", docsUrl: "https://apidocs.chargebee.com/docs/api/customers/customer-object", guidance: "Read customer billing identity, balances, billing address, and payment-source summaries with sensitive fields minimized." },
  { id: "subscriptions", label: "Subscriptions", docsUrl: "https://apidocs.chargebee.com/docs/api/subscriptions", guidance: "Read subscription lifecycle. Create, update, cancel, pause, resume, reactivate, or entitlement-affecting item changes require approval." },
  { id: "items_prices", label: "Items Plans Item Prices", docsUrl: "https://apidocs.chargebee.com/docs/api/items", guidance: "Read items, plan items, addon items, charge items, and item prices. Catalog or coupon changes require approval." },
  { id: "invoices_payments_credits", label: "Invoices Payments Credit Notes", docsUrl: "https://apidocs.chargebee.com/docs/api/invoices", guidance: "Read invoices, payments, transactions, and credit notes. Create/send/collect invoices, refunds, voids, write-offs, or credits require approval." },
  { id: "estimates", label: "Estimates", docsUrl: "https://apidocs.chargebee.com/docs/api/estimates/create-invoice-for-items-estimate", guidance: "Use estimates to preview invoice and subscription changes before requesting approval for writes." },
  { id: "hosted_pages", label: "Hosted Pages", docsUrl: "https://apidocs.chargebee.com/docs/api/hosted_pages", guidance: "Hosted pages support checkout, payment method update, collect-now, and subscription change flows; creation requires approval." },
  { id: "events_webhooks", label: "Events And Webhooks", docsUrl: "https://apidocs.chargebee.com/docs/api/webhooks", guidance: "Read events and webhook delivery state. Webhook configuration changes require approval and secrets must never be exposed." },
  { id: "rate_limits", label: "Rate Limits", docsUrl: "https://www.chargebee.com/docs/billing/2.0/kb/platform/what-are-the-chargebee-api-limits", guidance: "Default test limit is 150 requests/minute; live limits vary by plan and concurrent request pressure. Back off on 429." },
];
