// Generated by scripts/generate-homebase-operation-registry.mjs.
// Source: https://app.joinhomebase.com/api/public/swagger_doc.json
// SHA-256: 66ecd9f2cc5a93b8d7b26cbe81f17ec900c8460e8e6f0dec63273d26ee8074ff

export type HomebaseOperation = {
  id: string;
  method: "GET";
  path: string;
  summary: string;
  pathParameters: readonly string[];
  queryParameters: readonly string[];
};

export const HOMEBASE_SOURCE_SHA256 =
  "66ecd9f2cc5a93b8d7b26cbe81f17ec900c8460e8e6f0dec63273d26ee8074ff";

export const HOMEBASE_OPERATIONS = [
  {
    id: "getCompany",
    method: "GET",
    path: "/company",
    summary: "Retrieve the company for the current account",
    pathParameters: [],
    queryParameters: [],
  },
  {
    id: "getLocations",
    method: "GET",
    path: "/locations",
    summary: "Retrieve locations for the current account",
    pathParameters: [],
    queryParameters: [],
  },
  {
    id: "getLocationsLocationUuid",
    method: "GET",
    path: "/locations/{location_uuid}",
    summary: "Retrieve a given location for the current account",
    pathParameters: ["location_uuid"],
    queryParameters: [],
  },
  {
    id: "getLocationsLocationUuidEmployees",
    method: "GET",
    path: "/locations/{location_uuid}/employees",
    summary: "Retrieve employees for a given location",
    pathParameters: ["location_uuid"],
    queryParameters: ["page", "per_page", "with_archived"],
  },
  {
    id: "getLocationsLocationUuidEmployeesId",
    method: "GET",
    path: "/locations/{location_uuid}/employees/{id}",
    summary: "Retrieve a single employee for a given location",
    pathParameters: ["location_uuid", "id"],
    queryParameters: ["with_archived"],
  },
  {
    id: "getLocationsLocationUuidLabor",
    method: "GET",
    path: "/locations/{location_uuid}/labor",
    summary:
      "Retrieve aggregate labor for a given location, grouped by hour or by day",
    pathParameters: ["location_uuid"],
    queryParameters: ["group_by", "start_date", "end_date"],
  },
  {
    id: "getLocationsLocationUuidLaborByEmployee",
    method: "GET",
    path: "/locations/{location_uuid}/labor/by_employee",
    summary:
      "Retrieve aggregate labor for a given location, grouped by employee",
    pathParameters: ["location_uuid"],
    queryParameters: ["start_date", "end_date"],
  },
  {
    id: "getLocationsLocationUuidLaborByRole",
    method: "GET",
    path: "/locations/{location_uuid}/labor/by_role",
    summary: "Retrieve aggregate labor for a given location, grouped by role",
    pathParameters: ["location_uuid"],
    queryParameters: ["start_date", "end_date"],
  },
  {
    id: "getLocationsLocationUuidPlan",
    method: "GET",
    path: "/locations/{location_uuid}/plan",
    summary: "Retrieve plan for location",
    pathParameters: ["location_uuid"],
    queryParameters: [],
  },
  {
    id: "getLocationsLocationUuidShifts",
    method: "GET",
    path: "/locations/{location_uuid}/shifts",
    summary: "Retrieve shifts for a given location",
    pathParameters: ["location_uuid"],
    queryParameters: [
      "page",
      "per_page",
      "start_date",
      "end_date",
      "open",
      "with_note",
      "date_filter",
    ],
  },
  {
    id: "getLocationsLocationUuidShiftsDeleted",
    method: "GET",
    path: "/locations/{location_uuid}/shifts/deleted",
    summary: "Retrieve the IDs of deleted shifts for a given location",
    pathParameters: ["location_uuid"],
    queryParameters: ["page", "per_page", "start_date", "end_date"],
  },
  {
    id: "getLocationsLocationUuidShiftsId",
    method: "GET",
    path: "/locations/{location_uuid}/shifts/{id}",
    summary: "Retrieve a single shift for a given location",
    pathParameters: ["location_uuid", "id"],
    queryParameters: ["with_note"],
  },
  {
    id: "getLocationsLocationUuidTimecards",
    method: "GET",
    path: "/locations/{location_uuid}/timecards",
    summary: "Retrieve timecards for a given location",
    pathParameters: ["location_uuid"],
    queryParameters: [
      "page",
      "per_page",
      "start_date",
      "end_date",
      "date_filter",
    ],
  },
  {
    id: "getLocationsLocationUuidTimecardsDeleted",
    method: "GET",
    path: "/locations/{location_uuid}/timecards/deleted",
    summary: "Retrieve the IDs of deleted timecards for a given location",
    pathParameters: ["location_uuid"],
    queryParameters: ["page", "per_page", "start_date", "end_date"],
  },
  {
    id: "getLocationsLocationUuidTimecardsId",
    method: "GET",
    path: "/locations/{location_uuid}/timecards/{id}",
    summary: "Retrieve a single timecard for a given location",
    pathParameters: ["location_uuid", "id"],
    queryParameters: [],
  },
  {
    id: "getTimeclockStatus",
    method: "GET",
    path: "/timeclock/status",
    summary: "Retrieve the current timeclock status for a given job",
    pathParameters: [],
    queryParameters: ["job_id"],
  },
] as const satisfies readonly HomebaseOperation[];

export const HOMEBASE_OPERATION_IDS = HOMEBASE_OPERATIONS.map(
  (operation) => operation.id,
);

export const HOMEBASE_OPERATION_BY_ID = new Map<string, HomebaseOperation>(
  HOMEBASE_OPERATIONS.map((operation) => [operation.id, operation]),
);
