export const KONTAINER_OPENAPI_OPERATIONS = [
  ["GET", "/meta"],
  ["GET", "/dam/search"],
  ["GET", "/consent/agreements"],
  ["GET", "/consent/wards"],
  ["POST", "/dam/albums/{album_id}/relationships/files"],
  ["PATCH", "/dam/albums/{album_id}/relationships/files"],
  ["DELETE", "/dam/albums/{album_id}/files/{file_id}"],
  ["GET", "/dam/categories"],
  ["GET", "/dam/categories/{category_id}"],
  ["GET", "/dam/categories/{category_id}/elements"],
  ["GET", "/dam/categories/{category_id}/elements/{element_id}"],
  ["GET", "/dam/download-templates"],
  [
    "GET",
    "/dam/element-classification-labels/{element_classification_label_id}/translations",
  ],
  ["GET", "/dam/elements/{element_id}/element-options"],
  ["POST", "/dam/elements/{element_id}/element-options"],
  ["GET", "/dam/element-options/{element_option_id}"],
  ["DELETE", "/dam/element-options/{element_option_id}"],
  ["PATCH", "/dam/element-options/{element_option_id}"],
  ["GET", "/dam/element-options/{element_option_id}/translations"],
  [
    "GET",
    "/dam/element-options/{element_option_id}/translations/{translation_id}",
  ],
  [
    "DELETE",
    "/dam/element-options/{element_option_id}/translations/{translation_id}",
  ],
  [
    "PATCH",
    "/dam/element-options/{element_option_id}/translations/{translation_id}",
  ],
  [
    "POST",
    "/dam/elements/{element_id}/element-options/{element_option_id}/translations",
  ],
  ["GET", "/dam/files/{file_id}"],
  ["DELETE", "/dam/files/{file_id}"],
  ["GET", "/dam/files/{file_id}/deletion-warnings"],
  ["GET", "/dam/files/duplicates"],
  ["GET", "/dam/files/{file_id}/duplicates"],
  ["GET", "/dam/files/{file_id}/relationships/external-references"],
  ["GET", "/dam/files/trashed"],
  ["GET", "/dam/files/deleted"],
  ["GET", "/dam/files/removed"],
  ["POST", "/dam/files/{file_id}/thumbnails"],
  ["DELETE", "/dam/files/{file_id}/thumbnails"],
  ["GET", "/dam/folders"],
  ["GET", "/dam/folders/{folder_id}"],
  ["DELETE", "/dam/folders/{folder_id}"],
  ["PATCH", "/dam/folders/{folder_id}"],
  ["POST", "/dam/folders/{folder_id}/folders"],
  ["POST", "/dam/folders/{folder_id}/albums"],
  ["POST", "/dam/folders/{folder_id}/mirror-folders"],
  ["GET", "/dam/folders/{folder_id}/deletion-warnings"],
  ["POST", "/dam/folders/{folder_id}/copy-to"],
  ["GET", "/dam/folders/{folder_id}/files"],
  ["POST", "/dam/folders/{folder_id}/files"],
  ["GET", "/dam/folders/{folder_id}/files/{file_id}"],
  ["PATCH", "/dam/folders/{folder_id}/files/{file_id}"],
  ["POST", "/dam/files/{file_id}/cdn"],
  ["DELETE", "/dam/files/{file_id}/cdn"],
  ["GET", "/dam/files/{file_id}/video-cdn"],
  ["POST", "/dam/files/{file_id}/video-cdn"],
  ["DELETE", "/dam/files/{file_id}/video-cdn"],
  ["PATCH", "/dam/video-cdns/{video_cdn_id}"],
  ["GET", "/dam/video-cdns/{video_cdn_id}/embed-settings"],
  ["POST", "/dam/cdn/relationships/files"],
  ["DELETE", "/dam/cdn/relationships/files"],
  ["POST", "/dam/files/{file_id}/categories/{category_id}/custom-fields"],
  ["PATCH", "/dam/files/{file_id}/custom-fields/{custom_fields_id}"],
  ["POST", "/dam/folders/{folder_id}/move-to"],
  ["GET", "/dam/folders/{folder_id}/users/permissions"],
  ["GET", "/dam/folders/{folder_id}/users/{user_id}/permissions"],
  ["DELETE", "/dam/folders/{folder_id}/users/{user_id}/permissions"],
  ["PATCH", "/dam/folders/{folder_id}/users/{user_id}/permissions"],
  ["GET", "/dam/folders/{folder_id}/user-groups/permissions"],
  ["GET", "/dam/folders/{folder_id}/user-groups/{user_group_id}/permissions"],
  [
    "DELETE",
    "/dam/folders/{folder_id}/user-groups/{user_group_id}/permissions",
  ],
  ["PATCH", "/dam/folders/{folder_id}/user-groups/{user_group_id}/permissions"],
  ["GET", "/dam/files/{file_id}/stream"],
  ["GET", "/dam/files/{file_id}/thumbnails/{size}/stream"],
  ["GET", "/element-types"],
  ["GET", "/global-variables"],
  ["GET", "/global-variables/{global_variabel_id}"],
  ["POST", "/integration/job-logs"],
  ["PATCH", "/integration/job-logs/{job_log_id}"],
  ["GET", "/operation-logs"],
  ["GET", "/pim/categories"],
  ["GET", "/pim/categories/{category_id}"],
  ["GET", "/pim/categories/{category_id}/incomplete-items"],
  ["GET", "/pim/categories/{category_id}/items"],
  ["GET", "/pim/categories/{category_id}/items/{item_id}"],
  ["DELETE", "/pim/categories/{category_id}/items/{item_id}"],
  ["PATCH", "/pim/categories/{category_id}/items/{item_id}"],
  ["POST", "/pim/categories/{category_id}/variations/{variation_id}/items"],
  ["POST", "/pim/categories/{category_id}/items/{item_id}/variation-items"],
  ["GET", "/pim/categories/{category_id}/resources"],
  ["POST", "/pim/categories/{category_id}/resources"],
  ["GET", "/pim/categories/{category_id}/resources/{resource_id}"],
  ["DELETE", "/pim/categories/{category_id}/resources/{resource_id}"],
  ["PATCH", "/pim/categories/{category_id}/resources/{resource_id}"],
  ["GET", "/pim/categories/{category_id}/structure"],
  ["GET", "/pim/channels"],
  ["GET", "/pim/channels/{channel_id}"],
  ["GET", "/pim/channels/{channel_id}/items"],
  ["GET", "/pim/channels/{channel_id}/items/{item_id}"],
  ["DELETE", "/pim/channels/{channel_id}/items/{item_id}"],
  ["PATCH", "/pim/channels/{channel_id}/items/{item_id}"],
  ["GET", "/pim/channels/{channel_id}/variations/{variation_id}/items"],
  ["POST", "/pim/channels/{channel_id}/variations/{variation_id}/items"],
  ["POST", "/pim/channels/{channel_id}/items/{item_id}/variation-items"],
  ["GET", "/pim/categories/{category_id}/elements"],
  ["GET", "/pim/elements/{element_id}"],
  ["GET", "/pim/elements/{element_id}/element-options"],
  ["POST", "/pim/elements/{element_id}/element-options"],
  ["GET", "/pim/element-options/{element_option_id}"],
  ["DELETE", "/pim/element-options/{element_option_id}"],
  ["PATCH", "/pim/element-options/{element_option_id}"],
  ["GET", "/pim/elements/{element_id}/resource-options"],
  ["GET", "/statistics/cdn-usages"],
  ["GET", "/statistics/downloads"],
  ["GET", "/statistics/logins"],
  ["GET", "/statistics/uploads"],
  ["GET", "/users"],
  ["POST", "/users"],
  ["GET", "/users/{user_id}"],
  ["DELETE", "/users/{user_id}"],
  ["PATCH", "/users/{user_id}"],
  ["POST", "/users/{user_id}/relationships/user-groups"],
  ["DELETE", "/users/{user_id}/relationships/user-groups"],
  ["GET", "/users/{user_id}/user-invite-url"],
  ["POST", "/users/{user_id}/user-invite-url"],
  ["POST", "/users/{user_id}/send-welcome-email"],
  ["POST", "/users/{user_id}/send-login-email"],
  ["GET", "/user-groups"],
  ["POST", "/user-groups"],
  ["GET", "/user-groups/{usergroup_id}"],
  ["DELETE", "/user-groups/{usergroup_id}"],
  ["PATCH", "/user-groups/{Usergroup_id}"],
] as const;

export const KONTAINER_OPENAPI_OPERATION_COUNT =
  KONTAINER_OPENAPI_OPERATIONS.length;
