export type OAuthTokenResponse = {
  ok?: boolean;
  result?: number;
  error?: string;
  token_type?: string;
  access_token?: string;
  access_url?: string;
  base_url?: string;
  refresh_token?: string;
  expires_in?: number;
  expires_at?: string;
  subdomain?: string;
  apicp?: string;
  appcp?: string;
  scope?: string | string[];
  scopes?: string[];
  id_token?: string;
  owner_id?: string;
  refresh_token_expires_in?: number;
  app_id?: string;
  bot_user_id?: string;
  user_id?: string;
  organization_id?: string;
  team_id?: string;
  installation_id?: string;
  livemode?: boolean;
  stripe_user_id?: string;
  account_id?: string;
  businessId?: string;
  id?: string;
  instance_url?: string;
  issued_at?: string;
  signature?: string;
  userId?: string;
  uid?: string | number;
  api_domain?: string;
  location?: string;
  endpoint?: string;
  api_access_point?: string;
  "accounts-server"?: string;
  team?: { id?: string; name?: string };
  info?: {
    uuid?: string;
    name?: string;
    email?: string;
    team_uuid?: string;
    team_name?: string;
  };
  enterprise?: { id?: string; name?: string } | null;
  user?: Record<string, unknown>;
  authed_user?: {
    id?: string;
    scope?: string;
    access_token?: string;
    token_type?: string;
    refresh_token?: string;
    expires_in?: number;
  };
  installation?: {
    apiEndPoint?: string;
    id?: string | number;
    name?: string;
    region?: string;
    company?: { id?: string | number; name?: string };
  };
};
