#!/usr/bin/env python3
"""Export ClawChat's binary-only Hermes closures from a verified upstream uv lock."""

from __future__ import annotations

import argparse
import hashlib
import sys
from collections import deque
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - supports the macOS system Python
    import tomli as tomllib  # type: ignore[no-redef]

try:
    from packaging.markers import Marker, default_environment
except ModuleNotFoundError as error:  # pragma: no cover - operator guidance
    raise SystemExit(
        "Lock export requires the Python 'packaging' module."
    ) from error

UPSTREAM_TAG = "v2026.7.20"
UPSTREAM_URL = (
    "https://github.com/NousResearch/hermes-agent/blob/"
    f"{UPSTREAM_TAG}/uv.lock"
)
UPSTREAM_RAW_SHA256 = (
    "456f76d5396df0f543d1035c2d05173cae1882c290ba585cc926a79958b9d7fe"
)
UPSTREAM_GIT_BLOB_SHA1 = "257f7d69645cbfc0ad35d5339d7f651e43572ce6"
HERMES_VERSION = "0.19.0"
HERMES_WHEEL_SHA256 = (
    "bd0bac012aee38a60894781f4597dc29ee7bedb3448540249921f10d3bef327f"
)
TARGET_PYTHON_FULL_VERSION = "3.12.11"


def git_blob_sha1(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode()
    return hashlib.sha1(header + data).hexdigest()  # noqa: S324 - Git identity


def marker_environment() -> dict[str, str]:
    environment = default_environment()
    environment.update(
        {
            "extra": "",
            "implementation_name": "cpython",
            "platform_machine": "x86_64",
            "platform_python_implementation": "CPython",
            "platform_system": "Linux",
            "python_full_version": TARGET_PYTHON_FULL_VERSION,
            "python_version": "3.12",
            "sys_platform": "linux",
        }
    )
    return environment


def edge_applies(edge: dict[str, Any], environment: dict[str, str]) -> bool:
    marker = edge.get("marker")
    return marker is None or Marker(marker).evaluate(environment)


def package_map(lock: dict[str, Any]) -> dict[str, dict[str, Any]]:
    packages: dict[str, dict[str, Any]] = {}
    for package in lock["package"]:
        name = package["name"]
        if name in packages:
            raise ValueError(f"Upstream lock contains duplicate package {name!r}")
        packages[name] = package
    return packages


def resolve_closure(
    packages: dict[str, dict[str, Any]],
    initial_edges: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    environment = marker_environment()
    queue: deque[tuple[str, tuple[str, ...]]] = deque()
    for edge in initial_edges:
        if edge_applies(edge, environment):
            queue.append((edge["name"], tuple(edge.get("extra", ()))))

    selected_extras: dict[str, set[str]] = {}
    while queue:
        name, extras = queue.popleft()
        if name not in packages:
            raise ValueError(f"Dependency {name!r} is absent from upstream lock")
        previously_selected = selected_extras.setdefault(name, set())
        new_extras = set(extras) - previously_selected
        if previously_selected and not new_extras:
            continue
        previously_selected.update(extras)

        package = packages[name]
        for edge in package.get("dependencies", ()):
            if edge_applies(edge, environment):
                queue.append((edge["name"], tuple(edge.get("extra", ()))))

        optional = package.get("optional-dependencies", {})
        for extra in sorted(new_extras):
            if extra not in optional:
                raise ValueError(f"{name!r} has no locked {extra!r} extra")
            for edge in optional[extra]:
                if edge_applies(edge, environment):
                    queue.append((edge["name"], tuple(edge.get("extra", ()))))

    return {name: packages[name] for name in sorted(selected_extras)}


def wheel_hashes(package: dict[str, Any]) -> list[str]:
    hashes = sorted({wheel["hash"] for wheel in package.get("wheels", ())})
    if not hashes:
        raise ValueError(
            f"{package['name']}=={package['version']} has no locked wheel"
        )
    for digest in hashes:
        if not digest.startswith("sha256:") or len(digest) != 71:
            raise ValueError(
                f"{package['name']} has a non-SHA-256 wheel digest: {digest}"
            )
    source = package.get("source")
    if source != {"registry": "https://pypi.org/simple"}:
        raise ValueError(
            f"{package['name']} is not an exact PyPI registry dependency: {source}"
        )
    return hashes


def render_lock(
    packages: dict[str, dict[str, Any]],
    *,
    purpose: str,
    include_hermes_wheel: bool,
) -> str:
    lines = [
        "# Generated by hermes-runtime/scripts/export-upstream-lock.py; DO NOT EDIT.",
        f"# Purpose: {purpose}",
        f"# Source: {UPSTREAM_URL}",
        f"# Source Git blob SHA-1: {UPSTREAM_GIT_BLOB_SHA1}",
        f"# Source raw SHA-256: {UPSTREAM_RAW_SHA256}",
        "# Target: CPython 3.12 on Linux; binary wheels only.",
        "--require-hashes",
        "--only-binary=:all:",
        "",
    ]

    rendered_packages = dict(packages)
    if include_hermes_wheel:
        rendered_packages["hermes-agent"] = {
            "name": "hermes-agent",
            "version": HERMES_VERSION,
            "source": {"registry": "https://pypi.org/simple"},
            "wheels": [{"hash": f"sha256:{HERMES_WHEEL_SHA256}"}],
        }

    for name in sorted(rendered_packages):
        package = rendered_packages[name]
        hashes = wheel_hashes(package)
        lines.append(f"{name}=={package['version']} \\")
        for index, digest in enumerate(hashes):
            continuation = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash={digest}{continuation}")
        lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream-lock", required=True, type=Path)
    parser.add_argument("--runtime-output", required=True, type=Path)
    parser.add_argument("--test-output", required=True, type=Path)
    args = parser.parse_args()

    raw_lock = args.upstream_lock.read_bytes()
    raw_sha256 = hashlib.sha256(raw_lock).hexdigest()
    if raw_sha256 != UPSTREAM_RAW_SHA256:
        raise ValueError(
            f"Upstream lock SHA-256 mismatch: {raw_sha256} != {UPSTREAM_RAW_SHA256}"
        )
    blob_sha1 = git_blob_sha1(raw_lock)
    if blob_sha1 != UPSTREAM_GIT_BLOB_SHA1:
        raise ValueError(
            f"Upstream lock Git identity mismatch: {blob_sha1} != "
            f"{UPSTREAM_GIT_BLOB_SHA1}"
        )

    lock = tomllib.loads(raw_lock.decode())
    packages = package_map(lock)
    hermes = packages.get("hermes-agent")
    if hermes is None or hermes.get("version") != HERMES_VERSION:
        raise ValueError("Upstream lock does not describe Hermes Agent 0.19.0")

    runtime_edges = list(hermes.get("dependencies", ()))
    runtime_edges.extend(
        [
            {"name": "aiohttp"},
            {"name": "setuptools"},
        ]
    )
    runtime_closure = resolve_closure(packages, runtime_edges)
    test_closure = resolve_closure(packages, [{"name": "aiohttp"}])

    args.runtime_output.parent.mkdir(parents=True, exist_ok=True)
    args.test_output.parent.mkdir(parents=True, exist_ok=True)
    write_if_changed(
        args.runtime_output,
        render_lock(
            runtime_closure,
            purpose="Hermes production worker dependency closure",
            include_hermes_wheel=True,
        ),
    )
    write_if_changed(
        args.test_output,
        render_lock(
            test_closure,
            purpose="Hermes fake-worker transport test closure",
            include_hermes_wheel=False,
        ),
    )

    print(
        f"wrote {len(runtime_closure) + 1} runtime packages and "
        f"{len(test_closure)} test packages",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
