import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Generated from EveryAction's current official API-reference navigation on 2026-07-18. The separate-host PCI payment route is intentionally blocked. */
export const EVERYACTION_OPERATIONS = [
  {
    id: "post_echoes",
    method: "POST",
    path: "/echoes",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /echoes",
  },
  {
    id: "get_people",
    method: "GET",
    path: "/people",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /people",
  },
  {
    id: "post_people_find",
    method: "POST",
    path: "/people/find",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/find",
  },
  {
    id: "post_people_find_by_phone",
    method: "POST",
    path: "/people/findByPhone",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/findByPhone",
  },
  {
    id: "post_people_find_or_create",
    method: "POST",
    path: "/people/findOrCreate",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/findOrCreate",
  },
  {
    id: "post_people_by_van_id",
    method: "POST",
    path: "/people/{vanId}",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{vanId}",
  },
  {
    id: "post_people_by_person_id_type_by_person_id",
    method: "POST",
    path: "/people/{personIdType}:{personId}",
    pathParameters: ["personIdType", "personId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{personIdType}:{personId}",
  },
  {
    id: "put_people_by_van_id_merge_into",
    method: "PUT",
    path: "/people/{vanId}/mergeInto",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /people/{vanId}/mergeInto",
  },
  {
    id: "delete_people_by_van_id",
    method: "DELETE",
    path: "/people/{vanId}",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /people/{vanId}",
  },
  {
    id: "get_people_by_van_id",
    method: "GET",
    path: "/people/{vanId}",
    pathParameters: ["vanId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /people/{vanId}",
  },
  {
    id: "get_people_by_person_id_type_by_person_id",
    method: "GET",
    path: "/people/{personIdType}:{personId}",
    pathParameters: ["personIdType", "personId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /people/{personIdType}:{personId}",
  },
  {
    id: "post_people_by_van_id_canvass_responses",
    method: "POST",
    path: "/people/{vanId}/canvassResponses",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{vanId}/canvassResponses",
  },
  {
    id: "post_people_by_person_id_type_by_person_id_canvass_responses",
    method: "POST",
    path: "/people/{personIdType}:{personId}/canvassResponses",
    pathParameters: ["personIdType", "personId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{personIdType}:{personId}/canvassResponses",
  },
  {
    id: "get_people_by_van_id_canvass_responses_by_reference_id",
    method: "GET",
    path: "/people/{vanId}/canvassResponses/{referenceId}",
    pathParameters: ["vanId", "referenceId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /people/{vanId}/canvassResponses/{referenceId}",
  },
  {
    id: "get_people_by_person_id_type_by_person_id_canvass_responses_by_reference_id",
    method: "GET",
    path: "/people/{personIdType}:{personId}/canvassResponses/{referenceId}",
    pathParameters: ["personIdType", "personId", "referenceId"],
    mutating: false,
    bodyAllowed: false,
    description:
      "GET /people/{personIdType}:{personId}/canvassResponses/{referenceId}",
  },
  {
    id: "patch_people_by_van_id_canvass_responses_by_canvass_response_id",
    method: "PATCH",
    path: "/people/{vanId}/canvassResponses/{canvassResponseId}",
    pathParameters: ["vanId", "canvassResponseId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /people/{vanId}/canvassResponses/{canvassResponseId}",
  },
  {
    id: "patch_people_by_person_id_type_by_person_id_canvass_responses_by_canvass_response_id",
    method: "PATCH",
    path: "/people/{personIdType}:{personId}/canvassResponses/{canvassResponseId}",
    pathParameters: ["personIdType", "personId", "canvassResponseId"],
    mutating: true,
    bodyAllowed: true,
    description:
      "PATCH /people/{personIdType}:{personId}/canvassResponses/{canvassResponseId}",
  },
  {
    id: "get_people_by_van_id_activist_codes",
    method: "GET",
    path: "/people/{vanId}/activistCodes",
    pathParameters: ["vanId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /people/{vanId}/activistCodes",
  },
  {
    id: "post_people_by_van_id_codes",
    method: "POST",
    path: "/people/{vanId}/codes",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{vanId}/codes",
  },
  {
    id: "post_people_by_person_id_type_by_person_id_codes",
    method: "POST",
    path: "/people/{personIdType}:{personId}/codes",
    pathParameters: ["personIdType", "personId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{personIdType}:{personId}/codes",
  },
  {
    id: "post_people_by_van_id_disclosure_field_values",
    method: "POST",
    path: "/people/{vanId}/disclosureFieldValues",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{vanId}/disclosureFieldValues",
  },
  {
    id: "post_people_by_person_id_type_by_person_id_disclosure_field_values",
    method: "POST",
    path: "/people/{personIdType}:{personId}/disclosureFieldValues",
    pathParameters: ["personIdType", "personId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{personIdType}:{personId}/disclosureFieldValues",
  },
  {
    id: "post_people_by_van_id_relationships",
    method: "POST",
    path: "/people/{vanId}/relationships",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{vanId}/relationships",
  },
  {
    id: "get_people_by_van_id_notes",
    method: "GET",
    path: "/people/{vanId}/notes",
    pathParameters: ["vanId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /people/{vanId}/notes",
  },
  {
    id: "post_people_by_van_id_notes",
    method: "POST",
    path: "/people/{vanId}/notes",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{vanId}/notes",
  },
  {
    id: "post_people_by_person_id_type_by_person_id_notes",
    method: "POST",
    path: "/people/{personIdType}:{personId}/notes",
    pathParameters: ["personIdType", "personId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /people/{personIdType}:{personId}/notes",
  },
  {
    id: "put_people_by_van_id_notes_by_note_id",
    method: "PUT",
    path: "/people/{vanId}/notes/{noteId}",
    pathParameters: ["vanId", "noteId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /people/{vanId}/notes/{noteId}",
  },
  {
    id: "delete_people_by_van_id_codes_by_code_id",
    method: "DELETE",
    path: "/people/{vanId}/codes/{codeId}",
    pathParameters: ["vanId", "codeId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /people/{vanId}/codes/{codeId}",
  },
  {
    id: "delete_people_by_person_id_type_by_person_id_codes_by_code_id",
    method: "DELETE",
    path: "/people/{personIdType}:{personId}/codes/{codeId}",
    pathParameters: ["personIdType", "personId", "codeId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /people/{personIdType}:{personId}/codes/{codeId}",
  },
  {
    id: "put_people_by_van_id_my_activist_flags",
    method: "PUT",
    path: "/people/{vanId}/myActivistFlags",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /people/{vanId}/myActivistFlags",
  },
  {
    id: "delete_people_by_van_id_my_activist_flags",
    method: "DELETE",
    path: "/people/{vanId}/myActivistFlags",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /people/{vanId}/myActivistFlags",
  },
  {
    id: "get_people_by_van_id_membership",
    method: "GET",
    path: "/people/{vanId}/membership",
    pathParameters: ["vanId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /people/{vanId}/membership",
  },
  {
    id: "patch_people_by_van_id_names",
    method: "PATCH",
    path: "/people/{vanId}/names",
    pathParameters: ["vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /people/{vanId}/names",
  },
  {
    id: "get_activist_codes",
    method: "GET",
    path: "/activistCodes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /activistCodes",
  },
  {
    id: "get_activist_codes_by_activist_code_id",
    method: "GET",
    path: "/activistCodes/{activistCodeId}",
    pathParameters: ["activistCodeId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /activistCodes/{activistCodeId}",
  },
  {
    id: "get_ballot_return_statuses",
    method: "GET",
    path: "/ballotReturnStatuses",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /ballotReturnStatuses",
  },
  {
    id: "get_ballot_return_statuses_by_ballot_return_status_id",
    method: "GET",
    path: "/ballotReturnStatuses/{ballotReturnStatusId}",
    pathParameters: ["ballotReturnStatusId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /ballotReturnStatuses/{ballotReturnStatusId}",
  },
  {
    id: "get_ballot_request_types",
    method: "GET",
    path: "/ballotRequestTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /ballotRequestTypes",
  },
  {
    id: "get_ballot_request_types_by_ballot_request_type_id",
    method: "GET",
    path: "/ballotRequestTypes/{ballotRequestTypeId}",
    pathParameters: ["ballotRequestTypeId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /ballotRequestTypes/{ballotRequestTypeId}",
  },
  {
    id: "get_ballot_types",
    method: "GET",
    path: "/ballotTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /ballotTypes",
  },
  {
    id: "get_ballot_types_by_ballot_type_id",
    method: "GET",
    path: "/ballotTypes/{ballotTypeId}",
    pathParameters: ["ballotTypeId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /ballotTypes/{ballotTypeId}",
  },
  {
    id: "get_bargaining_units",
    method: "GET",
    path: "/bargainingUnits",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /bargainingUnits",
  },
  {
    id: "get_bargaining_units_by_bargaining_unit_id",
    method: "GET",
    path: "/bargainingUnits/{bargainingUnitId}",
    pathParameters: ["bargainingUnitId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /bargainingUnits/{bargainingUnitId}",
  },
  {
    id: "post_bargaining_units",
    method: "POST",
    path: "/bargainingUnits",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /bargainingUnits",
  },
  {
    id: "get_bulk_import_jobs_by_job_id",
    method: "GET",
    path: "/bulkImportJobs/{jobId}",
    pathParameters: ["jobId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /bulkImportJobs/{jobId}",
  },
  {
    id: "get_bulk_import_jobs_resources",
    method: "GET",
    path: "/bulkImportJobs/resources",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /bulkImportJobs/resources",
  },
  {
    id: "get_bulk_import_mapping_types",
    method: "GET",
    path: "/bulkImportMappingTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /bulkImportMappingTypes",
  },
  {
    id: "get_bulk_import_mapping_types_by_mapping_type_name",
    method: "GET",
    path: "/bulkImportMappingTypes/{mappingTypeName}",
    pathParameters: ["mappingTypeName"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /bulkImportMappingTypes/{mappingTypeName}",
  },
  {
    id: "get_bulk_import_mapping_types_by_mapping_type_name_by_field_name_values",
    method: "GET",
    path: "/bulkImportMappingTypes/{mappingTypeName}/{fieldName}/values",
    pathParameters: ["mappingTypeName", "fieldName"],
    mutating: false,
    bodyAllowed: false,
    description:
      "GET /bulkImportMappingTypes/{mappingTypeName}/{fieldName}/values",
  },
  {
    id: "post_bulk_import_jobs",
    method: "POST",
    path: "/bulkImportJobs",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /bulkImportJobs",
  },
  {
    id: "get_campaigns",
    method: "GET",
    path: "/campaigns",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /campaigns",
  },
  {
    id: "get_campaigns_by_campaign_id",
    method: "GET",
    path: "/campaigns/{campaignId}",
    pathParameters: ["campaignId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /campaigns/{campaignId}",
  },
  {
    id: "post_canvass_file_requests",
    method: "POST",
    path: "/canvassFileRequests",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /canvassFileRequests",
  },
  {
    id: "get_canvass_file_requests_by_canvass_file_request_id",
    method: "GET",
    path: "/canvassFileRequests/{canvassFileRequestId}",
    pathParameters: ["canvassFileRequestId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /canvassFileRequests/{canvassFileRequestId}",
  },
  {
    id: "get_canvass_responses_contact_types",
    method: "GET",
    path: "/canvassResponses/contactTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /canvassResponses/contactTypes",
  },
  {
    id: "get_canvass_responses_input_types",
    method: "GET",
    path: "/canvassResponses/inputTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /canvassResponses/inputTypes",
  },
  {
    id: "get_canvass_responses_result_codes",
    method: "GET",
    path: "/canvassResponses/resultCodes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /canvassResponses/resultCodes",
  },
  {
    id: "get_changed_entity_export_jobs_resources",
    method: "GET",
    path: "/changedEntityExportJobs/resources",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /changedEntityExportJobs/resources",
  },
  {
    id: "get_changed_entity_export_jobs_change_types_by_resource_type",
    method: "GET",
    path: "/changedEntityExportJobs/changeTypes/{resourceType}",
    pathParameters: ["resourceType"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /changedEntityExportJobs/changeTypes/{resourceType}",
  },
  {
    id: "get_changed_entity_export_jobs_fields_by_resource_type",
    method: "GET",
    path: "/changedEntityExportJobs/fields/{resourceType}",
    pathParameters: ["resourceType"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /changedEntityExportJobs/fields/{resourceType}",
  },
  {
    id: "post_changed_entity_export_jobs",
    method: "POST",
    path: "/changedEntityExportJobs",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /changedEntityExportJobs",
  },
  {
    id: "get_changed_entity_export_jobs_by_export_job_id",
    method: "GET",
    path: "/changedEntityExportJobs/{exportJobId}",
    pathParameters: ["exportJobId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /changedEntityExportJobs/{exportJobId}",
  },
  {
    id: "get_codes",
    method: "GET",
    path: "/codes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /codes",
  },
  {
    id: "get_codes_by_code_id",
    method: "GET",
    path: "/codes/{codeId}",
    pathParameters: ["codeId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /codes/{codeId}",
  },
  {
    id: "post_codes",
    method: "POST",
    path: "/codes",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /codes",
  },
  {
    id: "post_codes_batch",
    method: "POST",
    path: "/codes/batch",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /codes/batch",
  },
  {
    id: "patch_codes_by_code_id",
    method: "PATCH",
    path: "/codes/{codeId}",
    pathParameters: ["codeId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /codes/{codeId}",
  },
  {
    id: "put_codes",
    method: "PUT",
    path: "/codes",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /codes",
  },
  {
    id: "put_codes_by_code_id",
    method: "PUT",
    path: "/codes/{codeId}",
    pathParameters: ["codeId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /codes/{codeId}",
  },
  {
    id: "delete_codes",
    method: "DELETE",
    path: "/codes",
    pathParameters: [],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /codes",
  },
  {
    id: "delete_codes_by_code_id",
    method: "DELETE",
    path: "/codes/{codeId}",
    pathParameters: ["codeId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /codes/{codeId}",
  },
  {
    id: "get_codes_supported_entities",
    method: "GET",
    path: "/codes/supportedEntities",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /codes/supportedEntities",
  },
  {
    id: "get_code_types",
    method: "GET",
    path: "/codeTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /codeTypes",
  },
  {
    id: "post_commitments",
    method: "POST",
    path: "/commitments",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /commitments",
  },
  {
    id: "patch_commitments_by_commitment_id",
    method: "PATCH",
    path: "/commitments/{commitmentId}",
    pathParameters: ["commitmentId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /commitments/{commitmentId}",
  },
  {
    id: "post_commitments_recurring_payments",
    method: "POST",
    path: "/commitments/recurringPayments",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /commitments/recurringPayments",
  },
  {
    id: "post_contributions",
    method: "POST",
    path: "/contributions",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /contributions",
  },
  {
    id: "get_contributions_by_contribution_id",
    method: "GET",
    path: "/contributions/{contributionId}",
    pathParameters: ["contributionId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /contributions/{contributionId}",
  },
  {
    id: "get_contributions_by_alternate_id_type_by_alternate_id",
    method: "GET",
    path: "/contributions/{alternateIdType}:{alternateId}",
    pathParameters: ["alternateIdType", "alternateId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /contributions/{alternateIdType}:{alternateId}",
  },
  {
    id: "get_contributions_attribution_types",
    method: "GET",
    path: "/contributions/attributionTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /contributions/attributionTypes",
  },
  {
    id: "put_contributions_by_contribution_id_attributions_by_van_id",
    method: "PUT",
    path: "/contributions/{contributionId}/attributions/{vanId}",
    pathParameters: ["contributionId", "vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /contributions/{contributionId}/attributions/{vanId}",
  },
  {
    id: "delete_contributions_by_contribution_id_attributions_by_van_id",
    method: "DELETE",
    path: "/contributions/{contributionId}/attributions/{vanId}",
    pathParameters: ["contributionId", "vanId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /contributions/{contributionId}/attributions/{vanId}",
  },
  {
    id: "post_contributions_by_contribution_id_adjustments",
    method: "POST",
    path: "/contributions/{contributionId}/adjustments",
    pathParameters: ["contributionId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /contributions/{contributionId}/adjustments",
  },
  {
    id: "get_contributions_recent_contributions",
    method: "GET",
    path: "/contributions/recentContributions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /contributions/recentContributions",
  },
  {
    id: "get_custom_fields",
    method: "GET",
    path: "/customFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /customFields",
  },
  {
    id: "get_custom_fields_by_custom_field_id",
    method: "GET",
    path: "/customFields/{customFieldId}",
    pathParameters: ["customFieldId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /customFields/{customFieldId}",
  },
  {
    id: "get_departments",
    method: "GET",
    path: "/departments",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /departments",
  },
  {
    id: "get_departments_by_department_id",
    method: "GET",
    path: "/departments/{departmentId}",
    pathParameters: ["departmentId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /departments/{departmentId}",
  },
  {
    id: "get_designations",
    method: "GET",
    path: "/designations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /designations",
  },
  {
    id: "get_designations_by_designation_id",
    method: "GET",
    path: "/designations/{designationId}",
    pathParameters: ["designationId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /designations/{designationId}",
  },
  {
    id: "post_disbursements",
    method: "POST",
    path: "/disbursements",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /disbursements",
  },
  {
    id: "get_disbursements_by_disbursement_id",
    method: "GET",
    path: "/disbursements/{disbursementId}",
    pathParameters: ["disbursementId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /disbursements/{disbursementId}",
  },
  {
    id: "get_disbursements_recent_disbursements",
    method: "GET",
    path: "/disbursements/recentDisbursements",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /disbursements/recentDisbursements",
  },
  {
    id: "get_district_fields",
    method: "GET",
    path: "/districtFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /districtFields",
  },
  {
    id: "get_district_fields_by_district_field_id",
    method: "GET",
    path: "/districtFields/{districtFieldId}",
    pathParameters: ["districtFieldId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /districtFields/{districtFieldId}",
  },
  {
    id: "get_early_vote_fields",
    method: "GET",
    path: "/earlyVoteFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /earlyVoteFields",
  },
  {
    id: "get_early_vote_fields_by_early_vote_field_id",
    method: "GET",
    path: "/earlyVoteFields/{earlyVoteFieldId}",
    pathParameters: ["earlyVoteFieldId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /earlyVoteFields/{earlyVoteFieldId}",
  },
  {
    id: "get_email_messages",
    method: "GET",
    path: "/email/messages",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /email/messages",
  },
  {
    id: "get_email_message_by_email_id",
    method: "GET",
    path: "/email/message/{emailId}",
    pathParameters: ["emailId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /email/message/{emailId}",
  },
  {
    id: "get_employers",
    method: "GET",
    path: "/employers",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /employers",
  },
  {
    id: "get_employers_by_employer_id",
    method: "GET",
    path: "/employers/{employerId}",
    pathParameters: ["employerId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /employers/{employerId}",
  },
  {
    id: "patch_employers_by_employer_id",
    method: "PATCH",
    path: "/employers/{employerId}",
    pathParameters: ["employerId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /employers/{employerId}",
  },
  {
    id: "post_employers",
    method: "POST",
    path: "/employers",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /employers",
  },
  {
    id: "post_employers_by_employer_id_bargaining_units_by_bargaining_unit_id",
    method: "POST",
    path: "/employers/{employerId}/bargainingUnits/{bargainingUnitId}",
    pathParameters: ["employerId", "bargainingUnitId"],
    mutating: true,
    bodyAllowed: true,
    description:
      "POST /employers/{employerId}/bargainingUnits/{bargainingUnitId}",
  },
  {
    id: "delete_employers_by_employer_id_bargaining_units_by_bargaining_unit_id",
    method: "DELETE",
    path: "/employers/{employerId}/bargainingUnits/{bargainingUnitId}",
    pathParameters: ["employerId", "bargainingUnitId"],
    mutating: true,
    bodyAllowed: false,
    description:
      "DELETE /employers/{employerId}/bargainingUnits/{bargainingUnitId}",
  },
  {
    id: "post_employers_by_employer_id_bargaining_units_by_bargaining_unit_id_job_classes_by_job_class_id",
    method: "POST",
    path: "/employers/{employerId}/bargainingUnits/{bargainingUnitId}/jobClasses/{jobClassId}",
    pathParameters: ["employerId", "bargainingUnitId", "jobClassId"],
    mutating: true,
    bodyAllowed: true,
    description:
      "POST /employers/{employerId}/bargainingUnits/{bargainingUnitId}/jobClasses/{jobClassId}",
  },
  {
    id: "delete_employers_by_employer_id_bargaining_units_by_bargaining_unit_id_job_classes_by_job_class_id",
    method: "DELETE",
    path: "/employers/{employerId}/bargainingUnits/{bargainingUnitId}/jobClasses/{jobClassId}",
    pathParameters: ["employerId", "bargainingUnitId", "jobClassId"],
    mutating: true,
    bodyAllowed: false,
    description:
      "DELETE /employers/{employerId}/bargainingUnits/{bargainingUnitId}/jobClasses/{jobClassId}",
  },
  {
    id: "post_employers_by_employer_id_departments",
    method: "POST",
    path: "/employers/{employerId}/departments",
    pathParameters: ["employerId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /employers/{employerId}/departments",
  },
  {
    id: "post_employers_by_employer_id_shift_types_by_shift_type_id",
    method: "POST",
    path: "/employers/{employerId}/shiftTypes/{shiftTypeId}",
    pathParameters: ["employerId", "shiftTypeId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /employers/{employerId}/shiftTypes/{shiftTypeId}",
  },
  {
    id: "delete_employers_by_employer_id_shift_types_by_shift_type_id",
    method: "DELETE",
    path: "/employers/{employerId}/shiftTypes/{shiftTypeId}",
    pathParameters: ["employerId", "shiftTypeId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /employers/{employerId}/shiftTypes/{shiftTypeId}",
  },
  {
    id: "post_employers_by_employer_id_worksites",
    method: "POST",
    path: "/employers/{employerId}/worksites",
    pathParameters: ["employerId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /employers/{employerId}/worksites",
  },
  {
    id: "get_events_types",
    method: "GET",
    path: "/events/types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /events/types",
  },
  {
    id: "get_events_types_by_event_type_id",
    method: "GET",
    path: "/events/types/{eventTypeId}",
    pathParameters: ["eventTypeId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /events/types/{eventTypeId}",
  },
  {
    id: "get_events",
    method: "GET",
    path: "/events",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /events",
  },
  {
    id: "get_events_by_event_id",
    method: "GET",
    path: "/events/{eventId}",
    pathParameters: ["eventId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /events/{eventId}",
  },
  {
    id: "patch_events_by_event_id",
    method: "PATCH",
    path: "/events/{eventId}",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /events/{eventId}",
  },
  {
    id: "post_events",
    method: "POST",
    path: "/events",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /events",
  },
  {
    id: "post_events_by_event_id_shifts",
    method: "POST",
    path: "/events/{eventId}/shifts",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /events/{eventId}/shifts",
  },
  {
    id: "put_events_by_event_id",
    method: "PUT",
    path: "/events/{eventId}",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /events/{eventId}",
  },
  {
    id: "delete_events_by_event_id",
    method: "DELETE",
    path: "/events/{eventId}",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /events/{eventId}",
  },
  {
    id: "get_export_job_types",
    method: "GET",
    path: "/exportJobTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /exportJobTypes",
  },
  {
    id: "post_export_jobs",
    method: "POST",
    path: "/exportJobs",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /exportJobs",
  },
  {
    id: "get_export_jobs_by_export_job_id",
    method: "GET",
    path: "/exportJobs/{exportJobId}",
    pathParameters: ["exportJobId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /exportJobs/{exportJobId}",
  },
  {
    id: "get_codes_extended_source_codes",
    method: "GET",
    path: "/codes/extendedSourceCodes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /codes/extendedSourceCodes",
  },
  {
    id: "post_file_loading_jobs",
    method: "POST",
    path: "/fileLoadingJobs",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /fileLoadingJobs",
  },
  {
    id: "get_file_loading_jobs_by_job_id",
    method: "GET",
    path: "/fileLoadingJobs/{jobId}",
    pathParameters: ["jobId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /fileLoadingJobs/{jobId}",
  },
  {
    id: "get_file_loading_jobs_by_job_id_stats",
    method: "GET",
    path: "/fileLoadingJobs/{jobId}/stats",
    pathParameters: ["jobId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /fileLoadingJobs/{jobId}/stats",
  },
  {
    id: "get_financial_batches",
    method: "GET",
    path: "/financialBatches",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /financialBatches",
  },
  {
    id: "get_financial_batches_by_financial_batch_id",
    method: "GET",
    path: "/financialBatches/{financialBatchId}",
    pathParameters: ["financialBatchId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /financialBatches/{financialBatchId}",
  },
  {
    id: "post_financial_batches",
    method: "POST",
    path: "/financialBatches",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /financialBatches",
  },
  {
    id: "get_folders",
    method: "GET",
    path: "/folders",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /folders",
  },
  {
    id: "get_folders_by_folder_id",
    method: "GET",
    path: "/folders/{folderId}",
    pathParameters: ["folderId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /folders/{folderId}",
  },
  {
    id: "get_folders_by_folder_id_map_regions",
    method: "GET",
    path: "/folders/{folderId}/mapRegions",
    pathParameters: ["folderId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /folders/{folderId}/mapRegions",
  },
  {
    id: "post_folders_by_folder_id_map_regions_refresh",
    method: "POST",
    path: "/folders/{folderId}/mapRegions/refresh",
    pathParameters: ["folderId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /folders/{folderId}/mapRegions/refresh",
  },
  {
    id: "get_folders_by_folder_id_map_regions_by_map_region_id",
    method: "GET",
    path: "/folders/{folderId}/mapRegions/{mapRegionId}",
    pathParameters: ["folderId", "mapRegionId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /folders/{folderId}/mapRegions/{mapRegionId}",
  },
  {
    id: "post_folders_by_folder_id_map_regions_by_map_region_id_refresh",
    method: "POST",
    path: "/folders/{folderId}/mapRegions/{mapRegionId}/refresh",
    pathParameters: ["folderId", "mapRegionId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /folders/{folderId}/mapRegions/{mapRegionId}/refresh",
  },
  {
    id: "get_job_classes",
    method: "GET",
    path: "/jobClasses",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /jobClasses",
  },
  {
    id: "get_job_classes_by_job_class_id",
    method: "GET",
    path: "/jobClasses/{jobClassId}",
    pathParameters: ["jobClassId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /jobClasses/{jobClassId}",
  },
  {
    id: "post_job_classes",
    method: "POST",
    path: "/jobClasses",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /jobClasses",
  },
  {
    id: "get_locations",
    method: "GET",
    path: "/locations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /locations",
  },
  {
    id: "get_locations_by_location_id",
    method: "GET",
    path: "/locations/{locationId}",
    pathParameters: ["locationId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /locations/{locationId}",
  },
  {
    id: "post_locations_find_or_create",
    method: "POST",
    path: "/locations/findOrCreate",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /locations/findOrCreate",
  },
  {
    id: "post_locations",
    method: "POST",
    path: "/locations",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /locations",
  },
  {
    id: "delete_locations_by_location_id",
    method: "DELETE",
    path: "/locations/{locationId}",
    pathParameters: ["locationId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /locations/{locationId}",
  },
  {
    id: "get_member_statuses",
    method: "GET",
    path: "/memberStatuses",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /memberStatuses",
  },
  {
    id: "get_member_statuses_by_member_status_id",
    method: "GET",
    path: "/memberStatuses/{memberStatusId}",
    pathParameters: ["memberStatusId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /memberStatuses/{memberStatusId}",
  },
  {
    id: "post_member_statuses",
    method: "POST",
    path: "/memberStatuses",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /memberStatuses",
  },
  {
    id: "get_minivan_exports",
    method: "GET",
    path: "/minivanExports",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /minivanExports",
  },
  {
    id: "get_minivan_exports_by_minivan_export_id",
    method: "GET",
    path: "/minivanExports/{minivanExportId}",
    pathParameters: ["minivanExportId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /minivanExports/{minivanExportId}",
  },
  {
    id: "get_notes_category_types",
    method: "GET",
    path: "/notes/categoryTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /notes/categoryTypes",
  },
  {
    id: "get_notes_categories",
    method: "GET",
    path: "/notes/categories",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /notes/categories",
  },
  {
    id: "get_notes_categories_by_note_category_id",
    method: "GET",
    path: "/notes/categories/{noteCategoryId}",
    pathParameters: ["noteCategoryId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /notes/categories/{noteCategoryId}",
  },
  {
    id: "get_online_actions_forms",
    method: "GET",
    path: "/onlineActionsForms",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /onlineActionsForms",
  },
  {
    id: "get_online_actions_forms_by_form_tracking_id",
    method: "GET",
    path: "/onlineActionsForms/{formTrackingId}",
    pathParameters: ["formTrackingId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /onlineActionsForms/{formTrackingId}",
  },
  {
    id: "get_printed_lists",
    method: "GET",
    path: "/printedLists",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /printedLists",
  },
  {
    id: "get_printed_lists_by_printed_list_number",
    method: "GET",
    path: "/printedLists/{printedListNumber}",
    pathParameters: ["printedListNumber"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /printedLists/{printedListNumber}",
  },
  {
    id: "get_relationships",
    method: "GET",
    path: "/relationships",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /relationships",
  },
  {
    id: "get_reported_races",
    method: "GET",
    path: "/reportedRaces",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /reportedRaces",
  },
  {
    id: "get_reported_ethnicities",
    method: "GET",
    path: "/reportedEthnicities",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /reportedEthnicities",
  },
  {
    id: "get_reported_language_preferences",
    method: "GET",
    path: "/reportedLanguagePreferences",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /reportedLanguagePreferences",
  },
  {
    id: "get_reported_sexual_orientations",
    method: "GET",
    path: "/reportedSexualOrientations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /reportedSexualOrientations",
  },
  {
    id: "get_reported_genders",
    method: "GET",
    path: "/reportedGenders",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /reportedGenders",
  },
  {
    id: "get_pronouns",
    method: "GET",
    path: "/pronouns",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /pronouns",
  },
  {
    id: "get_saved_lists",
    method: "GET",
    path: "/savedLists",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /savedLists",
  },
  {
    id: "get_saved_lists_by_saved_list_id",
    method: "GET",
    path: "/savedLists/{savedListId}",
    pathParameters: ["savedListId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /savedLists/{savedListId}",
  },
  {
    id: "post_saved_lists_sms_sync",
    method: "POST",
    path: "/savedLists/smsSync",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /savedLists/smsSync",
  },
  {
    id: "get_schedule_types",
    method: "GET",
    path: "/scheduleTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /scheduleTypes",
  },
  {
    id: "get_schedule_types_by_schedule_type_id",
    method: "GET",
    path: "/scheduleTypes/{scheduleTypeId}",
    pathParameters: ["scheduleTypeId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /scheduleTypes/{scheduleTypeId}",
  },
  {
    id: "post_schedule_types",
    method: "POST",
    path: "/scheduleTypes",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /scheduleTypes",
  },
  {
    id: "get_score_updates",
    method: "GET",
    path: "/scoreUpdates",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /scoreUpdates",
  },
  {
    id: "get_score_updates_by_score_update_id",
    method: "GET",
    path: "/scoreUpdates/{scoreUpdateId}",
    pathParameters: ["scoreUpdateId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /scoreUpdates/{scoreUpdateId}",
  },
  {
    id: "patch_score_updates_by_score_update_id",
    method: "PATCH",
    path: "/scoreUpdates/{scoreUpdateId}",
    pathParameters: ["scoreUpdateId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /scoreUpdates/{scoreUpdateId}",
  },
  {
    id: "get_scores",
    method: "GET",
    path: "/scores",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /scores",
  },
  {
    id: "get_scores_by_score_id",
    method: "GET",
    path: "/scores/{scoreId}",
    pathParameters: ["scoreId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /scores/{scoreId}",
  },
  {
    id: "get_scores_by_score_id_committee_access",
    method: "GET",
    path: "/scores/{scoreId}/committeeAccess",
    pathParameters: ["scoreId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /scores/{scoreId}/committeeAccess",
  },
  {
    id: "get_shift_types",
    method: "GET",
    path: "/shiftTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /shiftTypes",
  },
  {
    id: "get_shift_types_by_shift_type_id",
    method: "GET",
    path: "/shiftTypes/{shiftTypeId}",
    pathParameters: ["shiftTypeId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /shiftTypes/{shiftTypeId}",
  },
  {
    id: "post_shift_types",
    method: "POST",
    path: "/shiftTypes",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /shiftTypes",
  },
  {
    id: "get_signups_statuses",
    method: "GET",
    path: "/signups/statuses",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /signups/statuses",
  },
  {
    id: "get_signups_by_event_signup_id",
    method: "GET",
    path: "/signups/{eventSignupId}",
    pathParameters: ["eventSignupId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /signups/{eventSignupId}",
  },
  {
    id: "get_signups",
    method: "GET",
    path: "/signups",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /signups",
  },
  {
    id: "post_signups",
    method: "POST",
    path: "/signups",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /signups",
  },
  {
    id: "put_signups_by_event_signup_id",
    method: "PUT",
    path: "/signups/{eventSignupId}",
    pathParameters: ["eventSignupId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /signups/{eventSignupId}",
  },
  {
    id: "delete_signups_by_event_signup_id",
    method: "DELETE",
    path: "/signups/{eventSignupId}",
    pathParameters: ["eventSignupId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /signups/{eventSignupId}",
  },
  {
    id: "get_stories_by_story_id",
    method: "GET",
    path: "/stories/{storyId}",
    pathParameters: ["storyId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /stories/{storyId}",
  },
  {
    id: "post_stories",
    method: "POST",
    path: "/stories",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /stories",
  },
  {
    id: "get_supporter_groups",
    method: "GET",
    path: "/supporterGroups",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /supporterGroups",
  },
  {
    id: "post_supporter_groups",
    method: "POST",
    path: "/supporterGroups",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /supporterGroups",
  },
  {
    id: "delete_supporter_groups_by_supporter_group_id",
    method: "DELETE",
    path: "/supporterGroups/{supporterGroupId}",
    pathParameters: ["supporterGroupId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /supporterGroups/{supporterGroupId}",
  },
  {
    id: "get_supporter_groups_by_supporter_group_id",
    method: "GET",
    path: "/supporterGroups/{supporterGroupId}",
    pathParameters: ["supporterGroupId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /supporterGroups/{supporterGroupId}",
  },
  {
    id: "put_supporter_groups_by_supporter_group_id_people_by_van_id",
    method: "PUT",
    path: "/supporterGroups/{supporterGroupId}/people/{vanId}",
    pathParameters: ["supporterGroupId", "vanId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /supporterGroups/{supporterGroupId}/people/{vanId}",
  },
  {
    id: "delete_supporter_groups_by_supporter_group_id_people_by_van_id",
    method: "DELETE",
    path: "/supporterGroups/{supporterGroupId}/people/{vanId}",
    pathParameters: ["supporterGroupId", "vanId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /supporterGroups/{supporterGroupId}/people/{vanId}",
  },
  {
    id: "get_survey_questions",
    method: "GET",
    path: "/surveyQuestions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /surveyQuestions",
  },
  {
    id: "get_survey_questions_by_survey_question_id",
    method: "GET",
    path: "/surveyQuestions/{surveyQuestionId}",
    pathParameters: ["surveyQuestionId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /surveyQuestions/{surveyQuestionId}",
  },
  {
    id: "post_survey_questions",
    method: "POST",
    path: "/surveyQuestions",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /surveyQuestions",
  },
  {
    id: "put_survey_questions_by_survey_question_id",
    method: "PUT",
    path: "/surveyQuestions/{surveyQuestionId}",
    pathParameters: ["surveyQuestionId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /surveyQuestions/{surveyQuestionId}",
  },
  {
    id: "post_target_export_jobs",
    method: "POST",
    path: "/targetExportJobs",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /targetExportJobs",
  },
  {
    id: "get_target_export_jobs_by_export_job_id",
    method: "GET",
    path: "/targetExportJobs/{exportJobId}",
    pathParameters: ["exportJobId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /targetExportJobs/{exportJobId}",
  },
  {
    id: "get_targets",
    method: "GET",
    path: "/targets",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /targets",
  },
  {
    id: "get_targets_by_target_id",
    method: "GET",
    path: "/targets/{targetId}",
    pathParameters: ["targetId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /targets/{targetId}",
  },
  {
    id: "get_users_by_user_id_district_field_values",
    method: "GET",
    path: "/users/{userId}/districtFieldValues",
    pathParameters: ["userId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /users/{userId}/districtFieldValues",
  },
  {
    id: "post_users_by_user_id_district_field_values",
    method: "POST",
    path: "/users/{userId}/districtFieldValues",
    pathParameters: ["userId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /users/{userId}/districtFieldValues",
  },
  {
    id: "put_users_by_user_id_district_field_values",
    method: "PUT",
    path: "/users/{userId}/districtFieldValues",
    pathParameters: ["userId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /users/{userId}/districtFieldValues",
  },
  {
    id: "get_voter_registration_batches",
    method: "GET",
    path: "/voterRegistrationBatches",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /voterRegistrationBatches",
  },
  {
    id: "get_voter_registration_batches_program_types",
    method: "GET",
    path: "/voterRegistrationBatches/programTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /voterRegistrationBatches/programTypes",
  },
  {
    id: "get_voter_registration_batches_registration_forms",
    method: "GET",
    path: "/voterRegistrationBatches/registrationForms",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /voterRegistrationBatches/registrationForms",
  },
  {
    id: "get_voter_registration_batches_state_by_state_supported_fields",
    method: "GET",
    path: "/voterRegistrationBatches/state/{state}/supportedFields",
    pathParameters: ["state"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /voterRegistrationBatches/state/{state}/supportedFields",
  },
  {
    id: "post_voter_registration_batches",
    method: "POST",
    path: "/voterRegistrationBatches",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "POST /voterRegistrationBatches",
  },
  {
    id: "patch_voter_registration_batches_by_batch_id",
    method: "PATCH",
    path: "/voterRegistrationBatches/{batchId}",
    pathParameters: ["batchId"],
    mutating: true,
    bodyAllowed: true,
    description: "PATCH /voterRegistrationBatches/{batchId}",
  },
  {
    id: "post_voter_registration_batches_by_batch_id_people",
    method: "POST",
    path: "/voterRegistrationBatches/{batchId}/people",
    pathParameters: ["batchId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /voterRegistrationBatches/{batchId}/people",
  },
  {
    id: "get_worksites",
    method: "GET",
    path: "/worksites",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "GET /worksites",
  },
  {
    id: "get_worksites_by_worksite_id",
    method: "GET",
    path: "/worksites/{worksiteId}",
    pathParameters: ["worksiteId"],
    mutating: false,
    bodyAllowed: false,
    description: "GET /worksites/{worksiteId}",
  },
  {
    id: "put_worksites_by_worksite_id",
    method: "PUT",
    path: "/worksites/{worksiteId}",
    pathParameters: ["worksiteId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /worksites/{worksiteId}",
  },
  {
    id: "delete_worksites_by_worksite_id",
    method: "DELETE",
    path: "/worksites/{worksiteId}",
    pathParameters: ["worksiteId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /worksites/{worksiteId}",
  },
  {
    id: "post_worksites_by_worksite_id_work_areas",
    method: "POST",
    path: "/worksites/{worksiteId}/workAreas",
    pathParameters: ["worksiteId"],
    mutating: true,
    bodyAllowed: true,
    description: "POST /worksites/{worksiteId}/workAreas",
  },
  {
    id: "put_worksites_by_worksite_id_work_areas_by_work_area_id",
    method: "PUT",
    path: "/worksites/{worksiteId}/workAreas/{workAreaId}",
    pathParameters: ["worksiteId", "workAreaId"],
    mutating: true,
    bodyAllowed: true,
    description: "PUT /worksites/{worksiteId}/workAreas/{workAreaId}",
  },
  {
    id: "delete_worksites_by_worksite_id_work_areas_by_work_area_id",
    method: "DELETE",
    path: "/worksites/{worksiteId}/workAreas/{workAreaId}",
    pathParameters: ["worksiteId", "workAreaId"],
    mutating: true,
    bodyAllowed: false,
    description: "DELETE /worksites/{worksiteId}/workAreas/{workAreaId}",
  },
] as const satisfies readonly BoundedRestOperation[];

export const EVERYACTION_READ_OPERATION_IDS = EVERYACTION_OPERATIONS.filter(
  (item) => !item.mutating,
).map((item) => item.id);
export const EVERYACTION_MANAGE_OPERATION_IDS = EVERYACTION_OPERATIONS.filter(
  (item) => item.mutating,
).map((item) => item.id);

export const EVERYACTION_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "everyaction",
  name: "EveryAction",
  baseUrl: "https://api.securevan.com/v4/",
  basicAuthorization: {
    usernameCredentialName: "EVERYACTION_APPLICATION_NAME",
    passwordCredentialName: "EVERYACTION_API_KEY",
  },
  operations: EVERYACTION_OPERATIONS,
  health: { operationId: "get_canvass_responses_contact_types" },
};
