import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Pinned from the official Lead Gen & CRM Open API methods page on 2026-07-18. */
export const CONSTANT_CONTACT_LEAD_GEN_METHODS = [
  "createAccounts",
  "deleteAccounts",
  "getAccount",
  "getAccounts",
  "getAccountsDateRange",
  "updateAccounts",
  "createCampaigns",
  "deleteCampaigns",
  "getCampaign",
  "getCampaigns",
  "getCampaignsDateRange",
  "updateCampaigns",
  "getClients",
  "createSendMail",
  "createDealStages",
  "deleteDealStages",
  "getDealStage",
  "getDealStages",
  "getDealStagesDateRange",
  "createEmail",
  "deleteEmail",
  "getEmail",
  "getEmailListing",
  "updateEmail",
  "deleteScheduleSend",
  "getEmailEvents",
  "getEmailSendEvents",
  "getEmailSendStatus",
  "getScheduleSendStatus",
  "getScheduleSends",
  "getSendCount",
  "addEmailVariable",
  "createEmailVariable",
  "createEmailVariables",
  "deleteEmailVariable",
  "getEmailVariables",
  "setEmailVariable",
  "getEventsByType",
  "createFields",
  "deleteFields",
  "getFields",
  "updateFields",
  "createFolder",
  "createFolders",
  "deleteFolder",
  "getFolders",
  "updateFolder",
  "getRelatedLeadsByEmail",
  "getListTags",
  "createLeads",
  "deleteLeads",
  "getLead",
  "getLeads",
  "getLeadsDateRange",
  "subscribeToLeadUpdates",
  "updateLeads",
  "updateLeadsV2",
  "createList",
  "deleteList",
  "getActiveLists",
  "updateList",
  "addListMember",
  "addListMemberEmailAddress",
  "addListMembers",
  "addListMembersEmailAddress",
  "getContactListMemberships",
  "getEmailSend",
  "getListMemberships",
  "removeListMember",
  "removeListMemberEmailAddress",
  "removeListMembers",
  "removeListMembersEmailAddress",
  "removeListMembersAll",
  "createNotes",
  "deleteNotes",
  "getAccountNotes",
  "getAccountsNotes",
  "getContactNotes",
  "getContactsNotes",
  "getOpportunitiesNotes",
  "getOpportunityNotes",
  "updateNotes",
  "createOpportunities",
  "deleteOpportunities",
  "getOpportunities",
  "getOpportunitiesDateRange",
  "getOpportunity",
  "updateOpportunities",
  "createOpportunityLeads",
  "deleteOpportunityLeads",
  "getOpportunityLead",
  "getOpportunityLeads",
  "getOpportunityLeadsDateRange",
  "createProduct",
  "createProducts",
  "deleteProduct",
  "getProducts",
  "updateProduct",
  "getUnsubscribeCategories",
  "getUserProfiles",
  "createTasks",
  "deleteTasks",
  "getTasks",
  "updateTasks",
  "updateAccountSendLimit",
  "createClient",
  "updateClient",
  "disableAccountSending",
  "enableAccountSending",
  "logCalls",
  "getEmailJobs",
  "getLeadListMemberships",
  "getLeadTimeline",
  "getRemovedListMembers",
  "getListMembers",
] as const;

const methodOperation = (
  rpcMethod: (typeof CONSTANT_CONTACT_LEAD_GEN_METHODS)[number],
): BoundedRestOperation => ({
  id: rpcMethod,
  method: "POST",
  path: "/",
  pathParameters: [],
  mutating: !rpcMethod.startsWith("get"),
  bodyAllowed: true,
  bodyEncoding: "json_rpc_method",
  rpcMethod,
  description: `Run the pinned ${rpcMethod} method`,
});

export const CONSTANT_CONTACT_LEAD_GEN_OPERATIONS: readonly BoundedRestOperation[] =
  CONSTANT_CONTACT_LEAD_GEN_METHODS.map(methodOperation);

export const CONSTANT_CONTACT_LEAD_GEN_READ_OPERATION_IDS =
  CONSTANT_CONTACT_LEAD_GEN_OPERATIONS.filter((item) => !item.mutating).map(
    (item) => item.id,
  );

export const CONSTANT_CONTACT_LEAD_GEN_MANAGE_OPERATION_IDS =
  CONSTANT_CONTACT_LEAD_GEN_OPERATIONS.filter((item) => item.mutating).map(
    (item) => item.id,
  );

export const CONSTANT_CONTACT_LEAD_GEN_BOUNDED_REST_CONNECTOR: BoundedRestConnector =
  {
    slug: "constant-contact-lead-gen",
    name: "Constant Contact Lead Gen & CRM",
    baseUrl: "https://api.sharpspring.com/pubapi/v1.2/",
    credentialHeaders: [
      {
        headerName: "X-Account-Id",
        credentialName: "CONSTANT_CONTACT_LEAD_GEN_ACCOUNT_ID",
      },
      {
        headerName: "Authorization",
        credentialName: "CONSTANT_CONTACT_LEAD_GEN_SECRET_KEY",
        prefix: "Bearer ",
      },
    ],
    maxArrayItems: 500,
    operations: CONSTANT_CONTACT_LEAD_GEN_OPERATIONS,
    health: { operationId: "getUserProfiles" },
  };
