import { action, capability } from "../../catalog/marketplace-catalog.types";
import type { MarketplaceConnectorManifest } from "../types";
import {
  CONSTANT_CONTACT_LEAD_GEN_MANAGE_OPERATION_IDS,
  CONSTANT_CONTACT_LEAD_GEN_OPERATIONS,
  CONSTANT_CONTACT_LEAD_GEN_READ_OPERATION_IDS,
} from "./constant-contact-lead-gen-operation-registry";

const read = action(
  "constant_contact_lead_gen_read",
  "Read Lead Gen & CRM data",
  "Read contacts, accounts, opportunities, campaigns, email activity and administration data; Safe mode requires approval.",
);
const manage = action(
  "constant_contact_lead_gen_manage",
  "Manage Lead Gen & CRM",
  "Create, update or delete CRM records, lists and email, or change client and sending controls; Safe mode requires approval.",
);

const tool = (
  suffix: "read" | "manage",
  capabilityId: string,
  actionType: "read" | "write",
  operations: readonly string[],
) => ({
  name: `constant-contact-lead-gen.${suffix}`,
  functionName: `constant_contact_lead_gen_${suffix}`,
  aliases: [
    `constant-contact-lead-gen.${suffix}`,
    `constant_contact_lead_gen_${suffix}`,
  ],
  capability: capabilityId,
  platformCapability: capabilityId,
  action: actionType,
  approvalRequired: true,
  description: `Run one pinned Lead Gen & CRM ${suffix} method; Safe mode requires approval.`,
  inputSchema: {
    type: "object" as const,
    properties: {
      operation: { type: "string", enum: [...operations] },
      json: {},
      approvalId: { type: "string", maxLength: 200 },
    },
    required: ["operation"],
    additionalProperties: false,
  },
});

export const CONSTANT_CONTACT_LEAD_GEN_CONNECTOR_MANIFEST: MarketplaceConnectorManifest =
  {
    slug: "constant-contact-lead-gen",
    name: "Constant Contact Lead Gen & CRM",
    connectorType: "native_clawchat",
    providerDocsUrl:
      "https://knowledgebase.constantcontact.com/lead-gen-crm/articles/KnowledgeBase/50374-Understanding-Lead-Gen--CRM-Open-API-Overview?lang=en_US",
    providerWebsiteUrl: "https://www.constantcontact.com/lead-gen-crm",
    capabilities: [
      {
        ...capability(
          "constant_contact_lead_gen_read",
          "Read CRM and email data",
          `Use all ${CONSTANT_CONTACT_LEAD_GEN_READ_OPERATION_IDS.length} current documented reads under approval.`,
          true,
        ),
        platformCapability: "constant_contact_lead_gen_read",
      },
      {
        ...capability(
          "constant_contact_lead_gen_manage",
          "Manage CRM, clients and email",
          `Use all ${CONSTANT_CONTACT_LEAD_GEN_MANAGE_OPERATION_IDS.length} current documented mutations under approval.`,
          true,
        ),
        platformCapability: "constant_contact_lead_gen_manage",
      },
    ],
    auth: {
      type: "api_key",
      credentialSchema: [
        {
          name: "CONSTANT_CONTACT_LEAD_GEN_ACCOUNT_ID",
          label: "Lead Gen & CRM account ID",
          required: true,
          secret: false,
          storedIn: "encrypted_secret",
          requiredForAuthTypes: ["api_key"],
          helpText:
            "The exact account ID generated by a Lead Gen & CRM administrator; Relay sends it only as X-Account-Id.",
        },
        {
          name: "CONSTANT_CONTACT_LEAD_GEN_SECRET_KEY",
          label: "Lead Gen & CRM secret key",
          required: true,
          secret: true,
          storedIn: "encrypted_secret",
          requiredForAuthTypes: ["api_key"],
          helpText:
            "A dedicated administrator-generated secret key; Relay encrypts it and sends it only to api.sharpspring.com as a bearer credential.",
        },
      ],
    },
    tools: [
      tool(
        "read",
        "constant_contact_lead_gen_read",
        "read",
        CONSTANT_CONTACT_LEAD_GEN_READ_OPERATION_IDS,
      ),
      tool(
        "manage",
        "constant_contact_lead_gen_manage",
        "write",
        CONSTANT_CONTACT_LEAD_GEN_MANAGE_OPERATION_IDS,
      ),
    ],
    approvalProfiles: [
      {
        id: "constant_contact_lead_gen_safe",
        label: "Safe",
        description:
          "Every CRM/email read and mutation requires approval because the API contains personal records and real bulk-email and client controls.",
        defaultSelected: true,
        allowedActions: [],
        approvalRequiredActions: [read, manage],
        blockedActions: [],
      },
      {
        id: "dangerously_skip_permissions",
        label: "Dangerously skip permissions",
        description: `All ${CONSTANT_CONTACT_LEAD_GEN_OPERATIONS.length} pinned methods run without Relay per-action approval; fixed origin, server-bound method names, 500-object bounds, encrypted credentials, audits and provider limits still apply.`,
        defaultSelected: false,
        allowedActions: [read, manage],
        approvalRequiredActions: [],
        blockedActions: [],
      },
    ],
    healthChecks: [
      {
        id: "account_id_and_secret_key",
        label: "Lead Gen & CRM account and secret key check",
      },
    ],
  };
