import { action, capability } from "../../catalog/marketplace-catalog.types";
import type { MarketplaceConnectorManifest } from "../types";

const reads = [
  action(
    "tresorit_list_main_folders",
    "List main folders",
    "List a bounded page of Tresorit main folders exposed by the customer's gateway.",
  ),
  action(
    "tresorit_list_files",
    "List files",
    "List a bounded page of files in one main folder.",
  ),
  action(
    "tresorit_read_file_metadata",
    "Read file metadata",
    "Read metadata for one file.",
  ),
  action(
    "tresorit_download_file",
    "Download file",
    "Download one file up to Relay's five-megabyte agent response limit.",
  ),
];

const writes = [
  action(
    "tresorit_create_main_folder",
    "Create main folder",
    "Create one Tresorit main folder; Safe mode requires approval.",
  ),
  action(
    "tresorit_delete_main_folder",
    "Delete main folder",
    "Delete one empty Tresorit main folder; Safe mode requires approval.",
  ),
  action(
    "tresorit_upload_file",
    "Upload file",
    "Upload one file up to five megabytes; Safe mode requires approval.",
  ),
  action(
    "tresorit_delete_file",
    "Delete file",
    "Delete one file; Safe mode requires approval.",
  ),
  action(
    "tresorit_delete_files",
    "Delete files",
    "Delete up to 100 explicitly named files; Safe mode requires approval.",
  ),
];

const commonProperties = {
  bucket: { type: "string", minLength: 1, maxLength: 200 },
  key: { type: "string", minLength: 1, maxLength: 1_024 },
  prefix: { type: "string", maxLength: 1_024 },
  maxKeys: { type: "integer", minimum: 1, maximum: 100 },
};

export const TRESORIT_CONNECTOR_MANIFEST: MarketplaceConnectorManifest = {
  slug: "tresorit",
  name: "Tresorit",
  connectorType: "native_clawchat",
  providerDocsUrl:
    "https://support.tresorit.com/hc/en-us/articles/33971802915858-Tresorit-API",
  providerWebsiteUrl: "https://tresorit.com/",
  capabilities: [
    {
      ...capability(
        "storage_read",
        "Read secure storage",
        "List main folders and files, inspect metadata, and download bounded files through the customer's Tresorit S3 gateway.",
        true,
      ),
      platformCapability: "tresorit_storage_read",
    },
    {
      ...capability(
        "storage_write",
        "Manage secure storage",
        "Create and delete main folders, upload files, and delete explicitly selected files through the customer's gateway.",
        true,
      ),
      platformCapability: "tresorit_storage_write",
    },
  ],
  auth: {
    type: "api_key",
    credentialSchema: [
      {
        name: "TRESORIT_S3_ENDPOINT",
        label: "Tresorit gateway URL",
        required: true,
        secret: false,
        storedIn: "metadata",
        requiredForAuthTypes: ["api_key"],
        helpText:
          "Enter the public HTTPS address of your Tresorit S3 gateway. The local default address cannot be reached by Relay Console.",
      },
      {
        name: "TRESORIT_S3_ACCESS_KEY_ID",
        label: "Access key ID",
        required: true,
        secret: true,
        storedIn: "encrypted_secret",
        requiredForAuthTypes: ["api_key"],
        helpText:
          "Copy client_id from the credentials generated by the Tresorit API setup.",
      },
      {
        name: "TRESORIT_S3_SECRET_ACCESS_KEY",
        label: "Secret access key",
        required: true,
        secret: true,
        storedIn: "encrypted_secret",
        requiredForAuthTypes: ["api_key"],
        helpText:
          "Copy client_secret from the credentials generated by the Tresorit API setup.",
      },
    ],
  },
  tools: [
    {
      name: "tresorit.read",
      functionName: "tresorit_read",
      aliases: ["tresorit.read", "tresorit_read"],
      capability: "storage_read",
      platformCapability: "tresorit_storage_read",
      action: "read",
      approvalRequired: false,
      description:
        "Run one documented, bounded read against the configured Tresorit S3 gateway.",
      inputSchema: {
        type: "object",
        properties: {
          operation: {
            type: "string",
            enum: ["listBuckets", "listObjects", "headObject", "getObject"],
          },
          ...commonProperties,
        },
        required: ["operation"],
        additionalProperties: false,
      },
    },
    {
      name: "tresorit.manage",
      functionName: "tresorit_manage",
      aliases: ["tresorit.manage", "tresorit_manage"],
      capability: "storage_write",
      platformCapability: "tresorit_storage_write",
      action: "write",
      approvalRequired: true,
      description:
        "Run one documented, bounded mutation against the configured Tresorit S3 gateway.",
      inputSchema: {
        type: "object",
        properties: {
          operation: {
            type: "string",
            enum: [
              "createBucket",
              "deleteBucket",
              "putObject",
              "deleteObject",
              "deleteObjects",
            ],
          },
          ...commonProperties,
          fileBase64: { type: "string", maxLength: 7_000_000 },
          contentType: { type: "string", maxLength: 200 },
          keys: {
            type: "array",
            minItems: 1,
            maxItems: 100,
            uniqueItems: true,
            items: { type: "string", minLength: 1, maxLength: 1_024 },
          },
          approvalId: { type: "string", maxLength: 200 },
        },
        required: ["operation"],
        additionalProperties: false,
      },
    },
  ],
  approvalProfiles: [
    {
      id: "tresorit_safe",
      label: "Safe",
      description:
        "Bounded main-folder, file-list, metadata, and download reads run directly; creation, upload, and deletion require approval.",
      defaultSelected: true,
      allowedActions: reads,
      approvalRequiredActions: writes,
      blockedActions: [],
    },
    {
      id: "dangerously_skip_permissions",
      label: "Dangerously skip permissions",
      description:
        "Every selected gateway-authorized Tresorit operation runs without Relay per-action approval; ownership, the configured HTTPS endpoint, bounds, auditing, redaction, gateway permissions, and provider limits still apply.",
      defaultSelected: false,
      allowedActions: [...reads, ...writes],
      approvalRequiredActions: [],
      blockedActions: [],
    },
  ],
  healthChecks: [
    {
      id: "list-main-folders",
      label: "Tresorit gateway and credential validation",
    },
  ],
};
