// Generated from Egnyte's official OpenAPI 3.0.3 specification (info version 1.3.2).
// Source SHA-256: 6dfc66a5060219d42b8d6f0c95e62812f29f531e6d53bd90ad2ff43ce2f97a05
// Evidence date: 2026-07-14. Four explicitly deprecated operations are intentionally excluded.

export type EgnyteOperation = {
  id: string;
  summary: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  tags: readonly string[];
  pathParameters: readonly string[];
  queryParameters: readonly string[];
  headerParameters: readonly string[];
  bodyParameters: readonly string[];
  bodyMode: "none" | "json" | "multipart" | "form";
  responseMode: "json" | "binary";
};

export const EGNYTE_OPERATIONS = [
  {
    id: "addComment",
    summary: "Add Comment",
    method: "POST",
    path: "/v1/notes",
    tags: ["comments"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["body", "path"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "addDocument",
    summary: "Add Documents",
    method: "POST",
    path: "/v1/etmf/studies/{studyId}/documents",
    tags: ["etmf"],
    pathParameters: ["studyId"],
    queryParameters: ["filingLevel.systemId", "filingLevel.type"],
    headerParameters: [],
    bodyParameters: ["classification", "filingLevel", "sourceFile"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "advancedSearchV1",
    summary: "Advanced search (v1)",
    method: "POST",
    path: "/v1/advanced_search",
    tags: ["search"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "keywords",
      "owners",
      "path",
      "sizeGreaterThan",
      "sizeLessThan",
      "uploadedAfter",
      "uploadedBefore",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "ask-agent",
    summary: "Ask a question to an agent",
    method: "POST",
    path: "/v1/ai/agents/{agentId}/ask",
    tags: ["agents"],
    pathParameters: ["agentId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "chatHistory",
      "conversationId",
      "entryIds",
      "instructions",
      "question",
      "selectedItems",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "ask-assistant",
    summary: "Ask AI Assistant a question (async)",
    method: "POST",
    path: "/v1/ai/assistant/ask",
    tags: ["ai"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "chatHistory",
      "conversationId",
      "includeCitations",
      "mcpSelectionId",
      "modelDetails",
      "question",
      "selectedItems",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "ask-document",
    summary: "Ask a question about a document",
    method: "POST",
    path: "/v1/ai/document/{entry-id}/ask",
    tags: ["ai"],
    pathParameters: ["entry-id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["chatHistory", "includeCitations", "question"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "ask-kb",
    summary: "Ask a question about a knowledge base",
    method: "POST",
    path: "/v1/ai/kb/{kb-id}/ask",
    tags: ["ai"],
    pathParameters: ["kb-id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["chatHistory", "includeCitations", "question"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "cancel-signature-request",
    summary: "Cancel Signature Request",
    method: "POST",
    path: "/v1/egnyte-sign/signature-requests/{agreement_id}/cancel",
    tags: ["sign"],
    pathParameters: ["agreement_id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["message"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "cancel-workflow",
    summary: "Cancel a workflow",
    method: "POST",
    path: "/v1/workflows/{workflowId}/cancel",
    tags: ["workflows"],
    pathParameters: ["workflowId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "checkAuditReportStatus",
    summary: "Check Audit Report Generation Status",
    method: "GET",
    path: "/v1/audit/jobs/{id}",
    tags: ["v1-reports"],
    pathParameters: ["id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "complete-webhook-task",
    summary: "Send completion signal for a webhook task",
    method: "POST",
    path: "/v1/workflows/{workflowId}/tasks/{taskId}/completion-signal",
    tags: ["workflows"],
    pathParameters: ["taskId", "workflowId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "create-signature-request",
    summary: "Create Signature Request",
    method: "POST",
    path: "/v1/egnyte-sign/signature-requests",
    tags: ["sign"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "email_message",
      "recipients",
      "signature_request_name",
      "template_id",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "create-user",
    summary: "Create a user",
    method: "POST",
    path: "/v2/users",
    tags: ["users"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "active",
      "authType",
      "email",
      "externalId",
      "idpUserId",
      "language",
      "name",
      "role",
      "sendInvite",
      "userName",
      "userPrincipalName",
      "userType",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "create-workflow",
    summary: "Create a workflow",
    method: "POST",
    path: "/v1/workflows",
    tags: ["workflows"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "file",
      "name",
      "reasonForChange",
      "steps",
      "workflowType",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createBookmark",
    summary: "Create Bookmark",
    method: "POST",
    path: "/v1/bookmarks",
    tags: ["bookmarks"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["folder_id", "path"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createConfigurationSettingsAuditReport",
    summary: "Create Configuration Settings Audit Report",
    method: "POST",
    path: "/v1/audit/workgroup-settings",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "format",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createEtmfAuditReport",
    summary: "Create eTMF Audit Report",
    method: "POST",
    path: "/v1/audit/etmf",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "etmf_actions",
      "etmf_artifact_number",
      "etmf_study_ids",
      "format",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createFileAuditReport",
    summary: "Create File Audit Report",
    method: "POST",
    path: "/v1/audit/files",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "file",
      "folders",
      "format",
      "suppress_emails",
      "transaction_type",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createGroupProvisioningAuditReport",
    summary: "Create Group Provisioning Audit Report",
    method: "POST",
    path: "/v1/audit/groups",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "action_type",
      "date_end",
      "date_start",
      "format",
      "groups",
      "include_system_actions",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createLoginAuditReport",
    summary: "Create Login Audit Report",
    method: "POST",
    path: "/v1/audit/logins",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "access_points",
      "date_end",
      "date_start",
      "events",
      "format",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createMspWebhook",
    summary: "Register a Webhook",
    method: "POST",
    path: "/v1/msp/webhooks",
    tags: ["Webhooks"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "auth_header",
      "auth_header_value",
      "event_types",
      "webhook_url",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createPermissionsAuditReport",
    summary: "Create Permissions Audit Report",
    method: "POST",
    path: "/v1/audit/permissions",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "assignee_groups",
      "assignee_users",
      "assigners",
      "date_end",
      "date_start",
      "folders",
      "format",
      "suppress_emails",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createQualityDocsAuditReport",
    summary: "Create Quality Docs Audit Report",
    method: "POST",
    path: "/v1/audit/quality-docs",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "format",
      "quality_docs_actions",
      "quality_docs_categories",
      "quality_docs_statuses",
      "quality_document_id",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createQualityDocsCategoriesAuditReport",
    summary: "Create Quality Docs Categories Audit Report",
    method: "POST",
    path: "/v1/audit/quality-docs-categories",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "format",
      "quality_docs_categories",
      "quality_docs_categories_actions",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createQualityDocsCoursesAuditReport",
    summary: "Create Quality Docs Courses Audit Report",
    method: "POST",
    path: "/v1/audit/quality-docs-courses",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "format",
      "quality_docs_courses_actions",
      "quality_docs_courses_ids",
      "quality_docs_courses_parameters",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createScimGroup",
    summary: "Create group",
    method: "POST",
    path: "/scim/v2/Groups",
    tags: ["scim"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["displayName", "id", "members"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createScimUser",
    summary: "Create user",
    method: "POST",
    path: "/scim/v2/Users",
    tags: ["scim"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "active",
      "emails",
      "externalId",
      "groups",
      "id",
      "name",
      "userName",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createSnapshotRestoreAuditReport",
    summary: "Create Snapshot Restore Audit Report",
    method: "POST",
    path: "/v1/audit/snapshot-restore",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "format",
      "include_system_actions",
      "suppress_emails",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createSync",
    summary: "Create sync project",
    method: "POST",
    path: "/v1/procore/sync",
    tags: ["procore"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "companyId",
      "folderPath",
      "procoreFolderPaths",
      "procoreProjectId",
    ],
    bodyMode: "form",
    responseMode: "json",
  },
  {
    id: "createUploadRequest",
    summary: "Create Upload Request",
    method: "POST",
    path: "/v1/upload-requests",
    tags: ["Upload Requests"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "assigneeInstructions",
      "assignees",
      "dueDate",
      "folderId",
      "name",
      "templateId",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createUploadRequestsAuditReport",
    summary: "Create Upload Requests Audit Report",
    method: "POST",
    path: "/v1/audit/upload-requests",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "format",
      "suppress_emails",
      "upload_requests_actions",
      "users",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createUserProvisioningAuditReport",
    summary: "Create User Provisioning Audit Report",
    method: "POST",
    path: "/v1/audit/users",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "action_type",
      "date_end",
      "date_start",
      "format",
      "include_system_actions",
      "performed_by",
      "subject",
      "suppress_emails",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createWorkflowAuditReport",
    summary: "Create Workflow Audit Report",
    method: "POST",
    path: "/v1/audit/workflows",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "file",
      "format",
      "suppress_emails",
      "users",
      "workflow_actions",
      "workflow_types",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createWorkflowTemplatesAuditReport",
    summary: "Create Workflow Templates Audit Report",
    method: "POST",
    path: "/v1/audit/workflow-templates",
    tags: ["v1-reports"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "date_end",
      "date_start",
      "format",
      "suppress_emails",
      "users",
      "workflow_template_actions",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "createWorkspace",
    summary: "Create Workspace",
    method: "POST",
    path: "/v1/document-portal/workspaces",
    tags: ["Workspaces"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "name",
      "status",
      "type",
      "variables",
      "workspaceFolderId",
      "workspaceParentFolderId",
      "workspaceTemplateId",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "delete-user",
    summary: "Delete a user",
    method: "DELETE",
    path: "/v2/users/{id}",
    tags: ["users"],
    pathParameters: ["id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "delete-webhook",
    summary: "Unregister a webhook",
    method: "DELETE",
    path: "/v1/webhooks/{webhookId}",
    tags: ["webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "deleteBookmark",
    summary: "Delete Bookmark",
    method: "DELETE",
    path: "/v1/bookmarks/{id}",
    tags: ["bookmarks"],
    pathParameters: ["id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "deleteComment",
    summary: "Delete Comment",
    method: "DELETE",
    path: "/v1/notes/{UUID}",
    tags: ["comments"],
    pathParameters: ["UUID"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "deleteMspWebhook",
    summary: "Unregister a Webhook",
    method: "DELETE",
    path: "/v1/msp/webhooks/{webhookId}",
    tags: ["Webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "deleteScimGroup",
    summary: "Delete group",
    method: "DELETE",
    path: "/scim/v2/Groups/{groupId}",
    tags: ["scim"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "deleteScimUser",
    summary: "Delete user",
    method: "DELETE",
    path: "/scim/v2/Users/{userId}",
    tags: ["scim"],
    pathParameters: ["userId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-agent-ask-status",
    summary: "Get agent execution status",
    method: "GET",
    path: "/v1/ai/agents/{agentId}/ask/{requestId}/status",
    tags: ["agents"],
    pathParameters: ["agentId", "requestId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-assistant-status",
    summary: "Get AI Assistant execution status",
    method: "GET",
    path: "/v1/ai/assistant/{executionId}/status",
    tags: ["ai"],
    pathParameters: ["executionId"],
    queryParameters: ["includeCitations"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-sign-template",
    summary: "Get Template Details",
    method: "GET",
    path: "/v1/egnyte-sign/templates/{template_id}",
    tags: ["sign"],
    pathParameters: ["template_id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-user",
    summary: "Get a single user",
    method: "GET",
    path: "/v2/users/{id}",
    tags: ["users"],
    pathParameters: ["id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-userinfo",
    summary: "Get user information for a token",
    method: "GET",
    path: "/v1/userinfo",
    tags: ["tokens"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-webhook-details",
    summary: "Get webhook details",
    method: "GET",
    path: "/v1/webhooks/{webhookId}/details",
    tags: ["webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-webhook-status",
    summary: "Get webhook status",
    method: "GET",
    path: "/v1/webhooks/{webhookId}/status",
    tags: ["webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "get-workflow",
    summary: "Get workflow details",
    method: "GET",
    path: "/v1/workflows/{workflowId}",
    tags: ["workflows"],
    pathParameters: ["workflowId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getBookmark",
    summary: "Get Bookmark by ID",
    method: "GET",
    path: "/v1/bookmarks/{id}",
    tags: ["bookmarks"],
    pathParameters: ["id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getComment",
    summary: "Show Comment",
    method: "GET",
    path: "/v1/notes/{UUID}",
    tags: ["comments"],
    pathParameters: ["UUID"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getEffectivePermissionsForUser",
    summary: "Get Effective Permissions for a User",
    method: "GET",
    path: "/v1/perms/user/{username}",
    tags: [],
    pathParameters: ["username"],
    queryParameters: ["folder"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getFolderPermissionsV2",
    summary: "Get Folder Permissions (v2)",
    method: "GET",
    path: "/v2/perms/{path}",
    tags: [],
    pathParameters: ["path"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getMspWebhook",
    summary: "Get Webhook Details",
    method: "GET",
    path: "/v1/msp/webhooks/{webhookId}",
    tags: ["Webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getProjectDetails",
    summary: "Get project details",
    method: "GET",
    path: "/v2/project-folders/{projectId}",
    tags: ["project_folders"],
    pathParameters: ["projectId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getScimGroup",
    summary: "Get group",
    method: "GET",
    path: "/scim/v2/Groups/{groupId}",
    tags: ["scim"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getScimUser",
    summary: "Get user",
    method: "GET",
    path: "/scim/v2/Users/{userId}",
    tags: ["scim"],
    pathParameters: ["userId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getSettings",
    summary: "Get Document Portal Settings",
    method: "GET",
    path: "/v1/document-portal/settings",
    tags: ["Settings"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getSfdcFolderMap",
    summary: "Get folder mapping for a Salesforce record",
    method: "GET",
    path: "/v1/sfdc/foldermap/{recordId}",
    tags: ["sfdc"],
    pathParameters: ["recordId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "getTrashTotalCount",
    summary: "Get Trash Total Count",
    method: "GET",
    path: "/v2/fs/trash/totalcount",
    tags: ["Trash"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "hybrid-search",
    summary: "Hybrid semantic and keyword search",
    method: "POST",
    path: "/v1/hybrid-search",
    tags: ["ai"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "createdBy",
      "dateFrom",
      "dateTo",
      "fileTypes",
      "folderPath",
      "includeArchived",
      "limit",
      "modifiedBy",
      "page",
      "query",
      "semanticWeight",
      "size",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "importDocument",
    summary: "Import a Document",
    method: "POST",
    path: "/v1/controlled-docs/documents/import",
    tags: ["Documents"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "approvedOn",
      "docId",
      "effectiveFromDate",
      "effectiveToDate",
      "entryId",
      "isDraft",
      "name",
      "responsibleDepartment",
      "version",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "importTrainingAssignment",
    summary: "Import Training Assignments",
    method: "POST",
    path: "/v1/controlled-docs/assignments/import",
    tags: ["Assignments"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "assignedById",
      "assignedDate",
      "assigneeId",
      "canceledDate",
      "completedDate",
      "docId",
      "dueDate",
      "version",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "list-agents",
    summary: "List agents",
    method: "GET",
    path: "/v1/ai/agents/list",
    tags: ["agents"],
    pathParameters: [],
    queryParameters: ["sortBy", "sortOrder"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-kb",
    summary: "List knowledge bases",
    method: "POST",
    path: "/v1/ai/kb/list",
    tags: ["ai"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "createdAfter",
      "createdBefore",
      "createdBy",
      "includePlaceholderData",
      "includeProcessingStatistics",
      "includePrompts",
      "page",
      "size",
      "sortBy",
      "sortDirection",
      "status",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "list-my-signature-requests",
    summary: "List Assigned Signature Requests",
    method: "GET",
    path: "/v1/egnyte-sign/signature-requests/my-requests",
    tags: ["sign"],
    pathParameters: [],
    queryParameters: ["limit", "offset", "sort_by", "sort_direction", "status"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-sent-signature-requests",
    summary: "List Sent Signature Requests",
    method: "GET",
    path: "/v1/egnyte-sign/signature-requests/sent-requests",
    tags: ["sign"],
    pathParameters: [],
    queryParameters: ["limit", "offset", "sort_by", "sort_direction", "status"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-sign-templates",
    summary: "List Templates",
    method: "GET",
    path: "/v1/egnyte-sign/templates",
    tags: ["sign"],
    pathParameters: [],
    queryParameters: ["sort_by", "sort_direction", "status"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-tasks",
    summary: "List tasks assigned to the current user",
    method: "GET",
    path: "/v1/workflows/tasks",
    tags: ["tasks"],
    pathParameters: [],
    queryParameters: ["limit", "offset", "sortBy", "sortDirection", "status"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-users",
    summary: "List users",
    method: "GET",
    path: "/v2/users",
    tags: ["users"],
    pathParameters: [],
    queryParameters: ["count", "filter", "startIndex"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-users-v1",
    summary: "List users (legacy)",
    method: "GET",
    path: "/1.0/users",
    tags: ["users"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-webhooks",
    summary: "List registered webhooks",
    method: "GET",
    path: "/v1/webhooks",
    tags: ["webhooks"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "list-workflows",
    summary: "List workflows",
    method: "GET",
    path: "/v1/workflows",
    tags: ["workflows"],
    pathParameters: [],
    queryParameters: [
      "assigneeId",
      "assignerId",
      "completionStatus",
      "groupId",
      "limit",
      "offset",
      "sortBy",
      "sortDirection",
      "status",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listArtifacts",
    summary: "List Artifacts and Milestones",
    method: "GET",
    path: "/v1/etmf/studies/{studyId}/artifacts",
    tags: ["etmf"],
    pathParameters: ["studyId"],
    queryParameters: ["filingLevel", "filingLevelId"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listBookmarks",
    summary: "List Bookmarks",
    method: "GET",
    path: "/v1/bookmarks",
    tags: ["bookmarks"],
    pathParameters: [],
    queryParameters: ["count", "offset"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listComments",
    summary: "List Comments",
    method: "GET",
    path: "/v1/notes",
    tags: ["comments"],
    pathParameters: [],
    queryParameters: ["count", "end_time", "file", "offset", "start_time"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listDocuments",
    summary: "List Documents",
    method: "POST",
    path: "/v1/etmf/studies/{studyId}/documents/listing",
    tags: ["etmf"],
    pathParameters: ["studyId"],
    queryParameters: [
      "artifact",
      "filingLevel",
      "filingLevelId",
      "limit",
      "offset",
      "status",
      "zone",
    ],
    headerParameters: [],
    bodyParameters: [
      "artifact",
      "filingLevel",
      "limit",
      "offset",
      "status",
      "zone",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "listFilingLevels",
    summary: "List Filing Levels",
    method: "GET",
    path: "/v1/etmf/studies/{studyId}/filing-levels",
    tags: ["etmf"],
    pathParameters: ["studyId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listMspDomains",
    summary: "List Managed Domains",
    method: "GET",
    path: "/v1/msp/domains",
    tags: ["Domains"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listMspWebhooks",
    summary: "List Webhooks",
    method: "GET",
    path: "/v1/msp/webhooks",
    tags: ["Webhooks"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listProcoreProjects",
    summary: "List Procore projects",
    method: "GET",
    path: "/v1/procore/company/{companyId}/projects",
    tags: ["procore"],
    pathParameters: ["companyId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listProjectFolders",
    summary: "List all projects",
    method: "GET",
    path: "/v2/project-folders",
    tags: ["project_folders"],
    pathParameters: [],
    queryParameters: ["count", "startIndex"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listScimGroups",
    summary: "List groups",
    method: "GET",
    path: "/scim/v2/Groups",
    tags: ["scim"],
    pathParameters: [],
    queryParameters: ["count", "filter", "startIndex"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listScimUsers",
    summary: "List users",
    method: "GET",
    path: "/scim/v2/Users",
    tags: ["scim"],
    pathParameters: [],
    queryParameters: ["count", "filter", "startIndex"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listStudies",
    summary: "List Studies",
    method: "GET",
    path: "/v1/etmf/studies",
    tags: ["etmf"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listSyncedProjects",
    summary: "List synced projects",
    method: "GET",
    path: "/v1/procore/sync",
    tags: ["procore"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listTrashV2",
    summary: "List Trash Contents (v2)",
    method: "GET",
    path: "/v2/fs/trash",
    tags: ["Trash"],
    pathParameters: [],
    queryParameters: [
      "count",
      "deletedBy",
      "endDate",
      "offset",
      "sort_by",
      "sort_direction",
      "startDate",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listUploadRequestTemplates",
    summary: "List Templates",
    method: "GET",
    path: "/v1/upload-requests/templates",
    tags: ["Templates"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "listWorkspaces",
    summary: "List Workspaces",
    method: "GET",
    path: "/v1/document-portal/workspaces",
    tags: ["Workspaces"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "markFolderAsProject",
    summary: "Mark folder as project",
    method: "POST",
    path: "/v1/project-folders",
    tags: ["project_folders"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "completionDate",
      "description",
      "name",
      "rootFolderId",
      "startDate",
      "status",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "navigate-post-v1",
    summary: "Launch a Navigate session (v1 – deprecated)",
    method: "POST",
    path: "/v1/navigate/embedded/{scope}",
    tags: ["navigate"],
    pathParameters: ["scope"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "navigate-post-v2",
    summary: "Launch a Navigate session (v2)",
    method: "POST",
    path: "/v2/navigate",
    tags: ["navigate"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "base",
      "componentId",
      "embedded",
      "fileVersion",
      "fileVersionFullUI",
      "items",
      "path",
      "postMessageNotifications",
      "share",
      "type",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "notes-delete-by-id-v1",
    summary: "Delete a comment",
    method: "DELETE",
    path: "/v1/notes/{noteId}",
    tags: ["notes"],
    pathParameters: ["noteId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "notes-get-by-id-v1",
    summary: "Get comment details",
    method: "GET",
    path: "/v1/notes/{noteId}",
    tags: ["notes"],
    pathParameters: ["noteId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "patchScimGroup",
    summary: "Update group",
    method: "PATCH",
    path: "/scim/v2/Groups/{groupId}",
    tags: ["scim"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["Operations", "schemas"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "patchScimUser",
    summary: "Update user",
    method: "PATCH",
    path: "/scim/v2/Users/{userId}",
    tags: ["scim"],
    pathParameters: ["userId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["Operations", "schemas"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-fs-by-id-v1",
    summary: "Delete a file or folder by ID",
    method: "DELETE",
    path: "/v1/fs/ids/{type}/{id}",
    tags: ["fs"],
    pathParameters: ["id", "type"],
    queryParameters: ["entry_id"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-fs-v1",
    summary: "Delete a file or folder",
    method: "DELETE",
    path: "/v1/fs/{path}",
    tags: ["fs"],
    pathParameters: ["path"],
    queryParameters: ["entry_id"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-fs-v2",
    summary: "Delete a file or folder (v2)",
    method: "DELETE",
    path: "/v2/fs/{path}",
    tags: ["fs"],
    pathParameters: ["path"],
    queryParameters: ["entry_id"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-groups-by-id-v2",
    summary: "Delete a group",
    method: "DELETE",
    path: "/v2/groups/{groupId}",
    tags: ["groups"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-links-by-id-v1",
    summary: "Delete a link",
    method: "DELETE",
    path: "/v1/links/{linkId}",
    tags: ["links"],
    pathParameters: ["linkId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-links-by-id-v2",
    summary: "Delete a link (v2)",
    method: "DELETE",
    path: "/v2/links/{linkId}",
    tags: ["links"],
    pathParameters: ["linkId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-metadata-key-v1",
    summary: "Delete a metadata key",
    method: "DELETE",
    path: "/v1/properties/namespace/{namespaceName}/keys/{keyName}",
    tags: ["metadata"],
    pathParameters: ["keyName", "namespaceName"],
    queryParameters: [],
    headerParameters: ["X-Egnyte-Force-Delete"],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-namespace-v1",
    summary: "Delete a namespace",
    method: "DELETE",
    path: "/v1/properties/namespace/{namespaceName}",
    tags: ["metadata"],
    pathParameters: ["namespaceName"],
    queryParameters: [],
    headerParameters: ["X-Egnyte-Force-Delete"],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-delete-project-custom-field-v1",
    summary: "Delete a custom field definition",
    method: "DELETE",
    path: "/v1/properties/project-tag/custom-fields/{field_name}",
    tags: ["project-custom-fields"],
    pathParameters: ["field_name"],
    queryParameters: [],
    headerParameters: ["X-Egnyte-Force-Delete"],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-events-cursor-v1",
    summary: "Get a cursor for the events stream",
    method: "GET",
    path: "/v1/events/cursor",
    tags: ["events"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-events-v1",
    summary: "List events (version 1)",
    method: "GET",
    path: "/v1/events",
    tags: ["events"],
    pathParameters: [],
    queryParameters: ["count", "folder", "id", "reverse", "suppress", "type"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-events-v2",
    summary: "List events (version 2)",
    method: "GET",
    path: "/v2/events",
    tags: ["events"],
    pathParameters: [],
    queryParameters: ["count", "folder", "id", "reverse", "suppress", "type"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-file-metadata-v1",
    summary: "Get metadata values for a file or file version",
    method: "GET",
    path: "/v1/fs/ids/file/{id}/properties/{namespaceName}",
    tags: ["metadata"],
    pathParameters: ["id", "namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-folder-metadata-v1",
    summary: "Get metadata values for a folder",
    method: "GET",
    path: "/v1/fs/ids/folder/{id}/properties/{namespaceName}",
    tags: ["metadata"],
    pathParameters: ["id", "namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-fs-by-id-v1",
    summary: "Retrieve file or folder metadata by ID",
    method: "GET",
    path: "/v1/fs/ids/{type}/{id}",
    tags: ["fs"],
    pathParameters: ["id", "type"],
    queryParameters: [
      "allowed_link_types",
      "count",
      "include_collaboration",
      "include_locks",
      "include_perm",
      "key",
      "list_content",
      "list_custom_metadata",
      "offset",
      "perms",
      "sort_by",
      "sort_direction",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-fs-content-by-id-v1",
    summary: "Download file content by file ID",
    method: "GET",
    path: "/v1/fs-content/ids/file/{id}",
    tags: ["fs_content"],
    pathParameters: ["id"],
    queryParameters: ["entry_id"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "binary",
  },
  {
    id: "portal-prod-get-fs-content-by-path-v1",
    summary: "Download file content by path",
    method: "GET",
    path: "/v1/fs-content/{path}",
    tags: ["fs_content"],
    pathParameters: ["path"],
    queryParameters: ["entry_id"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "binary",
  },
  {
    id: "portal-prod-get-fs-folder-stats-v1",
    summary: "Get folder statistics by ID",
    method: "GET",
    path: "/v1/fs/ids/folder/{folder_id}/stats",
    tags: ["fs"],
    pathParameters: ["folder_id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-fs-v1",
    summary: "Retrieve file or folder metadata",
    method: "GET",
    path: "/v1/fs/{path}",
    tags: ["fs"],
    pathParameters: ["path"],
    queryParameters: [
      "allowed_link_types",
      "count",
      "include_collaboration",
      "include_locks",
      "include_perm",
      "key",
      "list_content",
      "list_custom_metadata",
      "offset",
      "perms",
      "sort_by",
      "sort_direction",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-fs-v2",
    summary: "Retrieve file or folder metadata (v2)",
    method: "GET",
    path: "/v2/fs/{path}",
    tags: ["fs"],
    pathParameters: ["path"],
    queryParameters: [
      "allowed_link_types",
      "count",
      "include_collaboration",
      "include_locks",
      "include_perm",
      "key",
      "list_content",
      "list_custom_metadata",
      "offset",
      "perms",
      "sort_by",
      "sort_direction",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-groups-by-id-v2",
    summary: "Get group details",
    method: "GET",
    path: "/v2/groups/{groupId}",
    tags: ["groups"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-groups-v2",
    summary: "List groups",
    method: "GET",
    path: "/v2/groups",
    tags: ["groups"],
    pathParameters: [],
    queryParameters: ["count", "filter", "startIndex"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-insights-files-v1",
    summary: "List recently accessed files",
    method: "GET",
    path: "/v1/insights/files",
    tags: ["insights"],
    pathParameters: [],
    queryParameters: ["folder_path"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-links-by-id-v1",
    summary: "Get link details",
    method: "GET",
    path: "/v1/links/{linkId}",
    tags: ["links"],
    pathParameters: ["linkId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-links-by-id-v2",
    summary: "Get link details (v2)",
    method: "GET",
    path: "/v2/links/{linkId}",
    tags: ["links"],
    pathParameters: ["linkId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-links-v1",
    summary: "List links",
    method: "GET",
    path: "/v1/links",
    tags: ["links"],
    pathParameters: [],
    queryParameters: [
      "accessibility",
      "count",
      "created_after",
      "created_before",
      "offset",
      "path",
      "type",
      "username",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-links-v2",
    summary: "List links (v2)",
    method: "GET",
    path: "/v2/links",
    tags: ["links"],
    pathParameters: [],
    queryParameters: [
      "accessibility",
      "count",
      "created_after",
      "created_before",
      "offset",
      "path",
      "type",
      "username",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-namespace-v1",
    summary: "Get namespace keys",
    method: "GET",
    path: "/v1/properties/namespace/{namespaceName}",
    tags: ["metadata"],
    pathParameters: ["namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-namespaces-v1",
    summary: "List namespaces",
    method: "GET",
    path: "/v1/properties/namespace",
    tags: ["metadata"],
    pathParameters: [],
    queryParameters: ["includeFolderAssociations"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-get-project-custom-fields-v1",
    summary: "List all custom field definitions",
    method: "GET",
    path: "/v1/properties/project-tag/custom-fields",
    tags: ["project-custom-fields"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "portal-prod-patch-folder-options-v1",
    summary: "Modify folder options",
    method: "PATCH",
    path: "/v1/fs/{path}",
    tags: [],
    pathParameters: ["path"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "allow_links",
      "allow_upload_links",
      "email_preferences",
      "folder_description",
      "inheritance_rule",
      "move_delete_folder_restriction",
      "public_links",
      "restrict_move_delete",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-patch-groups-by-id-v2",
    summary: "Partially update a group",
    method: "PATCH",
    path: "/v2/groups/{groupId}",
    tags: ["groups"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["Operations", "schemas"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-patch-metadata-key-v1",
    summary: "Update a metadata key",
    method: "PATCH",
    path: "/v1/properties/namespace/{namespaceName}/keys/{keyName}",
    tags: ["metadata"],
    pathParameters: ["keyName", "namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["data", "displayName", "helpText", "priority", "type"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-patch-namespace-v1",
    summary: "Update namespace attributes",
    method: "PATCH",
    path: "/v1/properties/namespace/{namespaceName}",
    tags: ["metadata"],
    pathParameters: ["namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "displayName",
      "documentTypeAssociation",
      "folderAssociation",
      "priorities",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-patch-project-custom-field-data-v1",
    summary: "Delete custom field definition data",
    method: "PATCH",
    path: "/v1/properties/project-tag/custom-fields/{field_name}/data",
    tags: ["project-custom-fields"],
    pathParameters: ["field_name"],
    queryParameters: [],
    headerParameters: ["X-Egnyte-Force-Delete"],
    bodyParameters: [],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-patch-project-custom-field-v1",
    summary: "Update a custom field definition",
    method: "PATCH",
    path: "/v1/properties/project-tag/custom-fields/{field_name}",
    tags: ["project-custom-fields"],
    pathParameters: ["field_name"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["data", "displayName", "helpText", "priority"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-fs-by-id-v1",
    summary: "Perform a file or folder operation by ID",
    method: "POST",
    path: "/v1/fs/ids/{type}/{id}",
    tags: ["fs"],
    pathParameters: ["id", "type"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "action",
      "collaboration",
      "destination",
      "destination_id",
      "folder_options_mode",
      "lock_timeout",
      "lock_token",
      "name",
      "permissions",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-fs-content-by-path-v1",
    summary: "Upload file content by path",
    method: "POST",
    path: "/v1/fs-content/{path}",
    tags: ["fs_content"],
    pathParameters: ["path"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["file"],
    bodyMode: "multipart",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-fs-content-chunked-by-id-v1",
    summary: "Chunked upload by file ID",
    method: "POST",
    path: "/v1/fs-content/ids/file/{id}",
    tags: ["fs_content"],
    pathParameters: ["id"],
    queryParameters: [],
    headerParameters: [
      "Last-Modified",
      "X-Egnyte-Chunk-Num",
      "X-Egnyte-Chunk-Sha512-Checksum",
      "X-Egnyte-Last-Chunk",
      "X-Egnyte-Upload-Id",
      "X-Sha512-Checksum",
    ],
    bodyParameters: ["file"],
    bodyMode: "multipart",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-fs-v1",
    summary: "Perform a file or folder operation",
    method: "POST",
    path: "/v1/fs/{path}",
    tags: ["fs"],
    pathParameters: ["path"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "action",
      "collaboration",
      "destination",
      "destination_id",
      "folder_options_mode",
      "lock_timeout",
      "lock_token",
      "new_name",
      "permissions",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-fs-v2",
    summary: "Perform a file or folder operation (v2)",
    method: "POST",
    path: "/v2/fs/{path}",
    tags: ["fs"],
    pathParameters: ["path"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "action",
      "collaboration",
      "destination",
      "destination_id",
      "folder_options_mode",
      "lock_timeout",
      "lock_token",
      "new_name",
      "permissions",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-groups-v2",
    summary: "Create a group",
    method: "POST",
    path: "/v2/groups",
    tags: ["groups"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["displayName", "members"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-links-v1",
    summary: "Create a link",
    method: "POST",
    path: "/v1/links",
    tags: ["links"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "accessibility",
      "add_file_name",
      "copy_me",
      "expiry_clicks",
      "expiry_date",
      "folder_per_recipient",
      "link_to_current",
      "message",
      "notify",
      "password",
      "path",
      "protection",
      "recipients",
      "send_email",
      "type",
      "useDefaultSettings",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-links-v2",
    summary: "Create a link (v2)",
    method: "POST",
    path: "/v2/links",
    tags: ["links"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "accessibility",
      "expiry_clicks",
      "expiry_date",
      "link_to_current",
      "notify",
      "password",
      "path",
      "recipients",
      "type",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-metadata-key-v1",
    summary: "Create a metadata key",
    method: "POST",
    path: "/v1/properties/namespace/{namespaceName}/keys",
    tags: ["metadata"],
    pathParameters: ["namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "data",
      "displayName",
      "helpText",
      "key",
      "priority",
      "type",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-namespace-v1",
    summary: "Create a namespace",
    method: "POST",
    path: "/v1/properties/namespace",
    tags: ["metadata"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "associatedFolderIds",
      "displayName",
      "documentTypes",
      "inheritable",
      "keys",
      "metadataScopeType",
      "name",
      "scope",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-post-project-custom-field-v1",
    summary: "Create a custom field definition",
    method: "POST",
    path: "/v1/properties/project-tag/custom-fields",
    tags: ["project-custom-fields"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["data", "displayName", "helpText", "priority", "type"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-put-file-metadata-v1",
    summary: "Set metadata values on a file or file version",
    method: "PUT",
    path: "/v1/fs/ids/file/{id}/properties/{namespaceName}",
    tags: ["metadata"],
    pathParameters: ["id", "namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-put-folder-metadata-v1",
    summary: "Set metadata values on a folder",
    method: "PUT",
    path: "/v1/fs/ids/folder/{id}/properties/{namespaceName}",
    tags: ["metadata"],
    pathParameters: ["id", "namespaceName"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "portal-prod-put-groups-by-id-v2",
    summary: "Update a group",
    method: "PUT",
    path: "/v2/groups/{groupId}",
    tags: ["groups"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["displayName", "members"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "register-webhook",
    summary: "Register a webhook",
    method: "POST",
    path: "/v1/webhooks",
    tags: ["webhooks"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "authHeader",
      "authHeaderValue",
      "eventType",
      "path",
      "url",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "removeSync",
    summary: "Remove sync project",
    method: "DELETE",
    path: "/v1/procore/sync/{syncId}",
    tags: ["procore"],
    pathParameters: ["syncId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "replaceScimGroup",
    summary: "Replace group",
    method: "PUT",
    path: "/scim/v2/Groups/{groupId}",
    tags: ["scim"],
    pathParameters: ["groupId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["displayName", "id", "members"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "replaceScimUser",
    summary: "Replace user",
    method: "PUT",
    path: "/scim/v2/Users/{userId}",
    tags: ["scim"],
    pathParameters: ["userId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "active",
      "emails",
      "externalId",
      "groups",
      "id",
      "name",
      "userName",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "retrieveAuditReport",
    summary: "Retrieve Audit Report",
    method: "GET",
    path: "/v1/audit/{type}/{id}",
    tags: ["v1-reports"],
    pathParameters: ["id", "type"],
    queryParameters: ["count", "offset"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "binary",
  },
  {
    id: "revoke-token",
    summary: "Revoke an OAuth token",
    method: "POST",
    path: "/v1/tokens/revoke",
    tags: ["tokens"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["token"],
    bodyMode: "form",
    responseMode: "json",
  },
  {
    id: "searchV1Get",
    summary: "Search files and folders (v1)",
    method: "GET",
    path: "/v1/search",
    tags: ["search"],
    pathParameters: [],
    queryParameters: [
      "count",
      "file_query_fields",
      "folder",
      "folder_query_fields",
      "modified_after",
      "modified_before",
      "offset",
      "query",
      "query_operator",
      "snippet_requested",
      "sort_by",
      "sort_direction",
      "type",
      "uploaded_after",
      "uploaded_before",
    ],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "searchV1Post",
    summary: "Search files and folders with metadata (v1 POST)",
    method: "POST",
    path: "/v1/search",
    tags: ["search"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "count",
      "custom_metadata",
      "namespaces",
      "offset",
      "query",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "searchV2Post",
    summary: "Search with custom metadata (v2)",
    method: "POST",
    path: "/v2/search",
    tags: ["search"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "count",
      "custom_metadata",
      "file_query_fields",
      "folder",
      "folder_query_fields",
      "mlt",
      "mltt",
      "modified_after",
      "modified_before",
      "namespaces",
      "offset",
      "query",
      "query_operator",
      "snippet_requested",
      "sort_by",
      "sort_direction",
      "type",
      "uploaded_after",
      "uploaded_before",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "set-webhook-status",
    summary: "Set webhook status",
    method: "POST",
    path: "/v1/webhooks/{webhookId}/status",
    tags: ["webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["status"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "setFolderPermissionsV2",
    summary: "Set Folder Permissions (v2)",
    method: "POST",
    path: "/v2/perms/{path}",
    tags: [],
    pathParameters: ["path"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "groupPerms",
      "inheritsPermissions",
      "keepParentPermissions",
      "userPerms",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "streamAuditEventsGet",
    summary: "Retrieve Audit Events (stream via GET)",
    method: "GET",
    path: "/v2/audit/stream",
    tags: ["v2-stream"],
    pathParameters: [],
    queryParameters: ["auditType", "endDate", "nextCursor", "startDate"],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "streamAuditEventsPost",
    summary: "Retrieve Audit Events (stream via POST)",
    method: "POST",
    path: "/v2/audit/stream",
    tags: ["v2-stream"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["auditType", "endDate", "nextCursor", "startDate"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "summarize-document",
    summary: "Summarize a document",
    method: "POST",
    path: "/v1/ai/document/{entry-id}/summary",
    tags: ["ai"],
    pathParameters: ["entry-id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["chatHistory"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "syncedProjectsDetails",
    summary: "Synced project details",
    method: "GET",
    path: "/v1/procore/sync/{syncId}",
    tags: ["procore"],
    pathParameters: ["syncId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
  {
    id: "trashAction",
    summary: "Restore or Permanently Delete Items from Trash",
    method: "POST",
    path: "/v1/fs/trash",
    tags: ["Trash"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["action", "ids"],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "update-user",
    summary: "Update a user",
    method: "PATCH",
    path: "/v2/users/{id}",
    tags: ["users"],
    pathParameters: ["id"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "active",
      "authType",
      "email",
      "familyName",
      "givenName",
      "idpUserId",
      "language",
      "role",
      "sendInvite",
      "userPrincipalName",
      "userType",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "update-webhook",
    summary: "Update a webhook",
    method: "PUT",
    path: "/v1/webhooks/{webhookId}",
    tags: ["webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "authHeader",
      "authHeaderValue",
      "eventType",
      "path",
      "status",
      "url",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "updateMspWebhook",
    summary: "Update a Webhook",
    method: "PUT",
    path: "/v1/msp/webhooks/{webhookId}",
    tags: ["Webhooks"],
    pathParameters: ["webhookId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [
      "auth_header",
      "auth_header_value",
      "event_types",
      "webhook_url",
    ],
    bodyMode: "json",
    responseMode: "json",
  },
  {
    id: "updateSync",
    summary: "Update sync option",
    method: "PATCH",
    path: "/v1/procore/sync/{syncId}",
    tags: ["procore"],
    pathParameters: ["syncId"],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: ["procoreFolderPaths", "syncOption"],
    bodyMode: "form",
    responseMode: "json",
  },
  {
    id: "whoami",
    summary: "Get basic information about the caller",
    method: "GET",
    path: "/v1/whoami",
    tags: ["webhooks"],
    pathParameters: [],
    queryParameters: [],
    headerParameters: [],
    bodyParameters: [],
    bodyMode: "none",
    responseMode: "json",
  },
] as const satisfies readonly EgnyteOperation[];

export const EGNYTE_OPERATION_IDS = EGNYTE_OPERATIONS.map(
  (operation) => operation.id,
);
export const EGNYTE_READ_OPERATION_IDS = EGNYTE_OPERATIONS.filter(
  (operation) => operation.method === "GET",
).map((operation) => operation.id);
const EGNYTE_ADMIN_TAGS = new Set([
  "Domains",
  "Settings",
  "Templates",
  "Webhooks",
  "groups",
  "metadata",
  "project-custom-fields",
  "project_folders",
  "scim",
  "tokens",
  "users",
  "v1-reports",
  "v2-stream",
  "webhooks",
]);
export const EGNYTE_ADMIN_OPERATION_IDS = EGNYTE_OPERATIONS.filter(
  (operation) =>
    operation.method !== "GET" &&
    operation.tags.some((tag) => EGNYTE_ADMIN_TAGS.has(tag)),
).map((operation) => operation.id);
const EGNYTE_ADMIN_OPERATION_ID_SET = new Set(EGNYTE_ADMIN_OPERATION_IDS);
export const EGNYTE_CONTENT_WRITE_OPERATION_IDS = EGNYTE_OPERATIONS.filter(
  (operation) =>
    operation.method !== "GET" &&
    !EGNYTE_ADMIN_OPERATION_ID_SET.has(operation.id),
).map((operation) => operation.id);
export const EGNYTE_OPERATION_BY_ID = new Map<string, EgnyteOperation>(
  EGNYTE_OPERATIONS.map((operation) => [operation.id, operation]),
);
