import { action, capability } from "../../catalog/marketplace-catalog.types"; import type { MarketplaceConnectorManifest } from "../types";
const reads=[action("mailjet_read_profile","Read profile","Read bounded Mailjet profile metadata."),action("mailjet_read_messages","Read messages","List bounded message metadata."),action("mailjet_read_stats","Read statistics","Read bounded aggregate delivery statistics.")]; const writes=[action("mailjet_send","Send email","Sending requires approval in Safe mode."),action("mailjet_full_api","Use full Mailjet API","Other API operations require approval in Safe mode.")];
export const SINCH_MAILJET_CONNECTOR_MANIFEST:MarketplaceConnectorManifest={slug:"sinch-mailjet",name:"Sinch Mailjet",connectorType:"native_clawchat",providerDocsUrl:"https://dev.mailjet.com/email/reference/overview/",providerWebsiteUrl:"https://www.mailjet.com",capabilities:[{...capability("profile","Profile","Read bounded profile metadata.",true),platformCapability:"email_account_profile"},{...capability("messages","Messages","List bounded sent-message metadata.",true),platformCapability:"email_delivery_activity"},{...capability("stats","Statistics","Read bounded aggregate delivery statistics.",true),platformCapability:"email_delivery_metrics"},{...capability("send","Send email","Send through the bound verified sender.",true),platformCapability:"email_send"},{...capability("full_api","Full Mailjet API","Use all v3/v3.1 endpoints authorized by the customer credentials.",false),platformCapability:"mailjet_full_api"}],auth:{type:"api_key",credentialSchema:[{name:"MAILJET_API_KEY",label:"Mailjet API Key",required:true,secret:true,storedIn:"encrypted_secret",requiredForAuthTypes:["api_key"],helpText:"The customer or subaccount API Key."},{name:"MAILJET_SECRET_KEY",label:"Mailjet Secret Key",required:true,secret:true,storedIn:"encrypted_secret",requiredForAuthTypes:["api_key"],helpText:"The one-time-visible matching Secret Key."},{name:"MAILJET_SENDER_BOUNDARY",label:"Verified sender boundary",required:true,secret:false,storedIn:"encrypted_secret",requiredForAuthTypes:["api_key"],helpText:"An exact verified sender email or domain."}]},tools:[
{name:"mailjet.getProfile",functionName:"mailjet_get_profile",aliases:["mailjet.getProfile","mailjet_get_profile"],capability:"profile",platformCapability:"email_account_profile",action:"read",approvalRequired:false,description:"Read bounded Mailjet profile metadata.",inputSchema:empty()},
{name:"mailjet.listMessages",functionName:"mailjet_list_messages",aliases:["mailjet.listMessages","mailjet_list_messages"],capability:"messages",platformCapability:"email_delivery_activity",action:"read",approvalRequired:false,description:"List at most 100 message records.",inputSchema:{type:"object",properties:{limit:{type:"number",minimum:1,maximum:100,default:50},offset:{type:"number",minimum:0,default:0}},additionalProperties:false}},
{name:"mailjet.getStatistics",functionName:"mailjet_get_statistics",aliases:["mailjet.getStatistics","mailjet_get_statistics"],capability:"stats",platformCapability:"email_delivery_metrics",action:"read",approvalRequired:false,description:"Read bounded message-based aggregate counters.",inputSchema:{type:"object",properties:{fromTS:{type:"number"},toTS:{type:"number"}},additionalProperties:false}},
{name:"mailjet.send",functionName:"mailjet_send",aliases:["mailjet.send","mailjet_send","email_send"],capability:"send",platformCapability:"email_send",action:"write",approvalRequired:true,description:"Send a v3.1 Messages payload through the bound sender.",inputSchema:{type:"object",properties:{payload:{type:"object"},approvalId:{type:"string"}},required:["payload"],additionalProperties:false}},
{name:"mailjet.request",functionName:"mailjet_request",aliases:["mailjet.request","mailjet_request","mailjet_full_api"],capability:"full_api",platformCapability:"mailjet_full_api",action:"admin",approvalRequired:true,description:"Call a fixed-origin Mailjet v3 or v3.1 endpoint.",inputSchema:{type:"object",properties:{apiVersion:{type:"string",enum:["v3","v3.1"],default:"v3"},method:{type:"string",enum:["GET","POST","PUT","PATCH","DELETE"]},path:{type:"string",pattern:"^/"},query:{type:"object"},json:{type:["object","array"]},approvalId:{type:"string"}},required:["method","path"],additionalProperties:false}}
],approvalProfiles:[{id:"mailjet_safe",label:"Safe",description:"Bounded reads run directly; sends and all other API operations require approval.",defaultSelected:true,allowedActions:reads,approvalRequiredActions:writes,blockedActions:[]}],healthChecks:[{id:"profile",label:"Mailjet credential/profile check"}]}; function empty(){return{type:"object",properties:{},additionalProperties:false};}
