import { type MarketplacePackFactoryDocsConfig, type MarketplacePackSource } from "./types";

export type MarketplaceAppSourceConfig = {
  appSlug: string;
  docs: MarketplacePackFactoryDocsConfig & {
    coreEndpoints?: string;
    errors?: string;
  };
  sources: MarketplacePackSource[];
};

const source = (
  kind: MarketplacePackSource["kind"],
  url: string,
  title: string,
): MarketplacePackSource => ({
  kind,
  url,
  title,
  official: true,
});

export const MARKETPLACE_APP_SOURCE_CONFIGS: Record<string, MarketplaceAppSourceConfig> = {
  resend: config("resend", {
    apiOverview: "https://resend.com/docs/api-reference/introduction",
    auth: "https://resend.com/docs/api-reference/introduction",
    coreEndpoints: "https://resend.com/docs/api-reference/emails/send-email",
    rateLimits: "https://resend.com/docs/api-reference/rate-limit",
    webhooks: "https://resend.com/docs/dashboard/webhooks/introduction",
    errors: "https://resend.com/docs/api-reference/errors",
  }),
  gmail: config("gmail", {
    apiOverview: "https://developers.google.com/gmail/api/guides",
    auth: "https://developers.google.com/gmail/api/auth/about-auth",
    scopes: "https://developers.google.com/workspace/gmail/api/auth/scopes",
    coreEndpoints: "https://developers.google.com/workspace/gmail/api/reference/rest",
    webhooks: "https://developers.google.com/gmail/api/guides/push",
    errors: "https://developers.google.com/workspace/gmail/api/guides/handle-errors",
  }),
  outlook: config("outlook", {
    apiOverview: "https://learn.microsoft.com/en-us/graph/outlook-mail-concept-overview",
    auth: "https://learn.microsoft.com/en-us/graph/auth/",
    scopes: "https://learn.microsoft.com/en-us/graph/permissions-reference",
    coreEndpoints: "https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview",
    webhooks: "https://learn.microsoft.com/en-us/graph/change-notifications-overview",
    rateLimits: "https://learn.microsoft.com/en-us/graph/throttling",
    errors: "https://learn.microsoft.com/en-us/graph/errors",
  }),
  slack: config("slack", {
    apiOverview: "https://api.slack.com/web",
    auth: "https://api.slack.com/authentication/oauth-v2",
    scopes: "https://api.slack.com/scopes",
    coreEndpoints: "https://api.slack.com/methods/conversations.history",
    webhooks: "https://api.slack.com/apis/connections/events-api",
    rateLimits: "https://api.slack.com/apis/rate-limits",
    errors: "https://api.slack.com/errors",
  }),
  discord: config("discord", {
    apiOverview: "https://discord.com/developers/docs/intro",
    auth: "https://discord.com/developers/docs/topics/oauth2",
    scopes: "https://discord.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes",
    coreEndpoints: "https://discord.com/developers/docs/resources/channel",
    webhooks: "https://discord.com/developers/docs/resources/webhook",
    rateLimits: "https://discord.com/developers/docs/topics/rate-limits",
    errors: "https://discord.com/developers/docs/topics/opcodes-and-status-codes",
  }),
  twilio: config("twilio", {
    apiOverview: "https://www.twilio.com/docs/usage/api",
    auth: "https://www.twilio.com/docs/usage/requests-to-twilio",
    coreEndpoints: "https://www.twilio.com/docs/messaging/api/message-resource",
    webhooks: "https://www.twilio.com/docs/usage/webhooks",
    rateLimits: "https://www.twilio.com/docs/usage/rest-api-best-practices",
    errors: "https://www.twilio.com/docs/api/errors",
  }),
  linear: config("linear", {
    apiOverview: "https://developers.linear.app/docs/graphql/working-with-the-graphql-api",
    auth: "https://developers.linear.app/docs/graphql/oauth/authentication",
    scopes: "https://developers.linear.app/docs/oauth/authentication#scopes",
    coreEndpoints: "https://developers.linear.app/docs/graphql/graphql-api",
    webhooks: "https://developers.linear.app/docs/graphql/webhooks",
    rateLimits: "https://developers.linear.app/docs/graphql/working-with-the-graphql-api/rate-limiting",
    errors: "https://developers.linear.app/docs/graphql/working-with-the-graphql-api/errors",
  }),
  jira: config("jira", {
    apiOverview: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
    auth: "https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/",
    scopes: "https://developer.atlassian.com/platform/forge/manifest-reference/scopes-product-jira/",
    coreEndpoints: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/",
    webhooks: "https://developer.atlassian.com/cloud/jira/platform/webhooks/",
    rateLimits: "https://developer.atlassian.com/cloud/jira/platform/rate-limiting/",
    errors: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#status-codes",
  }),
  asana: config("asana", {
    apiOverview: "https://developers.asana.com/docs",
    auth: "https://developers.asana.com/docs/authentication",
    scopes: "https://developers.asana.com/docs/oauth",
    coreEndpoints: "https://developers.asana.com/reference/rest-api-reference",
    webhooks: "https://developers.asana.com/docs/webhooks-guide",
    rateLimits: "https://developers.asana.com/docs/rate-limits",
    errors: "https://developers.asana.com/docs/errors",
  }),
  trello: config("trello", {
    apiOverview: "https://developer.atlassian.com/cloud/trello/rest/",
    auth: "https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/",
    scopes: "https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/#authorization-via-the-1-oauth-api",
    coreEndpoints: "https://developer.atlassian.com/cloud/trello/rest/api-group-cards/",
    webhooks: "https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/",
    rateLimits: "https://developer.atlassian.com/cloud/trello/guides/rest-api/rate-limits/",
    errors: "https://developer.atlassian.com/cloud/trello/rest/",
  }),
  clickup: config("clickup", {
    apiOverview: "https://developer.clickup.com/docs",
    auth: "https://developer.clickup.com/docs/authentication",
    scopes: "https://developer.clickup.com/docs/authentication",
    coreEndpoints: "https://developer.clickup.com/reference",
    webhooks: "https://developer.clickup.com/docs/webhooks",
    rateLimits: "https://developer.clickup.com/docs/rate-limits",
    errors: "https://developer.clickup.com/reference",
  }),
  notion: config("notion", {
    apiOverview: "https://developers.notion.com/docs/getting-started",
    auth: "https://developers.notion.com/docs/authorization",
    scopes: "https://developers.notion.com/docs/authorization#capabilities",
    coreEndpoints: "https://developers.notion.com/reference/intro",
    webhooks: "https://developers.notion.com/reference/webhooks",
    rateLimits: "https://developers.notion.com/reference/request-limits",
    errors: "https://developers.notion.com/reference/status-codes",
  }),
  "google-drive": config("google-drive", {
    apiOverview: "https://developers.google.com/drive/api/guides/about-sdk",
    auth: "https://developers.google.com/drive/api/guides/about-auth",
    scopes: "https://developers.google.com/workspace/drive/api/guides/api-specific-auth",
    coreEndpoints: "https://developers.google.com/workspace/drive/api/reference/rest/v3",
    webhooks: "https://developers.google.com/drive/api/guides/push",
    errors: "https://developers.google.com/drive/api/guides/handle-errors",
  }),
  "exa-search": config("exa-search", {
    apiOverview: "https://docs.exa.ai/",
    auth: "https://docs.exa.ai/reference/search",
    coreEndpoints: "https://docs.exa.ai/reference/search",
    rateLimits: "https://docs.exa.ai/reference/get-contents",
    errors: "https://docs.exa.ai/reference/search",
  }),
  airtable: config("airtable", {
    apiOverview: "https://airtable.com/developers/web/api/introduction",
    auth: "https://airtable.com/developers/web/api/authentication",
    scopes: "https://airtable.com/developers/web/api/scopes",
    coreEndpoints: "https://airtable.com/developers/web/api/list-records",
    webhooks: "https://airtable.com/developers/web/api/webhooks-overview",
    rateLimits: "https://airtable.com/developers/web/api/rate-limits",
    errors: "https://airtable.com/developers/web/api/errors",
  }),
  dropbox: config("dropbox", {
    apiOverview: "https://www.dropbox.com/developers/documentation/http/overview",
    auth: "https://www.dropbox.com/developers/reference/oauth-guide",
    scopes: "https://developers.dropbox.com/oauth-guide#scopes",
    coreEndpoints: "https://www.dropbox.com/developers/documentation/http/documentation",
    webhooks: "https://www.dropbox.com/developers/reference/webhooks",
    errors: "https://www.dropbox.com/developers/documentation/http/documentation",
  }),
  confluence: config("confluence", {
    apiOverview: "https://developer.atlassian.com/cloud/confluence/rest/v2/intro/",
    auth: "https://developer.atlassian.com/cloud/confluence/oauth-2-3lo-apps/",
    scopes: "https://developer.atlassian.com/platform/forge/manifest-reference/scopes-product-confluence/",
    coreEndpoints: "https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-page/",
    webhooks: "https://developer.atlassian.com/cloud/confluence/modules/webhook/",
    rateLimits: "https://developer.atlassian.com/cloud/confluence/rate-limiting/",
    errors: "https://developer.atlassian.com/cloud/confluence/rest/v2/intro/#status-codes",
  }),
  coda: config("coda", {
    apiOverview: "https://coda.io/developers/apis/v1",
    auth: "https://coda.io/developers/apis/v1#section/Authentication",
    coreEndpoints: "https://coda.io/developers/apis/v1#operation/listDocs",
    webhooks: "https://coda.io/developers/apis/v1#tag/Webhooks",
    rateLimits: "https://coda.io/developers/apis/v1#section/Rate-limits",
    errors: "https://coda.io/developers/apis/v1#section/Errors",
  }),
  gitlab: config("gitlab", {
    apiOverview: "https://docs.gitlab.com/api/rest/",
    auth: "https://docs.gitlab.com/api/rest/authentication/",
    scopes: "https://docs.gitlab.com/user/profile/personal_access_tokens/#personal-access-token-scopes",
    coreEndpoints: "https://docs.gitlab.com/api/projects/",
    webhooks: "https://docs.gitlab.com/user/project/integrations/webhooks/",
    rateLimits: "https://docs.gitlab.com/security/rate_limits/",
    errors: "https://docs.gitlab.com/api/rest/troubleshooting/",
  }),
  supabase: config("supabase", {
    apiOverview: "https://supabase.com/docs/reference/api/introduction",
    auth: "https://supabase.com/docs/guides/api/api-keys",
    coreEndpoints: "https://supabase.com/docs/reference/javascript/introduction",
    webhooks: "https://supabase.com/docs/guides/database/webhooks",
    rateLimits: "https://supabase.com/docs/guides/platform/going-into-prod#rate-limiting-resource-allocation--abuse-prevention",
    errors: "https://supabase.com/docs/guides/platform/troubleshooting",
  }),
  vercel: config("vercel", {
    apiOverview: "https://vercel.com/docs/rest-api",
    auth: "https://vercel.com/docs/rest-api#introduction/api-basics/authentication",
    scopes: "https://vercel.com/docs/accounts/plans/pro/accounts/access-roles",
    coreEndpoints: "https://vercel.com/docs/rest-api/reference/endpoints/deployments",
    webhooks: "https://vercel.com/docs/integrations/webhooks-overview",
    rateLimits: "https://vercel.com/docs/rest-api#introduction/api-basics/rate-limits",
    errors: "https://vercel.com/docs/rest-api#introduction/api-basics/errors",
  }),
  railway: config("railway", {
    apiOverview: "https://docs.railway.com/reference/public-api",
    auth: "https://docs.railway.com/reference/public-api#authentication",
    coreEndpoints: "https://docs.railway.com/guides/public-api",
    webhooks: "https://docs.railway.com/guides/webhooks",
    errors: "https://docs.railway.com/reference/errors",
  }),
  sentry: config("sentry", {
    apiOverview: "https://docs.sentry.io/api/",
    auth: "https://docs.sentry.io/api/auth/",
    scopes: "https://docs.sentry.io/api/permissions/",
    coreEndpoints: "https://docs.sentry.io/api/events/",
    webhooks: "https://docs.sentry.io/organization/integrations/integration-platform/webhooks/",
    rateLimits: "https://docs.sentry.io/api/ratelimits/",
    errors: "https://docs.sentry.io/api/",
  }),
  posthog: config("posthog", {
    apiOverview: "https://posthog.com/docs/api",
    auth: "https://posthog.com/docs/api/overview#authentication",
    scopes: "https://posthog.com/docs/api/overview#private-projects",
    coreEndpoints: "https://posthog.com/docs/api/projects",
    webhooks: "https://posthog.com/docs/cdp",
    rateLimits: "https://posthog.com/docs/api/overview#rate-limits",
    errors: "https://posthog.com/docs/api/overview#errors",
  }),
  shopify: config("shopify", {
    apiOverview: "https://shopify.dev/docs/api",
    auth: "https://shopify.dev/docs/apps/build/authentication-authorization",
    scopes: "https://shopify.dev/docs/api/usage/access-scopes",
    coreEndpoints: "https://shopify.dev/docs/api/admin-graphql",
    webhooks: "https://shopify.dev/docs/apps/build/webhooks",
    rateLimits: "https://shopify.dev/docs/api/usage/rate-limits",
    errors: "https://shopify.dev/docs/api/admin-graphql#status-and-error-codes",
  }),
  paddle: config("paddle", {
    apiOverview: "https://developer.paddle.com/api-reference/overview",
    auth: "https://developer.paddle.com/api-reference/overview#authentication",
    coreEndpoints: "https://developer.paddle.com/api-reference/transactions/overview",
    webhooks: "https://developer.paddle.com/webhooks/overview",
    rateLimits: "https://developer.paddle.com/api-reference/overview#rate-limiting",
    errors: "https://developer.paddle.com/errors/overview",
  }),
  "lemon-squeezy": config("lemon-squeezy", {
    apiOverview: "https://docs.lemonsqueezy.com/api",
    auth: "https://docs.lemonsqueezy.com/api#authentication",
    coreEndpoints: "https://docs.lemonsqueezy.com/api/customers",
    webhooks: "https://docs.lemonsqueezy.com/help/webhooks",
    rateLimits: "https://docs.lemonsqueezy.com/api#rate-limits",
    errors: "https://docs.lemonsqueezy.com/api#errors",
  }),
  chargebee: config("chargebee", {
    apiOverview: "https://apidocs.chargebee.com/docs/api",
    auth: "https://apidocs.chargebee.com/docs/api/auth",
    coreEndpoints: "https://apidocs.chargebee.com/docs/api/customers",
    webhooks: "https://apidocs.chargebee.com/docs/api/events",
    rateLimits: "https://apidocs.chargebee.com/docs/api",
    errors: "https://apidocs.chargebee.com/docs/api/errors",
  }),
  hubspot: config("hubspot", {
    apiOverview: "https://developers.hubspot.com/docs/api/overview",
    auth: "https://developers.hubspot.com/docs/api/private-apps",
    scopes: "https://developers.hubspot.com/docs/api/scopes",
    coreEndpoints: "https://developers.hubspot.com/docs/api/crm/contacts",
    webhooks: "https://developers.hubspot.com/docs/api/webhooks",
    rateLimits: "https://developers.hubspot.com/docs/api/usage-details",
    errors: "https://developers.hubspot.com/docs/api/error-handling",
  }),
  salesforce: config("salesforce", {
    apiOverview: "https://developer.salesforce.com/docs/apis",
    auth: "https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_flows.htm&type=5",
    scopes: "https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_scopes.htm&type=5",
    coreEndpoints: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest.htm",
    webhooks: "https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_events_intro.htm",
    rateLimits: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_api_usage.htm",
    errors: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/errorcodes.htm",
  }),
  zendesk: config("zendesk", {
    apiOverview: "https://developer.zendesk.com/api-reference/",
    auth: "https://developer.zendesk.com/api-reference/introduction/security-and-auth/",
    scopes: "https://developer.zendesk.com/api-reference/introduction/security-and-auth/",
    coreEndpoints: "https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/",
    webhooks: "https://developer.zendesk.com/documentation/webhooks/",
    rateLimits: "https://developer.zendesk.com/api-reference/introduction/rate-limits/",
    errors: "https://developer.zendesk.com/api-reference/introduction/requests/#status-codes",
  }),
  intercom: config("intercom", {
    apiOverview: "https://developers.intercom.com/docs/references/rest-api/api.intercom.io",
    auth: "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication",
    scopes: "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication",
    coreEndpoints: "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/Conversations",
    webhooks: "https://developers.intercom.com/docs/references/rest-api/webhooks",
    rateLimits: "https://developers.intercom.com/docs/references/rest-api/errors/rate-limiting",
    errors: "https://developers.intercom.com/docs/references/rest-api/errors/rate-limiting",
  }),
  pipedrive: config("pipedrive", {
    apiOverview: "https://developers.pipedrive.com/docs/api/v1",
    auth: "https://pipedrive.readme.io/docs/core-api-concepts-authentication",
    scopes: "https://pipedrive.readme.io/docs/core-api-concepts-authentication",
    coreEndpoints: "https://developers.pipedrive.com/docs/api/v1/Deals",
    webhooks: "https://pipedrive.readme.io/docs/guide-for-webhooks",
    rateLimits: "https://pipedrive.readme.io/docs/core-api-concepts-rate-limiting",
    errors: "https://developers.pipedrive.com/docs/api/v1",
  }),
  figma: config("figma", {
    apiOverview: "https://www.figma.com/developers/api",
    auth: "https://www.figma.com/developers/api#authentication",
    scopes: "https://www.figma.com/developers/api#authentication-scopes",
    coreEndpoints: "https://www.figma.com/developers/api#get-files-endpoint",
    webhooks: "https://www.figma.com/developers/api#webhooks-v2",
    rateLimits: "https://www.figma.com/developers/api#rate-limits",
    errors: "https://www.figma.com/developers/api#errors",
  }),
  canva: config("canva", {
    apiOverview: "https://www.canva.dev/docs/connect/",
    auth: "https://www.canva.dev/docs/connect/authentication/",
    scopes: "https://www.canva.dev/docs/connect/appendix/scopes/",
    coreEndpoints: "https://www.canva.dev/docs/connect/api-reference/introduction/",
    webhooks: "https://www.canva.dev/docs/connect/webhooks/",
    rateLimits: "https://www.canva.dev/docs/connect/",
    errors: "https://www.canva.dev/docs/connect/api-reference/errors/",
  }),
  webflow: config("webflow", {
    apiOverview: "https://developers.webflow.com/data/reference/rest-introduction",
    auth: "https://developers.webflow.com/data/docs/getting-started-data-clients",
    scopes: "https://developers.webflow.com/data/reference/scopes",
    coreEndpoints: "https://developers.webflow.com/data/reference/cms/collection-items",
    webhooks: "https://developers.webflow.com/data/reference/webhooks",
    rateLimits: "https://developers.webflow.com/data/docs/working-with-the-api/rate-limits",
    errors: "https://developers.webflow.com/data/docs/working-with-the-api/errors",
  }),
  wordpress: config("wordpress", {
    apiOverview: "https://developer.wordpress.org/rest-api/",
    auth: "https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/",
    coreEndpoints: "https://developer.wordpress.org/rest-api/reference/posts/",
    webhooks: "https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/",
    errors: "https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_envelope",
  }),
  "youtube-data-api": config("youtube-data-api", {
    apiOverview: "https://developers.google.com/youtube/v3/getting-started",
    auth: "https://developers.google.com/youtube/v3/guides/authentication",
    scopes: "https://developers.google.com/youtube/v3/guides/auth/server-side-web-apps#identify-access-scopes",
    coreEndpoints: "https://developers.google.com/youtube/v3/docs",
    webhooks: "https://developers.google.com/youtube/v3/guides/push_notifications",
    errors: "https://developers.google.com/youtube/v3/docs/errors",
  }),
};

function config(
  appSlug: string,
  docs: MarketplaceAppSourceConfig["docs"],
): MarketplaceAppSourceConfig {
  const sources: MarketplacePackSource[] = [
    docs.apiOverview ? source("official_api_docs", docs.apiOverview, `${appSlug} API overview`) : null,
    docs.auth ? source("auth_docs", docs.auth, `${appSlug} authentication`) : null,
    docs.scopes ? source("auth_docs", docs.scopes, `${appSlug} permissions and scopes`) : null,
    docs.coreEndpoints ? source("official_api_docs", docs.coreEndpoints, `${appSlug} core endpoints and objects`) : null,
    docs.webhooks ? source("webhook_docs", docs.webhooks, `${appSlug} webhooks and events`) : null,
    docs.rateLimits ? source("official_api_docs", docs.rateLimits, `${appSlug} rate limits`) : null,
    docs.errors ? source("official_api_docs", docs.errors, `${appSlug} errors`) : null,
    docs.openApiSpec ? source("openapi_spec", docs.openApiSpec, `${appSlug} OpenAPI spec`) : null,
  ].filter((item): item is MarketplacePackSource => Boolean(item));
  return { appSlug, docs, sources };
}
