// Generated by scripts/generate-resource-guru-operation-registry.mjs.
// Source: https://resourceguruapp.com/docs/api.
// SHA-256: 2d134bbd7f8f144b2591fd0920158a2eeb1229f392b78f8f40ea0da58379d767

export type ResourceGuruOperation = {
  id: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  pathParameters: readonly string[];
  queryParameters: readonly string[];
  bodyAllowed: boolean;
};

export const RESOURCE_GURU_SOURCE_SHA256 = "2d134bbd7f8f144b2591fd0920158a2eeb1229f392b78f8f40ea0da58379d767";

export const RESOURCE_GURU_OPERATIONS = [
  {
    "id": "delete_v1_by_account_activity_types_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/activity_types/{id}",
    "summary": "Delete activity type",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_bookings_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/bookings/{id}",
    "summary": "Delete booking",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "delete_v1_by_account_calendars_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/calendars/{id}",
    "summary": "Delete calendar",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_clients_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/clients/{id}",
    "summary": "Delete client",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_custom_available_periods_reset",
    "method": "DELETE",
    "path": "/v1/{account}/custom_available_periods/reset",
    "summary": "Reset custom availability",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "delete_v1_by_account_custom_field_options_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/custom_field_options/{id}",
    "summary": "Delete custom field option",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_custom_fields_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/custom_fields/{id}",
    "summary": "Delete custom field",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_downtimes_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/downtimes/{id}",
    "summary": "Delete downtime",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_projects_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/projects/{id}",
    "summary": "Delete project",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_rates_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/rates/{id}",
    "summary": "Delete a rate",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "delete_v1_by_account_resources_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/resources/{id}",
    "summary": "Delete resource",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "delete_v1_by_account_webhooks_by_id",
    "method": "DELETE",
    "path": "/v1/{account}/webhooks/{id}",
    "summary": "Delete webhook",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_accounts",
    "method": "GET",
    "path": "/v1/accounts",
    "summary": "List accounts",
    "pathParameters": [],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_accounts_by_id",
    "method": "GET",
    "path": "/v1/accounts/{id}",
    "summary": "Get account",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_activity_types",
    "method": "GET",
    "path": "/v1/{account}/activity_types",
    "summary": "List active activity types",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_activity_types_archived",
    "method": "GET",
    "path": "/v1/{account}/activity_types/archived",
    "summary": "List archived activity types",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_activity_types_by_id",
    "method": "GET",
    "path": "/v1/{account}/activity_types/{id}",
    "summary": "Get activity type",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_activity_types_by_id_stats",
    "method": "GET",
    "path": "/v1/{account}/activity_types/{id}/stats",
    "summary": "Get activity type stats",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_bookings",
    "method": "GET",
    "path": "/v1/{account}/bookings",
    "summary": "List bookings",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "calendar",
      "resource_ids",
      "external_refs",
      "booker_id",
      "waiting",
      "include_archived_resources",
      "include_deleted_resources",
      "include_non_bookable_resources",
      "group_id",
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_bookings_by_id",
    "method": "GET",
    "path": "/v1/{account}/bookings/{id}",
    "summary": "Get booking",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_bookings_by_id_activities",
    "method": "GET",
    "path": "/v1/{account}/bookings/{id}/activities",
    "summary": "List booking activities",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_calendars",
    "method": "GET",
    "path": "/v1/{account}/calendars",
    "summary": "List calendars",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_calendars_by_id",
    "method": "GET",
    "path": "/v1/{account}/calendars/{id}",
    "summary": "Get calendar",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_calendars_external_events",
    "method": "GET",
    "path": "/v1/{account}/calendars/external_events",
    "summary": "List external events",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_clients",
    "method": "GET",
    "path": "/v1/{account}/clients",
    "summary": "List active clients",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "limit",
      "offset",
      "includeArchived",
      "includeDeleted"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_clients_archived",
    "method": "GET",
    "path": "/v1/{account}/clients/archived",
    "summary": "List archived clients",
    "pathParameters": [],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_clients_by_id",
    "method": "GET",
    "path": "/v1/{account}/clients/{id}",
    "summary": "Get client",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_clients_by_id_bookings",
    "method": "GET",
    "path": "/v1/{account}/clients/{id}/bookings",
    "summary": "List client bookings",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_custom_available_periods",
    "method": "GET",
    "path": "/v1/{account}/custom_available_periods",
    "summary": "List custom availability",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "resource_ids[]",
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_custom_field_options",
    "method": "GET",
    "path": "/v1/{account}/custom_field_options",
    "summary": "List custom field options",
    "pathParameters": [],
    "queryParameters": [
      "custom_field_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_custom_field_options_by_id",
    "method": "GET",
    "path": "/v1/{account}/custom_field_options/{id}",
    "summary": "Get custom field option",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_custom_fields",
    "method": "GET",
    "path": "/v1/{account}/custom_fields",
    "summary": "List custom fields",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_custom_fields_by_id",
    "method": "GET",
    "path": "/v1/{account}/custom_fields/{id}",
    "summary": "Get custom field",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_downtime_types",
    "method": "GET",
    "path": "/v1/{account}/downtime_types",
    "summary": "List downtime types",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_downtimes",
    "method": "GET",
    "path": "/v1/{account}/downtimes",
    "summary": "List downtimes",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "resource_ids",
      "booker_id",
      "from",
      "to",
      "include_archived_resources",
      "include_deleted_resources",
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_downtimes_by_id",
    "method": "GET",
    "path": "/v1/{account}/downtimes/{id}",
    "summary": "Get downtime",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_projects",
    "method": "GET",
    "path": "/v1/{account}/projects",
    "summary": "List active projects",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "limit",
      "offset",
      "includeArchived",
      "includeDeleted"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_projects_archived",
    "method": "GET",
    "path": "/v1/{account}/projects/archived",
    "summary": "List archived projects",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_projects_by_id",
    "method": "GET",
    "path": "/v1/{account}/projects/{id}",
    "summary": "Get project",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_projects_by_id_bookings",
    "method": "GET",
    "path": "/v1/{account}/projects/{id}/bookings",
    "summary": "List project bookings",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_rates",
    "method": "GET",
    "path": "/v1/{account}/rates",
    "summary": "List rates",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_reports_clients",
    "method": "GET",
    "path": "/v1/{account}/reports/clients",
    "summary": "Get report of clients",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_reports_clients_by_id",
    "method": "GET",
    "path": "/v1/{account}/reports/clients/{id}",
    "summary": "Get report of a client",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_reports_projects",
    "method": "GET",
    "path": "/v1/{account}/reports/projects",
    "summary": "Get report of projects",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_reports_projects_by_id",
    "method": "GET",
    "path": "/v1/{account}/reports/projects/{id}",
    "summary": "Get report of a project",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_reports_resources",
    "method": "GET",
    "path": "/v1/{account}/reports/resources",
    "summary": "Get report of resources",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_reports_resources_by_id",
    "method": "GET",
    "path": "/v1/{account}/reports/resources/{id}",
    "summary": "Get report of a resource",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_resource_types",
    "method": "GET",
    "path": "/v1/{account}/resource_types",
    "summary": "List resource types",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_resource_types_by_id",
    "method": "GET",
    "path": "/v1/{account}/resource_types/{id}",
    "summary": "Get resource type",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_resources",
    "method": "GET",
    "path": "/v1/{account}/resources",
    "summary": "List active resources",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "limit",
      "detail",
      "ids",
      "show_availability"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_resources_archived",
    "method": "GET",
    "path": "/v1/{account}/resources/archived",
    "summary": "List archived resources",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "limit",
      "detail",
      "ids",
      "show_availability"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_resources_by_id",
    "method": "GET",
    "path": "/v1/{account}/resources/{id}",
    "summary": "Get resource",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_resources_by_id_bookings",
    "method": "GET",
    "path": "/v1/{account}/resources/{id}/bookings",
    "summary": "List resource bookings",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_timesheets",
    "method": "GET",
    "path": "/v1/{account}/timesheets",
    "summary": "List timesheet entries",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "start_date",
      "end_date",
      "resource_ids",
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_timesheets_reports_projects",
    "method": "GET",
    "path": "/v1/{account}/timesheets/reports/projects",
    "summary": "Get timesheet entry reports grouped by projects",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "start_date",
      "end_date",
      "approved_only"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_timesheets_reports_resources",
    "method": "GET",
    "path": "/v1/{account}/timesheets/reports/resources",
    "summary": "Get timesheet entry reports grouped by resources",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "start_date",
      "end_date",
      "approved_only"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_users",
    "method": "GET",
    "path": "/v1/{account}/users",
    "summary": "List active users",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "limit",
      "offset"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_users_all",
    "method": "GET",
    "path": "/v1/{account}/users/all",
    "summary": "List users",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_users_by_id",
    "method": "GET",
    "path": "/v1/{account}/users/{id}",
    "summary": "Get user",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_users_me",
    "method": "GET",
    "path": "/v1/{account}/users/me",
    "summary": "Get my user details",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_webhooks",
    "method": "GET",
    "path": "/v1/{account}/webhooks",
    "summary": "List webhooks",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_webhooks_by_id",
    "method": "GET",
    "path": "/v1/{account}/webhooks/{id}",
    "summary": "Get webhook",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_by_account_webhooks_by_id_queue",
    "method": "GET",
    "path": "/v1/{account}/webhooks/{id}/queue",
    "summary": "Get webhook payloads",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [
      "offset",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v1_me",
    "method": "GET",
    "path": "/v1/me",
    "summary": "Get my user summary",
    "pathParameters": [],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_clients",
    "method": "GET",
    "path": "/v2/{account}/reports/clients",
    "summary": "Get report of clients",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_clients_by_id",
    "method": "GET",
    "path": "/v2/{account}/reports/clients/{id}",
    "summary": "Get report of a client",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_clients_unassigned",
    "method": "GET",
    "path": "/v2/{account}/reports/clients/unassigned",
    "summary": "Get report of bookings with no clients",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_projects",
    "method": "GET",
    "path": "/v2/{account}/reports/projects",
    "summary": "Get report of projects",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_projects_by_id",
    "method": "GET",
    "path": "/v2/{account}/reports/projects/{id}",
    "summary": "Get report of a project",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_projects_unassigned",
    "method": "GET",
    "path": "/v2/{account}/reports/projects/unassigned",
    "summary": "Get report of bookings with no project",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_resources",
    "method": "GET",
    "path": "/v2/{account}/reports/resources",
    "summary": "Get report of resources",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "get_v2_by_account_reports_resources_by_id",
    "method": "GET",
    "path": "/v2/{account}/reports/resources/{id}",
    "summary": "Get report of a resource",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "patch_v1_by_account_activity_types_by_id",
    "method": "PATCH",
    "path": "/v1/{account}/activity_types/{id}",
    "summary": "Update activity type",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_activity_types",
    "method": "POST",
    "path": "/v1/{account}/activity_types",
    "summary": "Create activity type",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_bookings",
    "method": "POST",
    "path": "/v1/{account}/bookings",
    "summary": "Create booking",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_bookings_by_id_remind",
    "method": "POST",
    "path": "/v1/{account}/bookings/{id}/remind",
    "summary": "Remind approvers",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_bookings_by_id_resolve",
    "method": "POST",
    "path": "/v1/{account}/bookings/{id}/resolve",
    "summary": "Approve/Decline a booking",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_bookings_by_id_split",
    "method": "POST",
    "path": "/v1/{account}/bookings/{id}/split",
    "summary": "Split booking",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_clients",
    "method": "POST",
    "path": "/v1/{account}/clients",
    "summary": "Create client",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_custom_available_periods",
    "method": "POST",
    "path": "/v1/{account}/custom_available_periods",
    "summary": "Set custom availability",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_custom_field_options",
    "method": "POST",
    "path": "/v1/{account}/custom_field_options",
    "summary": "Create custom field option",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_custom_fields",
    "method": "POST",
    "path": "/v1/{account}/custom_fields",
    "summary": "Create custom field",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_downtimes",
    "method": "POST",
    "path": "/v1/{account}/downtimes",
    "summary": "Create downtime",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_downtimes_by_id_split",
    "method": "POST",
    "path": "/v1/{account}/downtimes/{id}/split",
    "summary": "Split downtime",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_downtimes_clashes",
    "method": "POST",
    "path": "/v1/{account}/downtimes/clashes",
    "summary": "List downtime clashes",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_overtimes",
    "method": "POST",
    "path": "/v1/{account}/overtimes",
    "summary": "Set overtime",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_projects",
    "method": "POST",
    "path": "/v1/{account}/projects",
    "summary": "Create project",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_rates",
    "method": "POST",
    "path": "/v1/{account}/rates",
    "summary": "Create a new rate",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_resources",
    "method": "POST",
    "path": "/v1/{account}/resources",
    "summary": "Create resource",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_resources_by_id_availability",
    "method": "POST",
    "path": "/v1/{account}/resources/{id}/availability",
    "summary": "Update availability or timezone",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_resources_by_id_invite",
    "method": "POST",
    "path": "/v1/{account}/resources/{id}/invite",
    "summary": "Invite person",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_timesheets",
    "method": "POST",
    "path": "/v1/{account}/timesheets",
    "summary": "Create a new timesheet entry",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [
      "action"
    ],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_timesheets_by_id_dismiss",
    "method": "POST",
    "path": "/v1/{account}/timesheets/{id}/dismiss",
    "summary": "Dismiss timesheet entry",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "post_v1_by_account_timesheets_dismiss",
    "method": "POST",
    "path": "/v1/{account}/timesheets/dismiss",
    "summary": "Bulk dismiss timesheet entries",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_webhooks",
    "method": "POST",
    "path": "/v1/{account}/webhooks",
    "summary": "Create webhook",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "post_v1_by_account_webhooks_by_id_test",
    "method": "POST",
    "path": "/v1/{account}/webhooks/{id}/test",
    "summary": "Test webhook",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "post_v1_by_account_webhooks_test_payload_url",
    "method": "POST",
    "path": "/v1/{account}/webhooks/test-payload-url",
    "summary": "Send test payload",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_accounts_by_id",
    "method": "PUT",
    "path": "/v1/accounts/{id}",
    "summary": "Update account",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_activity_types_by_id",
    "method": "PUT",
    "path": "/v1/{account}/activity_types/{id}",
    "summary": "Update activity type",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_bookings_by_id",
    "method": "PUT",
    "path": "/v1/{account}/bookings/{id}",
    "summary": "Update booking",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_calendars_by_id",
    "method": "PUT",
    "path": "/v1/{account}/calendars/{id}",
    "summary": "Update calendar",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_clients_by_id",
    "method": "PUT",
    "path": "/v1/{account}/clients/{id}",
    "summary": "Update client",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_custom_field_options_by_id",
    "method": "PUT",
    "path": "/v1/{account}/custom_field_options/{id}",
    "summary": "Update custom field option",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_custom_fields_by_id",
    "method": "PUT",
    "path": "/v1/{account}/custom_fields/{id}",
    "summary": "Update custom field",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_downtimes_by_id",
    "method": "PUT",
    "path": "/v1/{account}/downtimes/{id}",
    "summary": "Update downtime",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_projects_by_id",
    "method": "PUT",
    "path": "/v1/{account}/projects/{id}",
    "summary": "Update project",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_rates_by_id",
    "method": "PUT",
    "path": "/v1/{account}/rates/{id}",
    "summary": "Update a specific rate by id",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_resources_by_id",
    "method": "PUT",
    "path": "/v1/{account}/resources/{id}",
    "summary": "Update resource",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_timesheets_by_id",
    "method": "PUT",
    "path": "/v1/{account}/timesheets/{id}",
    "summary": "Update timesheet entry",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_timesheets_update",
    "method": "PUT",
    "path": "/v1/{account}/timesheets/update",
    "summary": "Bulk update timesheet entries",
    "pathParameters": [
      "account"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_webhooks_by_id",
    "method": "PUT",
    "path": "/v1/{account}/webhooks/{id}",
    "summary": "Update webhook",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "put_v1_by_account_webhooks_by_id_send_payload_batch",
    "method": "PUT",
    "path": "/v1/{account}/webhooks/{id}/send_payload_batch",
    "summary": "Re-send webhook payload",
    "pathParameters": [
      "account",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  }
] as const satisfies readonly ResourceGuruOperation[];

export const RESOURCE_GURU_READ_OPERATION_IDS = RESOURCE_GURU_OPERATIONS.filter((operation) => operation.method === "GET").map((operation) => operation.id);
export const RESOURCE_GURU_MANAGE_OPERATION_IDS = RESOURCE_GURU_OPERATIONS.filter((operation) => operation.method !== "GET").map((operation) => operation.id);
export const RESOURCE_GURU_OPERATION_BY_ID = new Map<string, ResourceGuruOperation>(RESOURCE_GURU_OPERATIONS.map((operation) => [operation.id, operation]));
