export const PADDLE_ENDPOINT_FAMILIES = [
  { id: "auth", label: "Authentication", docsUrl: "https://developer.paddle.com/api-reference/about/authentication", guidance: "Use server-side Bearer API keys. Verify sandbox/live key environment and assigned permissions before writes." },
  { id: "customers", label: "Customers Addresses Businesses", docsUrl: "https://developer.paddle.com/api-reference/customers/overview", guidance: "Read and manage customer billing identity. Customer creation/update requires policy checks; no customer delete workflow is exposed." },
  { id: "products_prices", label: "Products And Prices", docsUrl: "https://developer.paddle.com/api-reference/products/overview", guidance: "Read products/prices freely when enabled. Product, price, discount, or tax-category changes require approval." },
  { id: "transactions_invoices", label: "Transactions Invoices Receipts", docsUrl: "https://developer.paddle.com/api-reference/transactions/overview", guidance: "Transactions calculate revenue and can create invoices or collect payment; creation and collection require approval." },
  { id: "subscriptions", label: "Subscriptions", docsUrl: "https://developer.paddle.com/api-reference/subscriptions/overview", guidance: "Read subscription state. Update, pause, resume, cancel, or immediate-charge subscription changes require approval." },
  { id: "adjustments", label: "Adjustments Refunds Credits", docsUrl: "https://developer.paddle.com/api-reference/adjustments/overview", guidance: "Adjustments refund or credit billed/completed transactions and require approval with amount, reason, transaction, and customer context." },
  { id: "webhooks", label: "Events And Webhooks", docsUrl: "https://developer.paddle.com/webhooks/overview", guidance: "Use webhooks for transaction, subscription, customer, and adjustment lifecycle changes. Webhook configuration changes require approval." },
  { id: "rate_limits_errors", label: "Rate Limits And Errors", docsUrl: "https://developer.paddle.com/api-reference/about/rate-limiting", guidance: "Most operations allow 240 requests/minute per IP; preview endpoints allow 1000/minute; immediate-charge subscription updates have per-subscription hourly/daily limits." },
];
