import { action, capability } from "../../catalog/marketplace-catalog.types";
import type { MarketplaceConnectorManifest } from "../types";

const reads = [
  action("descript_list_projects", "List projects", "List one bounded page of projects in the token's Drive."),
  action("descript_get_project", "Read project", "Read one project's media, compositions, and existing publishes."),
  action("descript_list_jobs", "List jobs", "List one bounded page of recent jobs."),
  action("descript_get_job", "Read job", "Read one job's current status and bounded result."),
  action("descript_list_agent_models", "List agent models", "Read the live list of available Underlord models and aliases."),
  action("descript_export_transcript", "Export transcript", "Export one authorized composition transcript in a supported bounded format."),
];
const changes = [
  action("descript_import_media", "Import media", "Import media or create a project; this can consume media minutes."),
  action("descript_agent_edit", "Edit with Underlord", "Create or edit a project with Underlord; this can consume AI credits."),
  action("descript_publish", "Publish project", "Publish a composition to a Descript share page and rendered download."),
  action("descript_cancel_job", "Cancel job", "Cancel a running Descript job."),
  action("descript_full_api", "Use full Descript API", "Use any current documented public API operation; Safe mode requires approval."),
];

const pageProperties = { cursor: { type: "string", maxLength: 10000 }, limit: { type: "number", minimum: 1, maximum: 100 } };

export const DESCRIPT_CONNECTOR_MANIFEST: MarketplaceConnectorManifest = {
  slug: "descript", name: "Descript", connectorType: "native_clawchat",
  providerDocsUrl: "https://docs.descriptapi.com/", providerWebsiteUrl: "https://www.descript.com/",
  capabilities: [
    { ...capability("projects_read", "Browse projects", "List and inspect projects, compositions, publishes, models, and recent jobs in the token's Drive.", true), platformCapability: "descript_projects_read" },
    { ...capability("transcripts", "Export transcripts", "Export a project composition as text, Markdown, HTML, RTF, DOCX, or SRT.", true), platformCapability: "descript_transcripts" },
    { ...capability("production", "Create and edit productions", "Import media, create projects and compositions, and run Underlord edits that can consume media minutes or AI credits.", true), platformCapability: "descript_production" },
    { ...capability("publishing", "Publish and manage jobs", "Publish compositions, retrieve share and download links, and cancel running jobs.", true), platformCapability: "descript_publishing" },
    { ...capability("administration", "Use the complete Descript API", "Use every current documented public API operation authorized by the token and Drive.", true), platformCapability: "descript_administration" },
  ],
  auth: { type: "api_key", credentialSchema: [{ name: "DESCRIPT_API_TOKEN", label: "Descript API token", required: true, secret: true, storedIn: "encrypted_secret", requiredForAuthTypes: ["api_key"], helpText: "Create a dedicated token in Descript Settings > API tokens and bind it to the Drive you want Relay Console to use." }] },
  tools: [
    { name: "descript.listProjects", functionName: "descript_list_projects", aliases: ["descript.listProjects", "descript_list_projects"], capability: "projects_read", platformCapability: "descript_projects_read", action: "read", approvalRequired: false, description: "List a bounded page of projects in the token's Drive.", inputSchema: { type: "object", properties: { name: { type: "string", maxLength: 1000 }, folder_path: { type: "string", maxLength: 2000 }, created_by: { type: "string", maxLength: 200 }, created_after: { type: "string", maxLength: 100 }, created_before: { type: "string", maxLength: 100 }, updated_after: { type: "string", maxLength: 100 }, updated_before: { type: "string", maxLength: 100 }, sort: { type: "string", enum: ["name", "created_at", "updated_at", "last_viewed_at"] }, direction: { type: "string", enum: ["asc", "desc"] }, ...pageProperties }, additionalProperties: false } },
    { name: "descript.getProject", functionName: "descript_get_project", aliases: ["descript.getProject", "descript_get_project"], capability: "projects_read", platformCapability: "descript_projects_read", action: "read", approvalRequired: false, description: "Read one project's media, compositions, and publishes.", inputSchema: { type: "object", properties: { projectId: { type: "string", format: "uuid" } }, required: ["projectId"], additionalProperties: false } },
    { name: "descript.listJobs", functionName: "descript_list_jobs", aliases: ["descript.listJobs", "descript_list_jobs"], capability: "projects_read", platformCapability: "descript_projects_read", action: "read", approvalRequired: false, description: "List a bounded page of recent jobs.", inputSchema: { type: "object", properties: { project_id: { type: "string", format: "uuid" }, type: { type: "string", enum: ["import/project_media", "agent", "publish"] }, created_after: { type: "string", maxLength: 100 }, created_before: { type: "string", maxLength: 100 }, ...pageProperties }, additionalProperties: false } },
    { name: "descript.getJob", functionName: "descript_get_job", aliases: ["descript.getJob", "descript_get_job"], capability: "projects_read", platformCapability: "descript_projects_read", action: "read", approvalRequired: false, description: "Read one job's status.", inputSchema: { type: "object", properties: { jobId: { type: "string", format: "uuid" } }, required: ["jobId"], additionalProperties: false } },
    { name: "descript.listAgentModels", functionName: "descript_list_agent_models", aliases: ["descript.listAgentModels", "descript_list_agent_models"], capability: "projects_read", platformCapability: "descript_projects_read", action: "read", approvalRequired: false, description: "List available Underlord models and aliases.", inputSchema: { type: "object", properties: {}, additionalProperties: false } },
    { name: "descript.exportTranscript", functionName: "descript_export_transcript", aliases: ["descript.exportTranscript", "descript_export_transcript"], capability: "transcripts", platformCapability: "descript_transcripts", action: "read", approvalRequired: false, description: "Export a bounded project transcript.", inputSchema: { type: "object", properties: { project_id: { type: "string", format: "uuid" }, composition_id: { type: "string", format: "uuid" }, format: { type: "string", enum: ["txt", "markdown", "html", "rtf", "docx", "srt"] }, include_speaker_labels: { type: "string", enum: ["off", "changes", "every_paragraph"] }, include_markers: { type: "boolean" }, timecodes: { type: "object" } }, required: ["project_id", "format"], additionalProperties: false } },
    { name: "descript.importMedia", functionName: "descript_import_media", aliases: ["descript.importMedia", "descript_import_media"], capability: "production", platformCapability: "descript_production", action: "write", approvalRequired: true, description: "Import URL-hosted media or create a project and compositions.", inputSchema: { type: "object", properties: { project_id: { type: "string", format: "uuid" }, project_name: { type: "string", maxLength: 1000 }, team_access: { type: "string", enum: ["edit", "comment", "view", "none"] }, folder_name: { type: "string", maxLength: 2000 }, add_media: { type: "object" }, add_compositions: { type: "array", maxItems: 100 }, approvalId: { type: "string" } }, additionalProperties: false } },
    { name: "descript.agentEdit", functionName: "descript_agent_edit", aliases: ["descript.agentEdit", "descript_agent_edit"], capability: "production", platformCapability: "descript_production", action: "write", approvalRequired: true, description: "Create or edit a project with Underlord.", inputSchema: { type: "object", properties: { project_id: { type: "string", format: "uuid" }, project_name: { type: "string", maxLength: 1000 }, composition_id: { type: "string", maxLength: 1000 }, model: { type: "string", maxLength: 200 }, prompt: { type: "string", minLength: 1, maxLength: 50000 }, team_access: { type: "string", enum: ["edit", "comment", "view", "none"] }, conversation_id: { type: "string", format: "uuid" }, approvalId: { type: "string" } }, required: ["prompt"], additionalProperties: false } },
    { name: "descript.publish", functionName: "descript_publish", aliases: ["descript.publish", "descript_publish"], capability: "publishing", platformCapability: "descript_publishing", action: "write", approvalRequired: true, description: "Publish a project composition.", inputSchema: { type: "object", properties: { project_id: { type: "string", format: "uuid" }, composition_id: { type: "string", maxLength: 1000 }, media_type: { type: "string", enum: ["Video", "Audio"] }, resolution: { type: "string", enum: ["480p", "720p", "1080p", "1440p", "4K"] }, access_level: { type: "string", enum: ["public", "unlisted", "drive", "private"] }, approvalId: { type: "string" } }, required: ["project_id"], additionalProperties: false } },
    { name: "descript.cancelJob", functionName: "descript_cancel_job", aliases: ["descript.cancelJob", "descript_cancel_job"], capability: "publishing", platformCapability: "descript_publishing", action: "write", approvalRequired: true, description: "Cancel a running job.", inputSchema: { type: "object", properties: { jobId: { type: "string", format: "uuid" }, approvalId: { type: "string" } }, required: ["jobId"], additionalProperties: false } },
    { name: "descript.request", functionName: "descript_request", aliases: ["descript.request", "descript_request", "descript_full_api"], capability: "administration", platformCapability: "descript_administration", action: "admin", approvalRequired: true, description: "Call an exact documented public v1 operation on the fixed Descript API origin.", inputSchema: { type: "object", properties: { method: { type: "string", enum: ["GET", "POST", "DELETE"] }, path: { type: "string", pattern: "^/" }, query: { type: "object" }, json: { type: "object" }, approvalId: { type: "string" } }, required: ["method", "path"], additionalProperties: false } },
  ],
  approvalProfiles: [
    { id: "descript_safe", label: "Safe", description: "Bounded project, job, model, and transcript reads run directly; imports, AI edits, publishing, cancellation, and other operations require approval.", defaultSelected: true, allowedActions: reads, approvalRequiredActions: changes, blockedActions: [] },
    { id: "dangerously_skip_permissions", label: "Dangerously skip permissions", description: "Every selected token- and Drive-authorized Descript API operation runs without Relay per-action approval; ownership, token secrecy, fixed origin, bounds, audits, plan credits, and provider limits still apply.", defaultSelected: false, allowedActions: [...reads, ...changes], approvalRequiredActions: [], blockedActions: [] },
  ],
  healthChecks: [{ id: "projects", label: "Descript Drive token validation with a one-project bounded read" }],
};
