import { partnerFinanceConnector } from "../partner-finance/partner-finance-connector.factory";

export const ETORO_CONNECTOR_MANIFEST = partnerFinanceConnector({
  slug: "etoro",
  name: "eToro",
  functionPrefix: "etoro",
  docsUrl: "https://api-portal.etoro.com/",
  websiteUrl: "https://www.etoro.com/",
  credentialSchema: [
    {
      name: "ETORO_PUBLIC_API_KEY",
      label: "eToro public API key",
      required: true,
      secret: true,
      storedIn: "encrypted_secret",
      helpText: "The application key available to the verified eToro API user.",
    },
    {
      name: "ETORO_USER_KEY",
      label: "eToro user key",
      required: true,
      secret: true,
      storedIn: "encrypted_secret",
      helpText:
        "The exact Demo or Real, Read or Write user key generated by the customer with optional IP and expiry restrictions.",
    },
  ],
  readDescription:
    "Read one bounded documented eToro portfolio, market, watchlist, social, or account resource authorized by the exact user key.",
  fullDescription:
    "Use the complete documented eToro Public API surface authorized by the exact user key, including trading and social mutations; Safe mode requires approval.",
});
