import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Generated from Donately official API v2 reference on 2026-07-17. */
export const DONATELY_OPERATIONS = [
  {
    id: "get_accounts",
    method: "GET",
    path: "/accounts",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List accounts",
  },
  {
    id: "get_accounts_by_id",
    method: "GET",
    path: "/accounts/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get account",
  },
  {
    id: "get_accounts_mine",
    method: "GET",
    path: "/accounts/mine",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get current account",
  },
  {
    id: "post_accounts",
    method: "POST",
    path: "/accounts",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create account",
  },
  {
    id: "post_accounts_by_id",
    method: "POST",
    path: "/accounts/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update account",
  },
  {
    id: "get_campaigns",
    method: "GET",
    path: "/campaigns",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List campaigns",
  },
  {
    id: "get_campaigns_by_id",
    method: "GET",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get campaign",
  },
  {
    id: "post_campaigns",
    method: "POST",
    path: "/campaigns",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create campaign",
  },
  {
    id: "post_campaigns_by_id",
    method: "POST",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update campaign",
  },
  {
    id: "delete_campaigns_by_id",
    method: "DELETE",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete campaign",
  },
  {
    id: "get_donations",
    method: "GET",
    path: "/donations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List donations",
  },
  {
    id: "get_donations_by_id",
    method: "GET",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get donation",
  },
  {
    id: "post_donations",
    method: "POST",
    path: "/donations",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create donation",
  },
  {
    id: "post_donations_by_id",
    method: "POST",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update donation",
  },
  {
    id: "post_donations_by_id_refund",
    method: "POST",
    path: "/donations/{id}/refund",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Refund donation",
  },
  {
    id: "post_donations_by_id_send_receipt",
    method: "POST",
    path: "/donations/{id}/send_receipt",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Resend receipt",
  },
  {
    id: "get_subscriptions",
    method: "GET",
    path: "/subscriptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List subscriptions",
  },
  {
    id: "get_subscriptions_by_id",
    method: "GET",
    path: "/subscriptions/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get subscription",
  },
  {
    id: "post_subscriptions_by_id",
    method: "POST",
    path: "/subscriptions/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update subscription",
  },
  {
    id: "post_subscriptions_by_id_run_now",
    method: "POST",
    path: "/subscriptions/{id}/run_now",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Charge now",
  },
  {
    id: "get_people",
    method: "GET",
    path: "/people",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List people",
  },
  {
    id: "get_people_by_id",
    method: "GET",
    path: "/people/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get person",
  },
  {
    id: "post_people",
    method: "POST",
    path: "/people",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create person",
  },
  {
    id: "get_people_exists",
    method: "GET",
    path: "/people/exists",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Check if person exists",
  },
  {
    id: "get_people_tax_receipt",
    method: "GET",
    path: "/people/tax_receipt",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get tax receipt",
  },
  {
    id: "get_fundraisers",
    method: "GET",
    path: "/fundraisers",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List fundraisers",
  },
  {
    id: "get_fundraisers_by_id",
    method: "GET",
    path: "/fundraisers/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get fundraiser",
  },
  {
    id: "get_forms",
    method: "GET",
    path: "/forms",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List forms",
  },
  {
    id: "get_forms_by_id",
    method: "GET",
    path: "/forms/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get form",
  },
  {
    id: "get_forms_by_id_config",
    method: "GET",
    path: "/forms/{id}/config",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get form config",
  },
  {
    id: "post_forms",
    method: "POST",
    path: "/forms",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create form",
  },
  {
    id: "post_forms_by_id",
    method: "POST",
    path: "/forms/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update form",
  },
  {
    id: "post_forms_by_id_make_form_default",
    method: "POST",
    path: "/forms/{id}/make_form_default",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Set as default",
  },
  {
    id: "delete_forms_by_id",
    method: "DELETE",
    path: "/forms/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete form",
  },
  {
    id: "get_webhooks",
    method: "GET",
    path: "/webhooks",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List webhooks",
  },
  {
    id: "get_webhooks_by_id",
    method: "GET",
    path: "/webhooks/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get webhook",
  },
  {
    id: "post_webhooks",
    method: "POST",
    path: "/webhooks",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create webhook",
  },
  {
    id: "delete_webhooks_by_id",
    method: "DELETE",
    path: "/webhooks/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete webhook",
  },
] as const satisfies readonly BoundedRestOperation[];

export const DONATELY_READ_OPERATION_IDS = DONATELY_OPERATIONS.filter(
  (item) => !item.mutating,
).map((item) => item.id);
export const DONATELY_MANAGE_OPERATION_IDS = DONATELY_OPERATIONS.filter(
  (item) => item.mutating,
).map((item) => item.id);

export const DONATELY_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "donately",
  name: "Donately",
  baseUrl: "https://api.donately.com/v2/",
  basicAuthorization: { usernameCredentialName: "DONATELY_API_TOKEN" },
  headers: { "Donately-Version": "2022-12-15" },
  credentialHeaders: [
    { headerName: "Donately-Account", credentialName: "DONATELY_ACCOUNT_ID" },
  ],
  operations: DONATELY_OPERATIONS,
  health: { operationId: "get_accounts_mine" },
};
