import type { MarketplaceConnectorSafeErrorCode } from "../types";
type Obj=Record<string,unknown>;
type Requester=(url:string|URL,init:RequestInit)=>Promise<Response>;
export type PushwooshCredentials={apiToken:string;applicationCode:string};
export class PushwooshApiError extends Error{constructor(public readonly code:MarketplaceConnectorSafeErrorCode,message:string,public readonly statusCode?:number){super(message)}}
export class PushwooshApiAdapter{
  private static readonly origin="https://api.pushwoosh.com";
  constructor(private readonly requester:Requester=fetch,private readonly now:()=>Date=()=>new Date()){}
  async health(credentials:PushwooshCredentials){await this.getSubscriberStatusSummary(credentials);return{apiOrigin:PushwooshApiAdapter.origin,applicationCode:credentials.applicationCode.toUpperCase()}}
  async getSubscriberStatusSummary(credentials:PushwooshCredentials){this.validate(credentials);const end=this.completedHour(this.now()),start=new Date(end.getTime()-24*60*60*1000),intervalFrom=this.format(start),intervalTo=this.format(end);const body={application_code:credentials.applicationCode.toUpperCase(),timestamp_from:intervalFrom,timestamp_to:intervalTo};const root=this.object(await this.post(new URL("/api/v2/statistics/application/getSubscribersStatistics",PushwooshApiAdapter.origin),credentials,body));const statistics=Array.isArray(root.statistics)?root.statistics:[];return{applicationCode:credentials.applicationCode.toUpperCase(),intervalFrom,intervalTo,statistics:statistics.slice(0,100).map(value=>{const item=this.object(value);return{timestamp:this.timestamp(item.timestamp),platform:this.platform(item.platform),pushEnabled:this.count(item.push_enabled),pushDisabled:this.count(item.push_disabled)}}),redactionStatus:"users-devices-tags-events-content-targeting-and-detailed-analytics-excluded"}}
  private async post(url:URL,credentials:PushwooshCredentials,body:Obj){let response:Response;try{response=await this.requester(url,{method:"POST",redirect:"error",signal:AbortSignal.timeout(30_000),cache:"no-store",headers:{Accept:"application/json","Content-Type":"application/json",Authorization:`Key ${credentials.apiToken}`,"User-Agent":"RelayConsole-Pushwoosh/1.0"},body:JSON.stringify(body)})}catch(error){if(error instanceof PushwooshApiError)throw error;throw new PushwooshApiError("provider_unavailable","Pushwoosh could not be reached.")}return this.response(response)}
  private async response(response:Response){const declared=Number(response.headers.get("content-length")??0);if(declared>1_000_000)throw this.validation("Pushwoosh response exceeds the 1 MB Relay boundary.");const raw=await response.text();if(Buffer.byteLength(raw,"utf8")>1_000_000)throw this.validation("Pushwoosh response exceeds the 1 MB Relay boundary.");let body:unknown;try{body=raw?JSON.parse(raw):null}catch{throw this.validation("Pushwoosh returned invalid JSON.",response.status)}if(!response.ok)throw new PushwooshApiError(this.safeCode(response.status),`Pushwoosh returned HTTP ${response.status}.`,response.status);return body}
  private validate(credentials:PushwooshCredentials){if(!credentials.apiToken.trim()||credentials.apiToken.length>30_000||/[\r\n]/.test(credentials.apiToken))throw new PushwooshApiError("credential_missing","A valid Pushwoosh Server API token is required.",401);if(!/^[A-Za-z0-9]{5}-[A-Za-z0-9]{5}$/.test(credentials.applicationCode))throw this.validation("Pushwoosh requires an exact 5-5 application code.")}
  private completedHour(value:Date){if(Number.isNaN(value.getTime()))throw this.validation("Pushwoosh statistics clock is invalid.");return new Date(Date.UTC(value.getUTCFullYear(),value.getUTCMonth(),value.getUTCDate(),value.getUTCHours()))}
  private format(value:Date){const n=(part:number)=>String(part).padStart(2,"0");return`${value.getUTCFullYear()}-${n(value.getUTCMonth()+1)}-${n(value.getUTCDate())} ${n(value.getUTCHours())}:${n(value.getUTCMinutes())}:${n(value.getUTCSeconds())}`}
  private timestamp(value:unknown){return typeof value==="string"&&/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value)?value:null}
  private platform(value:unknown){return typeof value==="number"&&Number.isSafeInteger(value)&&value>=0&&value<=100?value:null}
  private count(value:unknown){return typeof value==="number"&&Number.isSafeInteger(value)&&value>=0?value:null}
  private object(value:unknown):Obj{return value&&typeof value==="object"&&!Array.isArray(value)?value as Obj:{}}
  private safeCode(status:number):MarketplaceConnectorSafeErrorCode{if(status===401)return"token_expired";if(status===403||status===404)return"insufficient_scope";if(status===429)return"provider_rate_limited";if(status>=500)return"provider_unavailable";return"provider_validation_error"}
  private validation(message:string,statusCode?:number){return new PushwooshApiError("provider_validation_error",message,statusCode)}
}
