import assert from "node:assert/strict";
import { createRequire } from "node:module";
import test from "node:test";
import {
  analyzeTypeScriptFunctions,
  countSourceLines,
  evaluateGeneratedSources,
  evaluateOversizedFileProvenance,
  evaluateOversizedFiles,
  selectHandwrittenSources,
} from "./source-structure-gate.mjs";

const require = createRequire(
  new URL("../backend/package.json", import.meta.url),
);
const ts = require("typescript");

test("countSourceLines handles terminated and unterminated source", () => {
  assert.equal(countSourceLines(""), 0);
  assert.equal(countSourceLines("one\n"), 1);
  assert.equal(countSourceLines("one\ntwo"), 2);
});

test("evaluateOversizedFiles accepts an explained decreasing ratchet", () => {
  assert.deepEqual(
    evaluateOversizedFiles(
      { "src/large.ts": 2100 },
      2000,
      {
        "src/large.ts": {
          maximumLines: 2200,
          reason: "This existing service has a scheduled extraction package.",
          workPackage: "WP-05",
        },
      },
      { "src/": "Source platform maintainers" },
    ),
    [],
  );
});

test("evaluateOversizedFiles rejects new growth and stale exceptions", () => {
  const errors = evaluateOversizedFiles(
    {
      "src/new.ts": 2100,
      "src/grew.ts": 2300,
      "src/small.ts": 1900,
    },
    2000,
    {
      "src/grew.ts": {
        maximumLines: 2200,
        reason: "This existing service has a scheduled extraction package.",
        workPackage: "WP-05",
      },
      "src/small.ts": {
        maximumLines: 2200,
        reason: "This source has already moved below the global threshold.",
        workPackage: "WP-05",
      },
    },
  );
  assert.ok(errors.some((error) => error.includes("src/new.ts has 2100")));
  assert.ok(errors.some((error) => error.includes("grew from its 2200")));
  assert.ok(errors.some((error) => error.includes("stale oversized-file")));
  assert.ok(
    errors.some((error) =>
      error.includes("no accountable oversized-file owner"),
    ),
  );
});

test("post-baseline source cannot receive an oversized-file exception", () => {
  const exceptions = {
    "src/existing.ts": {},
    "src/new.ts": {},
  };
  assert.deepEqual(
    evaluateOversizedFileProvenance(exceptions, new Set(["src/existing.ts"])),
    [
      "src/new.ts was added after the structural baseline and cannot receive an oversized-file exception",
    ],
  );
});

test("generated source requires exact provenance and stays out of debt ratchets", () => {
  const sourceTexts = {
    "src/generated.ts":
      "// Generated by scripts/generate-large.mjs.\nexport const rows = [];\n",
    "src/handwritten.ts": "export function run() { return true; }\n",
  };
  const declaration = {
    "src/generated.ts": {
      marker: "Generated by scripts/generate-large.mjs.",
      generator: "scripts/generate-large.mjs",
      owner: "Source platform maintainers",
    },
  };
  assert.deepEqual(
    evaluateGeneratedSources(
      sourceTexts,
      declaration,
      (path) => path === "scripts/generate-large.mjs",
    ),
    [],
  );
  assert.deepEqual(selectHandwrittenSources(sourceTexts, declaration), {
    "src/handwritten.ts": "export function run() { return true; }\n",
  });

  const errors = evaluateGeneratedSources(
    sourceTexts,
    declaration,
    () => false,
    { "src/generated.ts": {} },
    { "src/generated.ts": {} },
  );
  assert.ok(errors.some((error) => error.includes("missing generator")));
  assert.ok(
    errors.some((error) =>
      error.includes("both generated source and an oversized-file exception"),
    ),
  );
  assert.ok(
    errors.some((error) =>
      error.includes("both generated source and a function ratchet"),
    ),
  );
});

test("generated source rejects stale, unmarked, and ambiguous declarations", () => {
  const errors = evaluateGeneratedSources(
    {
      "src/unmarked.ts": "export const rows = [];\n",
      "src/ambiguous.ts": "// Generated from an official source.\n",
    },
    {
      "src/missing.ts": {
        marker: "Generated from",
        externalProvenance: "Official provider API specification.",
        owner: "Source platform maintainers",
      },
      "src/unmarked.ts": {
        marker: "Generated from",
        externalProvenance: "Official provider API specification.",
        owner: "Source platform maintainers",
      },
      "src/ambiguous.ts": {
        marker: "Generated from",
        generator: "scripts/generate-ambiguous.mjs",
        externalProvenance: "Official provider API specification.",
        owner: "Source platform maintainers",
      },
    },
  );
  assert.ok(errors.some((error) => error.includes("missing source")));
  assert.ok(errors.some((error) => error.includes("first 10 lines")));
  assert.ok(errors.some((error) => error.includes("malformed")));
});

test("analyzeTypeScriptFunctions reports function spans", () => {
  const source = [
    "export function short() {",
    "  return 1;",
    "}",
    "",
    "export const arrow = () => {",
    "  return 2;",
    "};",
    "",
  ].join("\n");
  assert.deepEqual(analyzeTypeScriptFunctions("example.ts", source, ts), {
    maximumFunctionLines: 3,
    maximumFunctionName: "short",
    functionsOver500Lines: 0,
  });
});
