import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

function operation(
  id: string,
  method: BoundedRestOperation["method"],
  path: string,
  pathParameters: readonly string[],
  mutating: boolean,
  bodyAllowed: boolean,
  description: string,
): BoundedRestOperation {
  return {
    id,
    method,
    path,
    pathParameters,
    mutating,
    bodyAllowed,
    description,
  };
}

export const GIVEBUTTER_OPERATIONS = [
  operation(
    "account_self",
    "GET",
    "/account",
    [],
    false,
    false,
    "Read the authenticated Givebutter account.",
  ),
  operation(
    "add_contact_tags",
    "POST",
    "/contacts/{contact}/tags",
    ["contact"],
    true,
    true,
    "Add tags to a contact.",
  ),
  operation(
    "remove_contact_tags",
    "DELETE",
    "/contacts/{contact}/tags",
    ["contact"],
    true,
    false,
    "Remove tags from a contact.",
  ),
  operation(
    "add_household_contacts",
    "POST",
    "/households/{household}/contacts/associate",
    ["household"],
    true,
    true,
    "Associate contacts with a household.",
  ),
  operation(
    "campaigns_index",
    "GET",
    "/campaigns",
    [],
    false,
    false,
    "List campaigns.",
  ),
  operation(
    "campaigns_store",
    "POST",
    "/campaigns",
    [],
    true,
    true,
    "Create a campaign.",
  ),
  operation(
    "campaigns_show",
    "GET",
    "/campaigns/{campaign}",
    ["campaign"],
    false,
    false,
    "Read a campaign.",
  ),
  operation(
    "campaigns_update",
    "PUT",
    "/campaigns/{campaign}",
    ["campaign"],
    true,
    true,
    "Update a campaign.",
  ),
  operation(
    "campaigns_destroy",
    "DELETE",
    "/campaigns/{campaign}",
    ["campaign"],
    true,
    false,
    "Delete a campaign.",
  ),
  operation(
    "campaign_discount_codes_index",
    "GET",
    "/campaigns/{campaign}/discount-codes",
    ["campaign"],
    false,
    false,
    "List campaign discount codes.",
  ),
  operation(
    "campaign_discount_codes_store",
    "POST",
    "/campaigns/{campaign}/discount-codes",
    ["campaign"],
    true,
    true,
    "Create a campaign discount code.",
  ),
  operation(
    "campaign_discount_codes_show",
    "GET",
    "/campaigns/{campaign}/discount-codes/{discountCode}",
    ["campaign", "discountCode"],
    false,
    false,
    "Read a campaign discount code.",
  ),
  operation(
    "campaign_discount_codes_update",
    "PUT",
    "/campaigns/{campaign}/discount-codes/{discountCode}",
    ["campaign", "discountCode"],
    true,
    true,
    "Update a campaign discount code.",
  ),
  operation(
    "campaign_discount_codes_destroy",
    "DELETE",
    "/campaigns/{campaign}/discount-codes/{discountCode}",
    ["campaign", "discountCode"],
    true,
    false,
    "Delete a campaign discount code.",
  ),
  operation(
    "campaign_tickets_store",
    "POST",
    "/campaign-items/tickets",
    [],
    true,
    true,
    "Create a campaign ticket.",
  ),
  operation(
    "campaign_members_index",
    "GET",
    "/campaigns/{campaign}/members",
    ["campaign"],
    false,
    false,
    "List campaign members.",
  ),
  operation(
    "campaign_members_show",
    "GET",
    "/campaigns/{campaign}/members/{member}",
    ["campaign", "member"],
    false,
    false,
    "Read a campaign member.",
  ),
  operation(
    "campaign_members_destroy",
    "DELETE",
    "/campaigns/{campaign}/members/{member}",
    ["campaign", "member"],
    true,
    false,
    "Delete a campaign member.",
  ),
  operation(
    "campaign_teams_index",
    "GET",
    "/campaigns/{campaign}/teams",
    ["campaign"],
    false,
    false,
    "List campaign teams.",
  ),
  operation(
    "campaign_teams_show",
    "GET",
    "/campaigns/{campaign}/teams/{team}",
    ["campaign", "team"],
    false,
    false,
    "Read a campaign team.",
  ),
  operation(
    "campaign_teams_destroy",
    "DELETE",
    "/campaigns/{campaign}/teams/{team}",
    ["campaign", "team"],
    true,
    false,
    "Delete a campaign team.",
  ),
  operation(
    "contacts_index",
    "GET",
    "/contacts",
    [],
    false,
    false,
    "List contacts.",
  ),
  operation(
    "contacts_store",
    "POST",
    "/contacts",
    [],
    true,
    true,
    "Create a contact.",
  ),
  operation(
    "contacts_show",
    "GET",
    "/contacts/{contact}",
    ["contact"],
    false,
    false,
    "Read a contact.",
  ),
  operation(
    "contacts_update",
    "PUT",
    "/contacts/{contact}",
    ["contact"],
    true,
    true,
    "Update a contact.",
  ),
  operation(
    "contacts_destroy",
    "DELETE",
    "/contacts/{contact}",
    ["contact"],
    true,
    false,
    "Archive a contact.",
  ),
  operation(
    "contact_activities_index",
    "GET",
    "/contacts/{contact}/activities",
    ["contact"],
    false,
    false,
    "List contact activities.",
  ),
  operation(
    "contact_activities_store",
    "POST",
    "/contacts/{contact}/activities",
    ["contact"],
    true,
    true,
    "Create a contact activity.",
  ),
  operation(
    "contact_activities_show",
    "GET",
    "/contacts/{contact}/activities/{activity}",
    ["contact", "activity"],
    false,
    false,
    "Read a contact activity.",
  ),
  operation(
    "contact_activities_update",
    "PUT",
    "/contacts/{contact}/activities/{activity}",
    ["contact", "activity"],
    true,
    true,
    "Update a contact activity.",
  ),
  operation(
    "contact_activities_destroy",
    "DELETE",
    "/contacts/{contact}/activities/{activity}",
    ["contact", "activity"],
    true,
    false,
    "Delete a contact activity.",
  ),
  operation("funds_index", "GET", "/funds", [], false, false, "List funds."),
  operation("funds_store", "POST", "/funds", [], true, true, "Create a fund."),
  operation(
    "funds_show",
    "GET",
    "/funds/{fund}",
    ["fund"],
    false,
    false,
    "Read a fund.",
  ),
  operation(
    "funds_update",
    "PUT",
    "/funds/{fund}",
    ["fund"],
    true,
    true,
    "Update a fund.",
  ),
  operation(
    "funds_destroy",
    "DELETE",
    "/funds/{fund}",
    ["fund"],
    true,
    false,
    "Delete a fund.",
  ),
  operation(
    "households_index",
    "GET",
    "/households",
    [],
    false,
    false,
    "List households.",
  ),
  operation(
    "households_store",
    "POST",
    "/households",
    [],
    true,
    true,
    "Create a household.",
  ),
  operation(
    "households_show",
    "GET",
    "/households/{household}",
    ["household"],
    false,
    false,
    "Read a household.",
  ),
  operation(
    "households_update",
    "PUT",
    "/households/{household}",
    ["household"],
    true,
    true,
    "Update a household.",
  ),
  operation(
    "households_destroy",
    "DELETE",
    "/households/{household}",
    ["household"],
    true,
    false,
    "Delete a household.",
  ),
  operation(
    "messages_index",
    "GET",
    "/messages",
    [],
    false,
    false,
    "List messages.",
  ),
  operation(
    "messages_show",
    "GET",
    "/messages/{message}",
    ["message"],
    false,
    false,
    "Read a message.",
  ),
  operation(
    "payouts_index",
    "GET",
    "/payouts",
    [],
    false,
    false,
    "List payouts.",
  ),
  operation(
    "payouts_show",
    "GET",
    "/payouts/{payout}",
    ["payout"],
    false,
    false,
    "Read a payout.",
  ),
  operation(
    "plans_index",
    "GET",
    "/plans",
    [],
    false,
    false,
    "List recurring plans.",
  ),
  operation(
    "plans_show",
    "GET",
    "/plans/{plan}",
    ["plan"],
    false,
    false,
    "Read a recurring plan.",
  ),
  operation(
    "remove_household_contacts",
    "POST",
    "/households/{household}/contacts/disassociate",
    ["household"],
    true,
    true,
    "Disassociate contacts from a household.",
  ),
  operation(
    "restore_contact",
    "PATCH",
    "/contacts/{contact}/restore",
    ["contact"],
    true,
    true,
    "Restore an archived contact.",
  ),
  operation(
    "tickets_index",
    "GET",
    "/tickets",
    [],
    false,
    false,
    "List tickets.",
  ),
  operation(
    "tickets_show",
    "GET",
    "/tickets/{ticket}",
    ["ticket"],
    false,
    false,
    "Read a ticket.",
  ),
  operation(
    "transactions_index",
    "GET",
    "/transactions",
    [],
    false,
    false,
    "List transactions.",
  ),
  operation(
    "transactions_store",
    "POST",
    "/transactions",
    [],
    true,
    true,
    "Create an external transaction.",
  ),
  operation(
    "transactions_show",
    "GET",
    "/transactions/{transaction}",
    ["transaction"],
    false,
    false,
    "Read a transaction.",
  ),
  operation(
    "transactions_update",
    "PUT",
    "/transactions/{transaction}",
    ["transaction"],
    true,
    true,
    "Update a transaction.",
  ),
  operation(
    "webhooks_index",
    "GET",
    "/webhooks",
    [],
    false,
    false,
    "List webhooks.",
  ),
  operation(
    "webhooks_store",
    "POST",
    "/webhooks",
    [],
    true,
    true,
    "Create a webhook.",
  ),
  operation(
    "webhooks_show",
    "GET",
    "/webhooks/{webhook}",
    ["webhook"],
    false,
    false,
    "Read a webhook.",
  ),
  operation(
    "webhooks_update",
    "PUT",
    "/webhooks/{webhook}",
    ["webhook"],
    true,
    true,
    "Update a webhook.",
  ),
  operation(
    "webhooks_destroy",
    "DELETE",
    "/webhooks/{webhook}",
    ["webhook"],
    true,
    false,
    "Delete a webhook.",
  ),
  operation(
    "webhook_activities_index",
    "GET",
    "/webhooks/{webhook}/activities",
    ["webhook"],
    false,
    false,
    "List webhook activities.",
  ),
] as const satisfies readonly BoundedRestOperation[];

export const GIVEBUTTER_READ_OPERATION_IDS = GIVEBUTTER_OPERATIONS.filter(
  (item) => !item.mutating,
).map((item) => item.id);
export const GIVEBUTTER_MANAGE_OPERATION_IDS = GIVEBUTTER_OPERATIONS.filter(
  (item) => item.mutating,
).map((item) => item.id);

export const GIVEBUTTER_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "givebutter",
  name: "Givebutter",
  baseUrl: "https://api.givebutter.com/v1",
  credentialName: "GIVEBUTTER_API_KEY",
  authorization: { headerName: "Authorization", prefix: "Bearer " },
  operations: GIVEBUTTER_OPERATIONS,
  health: { operationId: "account_self" },
};
