import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Generated from Virtuous CRM+'s official public Postman collection on 2026-07-17. Explicitly deprecated Reminder and documentation PenTest examples are excluded. */
export const VIRTUOUS_CRM_OPERATIONS = [
  {
    id: "get_api_organization",
    method: "GET",
    path: "/api/Organization",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Organizations the current user belongs to",
  },
  {
    id: "get_api_organization_current",
    method: "GET",
    path: "/api/Organization/Current",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Current Organization for the current user",
  },
  {
    id: "put_api_organization_switch",
    method: "PUT",
    path: "/api/Organization/Switch",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Switch the Current Organization",
  },
  {
    id: "get_api_permission",
    method: "GET",
    path: "/api/Permission",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Permissions for the current user",
  },
  {
    id: "get_api_contact_by_contact_id",
    method: "GET",
    path: "/api/Contact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Contact",
  },
  {
    id: "get_api_contact_by_reference_source_by_reference_id",
    method: "GET",
    path: "/api/Contact/{referenceSource}/{referenceId}",
    pathParameters: ["referenceSource", "referenceId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Contact by Reference Source and ID",
  },
  {
    id: "get_api_contact_by_reference_by_reference_id",
    method: "GET",
    path: "/api/Contact/ByReference/{referenceId}",
    pathParameters: ["referenceId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Contact by Reference ID",
  },
  {
    id: "get_api_contact_by_tag_by_tag_id",
    method: "GET",
    path: "/api/Contact/ByTag/{tagId}",
    pathParameters: ["tagId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contacts by Tag ID",
  },
  {
    id: "get_api_contact_find",
    method: "GET",
    path: "/api/Contact/Find",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Find a Contact by Email Address or Reference Source and ID",
  },
  {
    id: "post_api_contact_search",
    method: "POST",
    path: "/api/Contact/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description:
      "Find all Contacts that match, fully or partially, the given search parameters",
  },
  {
    id: "post_api_contact_proximity",
    method: "POST",
    path: "/api/Contact/Proximity",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description:
      "Find all Contacts within a given proximity of a geocoordinate",
  },
  {
    id: "get_api_contact_activity",
    method: "GET",
    path: "/api/Contact/Activity",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Get the Activity for the Contacts the current user is following",
  },
  {
    id: "get_api_contact_following",
    method: "GET",
    path: "/api/Contact/Following",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Contacts the current user is following",
  },
  {
    id: "post_api_contact",
    method: "POST",
    path: "/api/Contact",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Contact",
  },
  {
    id: "put_api_contact_by_contact_id",
    method: "PUT",
    path: "/api/Contact/{contactId}",
    pathParameters: ["contactId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Contact",
  },
  {
    id: "put_api_contact_archive_by_contact_id",
    method: "PUT",
    path: "/api/Contact/Archive/{contactId}",
    pathParameters: ["contactId"],
    mutating: true,
    bodyAllowed: true,
    description: "Archive a Contact",
  },
  {
    id: "put_api_contact_unarchive_by_contact_id",
    method: "PUT",
    path: "/api/Contact/Unarchive/{contactId}",
    pathParameters: ["contactId"],
    mutating: true,
    bodyAllowed: true,
    description: "Unarchive a Contact",
  },
  {
    id: "put_api_contact_toggle_follow_by_contact_id",
    method: "PUT",
    path: "/api/Contact/ToggleFollow/{contactId}",
    pathParameters: ["contactId"],
    mutating: true,
    bodyAllowed: true,
    description: "Follow or Unfollow a Contact for the current user",
  },
  {
    id: "get_api_contact_custom_collections",
    method: "GET",
    path: "/api/Contact/CustomCollections",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Custom Collections for Contacts",
  },
  {
    id: "post_api_contact_by_contact_id_collection_by_custom_collection_id",
    method: "POST",
    path: "/api/Contact/{contactId}/Collection/{customCollectionId}",
    pathParameters: ["contactId", "customCollectionId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create Collection for a Contact",
  },
  {
    id: "put_api_contact_by_contact_id_collection_by_collection_instance_id",
    method: "PUT",
    path: "/api/Contact/{contactId}/Collection/{collectionInstanceId}",
    pathParameters: ["contactId", "collectionInstanceId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Collection for a Contact",
  },
  {
    id: "delete_api_contact_by_contact_id_collection_by_collection_instance_id",
    method: "DELETE",
    path: "/api/Contact/{contactId}/Collection/{collectionInstanceId}",
    pathParameters: ["contactId", "collectionInstanceId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Collection for a Contact",
  },
  {
    id: "post_api_contact_transaction",
    method: "POST",
    path: "/api/Contact/Transaction",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Contact that will go through the import process",
  },
  {
    id: "post_api_contact_batch",
    method: "POST",
    path: "/api/Contact/Batch",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description:
      "Create a Contact Import that will be processed for changes and duplicates",
  },
  {
    id: "get_api_contact_prefixes",
    method: "GET",
    path: "/api/Contact/Prefixes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Name Prefixes and Titles",
  },
  {
    id: "get_api_contact_types",
    method: "GET",
    path: "/api/Contact/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Types",
  },
  {
    id: "get_api_contact_custom_fields",
    method: "GET",
    path: "/api/Contact/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Custom Fields Available",
  },
  {
    id: "get_api_contact_query_options",
    method: "GET",
    path: "/api/Contact/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Query Options",
  },
  {
    id: "post_api_contact_query",
    method: "POST",
    path: "/api/Contact/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Contacts with Abbreviated Details",
  },
  {
    id: "post_api_contact_query_full_contact",
    method: "POST",
    path: "/api/Contact/Query/FullContact",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Contacts with Full Details",
  },
  {
    id: "get_api_contact_receipts",
    method: "GET",
    path: "/api/Contact/Receipts",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Receipts",
  },
  {
    id: "get_api_contact_receipts_by_receipt_id",
    method: "GET",
    path: "/api/Contact/Receipts/{receiptId}",
    pathParameters: ["receiptId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Receipt",
  },
  {
    id: "get_api_contact_individual_by_contact_by_contact_id",
    method: "GET",
    path: "/api/ContactIndividual/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Individuals for a Contact",
  },
  {
    id: "get_api_contact_individual_by_contact_individual_id",
    method: "GET",
    path: "/api/ContactIndividual/{contactIndividualId}",
    pathParameters: ["contactIndividualId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an Individual",
  },
  {
    id: "get_api_contact_individual_find",
    method: "GET",
    path: "/api/ContactIndividual/Find",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Find an individual by email address",
  },
  {
    id: "get_api_contact_individual_by_contact_individual_id_avatar",
    method: "GET",
    path: "/api/ContactIndividual/{contactIndividualId}/Avatar",
    pathParameters: ["contactIndividualId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets the avatar for a specified contact individual",
  },
  {
    id: "post_api_contact_individual",
    method: "POST",
    path: "/api/ContactIndividual",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create an Individual",
  },
  {
    id: "post_api_contact_individual_by_contact_individual_id_avatar",
    method: "POST",
    path: "/api/ContactIndividual/{contactIndividualId}/Avatar",
    pathParameters: ["contactIndividualId"],
    mutating: true,
    bodyAllowed: true,
    description: "Upload the avatar for an Individual",
  },
  {
    id: "put_api_contact_individual_by_contact_individual_id",
    method: "PUT",
    path: "/api/ContactIndividual/{contactIndividualId}",
    pathParameters: ["contactIndividualId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update an Individual",
  },
  {
    id: "delete_api_contact_individual_by_contact_individual_id",
    method: "DELETE",
    path: "/api/ContactIndividual/{contactIndividualId}",
    pathParameters: ["contactIndividualId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete an Individual",
  },
  {
    id: "get_api_contact_individual_custom_collections",
    method: "GET",
    path: "/api/ContactIndividual/CustomCollections",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Custom Collections for Individuals",
  },
  {
    id: "post_api_contact_individual_by_contact_individual_id_collection_by_custom_collection_id",
    method: "POST",
    path: "/api/ContactIndividual/{contactIndividualId}/Collection/{customCollectionId}",
    pathParameters: ["contactIndividualId", "customCollectionId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create Collection for an Individual",
  },
  {
    id: "put_api_contact_individual_by_contact_individual_id_collection_by_collection_instance_id",
    method: "PUT",
    path: "/api/ContactIndividual/{contactIndividualId}/Collection/{collectionInstanceId}",
    pathParameters: ["contactIndividualId", "collectionInstanceId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Collection for an Individual",
  },
  {
    id: "delete_api_contact_individual_by_contact_individual_id_collection_by_collection_id",
    method: "DELETE",
    path: "/api/ContactIndividual/{contactIndividualId}/Collection/{collectionId}",
    pathParameters: ["contactIndividualId", "collectionId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Collection for an Individual",
  },
  {
    id: "get_api_contact_individual_custom_fields",
    method: "GET",
    path: "/api/ContactIndividual/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets the custom fields for contact individuals",
  },
  {
    id: "get_api_contact_individual_query_options",
    method: "GET",
    path: "/api/ContactIndividual/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Individual Query Options",
  },
  {
    id: "post_api_contact_individual_query",
    method: "POST",
    path: "/api/ContactIndividual/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Individuals",
  },
  {
    id: "get_api_contact_individual_by_contact_individual_id_email_list",
    method: "GET",
    path: "/api/ContactIndividual/{contactIndividualId}/EmailList",
    pathParameters: ["contactIndividualId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Email Lists for an Individual",
  },
  {
    id: "get_api_contact_address_by_contact_by_contact_id",
    method: "GET",
    path: "/api/ContactAddress/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Contact Addresses for a Contact",
  },
  {
    id: "get_api_contact_address_by_contact_address_id",
    method: "GET",
    path: "/api/ContactAddress/{contactAddressId}",
    pathParameters: ["contactAddressId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Contact Address",
  },
  {
    id: "post_api_contact_address",
    method: "POST",
    path: "/api/ContactAddress",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Contact Address",
  },
  {
    id: "put_api_contact_address_by_contact_address_id",
    method: "PUT",
    path: "/api/ContactAddress/{contactAddressId}",
    pathParameters: ["contactAddressId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Contact Address",
  },
  {
    id: "put_api_contact_address_archive_by_contact_address_id",
    method: "PUT",
    path: "/api/ContactAddress/Archive/{contactAddressId}",
    pathParameters: ["contactAddressId"],
    mutating: true,
    bodyAllowed: true,
    description: "Archive a Contact Address",
  },
  {
    id: "put_api_contact_address_unarchive_by_contact_address_id",
    method: "PUT",
    path: "/api/ContactAddress/Unarchive/{contactAddressId}",
    pathParameters: ["contactAddressId"],
    mutating: true,
    bodyAllowed: true,
    description: "Unarchive a Contact Address",
  },
  {
    id: "delete_api_contact_address_by_contact_address_id",
    method: "DELETE",
    path: "/api/ContactAddress/{contactAddressId}",
    pathParameters: ["contactAddressId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Contact Address",
  },
  {
    id: "get_api_contact_method_types",
    method: "GET",
    path: "/api/ContactMethod/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Method Types",
  },
  {
    id: "get_api_contact_method_related_types",
    method: "GET",
    path: "/api/ContactMethod/RelatedTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Methods Types related to the Base Type",
  },
  {
    id: "get_api_contact_method_by_contact_method_id",
    method: "GET",
    path: "/api/ContactMethod/{contactMethodId}",
    pathParameters: ["contactMethodId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Contact Method",
  },
  {
    id: "post_api_contact_method",
    method: "POST",
    path: "/api/ContactMethod",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Contact Method for an Individual",
  },
  {
    id: "put_api_contact_method_by_contact_method_id",
    method: "PUT",
    path: "/api/ContactMethod/{contactMethodId}",
    pathParameters: ["contactMethodId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Contact Method",
  },
  {
    id: "put_api_contact_method_archive_by_contact_method_id",
    method: "PUT",
    path: "/api/ContactMethod/Archive/{contactMethodId}",
    pathParameters: ["contactMethodId"],
    mutating: true,
    bodyAllowed: true,
    description: "Archive a Contact Method",
  },
  {
    id: "put_api_contact_method_unarchive_by_contact_method_id",
    method: "PUT",
    path: "/api/ContactMethod/Unarchive/{contactMethodId}",
    pathParameters: ["contactMethodId"],
    mutating: true,
    bodyAllowed: true,
    description: "Unarchive a Contact Method",
  },
  {
    id: "delete_api_contact_method_by_contact_method_id",
    method: "DELETE",
    path: "/api/ContactMethod/{contactMethodId}",
    pathParameters: ["contactMethodId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Contact Method",
  },
  {
    id: "get_api_contact_note_by_contact_by_contact_id",
    method: "GET",
    path: "/api/ContactNote/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Notes for a Contact",
  },
  {
    id: "get_api_contact_note_important_by_contact_by_contact_id",
    method: "GET",
    path: "/api/ContactNote/Important/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Important Notes for a Contact",
  },
  {
    id: "get_api_contact_note_by_note_id",
    method: "GET",
    path: "/api/ContactNote/{noteId}",
    pathParameters: ["noteId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Note",
  },
  {
    id: "post_api_contact_note",
    method: "POST",
    path: "/api/ContactNote",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Note for a Contact",
  },
  {
    id: "post_api_contact_note_email",
    method: "POST",
    path: "/api/ContactNote/Email",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Note using an Email",
  },
  {
    id: "put_api_contact_note_by_note_id",
    method: "PUT",
    path: "/api/ContactNote/{noteId}",
    pathParameters: ["noteId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Note",
  },
  {
    id: "delete_api_contact_note_by_note_id",
    method: "DELETE",
    path: "/api/ContactNote/{noteId}",
    pathParameters: ["noteId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Note",
  },
  {
    id: "get_api_contact_note_query_options",
    method: "GET",
    path: "/api/ContactNote/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Note Query Options",
  },
  {
    id: "post_api_contact_note_query",
    method: "POST",
    path: "/api/ContactNote/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Contact Notes",
  },
  {
    id: "get_api_contact_note_types",
    method: "GET",
    path: "/api/ContactNote/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Contact Note Types",
  },
  {
    id: "get_api_contact_note_custom_fields",
    method: "GET",
    path: "/api/ContactNote/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets the custom fields for contact note",
  },
  {
    id: "post_api_contact_reference",
    method: "POST",
    path: "/api/ContactReference",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Contact Reference",
  },
  {
    id: "delete_api_contact_reference_by_reference_source",
    method: "DELETE",
    path: "/api/ContactReference/{referenceSource}",
    pathParameters: ["referenceSource"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Contact Reference",
  },
  {
    id: "get_api_tag",
    method: "GET",
    path: "/api/Tag",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get all Tags",
  },
  {
    id: "post_api_tag_search",
    method: "POST",
    path: "/api/Tag/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Find all Tags that match, fully or partially",
  },
  {
    id: "get_api_contact_tag_by_contact_by_contact_id",
    method: "GET",
    path: "/api/ContactTag/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Tags for a Contact",
  },
  {
    id: "post_api_contact_tag",
    method: "POST",
    path: "/api/ContactTag",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Contact Tag",
  },
  {
    id: "delete_api_contact_tag_by_contact_tag_id",
    method: "DELETE",
    path: "/api/ContactTag/{contactTagId}",
    pathParameters: ["contactTagId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Contact Tag",
  },
  {
    id: "get_api_organization_group",
    method: "GET",
    path: "/api/OrganizationGroup",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get all Organization Groups",
  },
  {
    id: "get_api_organization_group_by_contact_by_contact_id",
    method: "GET",
    path: "/api/OrganizationGroup/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Organization Groups for a Contact",
  },
  {
    id: "get_api_organization_group_by_organization_group_id_contacts",
    method: "GET",
    path: "/api/OrganizationGroup/{organizationGroupId}/contacts",
    pathParameters: ["organizationGroupId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Contacts in an Organization Group",
  },
  {
    id: "get_api_organization_group_by_organization_group_id",
    method: "GET",
    path: "/api/OrganizationGroup/{organizationGroupId}",
    pathParameters: ["organizationGroupId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an Organization Group",
  },
  {
    id: "put_api_organization_group_by_organization_group_id_contacts_by_contact_id",
    method: "PUT",
    path: "/api/OrganizationGroup/{organizationGroupId}/contacts/{contactId}",
    pathParameters: ["organizationGroupId", "contactId"],
    mutating: true,
    bodyAllowed: true,
    description: "Assign a Contact to an Organization Group",
  },
  {
    id: "delete_api_organization_group_by_organization_group_id_contacts_by_contact_id",
    method: "DELETE",
    path: "/api/OrganizationGroup/{organizationGroupId}/contacts/{contactId}",
    pathParameters: ["organizationGroupId", "contactId"],
    mutating: true,
    bodyAllowed: false,
    description: "Remove a Contact from an Organization Group",
  },
  {
    id: "get_api_relationship_by_contact_by_contact_id",
    method: "GET",
    path: "/api/Relationship/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Relationships for a Contact",
  },
  {
    id: "post_api_relationship",
    method: "POST",
    path: "/api/Relationship",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Relationship",
  },
  {
    id: "put_api_relationship_by_relationship_id",
    method: "PUT",
    path: "/api/Relationship/{relationshipId}",
    pathParameters: ["relationshipId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Relationship",
  },
  {
    id: "delete_api_relationship_by_relationship_id",
    method: "DELETE",
    path: "/api/Relationship/{relationshipId}",
    pathParameters: ["relationshipId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Relationship",
  },
  {
    id: "get_api_relationship_types",
    method: "GET",
    path: "/api/Relationship/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Relationship Types",
  },
  {
    id: "get_api_tribute_search",
    method: "GET",
    path: "/api/Tribute/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Search for Tributes",
  },
  {
    id: "post_api_tribute",
    method: "POST",
    path: "/api/Tribute",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Tribute",
  },
  {
    id: "put_api_tribute_by_tribute_id",
    method: "PUT",
    path: "/api/Tribute/{tributeId}",
    pathParameters: ["tributeId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Tribute",
  },
  {
    id: "get_api_gift_by_contact_by_contact_id",
    method: "GET",
    path: "/api/Gift/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gifts for a Contact",
  },
  {
    id: "get_api_gift_by_reference_by_reference_id",
    method: "GET",
    path: "/api/Gift/ByReference/{referenceId}",
    pathParameters: ["referenceId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gifts for a Contact by Reference ID",
  },
  {
    id: "get_api_gift_passthrough_by_contact_by_contact_id",
    method: "GET",
    path: "/api/Gift/Passthrough/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Passthrough Gifts for a Contact",
  },
  {
    id: "get_api_gift_by_gift_id",
    method: "GET",
    path: "/api/Gift/{giftId}",
    pathParameters: ["giftId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Gift",
  },
  {
    id: "get_api_gift_by_transaction_source_by_transaction_id",
    method: "GET",
    path: "/api/Gift/{transactionSource}/{transactionId}",
    pathParameters: ["transactionSource", "transactionId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Gift by Transaction Source and ID",
  },
  {
    id: "post_api_gift",
    method: "POST",
    path: "/api/Gift",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Gift *not recommended*",
  },
  {
    id: "post_api_gift_bulk",
    method: "POST",
    path: "/api/Gift/Bulk",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create many Gifts *not recommended*",
  },
  {
    id: "post_api_gift_reversing_transaction",
    method: "POST",
    path: "/api/Gift/ReversingTransaction",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Reversing Transaction",
  },
  {
    id: "put_api_gift_by_gift_id",
    method: "PUT",
    path: "/api/Gift/{giftId}",
    pathParameters: ["giftId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Gift",
  },
  {
    id: "patch_api_gift",
    method: "PATCH",
    path: "/api/Gift",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Update many Gifts",
  },
  {
    id: "delete_api_gift_by_gift_id",
    method: "DELETE",
    path: "/api/Gift/{giftId}",
    pathParameters: ["giftId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Gift",
  },
  {
    id: "post_api_v2_gift_transaction",
    method: "POST",
    path: "/api/v2/Gift/Transaction",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Gift Transaction",
  },
  {
    id: "post_api_v2_gift_transactions",
    method: "POST",
    path: "/api/v2/Gift/Transactions",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Batch of Gift Transactions",
  },
  {
    id: "get_api_gift_custom_fields",
    method: "GET",
    path: "/api/Gift/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gift Custom Fields Available",
  },
  {
    id: "get_api_gift_non_cash_gift_types",
    method: "GET",
    path: "/api/Gift/NonCashGiftTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Non-Cash Gift Types Available",
  },
  {
    id: "get_api_gift_query_options",
    method: "GET",
    path: "/api/Gift/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gift Query Options",
  },
  {
    id: "post_api_gift_query",
    method: "POST",
    path: "/api/Gift/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Gifts with Abbreviated Details",
  },
  {
    id: "post_api_gift_query_full_gift",
    method: "POST",
    path: "/api/Gift/Query/FullGift",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Gifts with Full Details",
  },
  {
    id: "get_api_gift_designation_query_options",
    method: "GET",
    path: "/api/GiftDesignation/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gift Designation Query Options",
  },
  {
    id: "post_api_gift_designation_query",
    method: "POST",
    path: "/api/GiftDesignation/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Gift Designations",
  },
  {
    id: "get_api_gift_ask_by_contact_by_contact_id",
    method: "GET",
    path: "/api/GiftAsk/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gift Asks for a Contact",
  },
  {
    id: "get_api_gift_ask_by_gift_ask_id_gifts",
    method: "GET",
    path: "/api/GiftAsk/{giftAskId}/Gifts",
    pathParameters: ["giftAskId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Gifts applied to a Gift Ask",
  },
  {
    id: "get_api_gift_ask_by_gift_ask_id",
    method: "GET",
    path: "/api/GiftAsk/{giftAskId}",
    pathParameters: ["giftAskId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Gift Ask",
  },
  {
    id: "post_api_gift_ask",
    method: "POST",
    path: "/api/GiftAsk",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Gift Ask",
  },
  {
    id: "put_api_gift_ask_by_gift_ask_id",
    method: "PUT",
    path: "/api/GiftAsk/{giftAskId}",
    pathParameters: ["giftAskId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Gift Ask",
  },
  {
    id: "get_api_gift_ask_custom_fields",
    method: "GET",
    path: "/api/GiftAsk/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gift Ask Custom Fields Available",
  },
  {
    id: "get_api_gift_ask_query_options",
    method: "GET",
    path: "/api/GiftAsk/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gift Ask Query Options",
  },
  {
    id: "post_api_gift_ask_query",
    method: "POST",
    path: "/api/GiftAsk/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Gift Asks",
  },
  {
    id: "get_api_planned_gift_by_contact_by_contact_id",
    method: "GET",
    path: "/api/PlannedGift/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Planned Gifts for a Contact",
  },
  {
    id: "get_api_planned_gift_by_planned_gift_id",
    method: "GET",
    path: "/api/PlannedGift/{plannedGiftId}",
    pathParameters: ["plannedGiftId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Planned Gift",
  },
  {
    id: "get_api_planned_gift_by_planned_gift_id_gifts",
    method: "GET",
    path: "/api/PlannedGift/{plannedGiftId}/Gifts",
    pathParameters: ["plannedGiftId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Gifts Applied to a Planned Gift",
  },
  {
    id: "post_api_planned_gift",
    method: "POST",
    path: "/api/PlannedGift",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Planned Gift",
  },
  {
    id: "put_api_planned_gift_by_planned_gift_id",
    method: "PUT",
    path: "/api/PlannedGift/{plannedGiftId}",
    pathParameters: ["plannedGiftId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Planned Gift",
  },
  {
    id: "get_api_planned_gift_custom_fields",
    method: "GET",
    path: "/api/PlannedGift/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Planned Gift Custom Fields Available",
  },
  {
    id: "get_api_planned_gift_query_options",
    method: "GET",
    path: "/api/PlannedGift/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Planned Gift Query Options",
  },
  {
    id: "post_api_planned_gift_query",
    method: "POST",
    path: "/api/PlannedGift/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Planned Gifts",
  },
  {
    id: "get_api_v2_pledge_by_contact_by_contact_id",
    method: "GET",
    path: "/api/v2/Pledge/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Pledges for a Contact",
  },
  {
    id: "get_api_v2_pledge_by_pledge_id",
    method: "GET",
    path: "/api/v2/Pledge/{pledgeId}",
    pathParameters: ["pledgeId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Pledge",
  },
  {
    id: "post_api_v2_pledge",
    method: "POST",
    path: "/api/v2/Pledge",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Pledge",
  },
  {
    id: "put_api_v2_pledge_by_pledge_id",
    method: "PUT",
    path: "/api/v2/Pledge/{pledgeId}",
    pathParameters: ["pledgeId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Pledge",
  },
  {
    id: "put_api_v2_pledge_write_off_by_pledge_id",
    method: "PUT",
    path: "/api/v2/Pledge/WriteOff/{pledgeId}",
    pathParameters: ["pledgeId"],
    mutating: true,
    bodyAllowed: true,
    description: "Write-off the Pledge",
  },
  {
    id: "get_api_v2_pledge_custom_fields",
    method: "GET",
    path: "/api/v2/Pledge/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Pledge Custom Fields Available",
  },
  {
    id: "get_api_v2_pledge_query_options",
    method: "GET",
    path: "/api/v2/Pledge/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Pledge Query Options",
  },
  {
    id: "post_api_v2_pledge_query",
    method: "POST",
    path: "/api/v2/Pledge/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Pledges",
  },
  {
    id: "get_api_premium_by_premium_id",
    method: "GET",
    path: "/api/Premium/{premiumId}",
    pathParameters: ["premiumId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Premium",
  },
  {
    id: "get_api_premium_code_by_premium_code",
    method: "GET",
    path: "/api/Premium/Code/{premiumCode}",
    pathParameters: ["premiumCode"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Premium using a unique Code",
  },
  {
    id: "post_api_premium_search",
    method: "POST",
    path: "/api/Premium/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Find Premiums",
  },
  {
    id: "post_api_premium",
    method: "POST",
    path: "/api/Premium",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Premium",
  },
  {
    id: "put_api_premium_by_premium_id",
    method: "PUT",
    path: "/api/Premium/{premiumId}",
    pathParameters: ["premiumId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Premium",
  },
  {
    id: "put_api_premium_increment_by_premium_id",
    method: "PUT",
    path: "/api/Premium/Increment/{premiumId}",
    pathParameters: ["premiumId"],
    mutating: true,
    bodyAllowed: true,
    description: "Increment the inventory count",
  },
  {
    id: "put_api_premium_decrement_by_premium_id",
    method: "PUT",
    path: "/api/Premium/Decrement/{premiumId}",
    pathParameters: ["premiumId"],
    mutating: true,
    bodyAllowed: true,
    description: "Decrement the inventory count",
  },
  {
    id: "get_api_premium_custom_fields",
    method: "GET",
    path: "/api/Premium/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Premium Custom Fields Available",
  },
  {
    id: "post_api_premium_query",
    method: "POST",
    path: "/api/Premium/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Premiums",
  },
  {
    id: "get_api_premium_query_options",
    method: "GET",
    path: "/api/Premium/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Premium Query Options",
  },
  {
    id: "get_api_recurring_gift_by_contact_by_contact_id",
    method: "GET",
    path: "/api/RecurringGift/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Recurring Gifts for a Contact",
  },
  {
    id: "get_api_recurring_gift_by_recurring_gift_id",
    method: "GET",
    path: "/api/RecurringGift/{recurringGiftId}",
    pathParameters: ["recurringGiftId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Recurring Gift",
  },
  {
    id: "post_api_recurring_gift",
    method: "POST",
    path: "/api/RecurringGift",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Recurring Gift",
  },
  {
    id: "put_api_recurring_gift_by_recurring_gift_id",
    method: "PUT",
    path: "/api/RecurringGift/{recurringGiftId}",
    pathParameters: ["recurringGiftId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Recurring Gift",
  },
  {
    id: "put_api_recurring_gift_cancel_by_recurring_gift_id",
    method: "PUT",
    path: "/api/RecurringGift/Cancel/{recurringGiftId}",
    pathParameters: ["recurringGiftId"],
    mutating: true,
    bodyAllowed: true,
    description: "Cancel a Recurring Gift",
  },
  {
    id: "get_api_recurring_gift_custom_fields",
    method: "GET",
    path: "/api/RecurringGift/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Recurring Gift Custom Fields Available",
  },
  {
    id: "get_api_recurring_gift_query_options",
    method: "GET",
    path: "/api/RecurringGift/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Recurring Gift Query Options",
  },
  {
    id: "post_api_recurring_gift_query",
    method: "POST",
    path: "/api/RecurringGift/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Recurring Gifts",
  },
  {
    id: "get_api_recurring_gift_payment_by_recurring_gift_id",
    method: "GET",
    path: "/api/RecurringGiftPayment/{recurringGiftId}",
    pathParameters: ["recurringGiftId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Payments for a Recurring Gift",
  },
  {
    id: "get_api_campaign_by_campaign_id",
    method: "GET",
    path: "/api/Campaign/{campaignId}",
    pathParameters: ["campaignId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Campaign",
  },
  {
    id: "get_api_campaign_get_steps_by_campaign_id_by_campaign_id",
    method: "GET",
    path: "/api/Campaign/GetStepsByCampaignId/{campaignId}",
    pathParameters: ["campaignId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets Campaign Steps",
  },
  {
    id: "get_api_campaign_query_options",
    method: "GET",
    path: "/api/Campaign/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Campaign Query Options",
  },
  {
    id: "post_api_campaign_query",
    method: "POST",
    path: "/api/Campaign/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Campaigns",
  },
  {
    id: "get_api_communication_by_campaign_by_campaign_id",
    method: "GET",
    path: "/api/Communication/ByCampaign/{campaignId}",
    pathParameters: ["campaignId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Communications for a Campaign",
  },
  {
    id: "get_api_communication_by_communication_id",
    method: "GET",
    path: "/api/Communication/{communicationId}",
    pathParameters: ["communicationId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Communication",
  },
  {
    id: "get_api_communication_channel_types",
    method: "GET",
    path: "/api/Communication/ChannelTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Channel Types",
  },
  {
    id: "get_api_communication_communication_types",
    method: "GET",
    path: "/api/Communication/CommunicationTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Communication Types",
  },
  {
    id: "post_api_communication",
    method: "POST",
    path: "/api/Communication",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create Communication",
  },
  {
    id: "post_api_communication_query",
    method: "POST",
    path: "/api/Communication/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Communications",
  },
  {
    id: "get_api_communication_query_options",
    method: "GET",
    path: "/api/Communication/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Communication Query Options",
  },
  {
    id: "get_api_segment_by_contact_by_contact_id",
    method: "GET",
    path: "/api/Segment/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Segments for a Contact",
  },
  {
    id: "get_api_segment_by_segment_id",
    method: "GET",
    path: "/api/Segment/{segmentId}",
    pathParameters: ["segmentId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Segment",
  },
  {
    id: "get_api_segment_code_by_segment_code",
    method: "GET",
    path: "/api/Segment/Code/{segmentCode}",
    pathParameters: ["segmentCode"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Segment using a unique Code",
  },
  {
    id: "post_api_segment_search",
    method: "POST",
    path: "/api/Segment/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Find Segments",
  },
  {
    id: "post_api_segment",
    method: "POST",
    path: "/api/Segment",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Segment",
  },
  {
    id: "put_api_segment_by_segment_id",
    method: "PUT",
    path: "/api/Segment/{segmentId}",
    pathParameters: ["segmentId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Segment",
  },
  {
    id: "get_api_project_by_project_id",
    method: "GET",
    path: "/api/Project/{projectId}",
    pathParameters: ["projectId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project",
  },
  {
    id: "get_api_project_code_by_project_code",
    method: "GET",
    path: "/api/Project/Code/{projectCode}",
    pathParameters: ["projectCode"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Project using a unique Code",
  },
  {
    id: "post_api_project_search",
    method: "POST",
    path: "/api/Project/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Find Projects",
  },
  {
    id: "post_api_project",
    method: "POST",
    path: "/api/Project",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Project",
  },
  {
    id: "put_api_project_by_project_id",
    method: "PUT",
    path: "/api/Project/{projectId}",
    pathParameters: ["projectId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Project",
  },
  {
    id: "patch_api_project",
    method: "PATCH",
    path: "/api/Project",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Update many Projects",
  },
  {
    id: "put_api_project_by_project_id_status",
    method: "PUT",
    path: "/api/Project/{projectId}/Status",
    pathParameters: ["projectId"],
    mutating: true,
    bodyAllowed: true,
    description: "Temporarily Change Project Inventory Status",
  },
  {
    id: "put_api_project_by_project_id_balance",
    method: "PUT",
    path: "/api/Project/{projectId}/Balance",
    pathParameters: ["projectId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Project Balance",
  },
  {
    id: "get_api_project_custom_fields",
    method: "GET",
    path: "/api/Project/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Custom Fields Available",
  },
  {
    id: "get_api_project_types",
    method: "GET",
    path: "/api/Project/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Types",
  },
  {
    id: "get_api_project_query_options",
    method: "GET",
    path: "/api/Project/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Query Options",
  },
  {
    id: "post_api_project_query",
    method: "POST",
    path: "/api/Project/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Projects",
  },
  {
    id: "get_api_project_expense",
    method: "GET",
    path: "/api/ProjectExpense",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Expenses for a Project",
  },
  {
    id: "get_api_project_expense_by_project_expense_id",
    method: "GET",
    path: "/api/ProjectExpense/{projectExpenseId}",
    pathParameters: ["projectExpenseId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Expense",
  },
  {
    id: "post_api_project_expense",
    method: "POST",
    path: "/api/ProjectExpense",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Project Expense",
  },
  {
    id: "post_api_project_expense_batch",
    method: "POST",
    path: "/api/ProjectExpense/Batch",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create many Project Expenses",
  },
  {
    id: "put_api_project_expense_by_project_expense_id",
    method: "PUT",
    path: "/api/ProjectExpense/{projectExpenseId}",
    pathParameters: ["projectExpenseId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Project Expense",
  },
  {
    id: "get_api_project_note_by_project_by_project_id",
    method: "GET",
    path: "/api/ProjectNote/ByProject/{projectId}",
    pathParameters: ["projectId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Notes for a Project",
  },
  {
    id: "get_api_project_note_by_note_id",
    method: "GET",
    path: "/api/ProjectNote/{noteId}",
    pathParameters: ["noteId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Note",
  },
  {
    id: "post_api_project_note",
    method: "POST",
    path: "/api/ProjectNote",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Project Note",
  },
  {
    id: "put_api_project_note_by_note_id",
    method: "PUT",
    path: "/api/ProjectNote/{noteId}",
    pathParameters: ["noteId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Project Note",
  },
  {
    id: "delete_api_project_note_by_note_id",
    method: "DELETE",
    path: "/api/ProjectNote/{noteId}",
    pathParameters: ["noteId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Project Note",
  },
  {
    id: "get_api_project_note_types",
    method: "GET",
    path: "/api/ProjectNote/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Note Types",
  },
  {
    id: "get_api_project_role_by_contact_by_contact_id",
    method: "GET",
    path: "/api/ProjectRole/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Roles for a Contact",
  },
  {
    id: "get_api_project_role_by_project_by_project_id",
    method: "GET",
    path: "/api/ProjectRole/ByProject/{projectId}",
    pathParameters: ["projectId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Roles for a Project",
  },
  {
    id: "get_api_project_role_by_project_role_id",
    method: "GET",
    path: "/api/ProjectRole/{projectRoleId}",
    pathParameters: ["projectRoleId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Role",
  },
  {
    id: "post_api_project_role",
    method: "POST",
    path: "/api/ProjectRole",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Project Role",
  },
  {
    id: "put_api_project_role_by_project_role_id",
    method: "PUT",
    path: "/api/ProjectRole/{projectRoleId}",
    pathParameters: ["projectRoleId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Project Role",
  },
  {
    id: "delete_api_project_role_by_project_role_id",
    method: "DELETE",
    path: "/api/ProjectRole/{projectRoleId}",
    pathParameters: ["projectRoleId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Project Role",
  },
  {
    id: "get_api_project_role_types",
    method: "GET",
    path: "/api/ProjectRole/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Project Role Types",
  },
  {
    id: "get_api_event",
    method: "GET",
    path: "/api/Event",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Events",
  },
  {
    id: "get_api_event_by_event_id",
    method: "GET",
    path: "/api/Event/{eventId}",
    pathParameters: ["eventId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an Event",
  },
  {
    id: "get_api_event_search",
    method: "GET",
    path: "/api/Event/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Find an Event",
  },
  {
    id: "post_api_event",
    method: "POST",
    path: "/api/Event",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create an Event",
  },
  {
    id: "put_api_event_by_event_id",
    method: "PUT",
    path: "/api/Event/{eventId}",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update an Event",
  },
  {
    id: "delete_api_event_by_event_id",
    method: "DELETE",
    path: "/api/Event/{eventId}",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete an Event",
  },
  {
    id: "get_api_event_types",
    method: "GET",
    path: "/api/Event/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Event Types",
  },
  {
    id: "get_api_event_custom_fields",
    method: "GET",
    path: "/api/Event/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Event Custom Fields Available",
  },
  {
    id: "get_api_event_query_options",
    method: "GET",
    path: "/api/Event/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Event Query Options",
  },
  {
    id: "post_api_event_query",
    method: "POST",
    path: "/api/Event/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Events",
  },
  {
    id: "get_api_event_by_event_id_attendees",
    method: "GET",
    path: "/api/Event/{eventId}/Attendees",
    pathParameters: ["eventId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Event Attendees for an Event",
  },
  {
    id: "get_api_event_by_event_id_attendees_by_event_attendee_id",
    method: "GET",
    path: "/api/Event/{eventId}/Attendees/{eventAttendeeId}",
    pathParameters: ["eventId", "eventAttendeeId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an Event Attendee",
  },
  {
    id: "post_api_event_by_event_id_attendees",
    method: "POST",
    path: "/api/Event/{eventId}/Attendees",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create an Event Attendee",
  },
  {
    id: "put_api_event_by_event_id_attendees_by_event_attendee_id",
    method: "PUT",
    path: "/api/Event/{eventId}/Attendees/{eventAttendeeId}",
    pathParameters: ["eventId", "eventAttendeeId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update an Event Attendee",
  },
  {
    id: "delete_api_event_by_event_id_attendees_by_event_attendee_id",
    method: "DELETE",
    path: "/api/Event/{eventId}/Attendees/{eventAttendeeId}",
    pathParameters: ["eventId", "eventAttendeeId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete an Event Attendee",
  },
  {
    id: "get_api_event_attendee_custom_fields",
    method: "GET",
    path: "/api/EventAttendee/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Event Attendee Custom Fields Available",
  },
  {
    id: "get_api_event_attendee_query_options",
    method: "GET",
    path: "/api/EventAttendee/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Event Attendee Query Options",
  },
  {
    id: "post_api_event_attendee_query",
    method: "POST",
    path: "/api/EventAttendee/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Event Attendees",
  },
  {
    id: "get_api_event_by_event_id_contacts",
    method: "GET",
    path: "/api/Event/{eventId}/Contacts",
    pathParameters: ["eventId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Event Contacts for an Event",
  },
  {
    id: "get_api_event_by_event_id_contacts_by_event_contact_id",
    method: "GET",
    path: "/api/Event/{eventId}/Contacts/{eventContactId}",
    pathParameters: ["eventId", "eventContactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an Event Contact",
  },
  {
    id: "post_api_event_by_event_id_contacts",
    method: "POST",
    path: "/api/Event/{eventId}/Contacts",
    pathParameters: ["eventId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create an Event Contact",
  },
  {
    id: "delete_api_event_by_event_id_contacts_by_event_contact_id",
    method: "DELETE",
    path: "/api/Event/{eventId}/Contacts/{eventContactId}",
    pathParameters: ["eventId", "eventContactId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete an Event Contact",
  },
  {
    id: "get_api_grant_by_contact_by_contact_id",
    method: "GET",
    path: "/api/Grant/ByContact/{contactId}",
    pathParameters: ["contactId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Grants for a Contact",
  },
  {
    id: "get_api_grant_by_grant_id",
    method: "GET",
    path: "/api/Grant/{grantId}",
    pathParameters: ["grantId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Grant",
  },
  {
    id: "get_api_grant_by_reference_by_reference_id",
    method: "GET",
    path: "/api/Grant/ByReference/{referenceId}",
    pathParameters: ["referenceId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Grant by Reference ID",
  },
  {
    id: "get_api_grant_by_grant_id_gifts",
    method: "GET",
    path: "/api/Grant/{grantId}/Gifts",
    pathParameters: ["grantId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get the Gifts applied to a Grant",
  },
  {
    id: "post_api_grant",
    method: "POST",
    path: "/api/Grant",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Grant",
  },
  {
    id: "put_api_grant_by_grant_id",
    method: "PUT",
    path: "/api/Grant/{grantId}",
    pathParameters: ["grantId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Grant",
  },
  {
    id: "delete_api_grant_by_grant_id",
    method: "DELETE",
    path: "/api/Grant/{grantId}",
    pathParameters: ["grantId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Grant",
  },
  {
    id: "get_api_grant_custom_fields",
    method: "GET",
    path: "/api/Grant/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Grant Custom Fields Available",
  },
  {
    id: "get_api_grant_query_options",
    method: "GET",
    path: "/api/Grant/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Grant Query Options",
  },
  {
    id: "post_api_grant_query",
    method: "POST",
    path: "/api/Grant/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Grants",
  },
  {
    id: "get_api_volunteer_opportunity",
    method: "GET",
    path: "/api/VolunteerOpportunity",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteer Opportunities",
  },
  {
    id: "get_api_volunteer_opportunity_by_volunteer_opportunity_id",
    method: "GET",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}",
    pathParameters: ["volunteerOpportunityId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteer Opportunity",
  },
  {
    id: "post_api_volunteer_opportunity",
    method: "POST",
    path: "/api/VolunteerOpportunity",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Volunteer Opportunity",
  },
  {
    id: "put_api_volunteer_opportunity_by_volunteer_opportunity_id",
    method: "PUT",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}",
    pathParameters: ["volunteerOpportunityId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Volunteer Opportunity",
  },
  {
    id: "delete_api_volunteer_opportunity_by_volunteer_opportunity_id",
    method: "DELETE",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}",
    pathParameters: ["volunteerOpportunityId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Volunteer Opportunity",
  },
  {
    id: "get_api_volunteer_opportunity_custom_fields",
    method: "GET",
    path: "/api/VolunteerOpportunity/CustomFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Custom Fields Available",
  },
  {
    id: "get_api_volunteer_opportunity_query_options",
    method: "GET",
    path: "/api/VolunteerOpportunity/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Query Options",
  },
  {
    id: "post_api_volunteer_opportunity_query",
    method: "POST",
    path: "/api/VolunteerOpportunity/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Queries Volunteer Opportunities",
  },
  {
    id: "get_api_volunteer_opportunity_by_volunteer_opportunity_id_volunteers",
    method: "GET",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Volunteers",
    pathParameters: ["volunteerOpportunityId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteers for a Volunteer Opportunity",
  },
  {
    id: "get_api_volunteer_opportunity_by_volunteer_opportunity_id_volunteers_by_volunteer_id",
    method: "GET",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Volunteers/{volunteerId}",
    pathParameters: ["volunteerOpportunityId", "volunteerId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteer",
  },
  {
    id: "get_api_volunteer_search",
    method: "GET",
    path: "/api/Volunteer/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Search for Volunteers",
  },
  {
    id: "post_api_volunteer_opportunity_by_volunteer_opportunity_id_volunteers",
    method: "POST",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Volunteers",
    pathParameters: ["volunteerOpportunityId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Volunteer",
  },
  {
    id: "delete_api_volunteer_opportunity_by_volunteer_opportunity_id_volunteers_by_volunteer_id",
    method: "DELETE",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Volunteers/{volunteerId}",
    pathParameters: ["volunteerOpportunityId", "volunteerId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Volunteer",
  },
  {
    id: "get_api_volunteer_query_options",
    method: "GET",
    path: "/api/Volunteer/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Query Options",
  },
  {
    id: "post_api_volunteer_query",
    method: "POST",
    path: "/api/Volunteer/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Volunteers",
  },
  {
    id: "get_api_volunteer_opportunity_by_volunteer_opportunity_id_volunteers_by_volunteer_id_attendance",
    method: "GET",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Volunteers/{volunteerId}/Attendance",
    pathParameters: ["volunteerOpportunityId", "volunteerId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteer Attendance for a Volunteer",
  },
  {
    id: "get_api_volunteer_opportunity_by_volunteer_opportunity_id_attendance_by_volunteer_attendance_id",
    method: "GET",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Attendance/{volunteerAttendanceId}",
    pathParameters: ["volunteerOpportunityId", "volunteerAttendanceId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteer Attendance",
  },
  {
    id: "post_api_volunteer_opportunity_by_volunteer_opportunity_id_volunteers_by_volunteer_id_attendance",
    method: "POST",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Volunteers/{volunteerId}/Attendance",
    pathParameters: ["volunteerOpportunityId", "volunteerId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Volunteer Attendance",
  },
  {
    id: "put_api_volunteer_opportunity_by_volunteer_opportunity_id_attendance_by_volunteer_attendance_id",
    method: "PUT",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Attendance/{volunteerAttendanceId}",
    pathParameters: ["volunteerOpportunityId", "volunteerAttendanceId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Volunteer Attendance",
  },
  {
    id: "delete_api_volunteer_opportunity_by_volunteer_opportunity_id_attendance_by_volunteer_attendance_id",
    method: "DELETE",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Attendance/{volunteerAttendanceId}",
    pathParameters: ["volunteerOpportunityId", "volunteerAttendanceId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Volunteer Attendance",
  },
  {
    id: "get_api_volunteer_opportunity_by_volunteer_opportunity_id_organizers",
    method: "GET",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Organizers",
    pathParameters: ["volunteerOpportunityId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteer Organizers",
  },
  {
    id: "get_api_volunteer_opportunity_by_volunteer_opportunity_id_organizers_by_volunteer_organizer_id",
    method: "GET",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Organizers/{volunteerOrganizerId}",
    pathParameters: ["volunteerOpportunityId", "volunteerOrganizerId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Volunteer Organizer",
  },
  {
    id: "post_api_volunteer_opportunity_by_volunteer_opportunity_id_organizers",
    method: "POST",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Organizers",
    pathParameters: ["volunteerOpportunityId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Volunteer Organizer",
  },
  {
    id: "delete_api_volunteer_opportunity_by_volunteer_opportunity_id_organizers_by_volunteer_organizer_id",
    method: "DELETE",
    path: "/api/VolunteerOpportunity/{volunteerOpportunityId}/Organizers/{volunteerOrganizerId}",
    pathParameters: ["volunteerOpportunityId", "volunteerOrganizerId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Volunteer Organizer",
  },
  {
    id: "post_api_email_search",
    method: "POST",
    path: "/api/Email/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Get Emails",
  },
  {
    id: "post_api_email_send",
    method: "POST",
    path: "/api/Email/Send",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Send an Email to a list of Contacts",
  },
  {
    id: "post_api_email_list_search",
    method: "POST",
    path: "/api/EmailList/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Search for an Email List",
  },
  {
    id: "post_api_email_list",
    method: "POST",
    path: "/api/EmailList",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Add Individuals to an Email List",
  },
  {
    id: "post_api_search",
    method: "POST",
    path: "/api/Search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Search for Contacts, Individuals or Entities",
  },
  {
    id: "post_api_task",
    method: "POST",
    path: "/api/Task",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Task",
  },
  {
    id: "get_api_task_types",
    method: "GET",
    path: "/api/Task/Types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Task Types",
  },
  {
    id: "post_api_task_query",
    method: "POST",
    path: "/api/Task/Query",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Query Tasks",
  },
  {
    id: "get_api_task_query_options",
    method: "GET",
    path: "/api/Task/QueryOptions",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Task Query Options",
  },
  {
    id: "get_api_webhook_by_webhook_id",
    method: "GET",
    path: "/api/Webhook/{webhookId}",
    pathParameters: ["webhookId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Webhook",
  },
  {
    id: "post_api_webhook",
    method: "POST",
    path: "/api/Webhook",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Webhook",
  },
  {
    id: "put_api_webhook_by_webhook_id",
    method: "PUT",
    path: "/api/Webhook/{webhookId}",
    pathParameters: ["webhookId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Webhook",
  },
  {
    id: "put_api_webhook_by_webhook_id_active",
    method: "PUT",
    path: "/api/Webhook/{webhookId}/Active",
    pathParameters: ["webhookId"],
    mutating: true,
    bodyAllowed: true,
    description: "Set the active state of a Webhook",
  },
  {
    id: "delete_api_webhook_by_webhook_id",
    method: "DELETE",
    path: "/api/Webhook/{webhookId}",
    pathParameters: ["webhookId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a Webhook",
  },
] as const satisfies readonly BoundedRestOperation[];

export const VIRTUOUS_CRM_READ_OPERATION_IDS = VIRTUOUS_CRM_OPERATIONS.filter(
  (item) => !item.mutating,
).map((item) => item.id);
export const VIRTUOUS_CRM_MANAGE_OPERATION_IDS = VIRTUOUS_CRM_OPERATIONS.filter(
  (item) => item.mutating,
).map((item) => item.id);

export const VIRTUOUS_CRM_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "virtuous-crm",
  name: "Virtuous CRM",
  baseUrl: "https://api.virtuoussoftware.com/",
  credentialName: "VIRTUOUS_CRM_API_KEY",
  authorization: { headerName: "Authorization", prefix: "Bearer " },
  operations: VIRTUOUS_CRM_OPERATIONS,
  health: { operationId: "get_api_organization_current" },
};
