// Generated from pCloud's official HTTP/JSON method documentation.
// Source corpus SHA-256: 55189b8eb15be62dc6f8884e47ff4c08af06b0a8561acba9fa74a220fff672a6
// Evidence date: 2026-07-14. Account credential, registration, newsletter, and OAuth broker methods are excluded.

export type PCloudOperation = {
  id: string;
  summary: string;
  category: string;
  parameters: readonly string[];
  requiresAuth: boolean;
  method: "GET" | "POST";
  responseMode: "json" | "binary";
  bodyMode: "form" | "multipart";
  group: "read" | "write";
};

export const PCLOUD_OPERATIONS = [
  {
    id: "acceptshare",
    summary:
      "Accept a share request. The request can be either identified by sharerequestid as reported by diff or by a code that comes from email. An optional name can be specified for the folder name, otherwise the share name will be used. Implementations are advised to ask for the local name with name pre-filled. Optionally the target folder to mount the share may be identified by folderid or path . If the folder is not specified, the user's default folder for accepting shares will be used, if no such fol",
    category: "sharing",
    parameters: [
      "always",
      "code",
      "folderid",
      "name",
      "path",
      "sharerequestid",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "cancelsharerequest",
    summary: "Cancels a share request sent by the current user.",
    category: "sharing",
    parameters: ["sharerequestid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "changepublink",
    summary: "Modify a specified public link",
    category: "public_links",
    parameters: [
      "deleteexpire",
      "deleteshortlink",
      "expire",
      "linkid",
      "linkpassword",
      "maxdownloads",
      "maxtraffic",
      "shortlink",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "changeshare",
    summary:
      "Change permissions of a share. The permissions are the same as in sharefolder Only the owner of the share/folder may use this method. That is - it is only allowed for outgoing shares.",
    category: "sharing",
    parameters: ["permissions", "shareid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "changeuploadlink",
    summary:
      "Modify upload link identified by uploadlinkid . Options that, could be changed include: Expiration date Space of the upload link Files of the upload link",
    category: "upload_links",
    parameters: [
      "deleteexpire",
      "expire",
      "maxfiles",
      "maxspace",
      "uploadlinkid",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "checksumfile",
    summary: "Calculate checksums of a given file",
    category: "file",
    parameters: ["fileid", "path"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "collection_create",
    summary:
      "Create a new collection for the current user. Optionally, files could be given for the collection to fill it.",
    category: "collection",
    parameters: ["fileids", "name", "type"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "collection_delete",
    summary:
      "Delete a given collection owned by the current user. System collections could not be deleted. In this case error 2065 (Collection not found.) will be raised.",
    category: "collection",
    parameters: ["collectionid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "collection_details",
    summary:
      "Get details for a given collection and the items in it. Optionally, paging could be used for the results in the collection. This method removes from the collection all items that could not be found at the time of invocation. Reasons are, for example, the files were moved to trash or there were in a shared folder, that now is not shared. For that reason, when paging is used, the page could have less results than the pagesize and more pages to be available.",
    category: "collection",
    parameters: ["collectionid", "page", "pagesize"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "collection_linkfiles",
    summary:
      "Appends files to the collection. The files will be added at the end of the collection. If you want to insert the files at another position, then link them via this method and then use collection_move . This method preserves the relative order given in the fileids field. Duplicates are not allowed to be met in the collections.",
    category: "collection",
    parameters: ["collectionid", "fileids", "noitems"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "collection_list",
    summary:
      "Get a list of the collections, that are owned from the current user. Optionally, the items in the collections could be returned and the collections could be filtered by type. The system collections of the current user are genereated on the first call of this method. This method removes from the collection all items that could not be found at the time of invocation. Reasons are, for example, the files were moved to trash or there were in a shared folder, that now is not shared.",
    category: "collection",
    parameters: ["pagesize", "showfiles", "type"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "collection_move",
    summary:
      "Changes the position of an item in a given colleciton, owned by the current user.",
    category: "collection",
    parameters: ["collectionid", "fileid", "item", "position"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "collection_rename",
    summary: "Renames a given collection owned by the current user.",
    category: "collection",
    parameters: ["collectionid", "name"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "collection_unlinkfiles",
    summary:
      "Remove files from a current collection. There are three methods to remove files from the collection: all items in the collections remove fileids from the collection remove items at given positions The priority is the method checks is position, then all , then fileids.",
    category: "collection",
    parameters: ["all", "collectionid", "fileids", "positions"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "copyfile",
    summary:
      "Takes one file and copies it as another file in the user's filesystem. Expects fileid or path to identify the source file and tofolderid + toname or topath to identify destination filename. If toname is ommited, original filename is used. The same is true if the last character of topath is '/' (slash), thus identifying only the target folder. The target file will be separate, newly created (with current creation time unless old file is overwritten) independent file. Any future operations on eith",
    category: "file",
    parameters: [
      "ctime",
      "fileid",
      "mtime",
      "noover",
      "path",
      "tofolderid",
      "toname",
      "topath",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "copyfolder",
    summary:
      "Copies a folder identified by folderid or path to either topath or tofolderid .",
    category: "folder",
    parameters: [
      "copycontentonly",
      "folderid",
      "noover",
      "path",
      "skipexisting",
      "tofolderid",
      "topath",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "copypubfile",
    summary:
      "Copies the file from the public link to the current user's filesystem Expects as parameter code that can be either 'code' or 'shortcode'. The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection If the link is to a folder also expects fileid . As with copyfile you can either specify topath or tofolderid (with optional toname ). Also the optional noover works as usual. Si",
    category: "public_links",
    parameters: [
      "code",
      "fileid",
      "noover",
      "path",
      "tofolderid",
      "toname",
      "topath",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "copytolink",
    summary: "Copy a file from the current user's filesystem to a upload link.",
    category: "upload_links",
    parameters: ["code", "fileid", "path"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "createfolder",
    summary:
      "Creates a folder. Expects either path string parameter (discouraged) or int folderid and string name parameters.",
    category: "folder",
    parameters: ["folderid", "name", "path"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "createfolderifnotexists",
    summary:
      "Creates a folder if the folder doesn't exist or returns the existing folder's metadata. Expects either path string parameter (discouraged) or int folderid and string name parameters.",
    category: "folder",
    parameters: ["folderid", "name", "path"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "createuploadlink",
    summary:
      "Creates upload link. Expects folderid / path of the folder where the uploaded files will be saved. The folder must be owned by the user. Share may be subject to confirmation from the other user. The folder to be shared is identified by folderid or path . Also SHOULD have a comment parameter that contains any comments/instructions the user is willing to provide to uploading users. Comments are the only information that uploading users will see (they will not know username of the owner nor the nam",
    category: "upload_links",
    parameters: [
      "comment",
      "expire",
      "folderid",
      "maxfiles",
      "maxspace",
      "path",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "currentserver",
    summary:
      "returns ip and hostname of the server you are currently connected to. The hostname is guaranteed to resolve only to the IP address(es) pointing to the same server. This call is useful when you need to track the upload progress.",
    category: "general",
    parameters: [],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "declineshare",
    summary:
      "Decline a share request. The request can be either identified by sharerequestid as reported by diff or by a code that comes from email. If the optional parameter block is set, all future share requests from the offering user will be automatically declined.",
    category: "sharing",
    parameters: ["block", "code", "sharerequestid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "deletefile",
    summary: "Delete a file identified by fileid or path .",
    category: "file",
    parameters: ["fileid", "path"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "deletefolder",
    summary:
      "Deletes a folder Expects either path string parameter (discouraged) or int folderid parameter. Note: Folders must be empty before calling deletefolder .",
    category: "folder",
    parameters: ["folderid", "path"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "deletefolderrecursive",
    summary:
      "Deletes a folder Expects either path string parameter (discouraged) or int folderid parameter. Note: This function deletes files, directories, and removes sharing. Use with extreme care.",
    category: "folder",
    parameters: ["folderid", "path"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "deletepublink",
    summary: "Delete a specified public link",
    category: "public_links",
    parameters: ["linkid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "deleteuploadlink",
    summary: "Deletes upload link identified by uploadlinkid .",
    category: "upload_links",
    parameters: ["uploadlinkid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "diff",
    summary:
      "List updates of the user's folders/files. Optionally, takes the parameter diffid , which if provided returns only changes since that diffid . Alternatively you can provide date/time in after parameter and you will only receive events generated after that time. Another alternative to providing diffid or after is providing last , which will return last number of events with highest diffids (that is the last events). Especially setting last to 0 is optimized to do nothing more than return the last ",
    category: "general",
    parameters: ["after", "block", "diffid", "last", "limit"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "downloadfile",
    summary:
      "Download a file/s Downloads one or more files from links suplied in the url parameter (links separated by any amount of whitespace) to the folder identified by either path or folderid (or to the root folder if both are omitted). The parameter string progresshash can be passed. The same should be passed to uploadprogress method. When monitoring progress with uploadprogress the following fields will be present: Field Description urlcount int number of URLs requested urlready int number of URLs alr",
    category: "file",
    parameters: ["folderid", "path", "target", "url"],
    requiresAuth: true,
    method: "POST",
    responseMode: "binary",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "downloadfileasync",
    summary:
      "Download a file/s Downloads one or more files from links suplied in the url parameter (links separated by any amount of whitespace) to the folder identified by either path or folderid (or to the root folder if both are omitted). The response will be recieved when the files are queued for download, not when they are downloaded. The parameter string progresshash can be passed. The same should be passed to uploadprogress method. When monitoring progress with uploadprogress the following fields will",
    category: "file",
    parameters: ["folderid", "path", "target", "url"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "extractarchive",
    summary:
      "Extracts archive file from the user's filesystem. Expects as paramters usual fileid or path of an archive file and tofolderid or topath for destination folder. If the archive is password protected, password parameter should be provided, otherwise error number 7009 will be returned. Implementations should expect this error code and if encountered prompt user for password and retry the extraction process. This method runs the extraction process for around 2 seconds. In case it manages to finish in",
    category: "archiving",
    parameters: ["nooutput", "overwrite", "password"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "extractarchiveprogress",
    summary:
      "Returns output and completion status of an archive extraction process. Expects as paramters progresshash as returned by extractarchive and optionally lines . The boolean value finished indicates if the process is finished or not. In output array lines of output of the extraction program are returned. The number in lines can be passed back to this method and will exclude already returned lines of output.",
    category: "archiving",
    parameters: ["lines"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "feedback",
    summary: "sends message to pCloud support",
    category: "general",
    parameters: ["mail", "message", "name", "reason"],
    requiresAuth: false,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "getapiserver",
    summary:
      "This method returns closest API server to the requesting client. The biggest speed gain will be with upload methods. Clients should have fallback logic. If request to API server different from api.pcloud.com fails (network error) the client should fallback to using api.pcloud.com.",
    category: "general",
    parameters: [],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getaudiolink",
    summary:
      "Get a streaming link for audio file Takes fileid (or path ) of an audio (or video) file and provides links from which audio can be streamed in mp3 format. (Same way getfilelink does with hosts and path ) Optional parameters are abitrate , forcedownload and contenttype . The default bitrate is 192kbit. It can also be used to extract the audio track from a video. The link itself supports the start GET parameter. This method can be used to play FLAC and other new formats on devices that only suppor",
    category: "streaming",
    parameters: ["abitrate", "contenttype", "fileid", "forcedownload", "path"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getcollectionpublink",
    summary:
      "Generates a public link to a collection, owned by the current user. This method has the same optional parameters as getfilepublink . Note: Public links pointing to a collection have the advantage that are real time image of the collection, while tree links are snapshots.",
    category: "public_links",
    parameters: [
      "collectionid",
      "expire",
      "maxdownloads",
      "maxtraffic",
      "shortlink",
    ],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getfilehistory",
    summary:
      "returns event history of a file identified by fileid . File might be a deleted one. The output format is the same as of diff method.",
    category: "general",
    parameters: ["fileid"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getfilelink",
    summary:
      "Get a download link for file Takes fileid (or path ) as parameter and provides links from which the file can be downloaded. If the optional parameter forcedownload is set, the file will be served by the content server with content type application/octet-stream , which typically forces user agents to save the file. Alternatively you can provide parameter contenttype with the Content-Type you wish the content server to send. If these parameters are not set, the content type will depend on the exte",
    category: "streaming",
    parameters: [
      "contenttype",
      "fileid",
      "forcedownload",
      "maxspeed",
      "path",
      "skipfilename",
    ],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getfilepublink",
    summary:
      "Creates and return a public link to a file. The file is identified by fileid or path .",
    category: "public_links",
    parameters: [
      "expire",
      "fileid",
      "linkpassword",
      "maxdownloads",
      "maxtraffic",
      "path",
      "shortlink",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "getfolderpublink",
    summary:
      "Creates and returns a public link to a folder. The folder is identified by folderid or path . Same optional parameters as getfilepublink . maxdownloads in this case limits total number of downloads from this folder (even for the same file).",
    category: "public_links",
    parameters: [
      "expire",
      "folderid",
      "linkpassword",
      "maxdownloads",
      "maxtraffic",
      "path",
      "shortlink",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "gethlslink",
    summary:
      "Get a m3u8 playlist for live streaming for video file Takes fileid (or path ) of a video file and provides links (in the same way getfilelink does with hosts and path ) from which a m3u8 playlist for HTTP Live Streaming can be downloaded. Optional parameters are abitrate , vbitrate , resolution and skipfilename . These have the same meaning as in getvideolink . The defaults are the same as for getvideolink .",
    category: "streaming",
    parameters: [
      "abitrate",
      "fileid",
      "path",
      "resolution",
      "skipfilename",
      "vbitrate",
    ],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getip",
    summary:
      "Get the IP address of the remote device from which the user connects to the API.",
    category: "general",
    parameters: [],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubaudiolink",
    summary:
      "Create a link to a audio file of a public link file. The link could be used for streaming. Same as getaudiolink , but works on public file identified by code (and fileid if link is to a folder) The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: ["abitrate", "code", "contenttype", "fileid", "forcedownload"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpublinkdownload",
    summary:
      "Returns link(s) where the file can be downloaded Expects as parameter code that can be either 'code' or 'shortcode'. The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection If the link is to a folder also expects fileid . Optional parameters forcedownload contenttype skipfilename maxspeed work exaclty as explained in getfilelink . This call is intentionally split from s",
    category: "public_links",
    parameters: [
      "code",
      "contenttype",
      "fileid",
      "forcedownload",
      "maxspeed",
      "skipfilename",
    ],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubtextfile",
    summary:
      "Download a file in different character encoding The file is streamed as response to this method by the content server. Same as gettextfile , but works on public file identified by code (and fileid if link is to a folder) The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: [
      "code",
      "contenttype",
      "fileid",
      "forcedownload",
      "fromencoding",
      "toencoding",
    ],
    requiresAuth: false,
    method: "GET",
    responseMode: "binary",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubthumb",
    summary:
      "Get a thumbnail of a public file Same as getthumb , but works on public file identified by code (and fileid if link is to a folder) The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: ["crop", "type"],
    requiresAuth: false,
    method: "GET",
    responseMode: "binary",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubthumblink",
    summary:
      "Get a link to a thumbnatil of a public file Same as getthumblink , but works on public file identified by code (and fileid if link is to a folder) The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: ["code", "crop", "fileid", "size", "type"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubthumbslinks",
    summary:
      "Get a link to a thumbnatil of a public file Same as getthumbslinks , but works on public file identified by code (and fileid if link is to a folder) The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: ["code", "crop", "fileid", "size", "type"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubvideolinks",
    summary:
      "Returns variants array of different quality/resolution versions of a video in a public link. Same as getvideolinks , but works on public file identified by code (and fileid if link is to a folder). The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: [
      "code",
      "contenttype",
      "fileid",
      "forcedownload",
      "maxspeed",
      "skipfilename",
    ],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubzip",
    summary:
      "Create a zip archive file of a public link file and download it Same as getzip , but works on public file identified by code (and fileid if link is to a folder) Takes code and optional parameters to define a tree and streams a zip file. The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection filename , forcedownload and timeoffset optional parameters work the same way a",
    category: "public_links",
    parameters: ["code", "filename", "forcedownload", "timeoffset"],
    requiresAuth: false,
    method: "GET",
    responseMode: "binary",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getpubziplink",
    summary:
      "Create a link to a zip archive file of a public link file Same as getziplink , but works on public file identified by code getpubziplink is slower and less efficient than getpubzip and takes time to generate the zip file as opposed to the former which starts the download right away. Takes code and optional parameters to define a tree and streams a zip file. The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree ",
    category: "public_links",
    parameters: ["code", "filename", "forcedownload", "timeoffset"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "gettextfile",
    summary:
      "Download a file in different character encoding Takes fileid (or path ) as parameter and returns contents of the file in different character encoding. The file is streamed as response to this method by the content server. Optional parameter fromencoding specify the original character encoding of the file. If ommited it will be guessed based on the contents of the file. Optional parameter toencoding specify the requested character encoding for the output. The default is utf-8 . If the optional pa",
    category: "streaming",
    parameters: [
      "contenttype",
      "fileid",
      "forcedownload",
      "fromencoding",
      "path",
      "toencoding",
    ],
    requiresAuth: true,
    method: "GET",
    responseMode: "binary",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getthumb",
    summary:
      "Get a thumbnail of a file Takes the same parameters as getthumblink , but returns the thumbnail over the current API connection. Getting thumbnails from API servers is generally NOT faster than getting them from storage servers. It makes sense only if you are reusing the (possibly expensive to open SSL) API connection.",
    category: "thumbnails",
    parameters: ["crop", "fileid", "path", "size", "type"],
    requiresAuth: true,
    method: "GET",
    responseMode: "binary",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getthumblink",
    summary:
      "Get a link to a thumbnail of a file Takes fileid (or path ) as parameter and provides links from which a thumbnail of the file can be downloaded. Thumbnails can be created only from files whose metadata has thumb value set to true . The parameter size MUST be provided, in the format WIDTHxHEIGHT. The width MUST be between 16 and 2048, and divisible by either 4 or 5. The height MUST be between 16 and 1024, and divisible by either 4 or 5. By default the thumb will have the same aspect ratio as the",
    category: "thumbnails",
    parameters: ["crop", "fileid", "path", "size", "type"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getthumbslinks",
    summary:
      "Get a link to thumbnails of a list of files Takes in fileids parameter coma-separated list of fileids and returns thumbs for all the files. size , type and crop work like in getthumblink and are all the same for all files. If you need to generate multiple thumbnails getthumbslinks is preferable than multiple calls to getthumblink (even if pipelined) getthumbslinks connects to multiple storage serves simultaneously to generate thumbs and in most cases it is just slightly slower than a single call",
    category: "thumbnails",
    parameters: ["crop", "fileids", "size", "type"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "gettreepublink",
    summary:
      "Creates and returns a public link to a virtual folder that is defined by requested tree. Tree is identified by the following parameters: Parameter Description fileids comma-separated fileids folderids comma-separated folderids folderid: just one folderid - the contents of the folder will be dumped into the virtual folder instead of the folder itself Also requires parameter name that will be the name of the virtual folder. Same optional parameters as getfilepublink . The created link will have si",
    category: "public_links",
    parameters: [
      "expire",
      "folderid",
      "linkpassword",
      "maxdownloads",
      "maxtraffic",
      "path",
      "shortlink",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "getvideolink",
    summary:
      "Get a streaming link for video file Takes fileid (or path ) of a video file and provides links (same way getfilelink does with hosts and path ) from which the video can be streamed with lower bitrate (and/or resolution). The transcoded video will be in a FLV container with x264 video and mp3 audio, by default the video bitrate will be adapted to the connection speed in real time. By default the content servers will send appropriate content-type for FLV files, this can be overridden with either f",
    category: "streaming",
    parameters: [
      "abitrate",
      "contenttype",
      "fileid",
      "fixedbitrate",
      "forcedownload",
      "maxspeed",
      "path",
      "resolution",
      "skipfilename",
      "vbitrate",
    ],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getvideolinks",
    summary:
      "Returns variants array of different quality/resolution versions of a video, identified by fileid (or path ). Each variant of the vide will have path and hosts (as with getfilelink ), width and height of the video, duration of the video in seconds (floating point number sent as string), fps - frames per second rate of the video, videobitrate and audiobitrate will specify the bitrate of the video and audio, encoded by respectively videocodec and audiocodec . For the original video variant isorigin",
    category: "streaming",
    parameters: [
      "contenttype",
      "fileid",
      "forcedownload",
      "maxspeed",
      "path",
      "skipfilename",
    ],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getzip",
    summary:
      "Receive a zip file from the user's filesystem. Expects as parameter a defined tree .",
    category: "archiving",
    parameters: ["filename", "forcedownload", "timeoffset"],
    requiresAuth: true,
    method: "GET",
    responseMode: "binary",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "getziplink",
    summary:
      "Receive a zip file link for files in the user's filesystem. Recognizes the same parameters as getzip . Expects as parameter a defined tree . Unlike getzip, returns a download link(s) the same way getfilelink does - returns path, hosts and expire. Note : This call is less efficient than getzip as the zip archive is created on our servers and only then you get a download link. So as fast as our servers are, it may take time to create a large archive. The parameter maxspeed may be used if you wish ",
    category: "archiving",
    parameters: ["filename", "forcedownload", "maxspeed", "timeoffset"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "listfolder",
    summary:
      "Receive data for a folder. Expects folderid or path parameter, returns folder's metadata . The metadata will have contents field that is array of metadatas of folder's contents. Recursively listing the root folder is not an expensive operation.",
    category: "folder",
    parameters: [
      "folderid",
      "nofiles",
      "noshares",
      "path",
      "recursive",
      "showdeleted",
    ],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "listplshort",
    summary:
      "Return a list of current user's public links listpublinks There is no metadata for each link, instead each link has isfolder field and fileid or folderid field. Takes no parameters",
    category: "public_links",
    parameters: [],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "listpublinks",
    summary: "Return a list of current user's public links Takes no parameters",
    category: "public_links",
    parameters: [],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "listrevisions",
    summary: "Lists revisions for a given fileid / path",
    category: "revisions",
    parameters: ["fileid", "path"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "listshares",
    summary: "List current shares and share requests.",
    category: "sharing",
    parameters: ["noincoming", "nooutgoing", "norequests", "noshares"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "listuploadlinks",
    summary: "Lists all upload links in uploadlinks.",
    category: "upload_links",
    parameters: [],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "removeshare",
    summary:
      "Remove an active share. This can be both incoming or outgoing share.",
    category: "sharing",
    parameters: ["shareid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "renamefile",
    summary:
      "Rename a file Renames (and/or moves) a file identified by fileid or path to either topath (if topath is a foldername without new filename it MUST end with slash - /newpath/ ) or tofolderid / toname (one or both can be provided). If the destination file already exists it will be replaced atomically with the source file, in this case the metadata will include deletedfileid with the fileid of the old file at the destination, and the source and destination files revisions will be merged together.",
    category: "file",
    parameters: ["fileid", "path", "tofolderid", "toname", "topath"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "renamefolder",
    summary:
      "Renames (and/or moves) a folder identified by folderid or path to either topath (if topath is a existing folder to place source folder without new name for the folder it MUST end with slash - /newpath/ ) or tofolderid / toname (one or both can be provided).",
    category: "folder",
    parameters: [],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "revertrevision",
    summary:
      "Takes fileid / path and revisionid as parameters and reverts the file to a given revision. Current file contents are saved as new revision.",
    category: "revisions",
    parameters: ["fileid", "path", "revisionid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "savepubthumb",
    summary:
      "Create a thumbnail of a public link file and save it in the current user's filesystem Same as savethumb , but works on public file identified by code (and fileid if link is to a folder) The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: [
      "code",
      "crop",
      "fileid",
      "noover",
      "size",
      "tofolderid",
      "toname",
      "topath",
      "type",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "savepubzip",
    summary:
      "Create a zip archive file of a public link file in the current user filesystem Same as savezip , but works on public file identified by code Takes code and optional parameters to define a tree and streams a zip file. The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: ["code", "timeoffset", "tofolderid", "toname", "topath"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "savethumb",
    summary:
      "Create a thumbnail of a file and save it in the current user's filesystem takes the same parameters as getthumblink in addition to topath or tofolderid + toname and save the generated thumbnail as a file. As usual by default this call overwrites existing files (saving the old one as revision) unless the noover parameter is set. In that case 'File or folder alredy exists.' error will be generated. If toname is not provided, but tofolderid is, the file's original name is used for the thumbnail. Si",
    category: "thumbnails",
    parameters: [
      "crop",
      "fileid",
      "noover",
      "path",
      "size",
      "tofolderid",
      "toname",
      "topath",
      "type",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "savezip",
    summary:
      "Create a zip file in the user's filesystem. Recognizes the same parameters as getzip without forcedownload and filename . Expects as parameter a defined tree . Additionally expects the usual topath or tofolderid + toname .",
    category: "archiving",
    parameters: [
      "progresshash",
      "timeoffset",
      "tofolderid",
      "toname",
      "topath",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "savezipprogress",
    summary:
      "Get the progress in process of zipping file in the user's filesystem. The process is started with the method savezip . On every zipped file the progress is updated. The process could be marked as ready, once when files equals totalfiles in the result. Expects as parameter progresshash - key passed to savezip with the intention to observe the progress. Please, use different progresshash for every call of savezip .",
    category: "archiving",
    parameters: ["progresshash"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "setlanguage",
    summary: "sets user's language to language .",
    category: "general",
    parameters: ["language"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "sharefolder",
    summary:
      "Shares a folder with another user. Share may be subject to confirmation from the other user. The folder to be shared is identified by folderid or path . Optional share name can be provided, if it is not, the folder name is used as sharename. Implementations are advised to give opportunity to the sharing user to select the share name , which should be pre-filled with the folder name. The required parameter mail holds the email address of the user with whom you are sharing the folder. The required",
    category: "sharing",
    parameters: ["folderid", "mail", "message", "name", "path", "permissions"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "sharerequestinfo",
    summary:
      "Get information about a share request from the code that was sent to the user's email.",
    category: "sharing",
    parameters: ["code"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "showpublink",
    summary:
      "Expects as parameter code that can be either 'code' or 'shortcode'. The code could be obtained from: getfilepublink - link to a single file getfolderpublink - link to a folder gettreepublink - link to a tree getcollectionpublink - link to a collection",
    category: "public_links",
    parameters: ["code"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "showuploadlink",
    summary:
      "Expects upload link code and returns back the link's comment and mail . If the link is deleted or expired, returns proper 7xxx error, which should be expected by the implementations. Modify upload link identified by uploadlinkid . Options that, could be changed include: Expiration date Space of the upload link Files of the upload link",
    category: "upload_links",
    parameters: [
      "deleteexpire",
      "expire",
      "maxfiles",
      "maxspace",
      "uploadlinkid",
    ],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "stat",
    summary:
      "The stat API method returns information about the file pointed to by fileid or path . It's is recomended to use fileid .",
    category: "file",
    parameters: ["fileid", "path"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "supportedlanguages",
    summary:
      "lists supported languages in the returned languages hash, where keys are language codes and values are languages names",
    category: "general",
    parameters: [],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "trash_clear",
    summary:
      "Deletes permanently files or folders from the Trash . Files and folders deleted via this method cannot be restored. If folderid='0' , then all data from the Trash will be removed.",
    category: "trash",
    parameters: ["fileid", "folderid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "trash_list",
    summary:
      "Lists the contents of a folder in the Trash . The root folder of the Trash has id='0' . Outputs the metadata of the folder. This metadata will have contents field that is array of metadatas of folder's contents. Note that the metadata from this function has the additional field origparentfolderid in the metadata. This is the folder, in which the file or folder was, before it was moved to Trash . So the field parentfolderid is showing the position in the Trash . Only files and folders that belong",
    category: "trash",
    parameters: ["folderid", "nofiles", "recursive"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "trash_restore",
    summary:
      "Restores files or folders from the Trash back to the filesystem. The destination, where the data will be restored can be automatically calculated via trash_restorepath or it could be specified by the user (use restoreto parameter). If folderid='0' , then all data in the Trash will be restored, as close to their original positions, as possible. If restoreto is set, then all data in the Trash will be placed into this folder. If the destination is a shared folder, then a user to which the folder wa",
    category: "trash",
    parameters: ["fileid", "folderid", "metadata", "restoreto"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "trash_restorepath",
    summary:
      "For a desired file or folder from the Trash , calculates where to restore. This method is granted that will choose such the destination folder, that ismine is true . If the parent folder is also deleted, then this method will calculate the path by going to the parent of the folder. That way the file or folder will be restored at most at the root of the file system. Also, if there are some name conflicts, then a new name will be generated, that is Name (k) , if there are k-1 files with the same n",
    category: "trash",
    parameters: ["fileid", "folderid"],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "form",
    group: "write",
  },
  {
    id: "uploadfile",
    summary:
      "Upload a file. String path or int folderid specify the target directory. If both are omitted the root folder is selected. Parameter string progresshash can be passed. Same should be passed to uploadprogress method. If nopartial is set, partially uploaded files will not be saved (that is when the connection breaks before file is read in full). If renameifexists is set, on name conflict, files will not be overwritten but renamed to name like filename (2).ext . Multiple files can be uploaded, using",
    category: "file",
    parameters: [
      "ctime",
      "filename",
      "folderid",
      "mtime",
      "nopartial",
      "path",
      "progresshash",
      "renameifexists",
    ],
    requiresAuth: true,
    method: "POST",
    responseMode: "json",
    bodyMode: "multipart",
    group: "write",
  },
  {
    id: "uploadlinkprogress",
    summary: "Monitor the progress of uploaded files.",
    category: "upload_links",
    parameters: ["code", "progresshash"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "uploadprogress",
    summary:
      "Get upload progress of a file. MUST be sent to the same api server that you are currently uploading to. The parameter string progresshash MUST be passed and must contain the same value that was passed in the upload request that is currently in progress.",
    category: "file",
    parameters: ["progresshash"],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "uploadtolink",
    summary:
      "Upload file(s) to a upload link. Expects code . Most things that apply to uploadfile also apply here, especially progresshash can be used in the same manner to monitor upload progress with uploadlinkprogress . There is a slight difference that renameifexists is omitted and the uploaded file is always renamed when a file with the requested name exists in the upload link.",
    category: "upload_links",
    parameters: ["code", "nopartial", "progresshash"],
    requiresAuth: false,
    method: "POST",
    responseMode: "json",
    bodyMode: "multipart",
    group: "write",
  },
  {
    id: "uploadtransfer",
    summary:
      "Does a file(s) transfer in way that creates and sends transfer links to receiver emails.",
    category: "transfer",
    parameters: ["message", "progresshash", "receivermails", "sendermail"],
    requiresAuth: false,
    method: "POST",
    responseMode: "json",
    bodyMode: "multipart",
    group: "write",
  },
  {
    id: "uploadtransferprogress",
    summary: "Monitor the progress of transfered files.",
    category: "transfer",
    parameters: ["progresshash"],
    requiresAuth: false,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
  {
    id: "userinfo",
    summary:
      "returns information about the current user. As there is no specific login method as credentials can be passed to any method, this is an especially good place for logging in with no particular action in mind.",
    category: "general",
    parameters: [],
    requiresAuth: true,
    method: "GET",
    responseMode: "json",
    bodyMode: "form",
    group: "read",
  },
] as const satisfies readonly PCloudOperation[];

export const PCLOUD_OPERATION_BY_ID = new Map(
  PCLOUD_OPERATIONS.map((operation) => [operation.id, operation]),
);
export const PCLOUD_READ_OPERATION_IDS = PCLOUD_OPERATIONS.filter(
  (operation) => operation.group === "read",
).map((operation) => operation.id);
export const PCLOUD_WRITE_OPERATION_IDS = PCLOUD_OPERATIONS.filter(
  (operation) => operation.group === "write",
).map((operation) => operation.id);
