import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Generated from Fundraise Up official OpenAPI v1.0.0 on 2026-07-17. */
export const FUNDRAISE_UP_OPERATIONS = [
  {
    id: "get_campaigns",
    method: "GET",
    path: "/campaigns",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get campaigns",
  },
  {
    id: "get_campaigns_by_id",
    method: "GET",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a campaign",
  },
  {
    id: "post_campaigns_by_id_designations_assign",
    method: "POST",
    path: "/campaigns/{id}/designations/assign",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Assign designations to a campaign",
  },
  {
    id: "post_campaigns_by_id_designations_unassign",
    method: "POST",
    path: "/campaigns/{id}/designations/unassign",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Unassign designations from a campaign",
  },
  {
    id: "get_designation_configurations",
    method: "GET",
    path: "/designation_configurations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get designation configurations",
  },
  {
    id: "get_designation_configurations_by_id",
    method: "GET",
    path: "/designation_configurations/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a designation configuration",
  },
  {
    id: "get_designations",
    method: "GET",
    path: "/designations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get designations",
  },
  {
    id: "post_designations",
    method: "POST",
    path: "/designations",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a designation",
  },
  {
    id: "get_designations_by_id",
    method: "GET",
    path: "/designations/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a designation",
  },
  {
    id: "post_designations_by_id",
    method: "POST",
    path: "/designations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a designation",
  },
  {
    id: "delete_designations_by_id",
    method: "DELETE",
    path: "/designations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a designation",
  },
  {
    id: "post_designations_batch_create",
    method: "POST",
    path: "/designations/batch/create",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create multiple designations",
  },
  {
    id: "post_designations_batch_update",
    method: "POST",
    path: "/designations/batch/update",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Update multiple designations",
  },
  {
    id: "post_designations_batch_delete",
    method: "POST",
    path: "/designations/batch/delete",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Delete multiple designations",
  },
  {
    id: "get_designation_groups",
    method: "GET",
    path: "/designation_groups",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get designation groups",
  },
  {
    id: "get_designation_groups_by_id",
    method: "GET",
    path: "/designation_groups/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a designation group",
  },
  {
    id: "post_designation_groups_by_id_designations_assign",
    method: "POST",
    path: "/designation_groups/{id}/designations/assign",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Assign designations to a designation group",
  },
  {
    id: "post_designation_groups_by_id_designations_unassign",
    method: "POST",
    path: "/designation_groups/{id}/designations/unassign",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Unassign designations from a designation group",
  },
  {
    id: "get_donations",
    method: "GET",
    path: "/donations",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get donations",
  },
  {
    id: "post_donations",
    method: "POST",
    path: "/donations",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a donation",
  },
  {
    id: "get_donations_by_id",
    method: "GET",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a donation",
  },
  {
    id: "post_donations_by_id",
    method: "POST",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a donation and its associated recurring plan",
  },
  {
    id: "get_donations_fee",
    method: "GET",
    path: "/donations/fee",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get donation fee",
  },
  {
    id: "get_events",
    method: "GET",
    path: "/events",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get events",
  },
  {
    id: "get_fundraisers",
    method: "GET",
    path: "/fundraisers",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get Fundraisers",
  },
  {
    id: "post_fundraisers",
    method: "POST",
    path: "/fundraisers",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Fundraiser",
  },
  {
    id: "get_fundraisers_by_id",
    method: "GET",
    path: "/fundraisers/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Fundraiser",
  },
  {
    id: "post_fundraisers_by_id",
    method: "POST",
    path: "/fundraisers/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a Fundraiser",
  },
  {
    id: "get_recurring_plans",
    method: "GET",
    path: "/recurring_plans",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get recurring plans",
  },
  {
    id: "get_recurring_plans_by_id",
    method: "GET",
    path: "/recurring_plans/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a recurring plan",
  },
  {
    id: "get_supporters",
    method: "GET",
    path: "/supporters",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get supporters",
  },
  {
    id: "get_supporters_by_id",
    method: "GET",
    path: "/supporters/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a supporter",
  },
  {
    id: "post_donor_portal_access_links_supporters_by_id",
    method: "POST",
    path: "/donor_portal/access_links/supporters/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Donor Portal access link for a supporter",
  },
  {
    id: "post_donor_portal_access_links_recurring_plans_by_id",
    method: "POST",
    path: "/donor_portal/access_links/recurring_plans/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a Donor Portal access link for a recurring plan",
  },
  {
    id: "post_upgrade_links_donations_by_id",
    method: "POST",
    path: "/upgrade_links/donations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Create an upgrade link for a one-time donation",
  },
] as const satisfies readonly BoundedRestOperation[];

export const FUNDRAISE_UP_READ_OPERATION_IDS = FUNDRAISE_UP_OPERATIONS.filter(
  (item) => !item.mutating,
).map((item) => item.id);
export const FUNDRAISE_UP_MANAGE_OPERATION_IDS = FUNDRAISE_UP_OPERATIONS.filter(
  (item) => item.mutating,
).map((item) => item.id);

export const FUNDRAISE_UP_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "fundraise-up",
  name: "Fundraise Up",
  baseUrl: "https://api.fundraiseup.com/v1/",
  credentialName: "FUNDRAISE_UP_API_KEY",
  authorization: { headerName: "Authorization", prefix: "Bearer " },
  operations: FUNDRAISE_UP_OPERATIONS,
  health: {
    operationId: "get_campaigns",
    input: { query: { livemode: false, limit: 1 } },
  },
};
