/** Generated from NationBuilder's official released V2 OpenAPI reference on 2026-07-18. */
import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

const NATIONBUILDER_ROUTES = [
  ["GET", "/api/v2/async_processes/{id}"],
  ["GET", "/api/v2/automation_enrollments"],
  ["POST", "/api/v2/automation_enrollments"],
  ["GET", "/api/v2/automation_enrollments/{id}"],
  ["DELETE", "/api/v2/automation_enrollments/{id}"],
  ["GET", "/api/v2/automations"],
  ["POST", "/api/v2/automations"],
  ["GET", "/api/v2/automations/{id}"],
  ["PATCH", "/api/v2/automations/{id}"],
  ["PATCH", "/api/v2/automations/{id}/archive"],
  ["GET", "/api/v2/ballots"],
  ["POST", "/api/v2/ballots"],
  ["GET", "/api/v2/ballots/{id}"],
  ["DELETE", "/api/v2/ballots/{id}"],
  ["PATCH", "/api/v2/ballots/{id}"],
  ["GET", "/api/v2/broadcasters"],
  ["GET", "/api/v2/broadcasters/{id}"],
  ["GET", "/api/v2/contacts"],
  ["POST", "/api/v2/contacts"],
  ["GET", "/api/v2/contacts/{id}"],
  ["DELETE", "/api/v2/contacts/{id}"],
  ["PATCH", "/api/v2/contacts/{id}"],
  ["GET", "/api/v2/custom_fields"],
  ["GET", "/api/v2/custom_fields/{id}"],
  ["GET", "/api/v2/donation_tracking_codes"],
  ["POST", "/api/v2/donation_tracking_codes"],
  ["GET", "/api/v2/donation_tracking_codes/{id}"],
  ["DELETE", "/api/v2/donation_tracking_codes/{id}"],
  ["PATCH", "/api/v2/donation_tracking_codes/{id}"],
  ["GET", "/api/v2/donations"],
  ["POST", "/api/v2/donations"],
  ["GET", "/api/v2/donations/{id}"],
  ["DELETE", "/api/v2/donations/{id}"],
  ["PATCH", "/api/v2/donations/{id}"],
  ["GET", "/api/v2/elections"],
  ["POST", "/api/v2/elections"],
  ["GET", "/api/v2/elections/{id}"],
  ["DELETE", "/api/v2/elections/{id}"],
  ["PATCH", "/api/v2/elections/{id}"],
  ["GET", "/api/v2/event_rsvps"],
  ["POST", "/api/v2/event_rsvps"],
  ["GET", "/api/v2/event_rsvps/{id}"],
  ["DELETE", "/api/v2/event_rsvps/{id}"],
  ["PATCH", "/api/v2/event_rsvps/{id}"],
  ["GET", "/api/v2/event_ticket_levels"],
  ["POST", "/api/v2/event_ticket_levels"],
  ["GET", "/api/v2/event_ticket_levels/{id}"],
  ["DELETE", "/api/v2/event_ticket_levels/{id}"],
  ["PATCH", "/api/v2/event_ticket_levels/{id}"],
  ["GET", "/api/v2/events"],
  ["POST", "/api/v2/events"],
  ["GET", "/api/v2/events/{id}"],
  ["DELETE", "/api/v2/events/{id}"],
  ["PATCH", "/api/v2/events/{id}"],
  ["GET", "/api/v2/imports"],
  ["GET", "/api/v2/imports/{id}"],
  ["GET", "/api/v2/lists"],
  ["POST", "/api/v2/lists"],
  ["GET", "/api/v2/lists/{id}"],
  ["DELETE", "/api/v2/lists/{id}"],
  ["PATCH", "/api/v2/lists/{id}"],
  ["PATCH", "/api/v2/lists/{id}/add_signups"],
  ["PATCH", "/api/v2/lists/{id}/remove_signups"],
  ["GET", "/api/v2/lists/{id}/signups"],
  ["PATCH", "/api/v2/lists/{id}/tag"],
  ["PATCH", "/api/v2/lists/{id}/untag"],
  ["GET", "/api/v2/mailings"],
  ["GET", "/api/v2/mailings/{id}"],
  ["GET", "/api/v2/membership_types"],
  ["POST", "/api/v2/membership_types"],
  ["GET", "/api/v2/membership_types/{id}"],
  ["DELETE", "/api/v2/membership_types/{id}"],
  ["PATCH", "/api/v2/membership_types/{id}"],
  ["GET", "/api/v2/memberships"],
  ["POST", "/api/v2/memberships"],
  ["GET", "/api/v2/memberships/{id}"],
  ["DELETE", "/api/v2/memberships/{id}"],
  ["PATCH", "/api/v2/memberships/{id}"],
  ["GET", "/api/v2/pages"],
  ["POST", "/api/v2/pages"],
  ["GET", "/api/v2/pages/{id}"],
  ["DELETE", "/api/v2/pages/{id}"],
  ["PATCH", "/api/v2/pages/{id}"],
  ["GET", "/api/v2/path_histories"],
  ["GET", "/api/v2/path_histories/{id}"],
  ["GET", "/api/v2/path_journey_status_changes"],
  ["POST", "/api/v2/path_journey_status_changes"],
  ["GET", "/api/v2/path_journey_status_changes/{id}"],
  ["DELETE", "/api/v2/path_journey_status_changes/{id}"],
  ["PATCH", "/api/v2/path_journey_status_changes/{id}"],
  ["GET", "/api/v2/path_journeys"],
  ["POST", "/api/v2/path_journeys"],
  ["GET", "/api/v2/path_journeys/{id}"],
  ["PATCH", "/api/v2/path_journeys/{id}"],
  ["PATCH", "/api/v2/path_journeys/{id}/abandon"],
  ["PATCH", "/api/v2/path_journeys/{id}/complete"],
  ["PATCH", "/api/v2/path_journeys/{id}/reactivate"],
  ["PATCH", "/api/v2/path_journeys/{id}/void"],
  ["GET", "/api/v2/path_steps"],
  ["POST", "/api/v2/path_steps"],
  ["GET", "/api/v2/path_steps/{id}"],
  ["DELETE", "/api/v2/path_steps/{id}"],
  ["PATCH", "/api/v2/path_steps/{id}"],
  ["GET", "/api/v2/paths"],
  ["POST", "/api/v2/paths"],
  ["GET", "/api/v2/paths/{id}"],
  ["DELETE", "/api/v2/paths/{id}"],
  ["PATCH", "/api/v2/paths/{id}"],
  ["GET", "/api/v2/petition_signatures"],
  ["POST", "/api/v2/petition_signatures"],
  ["GET", "/api/v2/petition_signatures/{id}"],
  ["DELETE", "/api/v2/petition_signatures/{id}"],
  ["PATCH", "/api/v2/petition_signatures/{id}"],
  ["GET", "/api/v2/petitions"],
  ["POST", "/api/v2/petitions"],
  ["GET", "/api/v2/petitions/{id}"],
  ["DELETE", "/api/v2/petitions/{id}"],
  ["PATCH", "/api/v2/petitions/{id}"],
  ["GET", "/api/v2/pledges"],
  ["POST", "/api/v2/pledges"],
  ["GET", "/api/v2/pledges/{id}"],
  ["DELETE", "/api/v2/pledges/{id}"],
  ["PATCH", "/api/v2/pledges/{id}"],
  ["GET", "/api/v2/precincts"],
  ["POST", "/api/v2/precincts"],
  ["GET", "/api/v2/precincts/{id}"],
  ["DELETE", "/api/v2/precincts/{id}"],
  ["PATCH", "/api/v2/precincts/{id}"],
  ["GET", "/api/v2/relationships"],
  ["POST", "/api/v2/relationships"],
  ["GET", "/api/v2/relationships/{id}"],
  ["DELETE", "/api/v2/relationships/{id}"],
  ["PATCH", "/api/v2/relationships/{id}"],
  ["GET", "/api/v2/signup_profiles"],
  ["POST", "/api/v2/signup_profiles"],
  ["GET", "/api/v2/signup_profiles/{id}"],
  ["DELETE", "/api/v2/signup_profiles/{id}"],
  ["PATCH", "/api/v2/signup_profiles/{id}"],
  ["GET", "/api/v2/signup_taggings"],
  ["POST", "/api/v2/signup_taggings"],
  ["GET", "/api/v2/signup_taggings/{id}"],
  ["DELETE", "/api/v2/signup_taggings/{id}"],
  ["GET", "/api/v2/signup_tags"],
  ["POST", "/api/v2/signup_tags"],
  ["GET", "/api/v2/signup_tags/{id}"],
  ["DELETE", "/api/v2/signup_tags/{id}"],
  ["PATCH", "/api/v2/signup_tags/{id}"],
  ["GET", "/api/v2/signups"],
  ["POST", "/api/v2/signups"],
  ["GET", "/api/v2/signups/me"],
  ["PATCH", "/api/v2/signups/push"],
  ["GET", "/api/v2/signups/{id}"],
  ["DELETE", "/api/v2/signups/{id}"],
  ["PATCH", "/api/v2/signups/{id}"],
  ["GET", "/api/v2/sites"],
  ["GET", "/api/v2/suggestion_boxes"],
  ["POST", "/api/v2/suggestion_boxes"],
  ["GET", "/api/v2/suggestion_boxes/{id}"],
  ["DELETE", "/api/v2/suggestion_boxes/{id}"],
  ["PATCH", "/api/v2/suggestion_boxes/{id}"],
  ["GET", "/api/v2/suggestions"],
  ["POST", "/api/v2/suggestions"],
  ["GET", "/api/v2/suggestions/{id}"],
  ["DELETE", "/api/v2/suggestions/{id}"],
  ["PATCH", "/api/v2/suggestions/{id}"],
  ["GET", "/api/v2/survey_question_possible_responses"],
  ["POST", "/api/v2/survey_question_possible_responses"],
  ["GET", "/api/v2/survey_question_possible_responses/{id}"],
  ["DELETE", "/api/v2/survey_question_possible_responses/{id}"],
  ["PATCH", "/api/v2/survey_question_possible_responses/{id}"],
  ["GET", "/api/v2/survey_question_responses"],
  ["POST", "/api/v2/survey_question_responses"],
  ["GET", "/api/v2/survey_question_responses/{id}"],
  ["DELETE", "/api/v2/survey_question_responses/{id}"],
  ["PATCH", "/api/v2/survey_question_responses/{id}"],
  ["GET", "/api/v2/survey_questions"],
  ["POST", "/api/v2/survey_questions"],
  ["GET", "/api/v2/survey_questions/{id}"],
  ["DELETE", "/api/v2/survey_questions/{id}"],
  ["PATCH", "/api/v2/survey_questions/{id}"],
  ["GET", "/api/v2/surveys"],
  ["POST", "/api/v2/surveys"],
  ["GET", "/api/v2/surveys/{id}"],
  ["DELETE", "/api/v2/surveys/{id}"],
  ["PATCH", "/api/v2/surveys/{id}"],
  ["GET", "/api/v2/voters"],
  ["POST", "/api/v2/voters"],
  ["GET", "/api/v2/voters/{id}"],
  ["DELETE", "/api/v2/voters/{id}"],
  ["PATCH", "/api/v2/voters/{id}"],
] as const;

function operation(
  route: (typeof NATIONBUILDER_ROUTES)[number],
): BoundedRestOperation {
  const [method, path] = route;
  return {
    id: `${method}_${path
      .replace(/^\/api\/v2\//, "")
      .replace(/[{}]/g, "")
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/^_|_$/g, "")}`.toLowerCase(),
    method,
    path,
    pathParameters: path.includes("{id}") ? ["id"] : [],
    mutating: method !== "GET",
    bodyAllowed: method === "POST" || method === "PATCH",
    description: `${method} ${path}`,
  };
}

export const NATIONBUILDER_OPERATIONS = NATIONBUILDER_ROUTES.map(operation);
export const NATIONBUILDER_READ_OPERATION_IDS = NATIONBUILDER_OPERATIONS.filter(
  (item) => !item.mutating,
).map((item) => item.id);
export const NATIONBUILDER_MANAGE_OPERATION_IDS =
  NATIONBUILDER_OPERATIONS.filter((item) => item.mutating).map(
    (item) => item.id,
  );

export const NATIONBUILDER_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "nationbuilder",
  name: "NationBuilder",
  baseUrl: "https://nationbuilder.com/",
  originSubdomain: {
    credentialName: "nationBuilderNationSlug",
    suffix: "nationbuilder.com",
  },
  credentialName: "accessToken",
  authorization: { headerName: "Authorization", prefix: "Bearer " },
  operations: NATIONBUILDER_OPERATIONS,
  health: { operationId: "get_signups_me" },
};
