import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Generated from Neon CRM API v2.11 official OpenAPI on 2026-07-17. */
export const NEON_CRM_OPERATIONS = [
  {
    id: "get_accounts",
    method: "GET",
    path: "/accounts",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of accounts",
  },
  {
    id: "post_accounts",
    method: "POST",
    path: "/accounts",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates an account",
  },
  {
    id: "post_accounts_link",
    method: "POST",
    path: "/accounts/link",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Link an individual account to an company",
  },
  {
    id: "post_accounts_search",
    method: "POST",
    path: "/accounts/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Searches for accounts",
  },
  {
    id: "get_accounts_search_output_fields",
    method: "GET",
    path: "/accounts/search/outputFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible output columns for the /accounts/search method",
  },
  {
    id: "get_accounts_search_search_fields",
    method: "GET",
    path: "/accounts/search/searchFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible search criteria fields for the /accounts/search method",
  },
  {
    id: "post_accounts_unlink",
    method: "POST",
    path: "/accounts/unlink",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Remove an individual account from an company",
  },
  {
    id: "delete_accounts_windfall",
    method: "DELETE",
    path: "/accounts/windfall",
    pathParameters: [],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Windfall data on all accounts",
  },
  {
    id: "get_accounts_by_id",
    method: "GET",
    path: "/accounts/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets an account",
  },
  {
    id: "put_accounts_by_id",
    method: "PUT",
    path: "/accounts/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates an account",
  },
  {
    id: "patch_accounts_by_id",
    method: "PATCH",
    path: "/accounts/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch an account",
  },
  {
    id: "get_accounts_by_id_contacts",
    method: "GET",
    path: "/accounts/{id}/contacts",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets company account contacts",
  },
  {
    id: "post_accounts_by_id_contacts",
    method: "POST",
    path: "/accounts/{id}/contacts",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a contact",
  },
  {
    id: "get_accounts_by_id_contacts_by_contact_id",
    method: "GET",
    path: "/accounts/{id}/contacts/{contactId}",
    pathParameters: ["contactId", "id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a contact",
  },
  {
    id: "put_accounts_by_id_contacts_by_contact_id",
    method: "PUT",
    path: "/accounts/{id}/contacts/{contactId}",
    pathParameters: ["contactId", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a contact",
  },
  {
    id: "patch_accounts_by_id_contacts_by_contact_id",
    method: "PATCH",
    path: "/accounts/{id}/contacts/{contactId}",
    pathParameters: ["contactId", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a contact",
  },
  {
    id: "delete_accounts_by_id_contacts_by_contact_id",
    method: "DELETE",
    path: "/accounts/{id}/contacts/{contactId}",
    pathParameters: ["contactId", "id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes an contact",
  },
  {
    id: "get_accounts_by_id_donations",
    method: "GET",
    path: "/accounts/{id}/donations",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of donations for this account",
  },
  {
    id: "get_accounts_by_id_event_registrations",
    method: "GET",
    path: "/accounts/{id}/eventRegistrations",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of event registrations for this account",
  },
  {
    id: "get_accounts_by_id_memberships",
    method: "GET",
    path: "/accounts/{id}/memberships",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an account's membership history",
  },
  {
    id: "get_accounts_by_id_orders",
    method: "GET",
    path: "/accounts/{id}/orders",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an account's order history",
  },
  {
    id: "get_accounts_by_id_pledges",
    method: "GET",
    path: "/accounts/{id}/pledges",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of pledges for this account",
  },
  {
    id: "get_accounts_by_id_windfall",
    method: "GET",
    path: "/accounts/{id}/windfall",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get Windfall data on an account",
  },
  {
    id: "post_accounts_by_id_windfall",
    method: "POST",
    path: "/accounts/{id}/windfall",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Add Windfall data to an account",
  },
  {
    id: "delete_accounts_by_id_windfall",
    method: "DELETE",
    path: "/accounts/{id}/windfall",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Windfall data on an account",
  },
  {
    id: "post_activities",
    method: "POST",
    path: "/activities",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a activity",
  },
  {
    id: "post_activities_search",
    method: "POST",
    path: "/activities/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Search for activities",
  },
  {
    id: "get_activities_search_output_fields",
    method: "GET",
    path: "/activities/search/outputFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible output columns for the /activities/search method",
  },
  {
    id: "get_activities_search_search_fields",
    method: "GET",
    path: "/activities/search/searchFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible search criteria fields for the /activities/search method",
  },
  {
    id: "get_activities_by_id",
    method: "GET",
    path: "/activities/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get an activity",
  },
  {
    id: "put_activities_by_id",
    method: "PUT",
    path: "/activities/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update an activity",
  },
  {
    id: "patch_activities_by_id",
    method: "PATCH",
    path: "/activities/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch an activity",
  },
  {
    id: "delete_activities_by_id",
    method: "DELETE",
    path: "/activities/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete an activity",
  },
  {
    id: "post_addresses",
    method: "POST",
    path: "/addresses",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a new address",
  },
  {
    id: "get_addresses_by_address_id",
    method: "GET",
    path: "/addresses/{addressId}",
    pathParameters: ["addressId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets an address",
  },
  {
    id: "put_addresses_by_address_id",
    method: "PUT",
    path: "/addresses/{addressId}",
    pathParameters: ["addressId"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates an address",
  },
  {
    id: "delete_addresses_by_address_id",
    method: "DELETE",
    path: "/addresses/{addressId}",
    pathParameters: ["addressId"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes an address",
  },
  {
    id: "patch_addresses_by_id",
    method: "PATCH",
    path: "/addresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch an address",
  },
  {
    id: "get_campaigns",
    method: "GET",
    path: "/campaigns",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of campaigns",
  },
  {
    id: "post_campaigns",
    method: "POST",
    path: "/campaigns",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a campaign",
  },
  {
    id: "get_campaigns_by_id",
    method: "GET",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a campaign",
  },
  {
    id: "put_campaigns_by_id",
    method: "PUT",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a campaign",
  },
  {
    id: "patch_campaigns_by_id",
    method: "PATCH",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a campaign",
  },
  {
    id: "delete_campaigns_by_id",
    method: "DELETE",
    path: "/campaigns/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a campaign",
  },
  {
    id: "get_campaigns_by_id_p2p",
    method: "GET",
    path: "/campaigns/{id}/p2p",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets peer-to-peer fundraiser list",
  },
  {
    id: "post_campaigns_by_id_p2p",
    method: "POST",
    path: "/campaigns/{id}/p2p",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Add a fundraiser to a campaign",
  },
  {
    id: "get_custom_fields",
    method: "GET",
    path: "/customFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets custom fields",
  },
  {
    id: "post_custom_fields",
    method: "POST",
    path: "/customFields",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a custom field",
  },
  {
    id: "post_custom_fields_add_to_group",
    method: "POST",
    path: "/customFields/addToGroup",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Add a custom field to a group",
  },
  {
    id: "get_custom_fields_groups",
    method: "GET",
    path: "/customFields/groups",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of custom field groups",
  },
  {
    id: "post_custom_fields_groups",
    method: "POST",
    path: "/customFields/groups",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a custom field group",
  },
  {
    id: "put_custom_fields_groups_by_group_id",
    method: "PUT",
    path: "/customFields/groups/{groupId}",
    pathParameters: ["groupId"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a custom field group",
  },
  {
    id: "delete_custom_fields_groups_by_group_id",
    method: "DELETE",
    path: "/customFields/groups/{groupId}",
    pathParameters: ["groupId"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a custom field group",
  },
  {
    id: "get_custom_fields_by_id",
    method: "GET",
    path: "/customFields/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a custom field",
  },
  {
    id: "put_custom_fields_by_id",
    method: "PUT",
    path: "/customFields/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a custom field",
  },
  {
    id: "delete_custom_fields_by_id",
    method: "DELETE",
    path: "/customFields/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a custom field",
  },
  {
    id: "post_donations",
    method: "POST",
    path: "/donations",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a new donation",
  },
  {
    id: "post_donations_search",
    method: "POST",
    path: "/donations/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Search for donations, pledges, and pledge payments",
  },
  {
    id: "get_donations_search_output_fields",
    method: "GET",
    path: "/donations/search/outputFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible output columns for the /donations/search method",
  },
  {
    id: "get_donations_search_search_fields",
    method: "GET",
    path: "/donations/search/searchFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible search criteria fields for the /donations/search method",
  },
  {
    id: "post_donations_by_donation_id_payments",
    method: "POST",
    path: "/donations/{donationId}/payments",
    pathParameters: ["donationId"],
    mutating: true,
    bodyAllowed: true,
    description: "Add a payment for donation",
  },
  {
    id: "get_donations_by_id",
    method: "GET",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a donation",
  },
  {
    id: "put_donations_by_id",
    method: "PUT",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a donation",
  },
  {
    id: "patch_donations_by_id",
    method: "PATCH",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a donation",
  },
  {
    id: "delete_donations_by_id",
    method: "DELETE",
    path: "/donations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a donation",
  },
  {
    id: "post_event_registrations",
    method: "POST",
    path: "/eventRegistrations",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a new event registration",
  },
  {
    id: "post_event_registrations_calculate",
    method: "POST",
    path: "/eventRegistrations/calculate",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description:
      "Calculate the correct fee for a new registration for this event",
  },
  {
    id: "get_event_registrations_by_registration_id",
    method: "GET",
    path: "/eventRegistrations/{registrationId}",
    pathParameters: ["registrationId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets an event registration",
  },
  {
    id: "put_event_registrations_by_registration_id",
    method: "PUT",
    path: "/eventRegistrations/{registrationId}",
    pathParameters: ["registrationId"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates an event registration",
  },
  {
    id: "patch_event_registrations_by_registration_id",
    method: "PATCH",
    path: "/eventRegistrations/{registrationId}",
    pathParameters: ["registrationId"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch an event registration",
  },
  {
    id: "delete_event_registrations_by_registration_id",
    method: "DELETE",
    path: "/eventRegistrations/{registrationId}",
    pathParameters: ["registrationId"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes an event registration",
  },
  {
    id: "post_event_registrations_by_registration_id_payments",
    method: "POST",
    path: "/eventRegistrations/{registrationId}/payments",
    pathParameters: ["registrationId"],
    mutating: true,
    bodyAllowed: true,
    description: "Add a payment for event registration",
  },
  {
    id: "post_grants",
    method: "POST",
    path: "/grants",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a grant",
  },
  {
    id: "post_grants_search",
    method: "POST",
    path: "/grants/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Search for grants",
  },
  {
    id: "get_events",
    method: "GET",
    path: "/events",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of events",
  },
  {
    id: "post_events",
    method: "POST",
    path: "/events",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates an event",
  },
  {
    id: "get_events_categories",
    method: "GET",
    path: "/events/categories",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets event categories",
  },
  {
    id: "post_events_search",
    method: "POST",
    path: "/events/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Search for events",
  },
  {
    id: "get_events_search_output_fields",
    method: "GET",
    path: "/events/search/outputFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible output columns for the /events/search method",
  },
  {
    id: "get_events_search_search_fields",
    method: "GET",
    path: "/events/search/searchFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible search criteria fields for the /events/search method",
  },
  {
    id: "get_grants_by_id",
    method: "GET",
    path: "/grants/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a grant",
  },
  {
    id: "put_grants_by_id",
    method: "PUT",
    path: "/grants/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a grant",
  },
  {
    id: "patch_grants_by_id",
    method: "PATCH",
    path: "/grants/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a grant",
  },
  {
    id: "delete_grants_by_id",
    method: "DELETE",
    path: "/grants/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a grant",
  },
  {
    id: "get_events_by_id",
    method: "GET",
    path: "/events/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets an event",
  },
  {
    id: "put_events_by_id",
    method: "PUT",
    path: "/events/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates an event",
  },
  {
    id: "patch_events_by_id",
    method: "PATCH",
    path: "/events/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch an event",
  },
  {
    id: "delete_events_by_id",
    method: "DELETE",
    path: "/events/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes an event",
  },
  {
    id: "get_events_by_id_attendees",
    method: "GET",
    path: "/events/{id}/attendees",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of attendees for an event",
  },
  {
    id: "get_grants_search_search_fields",
    method: "GET",
    path: "/grants/search/searchFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible search criteria fields for the /grants/search method",
  },
  {
    id: "get_grants_search_output_fields",
    method: "GET",
    path: "/grants/search/outputFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible output columns for the /grants/search method",
  },
  {
    id: "get_events_by_id_event_registrations",
    method: "GET",
    path: "/events/{id}/eventRegistrations",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of event registrations for this event",
  },
  {
    id: "get_events_by_id_tickets",
    method: "GET",
    path: "/events/{id}/tickets",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of ticket options for an event",
  },
  {
    id: "post_events_by_id_tickets",
    method: "POST",
    path: "/events/{id}/tickets",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Add a ticket option to an event",
  },
  {
    id: "get_events_by_id_tickets_by_ticket_id",
    method: "GET",
    path: "/events/{id}/tickets/{ticketId}",
    pathParameters: ["id", "ticketId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a ticket option",
  },
  {
    id: "put_events_by_id_tickets_by_ticket_id",
    method: "PUT",
    path: "/events/{id}/tickets/{ticketId}",
    pathParameters: ["id", "ticketId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a ticket option",
  },
  {
    id: "patch_events_by_id_tickets_by_ticket_id",
    method: "PATCH",
    path: "/events/{id}/tickets/{ticketId}",
    pathParameters: ["id", "ticketId"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch an event ticket",
  },
  {
    id: "delete_events_by_id_tickets_by_ticket_id",
    method: "DELETE",
    path: "/events/{id}/tickets/{ticketId}",
    pathParameters: ["id", "ticketId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a ticket option",
  },
  {
    id: "post_memberships",
    method: "POST",
    path: "/memberships",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a membership",
  },
  {
    id: "post_memberships_calculate_dates",
    method: "POST",
    path: "/memberships/calculateDates",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Calculate the membership term start and end dates",
  },
  {
    id: "post_memberships_calculate_fee",
    method: "POST",
    path: "/memberships/calculateFee",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Calculate the cost a membership",
  },
  {
    id: "get_memberships_levels",
    method: "GET",
    path: "/memberships/levels",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of membership levels",
  },
  {
    id: "get_memberships_terms",
    method: "GET",
    path: "/memberships/terms",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of membership terms",
  },
  {
    id: "get_memberships_by_membership_id",
    method: "GET",
    path: "/memberships/{membershipId}",
    pathParameters: ["membershipId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a membership",
  },
  {
    id: "put_memberships_by_membership_id",
    method: "PUT",
    path: "/memberships/{membershipId}",
    pathParameters: ["membershipId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a membership",
  },
  {
    id: "patch_memberships_by_membership_id",
    method: "PATCH",
    path: "/memberships/{membershipId}",
    pathParameters: ["membershipId"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a membership",
  },
  {
    id: "delete_memberships_by_membership_id",
    method: "DELETE",
    path: "/memberships/{membershipId}",
    pathParameters: ["membershipId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a membership",
  },
  {
    id: "get_memberships_by_membership_id_auto_renewal",
    method: "GET",
    path: "/memberships/{membershipId}/autoRenewal",
    pathParameters: ["membershipId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get auto-renewal of a membership",
  },
  {
    id: "post_memberships_by_membership_id_auto_renewal",
    method: "POST",
    path: "/memberships/{membershipId}/autoRenewal",
    pathParameters: ["membershipId"],
    mutating: true,
    bodyAllowed: true,
    description: "Edit auto-renewal for a membership",
  },
  {
    id: "post_memberships_by_membership_id_payments",
    method: "POST",
    path: "/memberships/{membershipId}/payments",
    pathParameters: ["membershipId"],
    mutating: true,
    bodyAllowed: true,
    description: "Add a payment for membership",
  },
  {
    id: "post_memberships_by_membership_id_renew",
    method: "POST",
    path: "/memberships/{membershipId}/renew",
    pathParameters: ["membershipId"],
    mutating: true,
    bodyAllowed: true,
    description: "Renew an existing membership",
  },
  {
    id: "get_memberships_by_membership_id_sub_members",
    method: "GET",
    path: "/memberships/{membershipId}/subMembers",
    pathParameters: ["membershipId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of sub-membership",
  },
  {
    id: "post_payments",
    method: "POST",
    path: "/payments",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Add additional payments to a transaction",
  },
  {
    id: "post_payments_by_id_refund",
    method: "POST",
    path: "/payments/{id}/refund",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Refund an Neon Pay payment or cancel a offline payment",
  },
  {
    id: "post_orders",
    method: "POST",
    path: "/orders",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a store order",
  },
  {
    id: "post_orders_calculate",
    method: "POST",
    path: "/orders/calculate",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: " Calculate the total cost of the order",
  },
  {
    id: "post_orders_search",
    method: "POST",
    path: "/orders/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Search for orders",
  },
  {
    id: "get_orders_search_output_fields",
    method: "GET",
    path: "/orders/search/outputFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible output columns for the /orders/search method",
  },
  {
    id: "get_orders_search_search_fields",
    method: "GET",
    path: "/orders/search/searchFields",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets a list of possible search criteria fields for the /orders/search method",
  },
  {
    id: "post_orders_shipping_methods",
    method: "POST",
    path: "/orders/shippingMethods",
    pathParameters: [],
    mutating: false,
    bodyAllowed: true,
    description: "Get a list of shipping methods",
  },
  {
    id: "get_orders_by_id",
    method: "GET",
    path: "/orders/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets an order",
  },
  {
    id: "delete_orders_by_id",
    method: "DELETE",
    path: "/orders/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes an order",
  },
  {
    id: "post_orders_by_order_id_payments",
    method: "POST",
    path: "/orders/{orderId}/payments",
    pathParameters: ["orderId"],
    mutating: true,
    bodyAllowed: true,
    description: "Add a payment for order",
  },
  {
    id: "get_payments_credit_card_types",
    method: "GET",
    path: "/payments/creditCardTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets credit card types",
  },
  {
    id: "get_payments_donor_covered_fees",
    method: "GET",
    path: "/payments/donorCoveredFees",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Calculate the donor covered fee according to the transaction amount",
  },
  {
    id: "get_payments_processor_settings",
    method: "GET",
    path: "/payments/processorSettings",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description:
      "Gets configuration settings specific to the payment processor in use",
  },
  {
    id: "get_payments_tenders",
    method: "GET",
    path: "/payments/tenders",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets tender types",
  },
  {
    id: "post_pledges",
    method: "POST",
    path: "/pledges",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a new pledge",
  },
  {
    id: "get_pledges_by_id",
    method: "GET",
    path: "/pledges/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a Pledge",
  },
  {
    id: "put_pledges_by_id",
    method: "PUT",
    path: "/pledges/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a pledge",
  },
  {
    id: "patch_pledges_by_id",
    method: "PATCH",
    path: "/pledges/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a pledge",
  },
  {
    id: "delete_pledges_by_id",
    method: "DELETE",
    path: "/pledges/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a pledge",
  },
  {
    id: "get_pledges_by_id_pledge_payments",
    method: "GET",
    path: "/pledges/{id}/pledgePayments",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of payments towards a specific pledge",
  },
  {
    id: "post_pledges_by_id_pledge_payments",
    method: "POST",
    path: "/pledges/{id}/pledgePayments",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a new pledge payment",
  },
  {
    id: "get_pledges_by_id_pledge_payments_by_payment_id",
    method: "GET",
    path: "/pledges/{id}/pledgePayments/{paymentId}",
    pathParameters: ["id", "paymentId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a single pledge payment",
  },
  {
    id: "delete_pledges_by_id_pledge_payments_by_payment_id",
    method: "DELETE",
    path: "/pledges/{id}/pledgePayments/{paymentId}",
    pathParameters: ["id", "paymentId"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes an existing pledge payment",
  },
  {
    id: "get_pledges_by_pledge_id_installments",
    method: "GET",
    path: "/pledges/{pledgeId}/installments",
    pathParameters: ["pledgeId"],
    mutating: false,
    bodyAllowed: false,
    description: "Retrieve a list of pledge installment.",
  },
  {
    id: "post_pledges_by_pledge_id_installments",
    method: "POST",
    path: "/pledges/{pledgeId}/installments",
    pathParameters: ["pledgeId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a pledge installment.",
  },
  {
    id: "get_pledges_by_pledge_id_installments_by_id",
    method: "GET",
    path: "/pledges/{pledgeId}/installments/{id}",
    pathParameters: ["id", "pledgeId"],
    mutating: false,
    bodyAllowed: false,
    description: "Retrieve a pledge installment.",
  },
  {
    id: "put_pledges_by_pledge_id_installments_by_id",
    method: "PUT",
    path: "/pledges/{pledgeId}/installments/{id}",
    pathParameters: ["id", "pledgeId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a pledge installment.",
  },
  {
    id: "delete_pledges_by_pledge_id_installments_by_id",
    method: "DELETE",
    path: "/pledges/{pledgeId}/installments/{id}",
    pathParameters: ["id", "pledgeId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a pledge installment.",
  },
  {
    id: "get_properties_activity_statuses",
    method: "GET",
    path: "/properties/activityStatuses",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of available Activity Statuses",
  },
  {
    id: "get_properties_address_types",
    method: "GET",
    path: "/properties/addressTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets address types",
  },
  {
    id: "get_properties_company_types",
    method: "GET",
    path: "/properties/companyTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets company types",
  },
  {
    id: "get_properties_countries",
    method: "GET",
    path: "/properties/countries",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets countries",
  },
  {
    id: "get_properties_current_system_user",
    method: "GET",
    path: "/properties/currentSystemUser",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets current system user",
  },
  {
    id: "get_properties_event_categories",
    method: "GET",
    path: "/properties/eventCategories",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets Event Categories",
  },
  {
    id: "post_properties_event_categories",
    method: "POST",
    path: "/properties/eventCategories",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a new event category",
  },
  {
    id: "get_properties_event_categories_by_id",
    method: "GET",
    path: "/properties/eventCategories/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a specific event category",
  },
  {
    id: "put_properties_event_categories_by_id",
    method: "PUT",
    path: "/properties/eventCategories/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates an event category",
  },
  {
    id: "delete_properties_event_categories_by_id",
    method: "DELETE",
    path: "/properties/eventCategories/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes an event category",
  },
  {
    id: "get_properties_event_topics",
    method: "GET",
    path: "/properties/eventTopics",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets Event Topics",
  },
  {
    id: "get_properties_funds",
    method: "GET",
    path: "/properties/funds",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets funds",
  },
  {
    id: "get_properties_genders",
    method: "GET",
    path: "/properties/genders",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets genders",
  },
  {
    id: "get_properties_individual_types",
    method: "GET",
    path: "/properties/individualTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets individual types",
  },
  {
    id: "get_properties_organization_profile",
    method: "GET",
    path: "/properties/organizationProfile",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets organization profile",
  },
  {
    id: "get_properties_prefixes",
    method: "GET",
    path: "/properties/prefixes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets prefixes",
  },
  {
    id: "get_properties_purposes",
    method: "GET",
    path: "/properties/purposes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets purposes",
  },
  {
    id: "get_properties_relation_types",
    method: "GET",
    path: "/properties/relationTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets relation types",
  },
  {
    id: "get_properties_solicitation_methods",
    method: "GET",
    path: "/properties/solicitationMethods",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of solicitation methods",
  },
  {
    id: "get_properties_sources",
    method: "GET",
    path: "/properties/sources",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets sources",
  },
  {
    id: "get_properties_state_provinces",
    method: "GET",
    path: "/properties/stateProvinces",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets states",
  },
  {
    id: "get_properties_system_timezones",
    method: "GET",
    path: "/properties/systemTimezones",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets system timezones",
  },
  {
    id: "get_properties_system_users",
    method: "GET",
    path: "/properties/systemUsers",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets system users",
  },
  {
    id: "get_recurring",
    method: "GET",
    path: "/recurring",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of recurring donation schedules",
  },
  {
    id: "post_recurring",
    method: "POST",
    path: "/recurring",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a new recurring donation schedule",
  },
  {
    id: "get_recurring_by_id",
    method: "GET",
    path: "/recurring/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a recurring donation schedule",
  },
  {
    id: "put_recurring_by_id",
    method: "PUT",
    path: "/recurring/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a recurring donation schedule",
  },
  {
    id: "patch_recurring_by_id",
    method: "PATCH",
    path: "/recurring/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a recurring donation schedule",
  },
  {
    id: "delete_recurring_by_id",
    method: "DELETE",
    path: "/recurring/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a recurring donation schedule",
  },
  {
    id: "post_shipping_addresses",
    method: "POST",
    path: "/shippingAddresses",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a new shipping address",
  },
  {
    id: "get_shipping_addresses_by_address_id",
    method: "GET",
    path: "/shippingAddresses/{addressId}",
    pathParameters: ["addressId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a shipping address",
  },
  {
    id: "put_shipping_addresses_by_address_id",
    method: "PUT",
    path: "/shippingAddresses/{addressId}",
    pathParameters: ["addressId"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a shipping address",
  },
  {
    id: "delete_shipping_addresses_by_address_id",
    method: "DELETE",
    path: "/shippingAddresses/{addressId}",
    pathParameters: ["addressId"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a shipping address",
  },
  {
    id: "patch_shipping_addresses_by_id",
    method: "PATCH",
    path: "/shippingAddresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a shipping address",
  },
  {
    id: "get_soft_credits",
    method: "GET",
    path: "/softCredits",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of soft credits",
  },
  {
    id: "post_soft_credits",
    method: "POST",
    path: "/softCredits",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Creates a soft credit",
  },
  {
    id: "get_soft_credits_by_id",
    method: "GET",
    path: "/softCredits/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a soft credit",
  },
  {
    id: "put_soft_credits_by_id",
    method: "PUT",
    path: "/softCredits/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Updates a soft credit",
  },
  {
    id: "patch_soft_credits_by_id",
    method: "PATCH",
    path: "/softCredits/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a soft credit",
  },
  {
    id: "delete_soft_credits_by_id",
    method: "DELETE",
    path: "/softCredits/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Deletes a soft credit",
  },
  {
    id: "get_store_catalogs",
    method: "GET",
    path: "/store/catalogs",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: " Get a list of store catalogs",
  },
  {
    id: "get_store_categories",
    method: "GET",
    path: "/store/categories",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of store categories",
  },
  {
    id: "get_store_products",
    method: "GET",
    path: "/store/products",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of store products",
  },
  {
    id: "get_store_products_by_product_id",
    method: "GET",
    path: "/store/products/{productId}",
    pathParameters: ["productId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a product",
  },
  {
    id: "get_webhooks",
    method: "GET",
    path: "/webhooks",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of webhook subscriptions",
  },
  {
    id: "post_webhooks",
    method: "POST",
    path: "/webhooks",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a new webhook subscription",
  },
  {
    id: "get_webhooks_by_id",
    method: "GET",
    path: "/webhooks/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Retrieve a webhook subscription",
  },
  {
    id: "put_webhooks_by_id",
    method: "PUT",
    path: "/webhooks/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a webhook subscription",
  },
  {
    id: "patch_webhooks_by_id",
    method: "PATCH",
    path: "/webhooks/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a webhook",
  },
  {
    id: "delete_webhooks_by_id",
    method: "DELETE",
    path: "/webhooks/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a webhook subscription",
  },
  {
    id: "get_volunteers",
    method: "GET",
    path: "/volunteers",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteers",
  },
  {
    id: "get_groups_by_id",
    method: "GET",
    path: "/groups/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a volunteer group",
  },
  {
    id: "put_groups_by_id",
    method: "PUT",
    path: "/groups/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a volunteer group",
  },
  {
    id: "delete_groups_by_id",
    method: "DELETE",
    path: "/groups/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a volunteer group",
  },
  {
    id: "post_groups",
    method: "POST",
    path: "/groups",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a volunteer group",
  },
  {
    id: "post_groups_by_id_add_volunteers",
    method: "POST",
    path: "/groups/{id}/addVolunteers",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Add volunteers to a volunteer group",
  },
  {
    id: "get_groups_by_id_volunteers",
    method: "GET",
    path: "/groups/{id}/volunteers",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteers in a volunteer group",
  },
  {
    id: "get_groups_list",
    method: "GET",
    path: "/groups/list",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteer groups",
  },
  {
    id: "delete_groups_by_id_remove_volunteers",
    method: "DELETE",
    path: "/groups/{id}/removeVolunteers",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Remove volunteers from a volunteer group",
  },
  {
    id: "get_opportunities",
    method: "GET",
    path: "/opportunities",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteer opportunities",
  },
  {
    id: "post_opportunities",
    method: "POST",
    path: "/opportunities",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a volunteer opportunity",
  },
  {
    id: "get_opportunities_by_id",
    method: "GET",
    path: "/opportunities/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a volunteer opportunity",
  },
  {
    id: "put_opportunities_by_id",
    method: "PUT",
    path: "/opportunities/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a volunteer opportunity",
  },
  {
    id: "patch_opportunities_by_id",
    method: "PATCH",
    path: "/opportunities/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a volunteer opportunity",
  },
  {
    id: "delete_opportunities_by_id",
    method: "DELETE",
    path: "/opportunities/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a volunteer opportunity",
  },
  {
    id: "get_opportunities_by_id_volunteers",
    method: "GET",
    path: "/opportunities/{id}/volunteers",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteers assigned to a volunteer opportunity",
  },
  {
    id: "post_opportunities_by_id_add_volunteers",
    method: "POST",
    path: "/opportunities/{id}/addVolunteers",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Add volunteers to a volunteer opportunity",
  },
  {
    id: "delete_opportunities_by_id_remove_volunteers",
    method: "DELETE",
    path: "/opportunities/{id}/removeVolunteers",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Remove volunteers from an opportunity",
  },
  {
    id: "post_roles",
    method: "POST",
    path: "/roles",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a volunteer role",
  },
  {
    id: "get_roles_list",
    method: "GET",
    path: "/roles/list",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteer roles",
  },
  {
    id: "get_roles_by_id",
    method: "GET",
    path: "/roles/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a volunteer role",
  },
  {
    id: "put_roles_by_id",
    method: "PUT",
    path: "/roles/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a volunteer role",
  },
  {
    id: "delete_roles_by_id",
    method: "DELETE",
    path: "/roles/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a volunteer role",
  },
  {
    id: "get_roles_by_id_volunteers",
    method: "GET",
    path: "/roles/{id}/volunteers",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteers assigned to a role",
  },
  {
    id: "get_opportunities_by_opportunity_id_shifts",
    method: "GET",
    path: "/opportunities/{opportunityId}/shifts",
    pathParameters: ["opportunityId"],
    mutating: false,
    bodyAllowed: false,
    description: "Gets a list of volunteer shifts for a volunteer opportunity",
  },
  {
    id: "post_opportunities_by_opportunity_id_shifts",
    method: "POST",
    path: "/opportunities/{opportunityId}/shifts",
    pathParameters: ["opportunityId"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a shift associated with a volunteer opportunity",
  },
  {
    id: "get_opportunities_by_opportunity_id_shifts_by_shift_id",
    method: "GET",
    path: "/opportunities/{opportunityId}/shifts/{shiftId}",
    pathParameters: ["opportunityId", "shiftId"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a volunteer shift",
  },
  {
    id: "put_opportunities_by_opportunity_id_shifts_by_shift_id",
    method: "PUT",
    path: "/opportunities/{opportunityId}/shifts/{shiftId}",
    pathParameters: ["opportunityId", "shiftId"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a volunteer shift",
  },
  {
    id: "patch_opportunities_by_opportunity_id_shifts_by_shift_id",
    method: "PATCH",
    path: "/opportunities/{opportunityId}/shifts/{shiftId}",
    pathParameters: ["opportunityId", "shiftId"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a volunteer shfit",
  },
  {
    id: "delete_opportunities_by_opportunity_id_shifts_by_shift_id",
    method: "DELETE",
    path: "/opportunities/{opportunityId}/shifts/{shiftId}",
    pathParameters: ["opportunityId", "shiftId"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a volunteer shift",
  },
  {
    id: "get_opportunities_by_opportunity_id_shifts_by_id_volunteers",
    method: "GET",
    path: "/opportunities/{opportunityId}/shifts/{id}/volunteers",
    pathParameters: ["opportunityId", "id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of volunteers assigned to a shift",
  },
  {
    id: "post_opportunities_by_opportunity_id_shifts_by_id_add_volunteers",
    method: "POST",
    path: "/opportunities/{opportunityId}/shifts/{id}/addVolunteers",
    pathParameters: ["opportunityId", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Add volunteers to a shift",
  },
  {
    id: "delete_opportunities_by_opportunity_id_shifts_by_id_remove_volunteers",
    method: "DELETE",
    path: "/opportunities/{opportunityId}/shifts/{id}/removeVolunteers",
    pathParameters: ["opportunityId", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Remove volunteers from a shift",
  },
  {
    id: "get_time_sheets",
    method: "GET",
    path: "/timeSheets",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get volunteer time sheets",
  },
  {
    id: "post_time_sheets",
    method: "POST",
    path: "/timeSheets",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a volunteer time sheet",
  },
  {
    id: "get_time_sheets_by_id",
    method: "GET",
    path: "/timeSheets/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a Volunteer Time Sheet",
  },
  {
    id: "put_time_sheets_by_id",
    method: "PUT",
    path: "/timeSheets/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a volunteer time sheet",
  },
  {
    id: "patch_time_sheets_by_id",
    method: "PATCH",
    path: "/timeSheets/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a volunteer time sheet",
  },
  {
    id: "delete_time_sheets_by_id",
    method: "DELETE",
    path: "/timeSheets/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a volunteer time sheet",
  },
  {
    id: "get_custom_objects_by_id_or_api_alias",
    method: "GET",
    path: "/customObjects/{idOrApiAlias}",
    pathParameters: ["idOrApiAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a custom object",
  },
  {
    id: "put_custom_objects_by_id_or_api_alias",
    method: "PUT",
    path: "/customObjects/{idOrApiAlias}",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a custom object",
  },
  {
    id: "patch_custom_objects_by_id_or_api_alias",
    method: "PATCH",
    path: "/customObjects/{idOrApiAlias}",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a custom object",
  },
  {
    id: "delete_custom_objects_by_id_or_api_alias",
    method: "DELETE",
    path: "/customObjects/{idOrApiAlias}",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a custom object",
  },
  {
    id: "get_custom_objects",
    method: "GET",
    path: "/customObjects",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of custom objects",
  },
  {
    id: "post_custom_objects",
    method: "POST",
    path: "/customObjects",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a custom object",
  },
  {
    id: "post_custom_objects_by_id_or_api_alias_update_status",
    method: "POST",
    path: "/customObjects/{idOrApiAlias}/updateStatus",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a custom object's status",
  },
  {
    id: "post_custom_objects_by_id_or_api_alias_email_notifications",
    method: "POST",
    path: "/customObjects/{idOrApiAlias}/emailNotifications",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Update the custom object email notification type",
  },
  {
    id: "get_custom_objects_by_id_or_api_alias_fields_by_field_alias",
    method: "GET",
    path: "/customObjects/{idOrApiAlias}/fields/{fieldAlias}",
    pathParameters: ["idOrApiAlias", "fieldAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a custom object field",
  },
  {
    id: "put_custom_objects_by_id_or_api_alias_fields_by_field_alias",
    method: "PUT",
    path: "/customObjects/{idOrApiAlias}/fields/{fieldAlias}",
    pathParameters: ["idOrApiAlias", "fieldAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a custom object field",
  },
  {
    id: "patch_custom_objects_by_id_or_api_alias_fields_by_field_alias",
    method: "PATCH",
    path: "/customObjects/{idOrApiAlias}/fields/{fieldAlias}",
    pathParameters: ["idOrApiAlias", "fieldAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a custom object field",
  },
  {
    id: "delete_custom_objects_by_id_or_api_alias_fields_by_field_alias",
    method: "DELETE",
    path: "/customObjects/{idOrApiAlias}/fields/{fieldAlias}",
    pathParameters: ["idOrApiAlias", "fieldAlias"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a custom object field",
  },
  {
    id: "get_custom_objects_by_id_or_api_alias_fields",
    method: "GET",
    path: "/customObjects/{idOrApiAlias}/fields",
    pathParameters: ["idOrApiAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of custom object fields",
  },
  {
    id: "post_custom_objects_by_id_or_api_alias_fields",
    method: "POST",
    path: "/customObjects/{idOrApiAlias}/fields",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a custom object field",
  },
  {
    id: "get_custom_objects_by_id_or_api_alias_master_detail_objects",
    method: "GET",
    path: "/customObjects/{idOrApiAlias}/masterDetailObjects",
    pathParameters: ["idOrApiAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "List master/detail objects",
  },
  {
    id: "get_custom_objects_lookup_objects",
    method: "GET",
    path: "/customObjects/lookupObjects",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List lookup objects",
  },
  {
    id: "get_custom_objects_by_api_alias_form_layouts_by_id",
    method: "GET",
    path: "/customObjects/{apiAlias}/formLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a custom object form layout",
  },
  {
    id: "put_custom_objects_by_api_alias_form_layouts_by_id",
    method: "PUT",
    path: "/customObjects/{apiAlias}/formLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a custom object form layout",
  },
  {
    id: "patch_custom_objects_by_api_alias_form_layouts_by_id",
    method: "PATCH",
    path: "/customObjects/{apiAlias}/formLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a custom object form layout",
  },
  {
    id: "delete_custom_objects_by_api_alias_form_layouts_by_id",
    method: "DELETE",
    path: "/customObjects/{apiAlias}/formLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a custom object form layout",
  },
  {
    id: "get_custom_objects_by_api_alias_form_layouts",
    method: "GET",
    path: "/customObjects/{apiAlias}/formLayouts",
    pathParameters: ["apiAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of custom object form layouts",
  },
  {
    id: "post_custom_objects_by_api_alias_form_layouts",
    method: "POST",
    path: "/customObjects/{apiAlias}/formLayouts",
    pathParameters: ["apiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a custom object form layout",
  },
  {
    id: "get_custom_objects_by_api_alias_list_layouts_by_id",
    method: "GET",
    path: "/customObjects/{apiAlias}/listLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a custom object list layout",
  },
  {
    id: "put_custom_objects_by_api_alias_list_layouts_by_id",
    method: "PUT",
    path: "/customObjects/{apiAlias}/listLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a custom object list layout",
  },
  {
    id: "patch_custom_objects_by_api_alias_list_layouts_by_id",
    method: "PATCH",
    path: "/customObjects/{apiAlias}/listLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a custom object list layout",
  },
  {
    id: "delete_custom_objects_by_api_alias_list_layouts_by_id",
    method: "DELETE",
    path: "/customObjects/{apiAlias}/listLayouts/{id}",
    pathParameters: ["apiAlias", "id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a custom object list layout",
  },
  {
    id: "get_custom_objects_by_api_alias_list_layouts",
    method: "GET",
    path: "/customObjects/{apiAlias}/listLayouts",
    pathParameters: ["apiAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of custom object list layouts",
  },
  {
    id: "post_custom_objects_by_api_alias_list_layouts",
    method: "POST",
    path: "/customObjects/{apiAlias}/listLayouts",
    pathParameters: ["apiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a custom object list layout",
  },
  {
    id: "get_custom_objects_by_id_or_api_alias_records_by_id",
    method: "GET",
    path: "/customObjects/{idOrApiAlias}/records/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a custom object record",
  },
  {
    id: "put_custom_objects_by_id_or_api_alias_records_by_id",
    method: "PUT",
    path: "/customObjects/{idOrApiAlias}/records/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a custom object record",
  },
  {
    id: "patch_custom_objects_by_id_or_api_alias_records_by_id",
    method: "PATCH",
    path: "/customObjects/{idOrApiAlias}/records/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a custom object record",
  },
  {
    id: "delete_custom_objects_by_id_or_api_alias_records_by_id",
    method: "DELETE",
    path: "/customObjects/{idOrApiAlias}/records/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a custom object record",
  },
  {
    id: "post_custom_objects_by_id_or_api_alias_records",
    method: "POST",
    path: "/customObjects/{idOrApiAlias}/records",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a custom object record",
  },
  {
    id: "post_custom_objects_by_id_or_api_alias_records_list",
    method: "POST",
    path: "/customObjects/{idOrApiAlias}/records/list",
    pathParameters: ["idOrApiAlias"],
    mutating: false,
    bodyAllowed: true,
    description: "List custom object records",
  },
  {
    id: "get_custom_objects_by_api_alias_relations",
    method: "GET",
    path: "/customObjects/{apiAlias}/relations",
    pathParameters: ["apiAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of custom object relations",
  },
  {
    id: "get_custom_objects_by_id_or_api_alias_validators_by_id",
    method: "GET",
    path: "/customObjects/{idOrApiAlias}/validators/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a custom object validator",
  },
  {
    id: "put_custom_objects_by_id_or_api_alias_validators_by_id",
    method: "PUT",
    path: "/customObjects/{idOrApiAlias}/validators/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a custom object validator",
  },
  {
    id: "patch_custom_objects_by_id_or_api_alias_validators_by_id",
    method: "PATCH",
    path: "/customObjects/{idOrApiAlias}/validators/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: true,
    bodyAllowed: true,
    description: "Patch a custom object validator",
  },
  {
    id: "delete_custom_objects_by_id_or_api_alias_validators_by_id",
    method: "DELETE",
    path: "/customObjects/{idOrApiAlias}/validators/{id}",
    pathParameters: ["idOrApiAlias", "id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a custom object validator",
  },
  {
    id: "get_custom_objects_by_id_or_api_alias_validators",
    method: "GET",
    path: "/customObjects/{idOrApiAlias}/validators",
    pathParameters: ["idOrApiAlias"],
    mutating: false,
    bodyAllowed: false,
    description: "Get a list of custom object validators",
  },
  {
    id: "post_custom_objects_by_id_or_api_alias_validators",
    method: "POST",
    path: "/customObjects/{idOrApiAlias}/validators",
    pathParameters: ["idOrApiAlias"],
    mutating: true,
    bodyAllowed: true,
    description: "Create a custom object validator",
  },
  {
    id: "put_households_by_id",
    method: "PUT",
    path: "/households/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update a household",
  },
  {
    id: "delete_households_by_id",
    method: "DELETE",
    path: "/households/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete a household",
  },
  {
    id: "post_households",
    method: "POST",
    path: "/households",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create a household",
  },
  {
    id: "get_households_list_relation_types",
    method: "GET",
    path: "/households/listRelationTypes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List relation types",
  },
  {
    id: "get_households_list_households",
    method: "GET",
    path: "/households/listHouseholds",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "List households",
  },
] as const satisfies readonly BoundedRestOperation[];

export const NEON_CRM_READ_OPERATION_IDS = NEON_CRM_OPERATIONS.filter(
  (item) => !item.mutating,
).map((item) => item.id);
export const NEON_CRM_MANAGE_OPERATION_IDS = NEON_CRM_OPERATIONS.filter(
  (item) => item.mutating,
).map((item) => item.id);

export const NEON_CRM_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "neon-crm",
  name: "Neon CRM",
  baseUrl: "https://api.neoncrm.com/v2/",
  basicAuthorization: {
    usernameCredentialName: "NEON_CRM_ORG_ID",
    passwordCredentialName: "NEON_CRM_API_KEY",
  },
  operations: NEON_CRM_OPERATIONS,
  health: { operationId: "get_properties_current_system_user" },
};
