export type PlutioOperation = {
  id: string;
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
};

export const PLUTIO_OPERATIONS = [
  {
    id: "archive-bulk-delete-archive",
    method: "DELETE",
    path: "/archive/bulk",
  },
  { id: "archive-delete-archive", method: "DELETE", path: "/archive" },
  { id: "archive-get-archive", method: "GET", path: "/archive" },
  { id: "block-create-block", method: "POST", path: "/blocks" },
  {
    id: "block-create-block-preset",
    method: "POST",
    path: "/blocks/create-preset",
  },
  { id: "block-delete-block", method: "DELETE", path: "/blocks" },
  { id: "block-get-block", method: "GET", path: "/blocks" },
  { id: "block-update-block", method: "PUT", path: "/blocks" },
  { id: "blocks-group-get-section", method: "GET", path: "/block-groups" },
  { id: "blocks-group-update-section", method: "PUT", path: "/block-groups" },
  { id: "business-create-workspace", method: "POST", path: "/businesses" },
  { id: "business-get-workspace", method: "GET", path: "/businesses" },
  { id: "business-update-workspace", method: "PUT", path: "/businesses" },
  {
    id: "canned-response-create-snippet",
    method: "POST",
    path: "/canned-responses",
  },
  {
    id: "canned-response-delete-snippet",
    method: "DELETE",
    path: "/canned-responses",
  },
  {
    id: "canned-response-get-snippet",
    method: "GET",
    path: "/canned-responses",
  },
  {
    id: "canned-response-update-snippet",
    method: "PUT",
    path: "/canned-responses",
  },
  { id: "category-create-category", method: "POST", path: "/categories" },
  { id: "category-delete-category", method: "DELETE", path: "/categories" },
  { id: "category-get-category", method: "GET", path: "/categories" },
  { id: "category-update-category", method: "PUT", path: "/categories" },
  { id: "comment-create-comment", method: "POST", path: "/comments" },
  { id: "comment-delete-comment", method: "DELETE", path: "/comments" },
  { id: "comment-get-comment", method: "GET", path: "/comments" },
  { id: "comment-update-comment", method: "PUT", path: "/comments" },
  {
    id: "company-bulk-delete-company",
    method: "DELETE",
    path: "/companies/bulk",
  },
  { id: "company-bulk-update-company", method: "PUT", path: "/companies/bulk" },
  { id: "company-create-company", method: "POST", path: "/companies" },
  { id: "company-delete-company", method: "DELETE", path: "/companies" },
  { id: "company-get-company", method: "GET", path: "/companies" },
  { id: "company-update-company", method: "PUT", path: "/companies" },
  {
    id: "contract-archive-contract",
    method: "POST",
    path: "/contracts/archive",
  },
  {
    id: "contract-bulk-archive-contract",
    method: "POST",
    path: "/contracts/bulk/archive",
  },
  {
    id: "contract-bulk-delete-contract",
    method: "DELETE",
    path: "/contracts/bulk",
  },
  {
    id: "contract-bulk-update-contract",
    method: "PUT",
    path: "/contracts/bulk",
  },
  { id: "contract-create-contract", method: "POST", path: "/contracts" },
  { id: "contract-delete-contract", method: "DELETE", path: "/contracts" },
  { id: "contract-email-contract", method: "POST", path: "/contracts/email" },
  { id: "contract-get-contract", method: "GET", path: "/contracts" },
  { id: "contract-update-contract", method: "PUT", path: "/contracts" },
  {
    id: "conversation-create-conversation",
    method: "POST",
    path: "/conversations",
  },
  {
    id: "conversation-delete-conversation",
    method: "DELETE",
    path: "/conversations",
  },
  {
    id: "conversation-get-conversation",
    method: "GET",
    path: "/conversations",
  },
  {
    id: "conversation-update-conversation",
    method: "PUT",
    path: "/conversations",
  },
  {
    id: "custom-field-add-custom-field-to-entity",
    method: "POST",
    path: "/custom-fields/entity",
  },
  {
    id: "custom-field-create-custom-field",
    method: "POST",
    path: "/custom-fields",
  },
  {
    id: "custom-field-delete-custom-field",
    method: "DELETE",
    path: "/custom-fields",
  },
  {
    id: "custom-field-get-custom-field",
    method: "GET",
    path: "/custom-fields",
  },
  {
    id: "custom-field-update-custom-field",
    method: "PUT",
    path: "/custom-fields",
  },
  {
    id: "custom-field-update-custom-field-on-entity",
    method: "PUT",
    path: "/custom-fields/entity",
  },
  {
    id: "dashboard-data-get-dashboard-data",
    method: "GET",
    path: "/dashboard-data",
  },
  {
    id: "dashboard-pages-create-dashboard-page",
    method: "POST",
    path: "/dashboard-pages",
  },
  {
    id: "dashboard-pages-delete-dashboard-page",
    method: "DELETE",
    path: "/dashboard-pages",
  },
  {
    id: "dashboard-pages-get-dashboard-page",
    method: "GET",
    path: "/dashboard-pages",
  },
  {
    id: "dashboard-pages-update-dashboard-page",
    method: "PUT",
    path: "/dashboard-pages",
  },
  { id: "dashboards-get-dashboard", method: "GET", path: "/dashboards" },
  { id: "dashboards-update-dashboard", method: "PUT", path: "/dashboards" },
  { id: "event-create-event", method: "POST", path: "/events" },
  { id: "event-delete-event", method: "DELETE", path: "/events" },
  { id: "event-get-event", method: "GET", path: "/events" },
  { id: "event-update-event", method: "PUT", path: "/events" },
  { id: "file-bulk-delete-file", method: "DELETE", path: "/files/bulk" },
  { id: "file-bulk-update-file", method: "PUT", path: "/files/bulk" },
  { id: "file-create-file", method: "POST", path: "/files" },
  { id: "file-delete-file", method: "DELETE", path: "/files" },
  { id: "file-folder-create-folder", method: "POST", path: "/file-folders" },
  { id: "file-folder-delete-folder", method: "DELETE", path: "/file-folders" },
  { id: "file-folder-get-folder", method: "GET", path: "/file-folders" },
  { id: "file-folder-move-folder", method: "POST", path: "/file-folders/move" },
  {
    id: "file-folder-share-folder",
    method: "POST",
    path: "/file-folders/share",
  },
  { id: "file-folder-update-folder", method: "PUT", path: "/file-folders" },
  { id: "file-get-file", method: "GET", path: "/files" },
  { id: "file-move-file", method: "POST", path: "/files/move" },
  { id: "file-share-file", method: "POST", path: "/files/share" },
  { id: "file-update-file", method: "PUT", path: "/files" },
  { id: "form-archive-form", method: "POST", path: "/forms/archive" },
  { id: "form-bulk-archive-form", method: "POST", path: "/forms/bulk/archive" },
  { id: "form-bulk-delete-form", method: "DELETE", path: "/forms/bulk" },
  { id: "form-bulk-update-form", method: "PUT", path: "/forms/bulk" },
  { id: "form-copy-form", method: "POST", path: "/forms/copy" },
  { id: "form-create-form", method: "POST", path: "/forms" },
  { id: "form-delete-form", method: "DELETE", path: "/forms" },
  { id: "form-get-form", method: "GET", path: "/forms" },
  {
    id: "form-response-bulk-delete-form-response",
    method: "DELETE",
    path: "/form-responses/bulk",
  },
  {
    id: "form-response-create-form-response",
    method: "POST",
    path: "/form-responses",
  },
  {
    id: "form-response-delete-form-response",
    method: "DELETE",
    path: "/form-responses",
  },
  {
    id: "form-response-get-form-response",
    method: "GET",
    path: "/form-responses",
  },
  {
    id: "form-response-update-form-response",
    method: "PUT",
    path: "/form-responses",
  },
  { id: "form-update-form", method: "PUT", path: "/forms" },
  { id: "inbox-group-create-messenger", method: "POST", path: "/inbox-groups" },
  {
    id: "inbox-group-delete-messenger",
    method: "DELETE",
    path: "/inbox-groups",
  },
  { id: "inbox-group-get-messenger", method: "GET", path: "/inbox-groups" },
  { id: "inbox-group-update-messenger", method: "PUT", path: "/inbox-groups" },
  { id: "invoice-archive-invoice", method: "POST", path: "/invoices/archive" },
  {
    id: "invoice-bulk-archive-invoice",
    method: "POST",
    path: "/invoices/bulk/archive",
  },
  {
    id: "invoice-bulk-delete-invoice",
    method: "DELETE",
    path: "/invoices/bulk",
  },
  { id: "invoice-bulk-update-invoice", method: "PUT", path: "/invoices/bulk" },
  { id: "invoice-create-invoice", method: "POST", path: "/invoices" },
  { id: "invoice-delete-invoice", method: "DELETE", path: "/invoices" },
  { id: "invoice-email-invoice", method: "POST", path: "/invoices/email" },
  { id: "invoice-get-invoice", method: "GET", path: "/invoices" },
  {
    id: "invoice-record-payment-for-invoice",
    method: "POST",
    path: "/invoices/record-payment",
  },
  {
    id: "invoice-subscription-bulk-delete-subscription",
    method: "DELETE",
    path: "/invoice-subscriptions/bulk",
  },
  {
    id: "invoice-subscription-bulk-update-subscription",
    method: "PUT",
    path: "/invoice-subscriptions/bulk",
  },
  {
    id: "invoice-subscription-create-subscription",
    method: "POST",
    path: "/invoice-subscriptions",
  },
  {
    id: "invoice-subscription-delete-subscription",
    method: "DELETE",
    path: "/invoice-subscriptions",
  },
  {
    id: "invoice-subscription-get-subscription",
    method: "GET",
    path: "/invoice-subscriptions",
  },
  {
    id: "invoice-subscription-update-subscription",
    method: "PUT",
    path: "/invoice-subscriptions",
  },
  { id: "invoice-update-invoice", method: "PUT", path: "/invoices" },
  { id: "item-create-item", method: "POST", path: "/items" },
  { id: "item-delete-item", method: "DELETE", path: "/items" },
  { id: "item-get-item", method: "GET", path: "/items" },
  { id: "item-update-item", method: "PUT", path: "/items" },
  { id: "note-create-note", method: "POST", path: "/notes" },
  { id: "note-delete-note", method: "DELETE", path: "/notes" },
  { id: "note-get-note", method: "GET", path: "/notes" },
  { id: "note-update-note", method: "PUT", path: "/notes" },
  { id: "person-archive-person", method: "POST", path: "/people/archive" },
  {
    id: "person-bulk-archive-person",
    method: "POST",
    path: "/people/bulk/archive",
  },
  { id: "person-bulk-delete-person", method: "DELETE", path: "/people/bulk" },
  { id: "person-bulk-update-person", method: "PUT", path: "/people/bulk" },
  { id: "person-create-person", method: "POST", path: "/people" },
  { id: "person-delete-person", method: "DELETE", path: "/people" },
  {
    id: "person-get-invitation-code-of-person",
    method: "GET",
    path: "/people/invitation-code",
  },
  { id: "person-get-person", method: "GET", path: "/people" },
  { id: "person-update-person", method: "PUT", path: "/people" },
  { id: "profile-get-profile", method: "GET", path: "/profiles" },
  { id: "project-archive-project", method: "POST", path: "/projects/archive" },
  {
    id: "project-bulk-archive-project",
    method: "POST",
    path: "/projects/bulk/archive",
  },
  {
    id: "project-bulk-delete-project",
    method: "DELETE",
    path: "/projects/bulk",
  },
  { id: "project-bulk-update-project", method: "PUT", path: "/projects/bulk" },
  { id: "project-copy-project", method: "POST", path: "/projects/copy" },
  { id: "project-create-project", method: "POST", path: "/projects" },
  { id: "project-delete-project", method: "DELETE", path: "/projects" },
  { id: "project-get-project", method: "GET", path: "/projects" },
  { id: "project-move-project", method: "POST", path: "/projects/move" },
  { id: "project-update-project", method: "PUT", path: "/projects" },
  {
    id: "proposal-archive-proposal",
    method: "POST",
    path: "/proposals/archive",
  },
  {
    id: "proposal-bulk-archive-proposal",
    method: "POST",
    path: "/proposals/bulk/archive",
  },
  {
    id: "proposal-bulk-delete-proposal",
    method: "DELETE",
    path: "/proposals/bulk",
  },
  {
    id: "proposal-bulk-update-proposal",
    method: "PUT",
    path: "/proposals/bulk",
  },
  { id: "proposal-create-proposal", method: "POST", path: "/proposals" },
  { id: "proposal-delete-proposal", method: "DELETE", path: "/proposals" },
  { id: "proposal-email-proposal", method: "POST", path: "/proposals/email" },
  { id: "proposal-get-proposal", method: "GET", path: "/proposals" },
  { id: "proposal-update-proposal", method: "PUT", path: "/proposals" },
  { id: "roles-create-role", method: "POST", path: "/roles" },
  { id: "roles-delete-role", method: "DELETE", path: "/roles" },
  { id: "roles-update-role", method: "PUT", path: "/roles" },
  {
    id: "scheduler-archive-scheduler",
    method: "POST",
    path: "/scheduler/archive",
  },
  {
    id: "scheduler-bulk-archive-scheduler",
    method: "POST",
    path: "/scheduler/bulk/archive",
  },
  {
    id: "scheduler-bulk-delete-scheduler",
    method: "DELETE",
    path: "/scheduler/bulk",
  },
  {
    id: "scheduler-bulk-update-scheduler",
    method: "PUT",
    path: "/scheduler/bulk",
  },
  { id: "scheduler-copy-scheduler", method: "POST", path: "/scheduler/copy" },
  { id: "scheduler-create-scheduler", method: "POST", path: "/scheduler" },
  { id: "scheduler-delete-scheduler", method: "DELETE", path: "/scheduler" },
  { id: "scheduler-get-scheduler", method: "GET", path: "/scheduler" },
  { id: "scheduler-update-scheduler", method: "PUT", path: "/scheduler" },
  { id: "status-create-status", method: "POST", path: "/statuses" },
  { id: "status-delete-status", method: "DELETE", path: "/statuses" },
  { id: "status-get-status", method: "GET", path: "/statuses" },
  { id: "status-move-status", method: "POST", path: "/statuses/move" },
  { id: "status-update-status", method: "PUT", path: "/statuses" },
  { id: "task-archive-task", method: "POST", path: "/tasks/archive" },
  {
    id: "task-board-archive-task-board",
    method: "POST",
    path: "/task-boards/archive",
  },
  {
    id: "task-board-copy-task-board",
    method: "POST",
    path: "/task-boards/copy",
  },
  { id: "task-board-create-task-board", method: "POST", path: "/task-boards" },
  {
    id: "task-board-delete-task-board",
    method: "DELETE",
    path: "/task-boards",
  },
  { id: "task-board-get-task-board", method: "GET", path: "/task-boards" },
  {
    id: "task-board-move-task-board",
    method: "POST",
    path: "/task-boards/move",
  },
  { id: "task-board-update-task-board", method: "PUT", path: "/task-boards" },
  { id: "task-bulk-archive-task", method: "POST", path: "/tasks/bulk/archive" },
  { id: "task-bulk-delete-task", method: "DELETE", path: "/tasks/bulk" },
  { id: "task-bulk-update-task", method: "PUT", path: "/tasks/bulk" },
  { id: "task-copy-task", method: "POST", path: "/tasks/copy" },
  { id: "task-create-task", method: "POST", path: "/tasks" },
  { id: "task-delete-task", method: "DELETE", path: "/tasks" },
  { id: "task-get-task", method: "GET", path: "/tasks" },
  {
    id: "task-group-archive-task-group",
    method: "POST",
    path: "/task-groups/archive",
  },
  {
    id: "task-group-copy-task-group",
    method: "POST",
    path: "/task-groups/copy",
  },
  { id: "task-group-create-task-group", method: "POST", path: "/task-groups" },
  {
    id: "task-group-delete-task-group",
    method: "DELETE",
    path: "/task-groups",
  },
  { id: "task-group-get-task-group", method: "GET", path: "/task-groups" },
  {
    id: "task-group-move-task-group",
    method: "POST",
    path: "/task-groups/move",
  },
  { id: "task-group-update-task-group", method: "PUT", path: "/task-groups" },
  { id: "task-move-task", method: "POST", path: "/tasks/move" },
  { id: "task-update-task", method: "PUT", path: "/tasks" },
  { id: "template-create-template", method: "POST", path: "/templates" },
  { id: "template-delete-template", method: "DELETE", path: "/templates" },
  { id: "template-get-template", method: "GET", path: "/templates" },
  { id: "template-update-template", method: "PUT", path: "/templates" },
  {
    id: "time-track-bulk-delete-time-entry",
    method: "DELETE",
    path: "/time-tracks/bulk",
  },
  {
    id: "time-track-bulk-update-time-entry",
    method: "PUT",
    path: "/time-tracks/bulk",
  },
  { id: "time-track-create-time-entry", method: "POST", path: "/time-tracks" },
  {
    id: "time-track-delete-time-entry",
    method: "DELETE",
    path: "/time-tracks",
  },
  { id: "time-track-get-time-entry", method: "GET", path: "/time-tracks" },
  { id: "time-track-update-time-entry", method: "PUT", path: "/time-tracks" },
  {
    id: "transaction-archive-transaction",
    method: "POST",
    path: "/transactions/archive",
  },
  {
    id: "transaction-bulk-archive-transaction",
    method: "POST",
    path: "/transactions/bulk/archive",
  },
  {
    id: "transaction-bulk-delete-transaction",
    method: "DELETE",
    path: "/transactions/bulk",
  },
  {
    id: "transaction-bulk-update-transaction",
    method: "PUT",
    path: "/transactions/bulk",
  },
  {
    id: "transaction-copy-transaction",
    method: "POST",
    path: "/transactions/copy",
  },
  {
    id: "transaction-create-transaction",
    method: "POST",
    path: "/transactions",
  },
  {
    id: "transaction-delete-transaction",
    method: "DELETE",
    path: "/transactions",
  },
  { id: "transaction-get-transaction", method: "GET", path: "/transactions" },
  {
    id: "transaction-update-transaction",
    method: "PUT",
    path: "/transactions",
  },
  {
    id: "trash-bin-bulk-delete-trash",
    method: "DELETE",
    path: "/trash-bin/bulk",
  },
  {
    id: "trash-bin-delete-all-trash",
    method: "DELETE",
    path: "/trash-bin/all",
  },
  { id: "trash-bin-delete-trash", method: "DELETE", path: "/trash-bin" },
  { id: "trash-bin-get-trash", method: "GET", path: "/trash-bin" },
  { id: "wiki-create-wiki", method: "POST", path: "/wiki" },
  { id: "wiki-delete-wiki", method: "DELETE", path: "/wiki" },
  { id: "wiki-get-wiki", method: "GET", path: "/wiki" },
  { id: "wiki-page-create-wiki-page", method: "POST", path: "/wiki-entities" },
  {
    id: "wiki-page-delete-wiki-page",
    method: "DELETE",
    path: "/wiki-entities",
  },
  { id: "wiki-page-get-wiki-page", method: "GET", path: "/wiki-entities" },
  {
    id: "wiki-page-move-wiki-page",
    method: "POST",
    path: "/wiki-entities/move",
  },
  { id: "wiki-page-update-wiki-page", method: "PUT", path: "/wiki-entities" },
  { id: "wiki-update-wiki", method: "PUT", path: "/wiki" },
] as const satisfies readonly PlutioOperation[];

export const PLUTIO_OPERATION_BY_ID = new Map<string, PlutioOperation>(
  PLUTIO_OPERATIONS.map((operation) => [operation.id, operation]),
);

export const PLUTIO_READ_OPERATION_IDS = PLUTIO_OPERATIONS.filter(
  (operation) => operation.method === "GET",
).map((operation) => operation.id);

export const PLUTIO_MANAGE_OPERATION_IDS = PLUTIO_OPERATIONS.filter(
  (operation) => operation.method !== "GET",
).map((operation) => operation.id);
