import { safeConnectorFetch } from "../safe-connector-fetch";
import { Injectable } from "@nestjs/common";
import type { MarketplaceConnectorSafeErrorCode } from "../types";
type J=Record<string,unknown>; export type ReadwiseCredentials={accessToken:string};
export class ReadwiseApiError extends Error{constructor(public readonly code:MarketplaceConnectorSafeErrorCode,message:string,public readonly statusCode?:number){super(message)}}
@Injectable() export class ReadwiseApiAdapter{
 health(c:ReadwiseCredentials){return this.request(c,{method:"GET",path:"/api/v2/auth/"})}
 listDocuments(c:ReadwiseCredentials,i:J){return this.request(c,{method:"GET",path:"/api/v3/list/",query:{limit:this.clamp(i.limit,25,1,100),pageCursor:i.pageCursor,location:i.location,category:i.category,tag:i.tag,updatedAfter:i.updatedAfter,withHtmlContent:i.withHtmlContent===true}})}
 listHighlights(c:ReadwiseCredentials,i:J){return this.request(c,{method:"GET",path:"/api/v2/highlights/",query:{page_size:this.clamp(i.pageSize,25,1,100),page:this.clamp(i.page,1,1,1000),book_id:i.bookId,updated__gt:i.updatedAfter}})}
 async request(c:ReadwiseCredentials,i:{method:string;path:string;query?:J;json?:J}){if(!c.accessToken)throw new ReadwiseApiError("credential_missing","Readwise access token is required.",401);const method=i.method.toUpperCase();if(!/^(GET|POST|PATCH|DELETE)$/.test(method)||!/^\/api\/v[23]\/[A-Za-z0-9_./-]*$/.test(i.path)||i.path.includes("..")||i.path.includes("//"))throw new ReadwiseApiError("provider_validation_error","Readwise method or path is invalid.");this.reject(i.query);this.reject(i.json);const body=i.json?JSON.stringify(i.json):undefined;if(body&&Buffer.byteLength(body)>1000000)throw new ReadwiseApiError("provider_validation_error","Readwise request exceeds 1 MB.");const url=new URL(`https://readwise.io${i.path}`);this.append(url.searchParams,i.query);const res=await safeConnectorFetch(url,{method,headers:{Authorization:`Token ${c.accessToken}`,Accept:"application/json",...(body?{"Content-Type":"application/json"}:{})},body,redirect:"error",signal:AbortSignal.timeout(20000)});const raw=await res.text();if(raw.length>2000000)throw new ReadwiseApiError("provider_validation_error","Readwise response exceeds 2 MB.");let data:unknown=raw;try{data=raw?JSON.parse(raw):null}catch{}data=this.redact(data);if(!res.ok)throw new ReadwiseApiError(this.code(res.status),this.message(data)??`Readwise returned HTTP ${res.status}.`,res.status);return data}
 private reject(v?:J){const walk=(x:unknown,d=0)=>{if(d>12)throw new ReadwiseApiError("policy_blocked","Readwise request is too deeply nested.");if(Array.isArray(x))return x.forEach(y=>walk(y,d+1));if(!x||typeof x!=="object")return;for(const[k,y]of Object.entries(x as J)){if(/(token|secret|authorization|password|cookie|credential)/i.test(k))throw new ReadwiseApiError("policy_blocked",`Credential-bearing field ${k} is not allowed.`);walk(y,d+1)}};if(v)walk(v)}
 private append(p:URLSearchParams,v?:J){if(!v)return;if(Object.keys(v).length>50)throw new ReadwiseApiError("provider_validation_error","Readwise query has too many fields.");for(const[k,x]of Object.entries(v))if(x!==undefined&&x!==null&&x!=="")p.append(k,String(x))}
 private redact(v:unknown,d=0):unknown{if(d>8)return"[truncated]";if(typeof v==="string")return v.slice(0,500000);if(Array.isArray(v))return v.slice(0,500).map(x=>this.redact(x,d+1));if(!v||typeof v!=="object")return v;return Object.fromEntries(Object.entries(v as J).slice(0,500).map(([k,x])=>[k,/(token|secret|authorization|password|cookie)/i.test(k)?"[redacted]":this.redact(x,d+1)]))}
 private message(v:unknown){const o=v&&typeof v==="object"&&!Array.isArray(v)?v as J:null;return typeof o?.detail==="string"?o.detail.slice(0,500):typeof o?.message==="string"?o.message.slice(0,500):null}private code(s:number):MarketplaceConnectorSafeErrorCode{if(s===401)return"credential_missing";if(s===403)return"insufficient_scope";if(s===429)return"provider_rate_limited";if(s>=500)return"provider_unavailable";return"provider_validation_error"}private clamp(v:unknown,f:number,min:number,max:number){const n=Number(v??f);return Number.isFinite(n)?Math.min(Math.max(Math.floor(n),min),max):f}
}
