import { action, capability } from "../../catalog/marketplace-catalog.types";
import type { MarketplaceConnectorManifest } from "../types";
const reads=[action("readwise_list_documents","List Reader documents","List a bounded Reader page."),action("readwise_list_highlights","List highlights","List a bounded Readwise highlight page.")];
const writes=[action("readwise_full_api","Use full Readwise API","Use any documented Readwise or Reader v2/v3 operation; Safe mode requires approval.")];
export const READWISE_CONNECTOR_MANIFEST: MarketplaceConnectorManifest={
 slug:"readwise",name:"Readwise",connectorType:"native_clawchat",providerDocsUrl:"https://readwise.io/reader_api",providerWebsiteUrl:"https://readwise.io/",
 capabilities:[{...capability("library_read","Read library","List bounded Reader documents and Readwise highlights.",true),platformCapability:"readwise_library_read"},{...capability("full_api","Full Readwise API","Use the complete documented Reader and Readwise v2/v3 API authorized by the customer's token.",true),platformCapability:"readwise_full_api"}],
 auth:{type:"api_key",credentialSchema:[{name:"READWISE_ACCESS_TOKEN",label:"Readwise access token",required:true,secret:true,storedIn:"encrypted_secret",requiredForAuthTypes:["api_key"],helpText:"Create your token at readwise.io/access_token. Railway stores it encrypted and sends it only to readwise.io."}]},
 tools:[
  {name:"readwise.listDocuments",functionName:"readwise_list_documents",aliases:["readwise.listDocuments","readwise_list_documents"],capability:"library_read",platformCapability:"readwise_library_read",action:"read",approvalRequired:false,description:"List a bounded page of Reader documents.",inputSchema:{type:"object",properties:{limit:{type:"number",minimum:1,maximum:100},pageCursor:{type:"string",maxLength:2000},location:{type:"string"},category:{type:"string"},tag:{type:"string"},updatedAfter:{type:"string"},withHtmlContent:{type:"boolean"}},additionalProperties:false}},
  {name:"readwise.listHighlights",functionName:"readwise_list_highlights",aliases:["readwise.listHighlights","readwise_list_highlights"],capability:"library_read",platformCapability:"readwise_library_read",action:"read",approvalRequired:false,description:"List a bounded page of Readwise highlights.",inputSchema:{type:"object",properties:{pageSize:{type:"number",minimum:1,maximum:100},page:{type:"number",minimum:1,maximum:1000},bookId:{type:"number"},updatedAfter:{type:"string"}},additionalProperties:false}},
  {name:"readwise.request",functionName:"readwise_request",aliases:["readwise.request","readwise_request","readwise_full_api"],capability:"full_api",platformCapability:"readwise_full_api",action:"admin",approvalRequired:true,description:"Call any documented readwise.io /api/v2 or /api/v3 endpoint. Absolute URLs and credential-bearing fields are rejected.",inputSchema:{type:"object",properties:{method:{type:"string",enum:["GET","POST","PATCH","DELETE"]},path:{type:"string",pattern:"^/api/v[23]/"},query:{type:"object"},json:{type:"object"},approvalId:{type:"string"}},required:["method","path"],additionalProperties:false}}
 ],
 approvalProfiles:[{id:"readwise_safe",label:"Safe",description:"Bounded library reads run directly; every other API operation requires approval.",defaultSelected:true,allowedActions:reads,approvalRequiredActions:writes,blockedActions:[]},{id:"dangerously_skip_permissions",label:"Dangerously skip permissions",description:"Every selected token-authorized operation runs without Relay per-action approval; ownership, token authority, fixed origin, bounds, audits, and provider rate limits still apply.",defaultSelected:false,allowedActions:[...reads,...writes],approvalRequiredActions:[],blockedActions:[]}],
 healthChecks:[{id:"token_auth",label:"Readwise token validation"}]
};
