// Generated from ShootProof's official Studio API OpenAPI 3.0 document.
// Source: https://developer.shootproof.com/oas/studio.json
// SHA-256: 635c005b078ebe2c7fd7276329eaf17beafcdf4d0048a99aa06113c1eab84f47
// Evidence date: 2026-07-17.

export type ShootProofOperation = {
  id: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  pathParameters: readonly string[];
  queryParameters: readonly string[];
  bodyAllowed: boolean;
};

export const SHOOTPROOF_SOURCE_SHA256 =
  "635c005b078ebe2c7fd7276329eaf17beafcdf4d0048a99aa06113c1eab84f47";

export const SHOOTPROOF_OPERATIONS = [
  {
    id: "addEventCoverPhoto",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/cover-photo",
    summary: "Adds or updates a cover photo on an event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "addInvoiceContract",
    method: "PUT",
    path: "/brand/{brandId}/invoice/{invoiceId}/contract/{contractId}",
    summary: "Adds a linked contract to an invoice.",
    pathParameters: ["brandId", "invoiceId", "contractId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "addInvoiceCreditCard",
    method: "PUT",
    path: "/brand/{brandId}/invoice/{invoiceId}/credit-card",
    summary: "Adds an invoice credit card to an invoice.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchDeleteEventPhotos",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/photo",
    summary: "Deletes a batch of event photos.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchDeleteResourceEvent",
    method: "DELETE",
    path: "/brand/{brandId}/event",
    summary: "Delete a batch of events",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchDeleteResourceEventAlbum",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/album",
    summary: "Delete a batch of event albums.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchDeleteResourceEventAlbumChildren",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/children",
    summary: "Delete a batch of children for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchDeleteResourceEventAlbumPhoto",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/photo",
    summary: "Remove a batch of photos from an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchDeleteResourceInvoiceDiscount",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/{invoiceId}/discount",
    summary: "Remove all discounts from an invoice",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "batchDeleteResourceInvoiceTemplateDiscount",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}/discount",
    summary: "Remove all discounts from an invoice template",
    pathParameters: ["brandId", "invoiceTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "batchDeleteResourcePriceSheetItem",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item",
    summary: "Delete a batch of items on a price sheet",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateEventPhotos",
    method: "PATCH",
    path: "/brand/{brandId}/event/{eventId}/photo",
    summary: "Updates a batch of event photos.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourceEvent",
    method: "PATCH",
    path: "/brand/{brandId}/event",
    summary: "Update a batch of events",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourceEventAlbum",
    method: "PATCH",
    path: "/brand/{brandId}/event/{eventId}/album",
    summary: "Update a batch of albums in an event",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourceEventAlbumChildren",
    method: "PATCH",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/children",
    summary: "Update a batch of children for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourceEventAlbumPhoto",
    method: "PATCH",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/photo",
    summary: "Add a batch of photos to an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourcePriceSheetGroup",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group",
    summary: "Updates a batch of Price Sheet Groups.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourcePriceSheetItem",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item",
    summary: "Update a batch of items on a price sheet",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourcePriceSheetItemImage",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}/image",
    summary: "Updates a batch of price sheet item images.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetItemId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "batchUpdateResourcePriceSheetSubgroup",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}/subgroup",
    summary: "Updates a batch of price sheet subgroups.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetGroupId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "copyResourceCuratedEmailAutomationGroup",
    method: "POST",
    path: "/email/curated-automation-group/{emailAutomationGroupId}",
    summary: "Copy a ShootProof-curated email automation group",
    pathParameters: ["emailAutomationGroupId"],
    queryParameters: ["method"],
    bodyAllowed: false,
  },
  {
    id: "createAlbumDigitalRule",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/digital-rule",
    summary: "Create a digital rule for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createDpa",
    method: "POST",
    path: "/dpa",
    summary: "Creates a new signed Data Processing Addendum document.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createEventCategory",
    method: "POST",
    path: "/brand/{brandId}/event-category",
    summary: "Create a new event category",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createEventContactDefaults",
    method: "POST",
    path: "/brand/{brandId}/event-contact-defaults",
    summary: "Create a set of default settings for event contacts",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createEventContactDigitalRule",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}/digital-rule",
    summary:
      "Creates a new digital rule and associates it with an event contact.",
    pathParameters: ["brandId", "eventId", "contactId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createEventDefaults",
    method: "POST",
    path: "/brand/{brandId}/event-defaults",
    summary: "Create a set of default settings for events",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createEventDefaultsDigitalRule",
    method: "POST",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}/digital-rule",
    summary: "Create a digital rule for a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createEventDigitalRule",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/digital-rule",
    summary: "Creates a new digital rule and associates it with an event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createEventEmail",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/email",
    summary: "Sends an email message to the contact for an event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createFeedback",
    method: "POST",
    path: "/feedback",
    summary: "Creates a new feedback entry.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createInvoice",
    method: "POST",
    path: "/brand/{brandId}/invoice",
    summary: "Creates a new invoice for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createInvoiceEmail",
    method: "POST",
    path: "/brand/{brandId}/invoice/{invoiceId}/email",
    summary: "Sends an email message to the contact for an invoice.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createInvoiceItemTemplate",
    method: "POST",
    path: "/brand/{brandId}/invoice/item-template",
    summary: "Creates a new invoice item template for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createInvoicePayment",
    method: "POST",
    path: "/brand/{brandId}/invoice/{invoiceId}/payment",
    summary: "Creates a payment for an invoice.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createInvoiceRefund",
    method: "POST",
    path: "/brand/{brandId}/invoice/{invoiceId}/refund",
    summary: "Creates a refund for an invoice.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createInvoiceTemplate",
    method: "POST",
    path: "/brand/{brandId}/invoice/template",
    summary: "Creates a new invoice template for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createMobileApp",
    method: "POST",
    path: "/brand/{brandId}/mobile-app",
    summary: "Creates a mobile app.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createOrder",
    method: "POST",
    path: "/brand/{brandId}/order",
    summary: "Creates a new order for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createOrderEmail",
    method: "POST",
    path: "/brand/{brandId}/order/{orderId}/email",
    summary:
      "Sends an email message with the order receipt to a single recipient.",
    pathParameters: ["brandId", "orderId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createOrderItem",
    method: "POST",
    path: "/brand/{brandId}/order/{orderId}/item",
    summary: "Creates a new order item for the current order.",
    pathParameters: ["brandId", "orderId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createOrderLabShipment",
    method: "POST",
    path: "/brand/{brandId}/order/{orderId}/lab-shipment",
    summary: "Creates a new lab shipment or shipments for the current order.",
    pathParameters: ["brandId", "orderId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createPriceSheet",
    method: "POST",
    path: "/price-sheet",
    summary: "Creates a new price sheet object for the current studio.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createPriceSheetBrand",
    method: "POST",
    path: "/brand/{brandId}/price-sheet",
    summary: "Creates a new price sheet object for the current studio.",
    pathParameters: ["brandId"],
    queryParameters: ["duplicatesId"],
    bodyAllowed: true,
  },
  {
    id: "createPriceSheetItemImage",
    method: "POST",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}/image",
    summary: "Creates a new price sheet item image object.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetItemId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceContact",
    method: "POST",
    path: "/brand/{brandId}/contact",
    summary: "Create a contact",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceContactEmail",
    method: "POST",
    path: "/brand/{brandId}/contact/{contactId}/email",
    summary: "Send an email message to a contact",
    pathParameters: ["brandId", "contactId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceContract",
    method: "POST",
    path: "/brand/{brandId}/contract",
    summary: "Create a contract",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceContractEmail",
    method: "POST",
    path: "/brand/{brandId}/contract/{contractId}/email",
    summary: "Send an email message to a contract’s contacts",
    pathParameters: ["brandId", "contractId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceContractTemplate",
    method: "POST",
    path: "/brand/{brandId}/contract/template",
    summary: "Create a contract template",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceEmailAutomationGroup",
    method: "POST",
    path: "/brand/{brandId}/email/automation-group",
    summary: "Create an email automation group",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceEvent",
    method: "POST",
    path: "/brand/{brandId}/event",
    summary: "Create an event",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceEventAlbum",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/album",
    summary: "Create a new album in an event",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceEventAlbumZipBundle",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/zip-bundle",
    summary: "Create a new zip bundle for an album's photos.",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceEventPhoto",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/photo",
    summary: "Creates a new photo within the event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceEventPhotoUploadPolicy",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/photo/upload-policy",
    summary: "Generates a photo upload policy for the event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "createResourceEventQrCode",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/qr-code",
    summary: "Create a new QR Code for a Volume event",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceEventZipBundle",
    method: "POST",
    path: "/brand/{brandId}/event/{eventId}/zip-bundle",
    summary: "Create a new zip bundle link for event photos.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceInvoiceDiscount",
    method: "POST",
    path: "/brand/{brandId}/invoice/{invoiceId}/discount",
    summary: "Apply a discount to an invoice",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceInvoiceDiscountTemplate",
    method: "POST",
    path: "/brand/{brandId}/invoice/discount-template",
    summary: "Create an invoice discount template",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceInvoiceTemplateDiscount",
    method: "POST",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}/discount",
    summary: "Apply a discount to an invoice template",
    pathParameters: ["brandId", "invoiceTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceMeMfa",
    method: "POST",
    path: "/me/mfa/{mfaType}",
    summary: "Configures MFA for the authenticated user",
    pathParameters: ["mfaType"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceMeMfaCode",
    method: "POST",
    path: "/me/mfa/code",
    summary:
      "Sends a code to the authenticated user based on their MFA configuration",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "createResourcePlaylist",
    method: "POST",
    path: "/playlist",
    summary: "Creates a new playlist for the studio.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourcePriceSheetGroup",
    method: "POST",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group",
    summary: "Create a Price Sheet Group",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourcePriceSheetItem",
    method: "POST",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item",
    summary: "Create an item on a price sheet",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourcePriceSheetShippingOption",
    method: "POST",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/shipping-option",
    summary: "Create a Price Sheet Shipping Option",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourcePriceSheetSubgroup",
    method: "POST",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}/subgroup",
    summary: "Create a price sheet subgroup",
    pathParameters: ["brandId", "priceSheetId", "priceSheetGroupId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceReferralEmail",
    method: "POST",
    path: "/referral/email",
    summary: "Send an email message to refer others to ShootProof",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceShorturl",
    method: "POST",
    path: "/shorturl",
    summary: "Shorten a URL for social sharing",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "createResourceSignature",
    method: "POST",
    path: "/signature",
    summary: "Create a signature",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "deleteAlbumDigitalRule",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/digital-rule/{digitalRuleId}",
    summary: "Delete a digital rule from album",
    pathParameters: ["brandId", "eventId", "eventAlbumId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteBrandHomepageAboutImage",
    method: "DELETE",
    path: "/brand/{brandId}/homepage/about-image",
    summary: "Delete the About image for the brand homepage",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteDigitalRule",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/digital-rule/{digitalRuleId}",
    summary: "Removes digital rule from event",
    pathParameters: ["brandId", "eventId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventCategory",
    method: "DELETE",
    path: "/brand/{brandId}/event-category/{eventCategoryId}",
    summary: "Delete an event category",
    pathParameters: ["brandId", "eventCategoryId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventContact",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}",
    summary: "Removes an event contact.",
    pathParameters: ["brandId", "eventId", "contactId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventContactDefaults",
    method: "DELETE",
    path: "/brand/{brandId}/event-contact-defaults/{eventContactDefaultsId}",
    summary: "Delete a set of default settings for event contacts",
    pathParameters: ["brandId", "eventContactDefaultsId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventContactDigitalRule",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}/digital-rule/{digitalRuleId}",
    summary: "Removes digital rule from event contact.",
    pathParameters: ["brandId", "eventId", "contactId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventCoverPhoto",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/cover-photo",
    summary: "Deletes a cover photo from an event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventDefaultDigitalRule",
    method: "DELETE",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}/digital-rule/{digitalRuleId}",
    summary: "Delete a digital rule for a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventDefaults",
    method: "DELETE",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}",
    summary: "Delete a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteEventPhoto",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/photo/{eventPhotoId}",
    summary: "Removes an event photo.",
    pathParameters: ["brandId", "eventId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteInvoice",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/{invoiceId}",
    summary: "Removes an invoice.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteInvoiceContract",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/{invoiceId}/contract/{contractId}",
    summary: "Deletes a linked contract from a invoice.",
    pathParameters: ["brandId", "invoiceId", "contractId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteInvoiceCreditCard",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/{invoiceId}/credit-card",
    summary: "Removes an invoice credit card.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteInvoiceItemTemplate",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/item-template/{invoiceItemTemplateId}",
    summary: "Removes an invoice item template.",
    pathParameters: ["brandId", "invoiceItemTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteInvoiceTemplate",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}",
    summary: "Removes an invoice template.",
    pathParameters: ["brandId", "invoiceTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteOrder",
    method: "DELETE",
    path: "/brand/{brandId}/order/{orderId}",
    summary: "Removes an order.",
    pathParameters: ["brandId", "orderId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteOrderItem",
    method: "DELETE",
    path: "/brand/{brandId}/order/{orderId}/item/{orderItemId}",
    summary: "Removes an order item.",
    pathParameters: ["brandId", "orderId", "orderItemId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deletePriceSheet",
    method: "DELETE",
    path: "/price-sheet/{priceSheetId}",
    summary: "Removes a single price sheet object from the studio.",
    pathParameters: ["priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deletePriceSheetBrand",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}",
    summary: "Removes a single price sheet object from the studio.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deletePriceSheetItemImage",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}/image/{priceSheetItemImageId}",
    summary: "Removes a single price sheet item image object.",
    pathParameters: [
      "brandId",
      "priceSheetId",
      "priceSheetItemId",
      "priceSheetItemImageId",
    ],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceContact",
    method: "DELETE",
    path: "/brand/{brandId}/contact/{contactId}",
    summary: "Delete a contact",
    pathParameters: ["brandId", "contactId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceContract",
    method: "DELETE",
    path: "/brand/{brandId}/contract/{contractId}",
    summary: "Delete a contract",
    pathParameters: ["brandId", "contractId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceContractInvoice",
    method: "DELETE",
    path: "/brand/{brandId}/contract/{contractId}/invoice/{invoiceId}",
    summary: "Remove an invoice from a contract",
    pathParameters: ["brandId", "contractId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceContractTemplate",
    method: "DELETE",
    path: "/brand/{brandId}/contract/template/{contractTemplateId}",
    summary: "Delete a contract template",
    pathParameters: ["brandId", "contractTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceEmailAutomationGroup",
    method: "DELETE",
    path: "/brand/{brandId}/email/automation-group/{emailAutomationGroupId}",
    summary: "Delete an email automation group",
    pathParameters: ["brandId", "emailAutomationGroupId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceEvent",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}",
    summary: "Delete an event",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceEventAlbum",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}",
    summary: "Delete an album from an event",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceEventAlbumCoverPhoto",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/cover-photo",
    summary: "Delete a cover photo from an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceEventAlbumEventPhoto",
    method: "DELETE",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/photo/{eventPhotoId}",
    summary: "Removes an event photo from the album.",
    pathParameters: ["brandId", "eventId", "eventAlbumId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceInvoiceDiscount",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/{invoiceId}/discount/{invoiceDiscountId}",
    summary: "Remove a discount from an invoice",
    pathParameters: ["brandId", "invoiceId", "invoiceDiscountId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceInvoiceDiscountTemplate",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/discount-template/{invoiceDiscountTemplateId}",
    summary: "Delete an invoice discount template",
    pathParameters: ["brandId", "invoiceDiscountTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceInvoiceTemplateDiscount",
    method: "DELETE",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}/discount/{invoiceDiscountId}",
    summary: "Remove a discount from an invoice template",
    pathParameters: ["brandId", "invoiceTemplateId", "invoiceDiscountId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourceMeMfa",
    method: "DELETE",
    path: "/me/mfa/{mfaType}",
    summary: "Remove the authenticated user’s MFA configuration",
    pathParameters: ["mfaType"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "deleteResourceMeSignature",
    method: "DELETE",
    path: "/me/signature",
    summary: "Remove the authenticated user’s signature",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourcePlaylist",
    method: "DELETE",
    path: "/playlist/{playlistId}",
    summary: "Deletes a single playlist by ID.",
    pathParameters: ["playlistId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourcePriceSheetChildItem",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}/child-item/{priceSheetChildItemId}",
    summary: "Remove a child item from a price sheet item",
    pathParameters: [
      "brandId",
      "priceSheetId",
      "priceSheetItemId",
      "priceSheetChildItemId",
    ],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourcePriceSheetGroup",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}",
    summary: "Removes a Price Sheet Group.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetGroupId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourcePriceSheetItem",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}",
    summary: "Remove an item from a price sheet",
    pathParameters: ["brandId", "priceSheetId", "priceSheetItemId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourcePriceSheetShippingOption",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/shipping-option/{priceSheetShippingOptionId}",
    summary: "Removes a Price Sheet Shipping Option.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetShippingOptionId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "deleteResourcePriceSheetSubgroup",
    method: "DELETE",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}/subgroup/{priceSheetSubgroupId}",
    summary:
      "Removes a single price sheet subgroup object from the price sheet.",
    pathParameters: [
      "brandId",
      "priceSheetId",
      "priceSheetGroupId",
      "priceSheetSubgroupId",
    ],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "getDashboardMessage",
    method: "GET",
    path: "/dashboard-message",
    summary: "Returns dashboard messages.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "getOrderItem",
    method: "GET",
    path: "/brand/{brandId}/order/{orderId}/item/{orderItemId}",
    summary: "Lists an order item identified by it id",
    pathParameters: ["brandId", "orderId", "orderItemId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listAlbumDigitalRules",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/digital-rule",
    summary: "List the digital rules for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listBrandAffiliateProgramSummary",
    method: "GET",
    path: "/brand/{brandId}/affiliate-program-summary",
    summary: "Provides affiliate program metrics",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listBrandSalesHistory",
    method: "GET",
    path: "/brand/{brandId}/lab-order-summary",
    summary: "Provides order fulfillment metrics",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listBrandSalesHistory513e942a",
    method: "GET",
    path: "/brand/{brandId}/sales-history",
    summary: "Lists the sales history for the brand",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listDigitalRules",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/digital-rule",
    summary: "Retrieves the digital rules associated with the event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listDpa",
    method: "GET",
    path: "/dpa",
    summary:
      "Returns a resource containing links to view a blank Data Processing Addendum document.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listEventCategories",
    method: "GET",
    path: "/brand/{brandId}/event-category",
    summary: "List a brand’s event categories",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy"],
    bodyAllowed: false,
  },
  {
    id: "listEventContactDefaults",
    method: "GET",
    path: "/brand/{brandId}/event-contact-defaults",
    summary: "List default settings for event contacts",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy"],
    bodyAllowed: false,
  },
  {
    id: "listEventContactDigitalRules",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}/digital-rule",
    summary: "Retrieves the digital rules associated with the event contact.",
    pathParameters: ["brandId", "eventId", "contactId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listEventDefaults",
    method: "GET",
    path: "/brand/{brandId}/event-defaults",
    summary: "List default settings for events",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy", "filterDefault"],
    bodyAllowed: false,
  },
  {
    id: "listEventDefaultsDigitalRules",
    method: "GET",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}/digital-rule",
    summary: "List the digital rules for a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listEventPhotos",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/photo",
    summary: "Lists all event photos for the event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [
      "sortBy",
      "searchName",
      "filterPhotoId",
      "filterEventContactId",
      "filterFavorite",
      "filterHidden",
      "filterPhotoTag",
      "filterShare",
      "filterStatus",
      "filterVisitorEmail",
      "filterNotInAlbums",
    ],
    bodyAllowed: false,
  },
  {
    id: "listGalleryActivitySummary",
    method: "GET",
    path: "/brand/{brandId}/gallery-activity-summary",
    summary: "Lists the activity summary for each gallery.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listInvoiceItemTemplates",
    method: "GET",
    path: "/brand/{brandId}/invoice/item-template",
    summary: "Lists all invoice item templates for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy", "searchNameDescription"],
    bodyAllowed: false,
  },
  {
    id: "listInvoiceTemplates",
    method: "GET",
    path: "/brand/{brandId}/invoice/template",
    summary: "Lists all invoice templates for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy", "searchName", "searchInvoiceItem"],
    bodyAllowed: false,
  },
  {
    id: "listInvoices",
    method: "GET",
    path: "/brand/{brandId}/invoice",
    summary: "Lists all invoices for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: [
      "sortBy",
      "filterContactIds",
      "searchContactInfo",
      "searchInvoiceStatus",
      "searchInvoiceItem",
      "searchCustomInvoiceId",
      "filterExcludeLinkedToContract",
      "filterOrderId",
      "filterHidden",
      "filterInvoiceGrouping",
    ],
    bodyAllowed: false,
  },
  {
    id: "listOrderItems",
    method: "GET",
    path: "/brand/{brandId}/order/{orderId}/item",
    summary: "Lists all order items for the identified order..",
    pathParameters: ["brandId", "orderId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listOrderPayment",
    method: "GET",
    path: "/brand/{brandId}/order/{orderId}/payment",
    summary: "Returns a list of client payments for an order.",
    pathParameters: ["brandId", "orderId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listOrders",
    method: "GET",
    path: "/brand/{brandId}/order",
    summary: "Lists all orders for the current brand.",
    pathParameters: ["brandId"],
    queryParameters: [
      "sortBy",
      "filterOrderId",
      "filterParentOrderId",
      "filterEventId",
      "searchCustomerName",
      "searchCustomerEmail",
      "filterFulfillmentType",
      "filterHasCustomerCrop",
      "filterHasCustomerNotes",
      "filterHasRetouchRequest",
      "filterOrderOrigin",
      "filterCombinedOrder",
      "filterOrderStatus",
      "filterDigitalStatus",
      "filterLabStatus",
      "filterPaymentStatus",
    ],
    bodyAllowed: false,
  },
  {
    id: "listPriceSheetDiscounts",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/discount",
    summary: "Lists all discounts available for a price sheet.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listPriceSheetEvent",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/event",
    summary: "Lists all events which have been linked to the price sheet.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listPriceSheetGroups",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group",
    summary: "Lists all groups for the price sheet.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listPriceSheetShippingOptions",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/shipping-option",
    summary: "Lists all custom shipping options for the price sheet.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listPriceSheetSubgroups",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}/subgroup",
    summary: "Lists all subgroups for the price sheet group.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetGroupId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listPriceSheets",
    method: "GET",
    path: "/price-sheet",
    summary: "Lists all price sheets for the studio.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listPriceSheetsBrand",
    method: "GET",
    path: "/brand/{brandId}/price-sheet",
    summary: "Lists all price sheets for the studio.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceBrand",
    method: "GET",
    path: "/brand",
    summary: "List all of a studio’s brands",
    pathParameters: [],
    queryParameters: ["sortBy"],
    bodyAllowed: false,
  },
  {
    id: "listResourceBrandTheme",
    method: "GET",
    path: "/brand/{brandId}/brand-theme",
    summary: "List all of a brand’s themes",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy"],
    bodyAllowed: false,
  },
  {
    id: "listResourceContact",
    method: "GET",
    path: "/brand/{brandId}/contact",
    summary: "List a brand’s contacts",
    pathParameters: ["brandId"],
    queryParameters: [
      "sortBy",
      "filterAllBrands",
      "filterTag",
      "searchContactInfo",
      "searchEmail",
    ],
    bodyAllowed: false,
  },
  {
    id: "listResourceContactRecentActivity",
    method: "GET",
    path: "/brand/{brandId}/contact/{contactId}/recent-activity",
    summary: "List recent activity for a contact",
    pathParameters: ["brandId", "contactId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceContactReferee",
    method: "GET",
    path: "/brand/{brandId}/contact/referee",
    summary: "List available contacts that may be selected for referral",
    pathParameters: ["brandId"],
    queryParameters: ["searchContactInfo", "forContactId"],
    bodyAllowed: false,
  },
  {
    id: "listResourceContactReferredBy",
    method: "GET",
    path: "/brand/{brandId}/contact/referred-by",
    summary: "Get all contacts for the brand (referral autocompletion)",
    pathParameters: ["brandId"],
    queryParameters: ["searchContactInfo", "forContactId"],
    bodyAllowed: false,
  },
  {
    id: "listResourceContactTag",
    method: "GET",
    path: "/brand/{brandId}/contact/tag",
    summary: "List tags that may be applied to contacts",
    pathParameters: ["brandId"],
    queryParameters: ["searchTagName"],
    bodyAllowed: false,
  },
  {
    id: "listResourceContract",
    method: "GET",
    path: "/brand/{brandId}/contract",
    summary: "List a brand’s contracts",
    pathParameters: ["brandId"],
    queryParameters: [
      "sortBy",
      "searchContractName",
      "filterContactId",
      "searchContactInfo",
      "filterStatus",
      "filterExpirationDateStart",
      "filterExpirationDateEnd",
      "filterExcludeLinkedToInvoice",
    ],
    bodyAllowed: false,
  },
  {
    id: "listResourceContractTemplate",
    method: "GET",
    path: "/brand/{brandId}/contract/template",
    summary: "List a brand’s contract templates",
    pathParameters: ["brandId"],
    queryParameters: [
      "sortBy",
      "searchContractTemplateName",
      "filterCreatedStart",
      "filterExpirationDateEnd",
    ],
    bodyAllowed: false,
  },
  {
    id: "listResourceCuratedEmailAutomationGroup",
    method: "GET",
    path: "/email/curated-automation-group",
    summary: "List ShootProof-curated email automation groups",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceCuratedEmailTemplate",
    method: "GET",
    path: "/email/curated-template",
    summary: "List ShootProof-curated email templates",
    pathParameters: [],
    queryParameters: ["filterCuratedAutomationGroupId"],
    bodyAllowed: false,
  },
  {
    id: "listResourceEmailAutomationGroup",
    method: "GET",
    path: "/brand/{brandId}/email/automation-group",
    summary: "List email automation groups",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy", "filterCuratedUserAutomations"],
    bodyAllowed: false,
  },
  {
    id: "listResourceEmailTemplate",
    method: "GET",
    path: "/brand/{brandId}/email/template",
    summary: "List a brand’s email templates",
    pathParameters: ["brandId"],
    queryParameters: ["filterForEmailAutomation"],
    bodyAllowed: false,
  },
  {
    id: "listResourceEmailTemplateType",
    method: "GET",
    path: "/email/template-type",
    summary: "Get a list of email template types",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceEvent",
    method: "GET",
    path: "/brand/{brandId}/event",
    summary: "List a brand’s events",
    pathParameters: ["brandId"],
    queryParameters: [
      "sortBy",
      "searchName",
      "filterContactId",
      "filterEventAccessLevel",
      "filterEventCategoryId",
      "filterEventDateYear",
      "searchContactInfo",
      "filterEventStatus",
      "filterPreRegistration",
    ],
    bodyAllowed: false,
  },
  {
    id: "listResourceEventAlbum",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album",
    summary: "List an event’s albums",
    pathParameters: ["brandId", "eventId"],
    queryParameters: ["sortBy"],
    bodyAllowed: false,
  },
  {
    id: "listResourceEventAlbumChildren",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/children",
    summary: "List an album’s children",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: ["sortBy"],
    bodyAllowed: false,
  },
  {
    id: "listResourceEventAlbumPasswords",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/passwords",
    summary: "Lists all album passwords for the event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceEventAlbumPhoto",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/photo",
    summary: "List an album’s photo children",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: ["sortBy", "includeDescendants"],
    bodyAllowed: false,
  },
  {
    id: "listResourceEventQrCode",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/qr-code",
    summary: "List an event's QR codes",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceEventVolumeSort",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/volume-sort",
    summary: "List properties for an Event Volume Sort job.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceInvoiceDiscountTemplate",
    method: "GET",
    path: "/brand/{brandId}/invoice/discount-template",
    summary: "List invoice discount templates",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy"],
    bodyAllowed: false,
  },
  {
    id: "listResourceLabCatalog",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog",
    summary: "Lists all lab catalogs for the brand.",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceLabCatalogGroup",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog/{labCatalogId}/group",
    summary: "List all lab catalog groups for the lab catalog.",
    pathParameters: ["brandId", "labCatalogId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceLabCatalogProduct",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog/{labCatalogId}/product",
    summary: "List all lab catalog products for the lab catalog.",
    pathParameters: ["brandId", "labCatalogId"],
    queryParameters: [
      "filterIsBestseller",
      "filterLabCatalogGroupId",
      "filterGroupType",
    ],
    bodyAllowed: false,
  },
  {
    id: "listResourceLabCatalogShippingOption",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog/{labCatalogId}/shipping-option",
    summary: "List all lab catalog shipping options for the lab catalog.",
    pathParameters: ["brandId", "labCatalogId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceLanguage",
    method: "GET",
    path: "/language",
    summary: "Get a list of ShootProof supported languages",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceMusicPlan",
    method: "GET",
    path: "/plan/music",
    summary: "List all music plans available for the current studio.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceNotification",
    method: "GET",
    path: "/brand/{brandId}/notification",
    summary: "List the authenticated user’s notifications",
    pathParameters: ["brandId"],
    queryParameters: ["filterDismissed"],
    bodyAllowed: false,
  },
  {
    id: "listResourcePhotoPlan",
    method: "GET",
    path: "/plan-photo",
    summary: "List all photo plans available for the current studio.",
    pathParameters: [],
    queryParameters: ["filterPromoCode"],
    bodyAllowed: false,
  },
  {
    id: "listResourcePlaylist",
    method: "GET",
    path: "/playlist",
    summary: "Lists all music playlists for the studio.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourcePriceSheetItem",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item",
    summary: "List items on a price sheet",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: ["filterPriceSheetGroupId", "filterPriceSheetSubgroupId"],
    bodyAllowed: false,
  },
  {
    id: "listResourceSong",
    method: "POST",
    path: "/song-search",
    summary: "List all songs",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "listResourceSongArtist",
    method: "GET",
    path: "/song-search/artist",
    summary:
      "List all song artists. Response items can be used as a `filterArtist` value in the `/song-search`",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceSongGet",
    method: "GET",
    path: "/song-search",
    summary: "List all songs",
    pathParameters: [],
    queryParameters: [
      "filterArtist",
      "filterTheme",
      "filterMood",
      "filterPlan",
      "filterStyle",
      "filterInstrument",
      "filterDurationMax",
      "filterDurationMin",
      "filterTempo",
      "filterIsInstrumental",
      "searchTitle",
      "searchArtist",
      "searchLyrics",
    ],
    bodyAllowed: false,
  },
  {
    id: "listResourceSongInstrument",
    method: "GET",
    path: "/song-search/instrument",
    summary:
      "List all song instruments. Response items can be used as a `filterInstrument` value in the `/song-search`.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceSongMood",
    method: "GET",
    path: "/song-search/mood",
    summary:
      "List all song moods. Response items can be used as a `filterMood` value in the `/song-search`",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceSongPlan",
    method: "GET",
    path: "/song-search/plan",
    summary:
      "List all song Music Plans. Response items can be used as a `filterPlan` value in the `/song-search`",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceSongStyle",
    method: "GET",
    path: "/song-search/style",
    summary:
      "List all song styles. Response items can be used as a `filterStyle` value in the `/song-search`",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceSongTheme",
    method: "GET",
    path: "/song-search/theme",
    summary:
      "List all song themes. Response items can be used as a `filterTheme` value in the `/song-search`",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "listResourceSongV2",
    method: "GET",
    path: "/song",
    summary: "Search songs (v2)",
    pathParameters: [],
    queryParameters: [
      "ids",
      "pageIndex",
      "pageRowCount",
      "promptText",
      "artist",
      "durationSecondsMin",
      "durationSecondsMax",
      "playlistId",
      "genreIds",
      "themeIds",
      "moodIds",
      "instrumentIds",
      "vocalTypeIds",
      "minBpm",
      "maxBpm",
      "languageId",
    ],
    bodyAllowed: false,
  },
  {
    id: "listWatermarks",
    method: "GET",
    path: "/brand/{brandId}/watermark",
    summary: "Lists all watermarks for the brand.",
    pathParameters: ["brandId"],
    queryParameters: ["sortBy", "searchName"],
    bodyAllowed: false,
  },
  {
    id: "partialUpdateEventContactDefaults",
    method: "PATCH",
    path: "/brand/{brandId}/event-contact-defaults/{eventContactDefaultsId}",
    summary: "Partially update a set of default settings for event contacts",
    pathParameters: ["brandId", "eventContactDefaultsId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdateEventDefaults",
    method: "PATCH",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}",
    summary: "Partially update a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdateEventPhoto",
    method: "PATCH",
    path: "/brand/{brandId}/event/{eventId}/photo/{eventPhotoId}",
    summary: "Partially updates an event photo.",
    pathParameters: ["brandId", "eventId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdateInvoice",
    method: "PATCH",
    path: "/brand/{brandId}/invoice/{invoiceId}",
    summary: "Partially updates an invoice.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdateInvoiceCreditCard",
    method: "PATCH",
    path: "/brand/{brandId}/invoice/{invoiceId}/credit-card",
    summary: "Partially updates an invoice credit card.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdateInvoiceItemTemplate",
    method: "PATCH",
    path: "/brand/{brandId}/invoice/item-template/{invoiceItemTemplateId}",
    summary: "Partially updates an invoice item template.",
    pathParameters: ["brandId", "invoiceItemTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdateOrderItem",
    method: "PATCH",
    path: "/brand/{brandId}/order/{orderId}/item/{orderItemId}",
    summary: "Partially updates an order item.",
    pathParameters: ["brandId", "orderId", "orderItemId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdatePriceSheetBrand",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}",
    summary: "Partially updates a price sheet.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdatePriceSheetGroup",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}",
    summary: "Partially updates a Price Sheet Group.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetGroupId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdatePriceSheetItemImage",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}/image/{priceSheetItemImageId}",
    summary: "Partially updates a specific price sheet item image object.",
    pathParameters: [
      "brandId",
      "priceSheetId",
      "priceSheetItemId",
      "priceSheetItemImageId",
    ],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "partialUpdatePriceSheetSubgroup",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}/subgroup/{priceSheetSubgroupId}",
    summary: "Partially updates a specific price sheet subgroup object.",
    pathParameters: [
      "brandId",
      "priceSheetId",
      "priceSheetGroupId",
      "priceSheetSubgroupId",
    ],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchBrandHomepage",
    method: "PATCH",
    path: "/brand/{brandId}/homepage",
    summary: "Update homepage settings for the brand",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchEventCategory",
    method: "PATCH",
    path: "/brand/{brandId}/event-category/{eventCategoryId}",
    summary: "Partially update an event category",
    pathParameters: ["brandId", "eventCategoryId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceBrand",
    method: "PATCH",
    path: "/brand/{brandId}",
    summary: "Partially update a brand",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceBrandTheme",
    method: "PATCH",
    path: "/brand/{brandId}/brand-theme/{brandThemeId}",
    summary: "Partially update a brand theme",
    pathParameters: ["brandId", "brandThemeId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceContract",
    method: "PATCH",
    path: "/brand/{brandId}/contract/{contractId}",
    summary: "Partially update a contract",
    pathParameters: ["brandId", "contractId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceContractTemplate",
    method: "PATCH",
    path: "/brand/{brandId}/contract/template/{contractTemplateId}",
    summary: "Partially update a contract template",
    pathParameters: ["brandId", "contractTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceEvent",
    method: "PATCH",
    path: "/brand/{brandId}/event/{eventId}",
    summary: "Partially update an event",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceEventAlbum",
    method: "PATCH",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}",
    summary: "Partially update an album for an event",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceInvoiceDiscount",
    method: "PATCH",
    path: "/brand/{brandId}/invoice/{invoiceId}/discount/{invoiceDiscountId}",
    summary: "Partially update a discount on an invoice",
    pathParameters: ["brandId", "invoiceId", "invoiceDiscountId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceInvoiceDiscountTemplate",
    method: "PATCH",
    path: "/brand/{brandId}/invoice/discount-template/{invoiceDiscountTemplateId}",
    summary: "Partially update an invoice discount template",
    pathParameters: ["brandId", "invoiceDiscountTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceInvoiceTemplateDiscount",
    method: "PATCH",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}/discount/{invoiceDiscountId}",
    summary: "Partially update a discount on an invoice template",
    pathParameters: ["brandId", "invoiceTemplateId", "invoiceDiscountId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceMe",
    method: "PATCH",
    path: "/me",
    summary: "Update user-settable features of the authenticated user",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceMeMfa",
    method: "PATCH",
    path: "/me/mfa/{mfaType}",
    summary: "Activates MFA for the authenticated user",
    pathParameters: ["mfaType"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceMeMfaVerification",
    method: "PATCH",
    path: "/me/mfa/verification",
    summary: "Verifies the authenticated user’s MFA configuration",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceMeMfaVerification7e0c3fbc",
    method: "PATCH",
    path: "/studio",
    summary: "Updates the Studio",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceNotification",
    method: "PATCH",
    path: "/brand/{brandId}/notification/{notificationId}",
    summary: "Partially update a notification",
    pathParameters: ["brandId", "notificationId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceOnboarding",
    method: "PATCH",
    path: "/onboarding",
    summary: "Dismiss some onboarding tasks so they appear complete.",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourcePlaylist",
    method: "PATCH",
    path: "/playlist/{playlistId}",
    summary: "Updates a playlist for the studio.",
    pathParameters: ["playlistId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourcePriceSheetItem",
    method: "PATCH",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}",
    summary: "Partially update an item on a price sheet",
    pathParameters: ["brandId", "priceSheetId", "priceSheetItemId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "patchResourceWelcome",
    method: "PATCH",
    path: "/welcome",
    summary: "Update answers to welcome survey",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "readBrandHomepage",
    method: "GET",
    path: "/brand/{brandId}/homepage",
    summary: "Get homepage settings for the brand",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readDpa",
    method: "GET",
    path: "/dpa/{dpaId}",
    summary: "Returns a signed Data Processing Addendum document by ID.",
    pathParameters: ["dpaId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventAlbumDigitalRule",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/digital-rule/{digitalRuleId}",
    summary: "Get a digital rule for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventArchive",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/archive-cost",
    summary: "Returns archive costs for a single event by ID.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventCategory",
    method: "GET",
    path: "/brand/{brandId}/event-category/{eventCategoryId}",
    summary: "Get an event category",
    pathParameters: ["brandId", "eventCategoryId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventContact",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}",
    summary: "Returns an event's contact by contact ID.",
    pathParameters: ["brandId", "eventId", "contactId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventContactDefaults",
    method: "GET",
    path: "/brand/{brandId}/event-contact-defaults/{eventContactDefaultsId}",
    summary: "Get a set of default settings for event contacts",
    pathParameters: ["brandId", "eventContactDefaultsId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventContactDigitalRule",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}/digital-rule/{digitalRuleId}",
    summary: "Returns a digital rule for an event contact.",
    pathParameters: ["brandId", "eventId", "contactId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventCoverPhoto",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/cover-photo",
    summary: "Returns the cover photo for the event.",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventDefaultDigitalRule",
    method: "GET",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}/digital-rule/{digitalRuleId}",
    summary: "Get a digital rule for a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventDefaults",
    method: "GET",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}",
    summary: "Get a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventDigitalRule",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/digital-rule/{digitalRuleId}",
    summary: "Returns a digital rule for an event.",
    pathParameters: ["brandId", "eventId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventPhoto",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/photo/{eventPhotoId}",
    summary: "Returns a single event photo by ID.",
    pathParameters: ["brandId", "eventId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readEventPhotoOriginal",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/photo/{eventPhotoId}/original",
    summary:
      "Redirects to a temporary URL where photo's original image can be retrieved.",
    pathParameters: ["brandId", "eventId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readInvoice",
    method: "GET",
    path: "/brand/{brandId}/invoice/{invoiceId}",
    summary: "Returns a single invoice by ID.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readInvoiceItemTemplate",
    method: "GET",
    path: "/brand/{brandId}/invoice/item-template/{invoiceItemTemplateId}",
    summary: "Returns a single invoice item template by ID.",
    pathParameters: ["brandId", "invoiceItemTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readInvoiceTemplate",
    method: "GET",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}",
    summary: "Returns a single invoice template by ID.",
    pathParameters: ["brandId", "invoiceTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readLabCatalog",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog/{labCatalogId}",
    summary: "Returns a single lab catalog object by ID.",
    pathParameters: ["brandId", "labCatalogId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readMerchantAccount",
    method: "GET",
    path: "/merchant-account",
    summary: "Get the associated merchant accounts",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readOrder",
    method: "GET",
    path: "/brand/{brandId}/order/{orderId}",
    summary: "Returns a single order by ID.",
    pathParameters: ["brandId", "orderId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPriceSheet",
    method: "GET",
    path: "/price-sheet/{priceSheetId}",
    summary: "Returns a single price sheet object by ID.",
    pathParameters: ["priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPriceSheetBrand",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}",
    summary: "Returns a single price sheet object by ID.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPriceSheetDiscount",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/discount/{priceSheetDiscountId}",
    summary: "Returns a single price sheet discount object by ID.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetDiscountId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPriceSheetGroup",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}",
    summary: "Returns a single Price Sheet Group object by ID.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetGroupId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPriceSheetItemImage",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}/image/{priceSheetItemImageId}",
    summary: "Returns a single price sheet item image object by ID.",
    pathParameters: [
      "brandId",
      "priceSheetId",
      "priceSheetItemId",
      "priceSheetItemImageId",
    ],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPriceSheetShippingOption",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/shipping-option/{priceSheetShippingOptionId}",
    summary: "Returns a single Price Sheet Shipping Option object by ID.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetShippingOptionId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPriceSheetSubgroup",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}/subgroup/{priceSheetSubgroupId}",
    summary: "Returns a single price sheet subgroup object by ID.",
    pathParameters: [
      "brandId",
      "priceSheetId",
      "priceSheetGroupId",
      "priceSheetSubgroupId",
    ],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readPromo",
    method: "GET",
    path: "/promo/{promoCode}",
    summary: "Returns a Promo by promo code.",
    pathParameters: ["promoCode"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceBrand",
    method: "GET",
    path: "/brand/{brandId}",
    summary: "Get a brand",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceBrandTheme",
    method: "GET",
    path: "/brand/{brandId}/brand-theme/{brandThemeId}",
    summary: "Get a brand theme",
    pathParameters: ["brandId", "brandThemeId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceContact",
    method: "GET",
    path: "/brand/{brandId}/contact/{contactId}",
    summary: "Get a contact",
    pathParameters: ["brandId", "contactId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceContract",
    method: "GET",
    path: "/brand/{brandId}/contract/{contractId}",
    summary: "Get a contract",
    pathParameters: ["brandId", "contractId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceContractTemplate",
    method: "GET",
    path: "/brand/{brandId}/contract/template/{contractTemplateId}",
    summary: "Get a contract template",
    pathParameters: ["brandId", "contractTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceCuratedEmailAutomationGroup",
    method: "GET",
    path: "/email/curated-automation-group/{emailAutomationGroupId}",
    summary: "Get a ShootProof-curated email automation group",
    pathParameters: ["emailAutomationGroupId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceCuratedEmailTemplate",
    method: "GET",
    path: "/email/curated-template/{emailTemplateId}",
    summary: "Get a ShootProof-curated email template",
    pathParameters: ["emailTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceEmailAutomationGroup",
    method: "GET",
    path: "/brand/{brandId}/email/automation-group/{emailAutomationGroupId}",
    summary: "Get an email automation group",
    pathParameters: ["brandId", "emailAutomationGroupId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceEmailTemplate",
    method: "GET",
    path: "/brand/{brandId}/email/template/{emailTemplateId}",
    summary: "Get an email template",
    pathParameters: ["brandId", "emailTemplateId"],
    queryParameters: ["resourceType", "resourceId"],
    bodyAllowed: false,
  },
  {
    id: "readResourceEmailTemplateType",
    method: "GET",
    path: "/email/template-type/{emailTemplateTypeId}",
    summary: "Returns an email template type",
    pathParameters: ["emailTemplateTypeId"],
    queryParameters: ["resourceType", "resourceId"],
    bodyAllowed: false,
  },
  {
    id: "readResourceEvent",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}",
    summary: "Get an event",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceEventAlbum",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}",
    summary: "Get an album for an event",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceEventAlbumCoverPhoto",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/cover-photo",
    summary: "Get the cover photo for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceEventAlbumEventPhoto",
    method: "GET",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/photo/{eventPhotoId}",
    summary: "Retrieves an event photo on an event album.",
    pathParameters: ["brandId", "eventId", "eventAlbumId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceInvoiceDiscountTemplate",
    method: "GET",
    path: "/brand/{brandId}/invoice/discount-template/{invoiceDiscountTemplateId}",
    summary: "Get an invoice discount template",
    pathParameters: ["brandId", "invoiceDiscountTemplateId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceLabCatalogGroup",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog/{labCatalogId}/group/{labCatalogGroupId}",
    summary: "Returns a lab catalog group for the lab catalog.",
    pathParameters: ["brandId", "labCatalogId", "labCatalogGroupId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceLabCatalogProduct",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog/{labCatalogId}/product/{labCatalogProductId}",
    summary: "Returns a lab catalog product for the lab catalog.",
    pathParameters: ["brandId", "labCatalogId", "labCatalogProductId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceLabCatalogShippingOption",
    method: "GET",
    path: "/brand/{brandId}/lab-catalog/{labCatalogId}/shipping-option/{labCatalogShippingOptionId}",
    summary: "Returns a lab catalog shipping option for the lab catalog.",
    pathParameters: ["brandId", "labCatalogId", "labCatalogShippingOptionId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceMe",
    method: "GET",
    path: "/me",
    summary: "Get the authenticated user",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceMeMfa",
    method: "GET",
    path: "/me/mfa/{mfaType}",
    summary: "Gets the authenticated user's MFA configuration",
    pathParameters: ["mfaType"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceNotification",
    method: "GET",
    path: "/brand/{brandId}/notification/{notificationId}",
    summary: "Get a notification",
    pathParameters: ["brandId", "notificationId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceOnboarding",
    method: "GET",
    path: "/onboarding",
    summary: "Get the onboarding status of the studio",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourcePlaylist",
    method: "GET",
    path: "/playlist/{playlistId}",
    summary: "Returns a single playlist by ID.",
    pathParameters: ["playlistId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourcePriceSheetItem",
    method: "GET",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}",
    summary: "Get an item from a price sheet",
    pathParameters: ["brandId", "priceSheetId", "priceSheetItemId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceSignature",
    method: "GET",
    path: "/signature/{signatureId}",
    summary: "Get a signature",
    pathParameters: ["signatureId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceSongOptions",
    method: "GET",
    path: "/song/options",
    summary: "Get song filter options (v2)",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readResourceWelcome",
    method: "GET",
    path: "/welcome",
    summary: "Get the welcome survey information",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "readServiceDescription",
    method: "GET",
    path: "/",
    summary: "Get the Studio API service description",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "updateAlbumDigitalRule",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/digital-rule/{digitalRuleId}",
    summary: "Update a digital rule for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateBrandHomepageAboutImage",
    method: "PUT",
    path: "/brand/{brandId}/homepage/about-image",
    summary: "Update the About image for the brand homepage",
    pathParameters: ["brandId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateEventContact",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}",
    summary:
      "Sets the contact for the event and updates their permissions values, if provided.",
    pathParameters: ["brandId", "eventId", "contactId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateEventContactDefaults",
    method: "PUT",
    path: "/brand/{brandId}/event-contact-defaults/{eventContactDefaultsId}",
    summary: "Update a set of default settings for event contacts",
    pathParameters: ["brandId", "eventContactDefaultsId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateEventContactDigitalRule",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/contact/{contactId}/digital-rule/{digitalRuleId}",
    summary: "Fully updates an event contact's digital rule.",
    pathParameters: ["brandId", "eventId", "contactId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateEventDefaultDigitalRule",
    method: "PUT",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}/digital-rule/{digitalRuleId}",
    summary: "Update a digital rule for a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateEventDefaults",
    method: "PUT",
    path: "/brand/{brandId}/event-defaults/{eventDefaultsId}",
    summary: "Update a set of default settings for events",
    pathParameters: ["brandId", "eventDefaultsId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateEventDigitalRule",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/digital-rule/{digitalRuleId}",
    summary: "Fully updates an event's digital rule.",
    pathParameters: ["brandId", "eventId", "digitalRuleId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateEventPhoto",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/photo/{eventPhotoId}",
    summary: "Fully updates an event photo.",
    pathParameters: ["brandId", "eventId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateInvoice",
    method: "PUT",
    path: "/brand/{brandId}/invoice/{invoiceId}",
    summary: "Fully updates an invoice.",
    pathParameters: ["brandId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateInvoiceItemTemplate",
    method: "PUT",
    path: "/brand/{brandId}/invoice/item-template/{invoiceItemTemplateId}",
    summary: "Fully updates an invoice item template.",
    pathParameters: ["brandId", "invoiceItemTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateInvoiceTemplate",
    method: "PUT",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}",
    summary: "Fully updates an invoice template.",
    pathParameters: ["brandId", "invoiceTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateOrderItem",
    method: "PUT",
    path: "/brand/{brandId}/order/{orderId}/item/{orderItemId}",
    summary: "Fully updates an order item.",
    pathParameters: ["brandId", "orderId", "orderItemId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updatePriceSheet",
    method: "PUT",
    path: "/price-sheet/{priceSheetId}",
    summary: "Fully updates a specific studio price sheet.",
    pathParameters: ["priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updatePriceSheetBrand",
    method: "PUT",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}",
    summary: "Fully updates a specific studio price sheet.",
    pathParameters: ["brandId", "priceSheetId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceBrandTheme",
    method: "PUT",
    path: "/brand/{brandId}/brand-theme/{brandThemeId}",
    summary: "Update a brand theme",
    pathParameters: ["brandId", "brandThemeId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceContact",
    method: "PUT",
    path: "/brand/{brandId}/contact/{contactId}",
    summary: "Update a contact",
    pathParameters: ["brandId", "contactId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceContract",
    method: "PUT",
    path: "/brand/{brandId}/contract/{contractId}",
    summary: "Update a contract",
    pathParameters: ["brandId", "contractId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceContractInvoice",
    method: "PUT",
    path: "/brand/{brandId}/contract/{contractId}/invoice/{invoiceId}",
    summary: "Attach an invoice to a contract",
    pathParameters: ["brandId", "contractId", "invoiceId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "updateResourceContractSignature",
    method: "PUT",
    path: "/brand/{brandId}/contract/{contractId}/signature/{signatureId}",
    summary: "Countersign a contract",
    pathParameters: ["brandId", "contractId", "signatureId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "updateResourceContractTemplate",
    method: "PUT",
    path: "/brand/{brandId}/contract/template/{contractTemplateId}",
    summary: "Update a contract template",
    pathParameters: ["brandId", "contractTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceEmailAutomationGroup",
    method: "PUT",
    path: "/brand/{brandId}/email/automation-group/{emailAutomationGroupId}",
    summary: "Update an email automation group",
    pathParameters: ["brandId", "emailAutomationGroupId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceEvent",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}",
    summary: "Update an event",
    pathParameters: ["brandId", "eventId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceEventAlbum",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}",
    summary: "Update an album for an event",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceEventAlbumCoverPhoto",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/cover-photo",
    summary: "Add or update the cover photo for an album",
    pathParameters: ["brandId", "eventId", "eventAlbumId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceEventAlbumEventPhoto",
    method: "PUT",
    path: "/brand/{brandId}/event/{eventId}/album/{eventAlbumId}/photo/{eventPhotoId}",
    summary: "Adds an event photo to the album.",
    pathParameters: ["brandId", "eventId", "eventAlbumId", "eventPhotoId"],
    queryParameters: [],
    bodyAllowed: false,
  },
  {
    id: "updateResourceInvoiceDiscount",
    method: "PUT",
    path: "/brand/{brandId}/invoice/{invoiceId}/discount/{invoiceDiscountId}",
    summary: "Update a discount on an invoice",
    pathParameters: ["brandId", "invoiceId", "invoiceDiscountId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceInvoiceDiscountTemplate",
    method: "PUT",
    path: "/brand/{brandId}/invoice/discount-template/{invoiceDiscountTemplateId}",
    summary: "Update an invoice discount template",
    pathParameters: ["brandId", "invoiceDiscountTemplateId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceInvoiceTemplateDiscount",
    method: "PUT",
    path: "/brand/{brandId}/invoice/template/{invoiceTemplateId}/discount/{invoiceDiscountId}",
    summary: "Update a discount on an invoice template",
    pathParameters: ["brandId", "invoiceTemplateId", "invoiceDiscountId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceMeSignature",
    method: "PUT",
    path: "/me/signature",
    summary: "Add a signature for the authenticated user",
    pathParameters: [],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourceNotification",
    method: "PUT",
    path: "/brand/{brandId}/notification/{notificationId}",
    summary: "Update a notification",
    pathParameters: ["brandId", "notificationId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourcePriceSheetGroup",
    method: "PUT",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/group/{priceSheetGroupId}",
    summary: "Fully updates a specific Price Sheet Group.",
    pathParameters: ["brandId", "priceSheetId", "priceSheetGroupId"],
    queryParameters: [],
    bodyAllowed: true,
  },
  {
    id: "updateResourcePriceSheetItem",
    method: "PUT",
    path: "/brand/{brandId}/price-sheet/{priceSheetId}/item/{priceSheetItemId}",
    summary: "Update an item on a price sheet",
    pathParameters: ["brandId", "priceSheetId", "priceSheetItemId"],
    queryParameters: [],
    bodyAllowed: true,
  },
] as const satisfies readonly ShootProofOperation[];

export const SHOOTPROOF_OPERATION_BY_ID = new Map<string, ShootProofOperation>(
  SHOOTPROOF_OPERATIONS.map((operation) => [operation.id, operation]),
);
export const SHOOTPROOF_READ_OPERATION_IDS = SHOOTPROOF_OPERATIONS.filter(
  (operation) => operation.method === "GET",
).map((operation) => operation.id);
export const SHOOTPROOF_MANAGE_OPERATION_IDS = SHOOTPROOF_OPERATIONS.filter(
  (operation) => operation.method !== "GET",
).map((operation) => operation.id);
