// Generated by scripts/generate-seven-shifts-operation-registry.mjs.
// Source: https://developers.7shifts.com/llms.txt and its official reference OpenAPI fragments.
// SHA-256: a1c6e8daea9bb6150522fc0698d1cb4a163281a5311a120bdc1371c0924f73e5

export type SevenShiftsOperation = {
  id: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  pathParameters: readonly string[];
  queryParameters: readonly string[];
  bodyAllowed: boolean;
};

export const SEVEN_SHIFTS_API_VERSION = "2026-06-01";
export const SEVEN_SHIFTS_SOURCE_SHA256 = "a1c6e8daea9bb6150522fc0698d1cb4a163281a5311a120bdc1371c0924f73e5";

export const SEVEN_SHIFTS_OPERATIONS = [
  {
    "id": "approveTimeOff",
    "method": "POST",
    "path": "/v2/time_off/{time_off_id}/approve",
    "summary": "Approve Time Off Request",
    "pathParameters": [
      "time_off_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "clearTask",
    "method": "POST",
    "path": "/v2/company/{company_id}/task_lists/{list_id}/tasks/{task_id}/clear",
    "summary": "Clear Task",
    "pathParameters": [
      "company_id",
      "list_id",
      "task_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "completeTask",
    "method": "POST",
    "path": "/v2/company/{company_id}/task_lists/{list_id}/tasks/{task_id}/complete",
    "summary": "Complete Task",
    "pathParameters": [
      "company_id",
      "list_id",
      "task_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "CreateAvailability",
    "method": "POST",
    "path": "/v2/company/{company_id}/availabilities",
    "summary": "Create Availability",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createAvailabilityReason",
    "method": "POST",
    "path": "/v2/company/{company_id}/availability_reasons",
    "summary": "Create Availability Reason",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createBulkForecastOverrides",
    "method": "POST",
    "path": "/v2/company/{company_id}/location/{location_id}/forecast_overrides",
    "summary": "Create Daily Projected Forecast Overrides",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createBulkProjectedSalesIntervalOverride",
    "method": "POST",
    "path": "/v2/company/{company_id}/locations/{location_id}/forecast_overrides_intervals",
    "summary": "Create Bulk Forecast Override Intervals",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createCompleteReceipt",
    "method": "POST",
    "path": "/v2/company/{company_id}/receipts",
    "summary": "Create Receipt",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createDepartment",
    "method": "POST",
    "path": "/v2/company/{company_id}/departments",
    "summary": "Create Department",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createDepartmentAssignment",
    "method": "POST",
    "path": "/v2/company/{company_id}/users/{user_id}/department_assignments",
    "summary": "Create Department Assignment",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createEmploymentRecord",
    "method": "POST",
    "path": "/v2/company/{company_id}/employment_records",
    "summary": "Create Employment Record",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createEvent",
    "method": "POST",
    "path": "/v2/company/{company_id}/events",
    "summary": "Create Event",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createExternalUserMapping",
    "method": "POST",
    "path": "/v2/company/{company_id}/location/{location_id}/external_user_mappings",
    "summary": "Create External User Mapping",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createExternalUserMappings",
    "method": "POST",
    "path": "/v2/company/{company_id}/external_user_mappings",
    "summary": "Create External User Mapping",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id"
    ],
    "bodyAllowed": true
  },
  {
    "id": "createForecastOverride",
    "method": "POST",
    "path": "/v2/company/{company_id}/location/{location_id}/forecast_override",
    "summary": "Create Daily Projected Forecast Override",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createForecastOverrides",
    "method": "POST",
    "path": "/v2/batch/company/{company_id}/location/{location_id}/forecast_override",
    "summary": "Create Daily Projected Forecast Overrides",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createLocation",
    "method": "POST",
    "path": "/v2/company/{company_id}/locations",
    "summary": "Create Location",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createLocationAssignment",
    "method": "POST",
    "path": "/v2/company/{company_id}/users/{user_id}/location_assignments",
    "summary": "Create Location Assignments",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createLogBookCategory",
    "method": "POST",
    "path": "/v2/company/{company_id}/log_book_categories",
    "summary": "Create Log Book Category",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createLogBookComment",
    "method": "POST",
    "path": "/v2/company/{company_id}/log_book_comments",
    "summary": "Create Log Book Comment",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createLogBookPost",
    "method": "POST",
    "path": "/v2/company/{company_id}/log_book_posts",
    "summary": "Create Log Book Post",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createManyRoleAssignments",
    "method": "POST",
    "path": "/v2/batch/company/{company_id}/users/role_assignments",
    "summary": "Create Many Role Assignments",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createManyUsers",
    "method": "POST",
    "path": "/v2/company/{company_id}/create_many_users",
    "summary": "Create Many Users",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createProjectedSalesIntervalOverride",
    "method": "POST",
    "path": "/v2/company/{company_id}/locations/{location_id}/forecast_override_interval",
    "summary": "Create Sales Forecast Override Interval",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createRole",
    "method": "POST",
    "path": "/v2/company/{company_id}/roles",
    "summary": "Create Role",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createRoleAssignment",
    "method": "POST",
    "path": "/v2/company/{company_id}/users/{user_id}/role_assignments",
    "summary": "Create Role Assignment",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createTaskListTemplate",
    "method": "POST",
    "path": "/v2/company/{company_id}/task_list_templates",
    "summary": "Create Task List Template",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createTaskTags",
    "method": "POST",
    "path": "/v2/company/{company_id}/task_tags",
    "summary": "Create Task Tags",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createTimeOff",
    "method": "POST",
    "path": "/v2/time_off",
    "summary": "Create Time Off",
    "pathParameters": [],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createUserMappings",
    "method": "POST",
    "path": "/v2/company/{company_id}/location/{location_id}/external_user_mappings_bulk",
    "summary": "Create User External Mappings",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createUserMappingsBulk",
    "method": "POST",
    "path": "/v2/company/{company_id}/external_user_mappings_bulk",
    "summary": "Create User External Mappings",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id"
    ],
    "bodyAllowed": true
  },
  {
    "id": "createUserWages",
    "method": "POST",
    "path": "/v2/company/{company_id}/users/{user_id}/wages",
    "summary": "Create User Wage",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "createWebhook",
    "method": "POST",
    "path": "/v2/company/{company_id}/webhooks",
    "summary": "Create Webhook",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "deactivateUser",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/users/{identifier}",
    "summary": "Deactivate User",
    "pathParameters": [
      "company_id",
      "identifier"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "declineTimeOff",
    "method": "POST",
    "path": "/v2/time_off/{time_off_id}/decline",
    "summary": "Decline Time Off Request",
    "pathParameters": [
      "time_off_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "deleteAvailability",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/availabilities/{availability_id}",
    "summary": "Delete Availability",
    "pathParameters": [
      "company_id",
      "availability_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteAvailabilityReason",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/availability_reasons/{availability_reason_id}",
    "summary": "Delete Availability Reason",
    "pathParameters": [
      "company_id",
      "availability_reason_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteCompanyWebhook",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/webhooks/{webhook_id}",
    "summary": "Delete Webhook",
    "pathParameters": [
      "company_id",
      "webhook_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteDepartment",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/departments/{department_id}",
    "summary": "Delete Department",
    "pathParameters": [
      "company_id",
      "department_id"
    ],
    "queryParameters": [
      "transfer_to"
    ],
    "bodyAllowed": false
  },
  {
    "id": "deleteDepartmentAssignment",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/users/{user_id}/department_assignments/{department_id}",
    "summary": "Delete Department Assignment",
    "pathParameters": [
      "company_id",
      "user_id",
      "department_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteEmploymentRecord",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/employment_record/{uuid}",
    "summary": "Delete Employment Record",
    "pathParameters": [
      "company_id",
      "uuid"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteEvent",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/events/{event_id}",
    "summary": "Delete Event",
    "pathParameters": [
      "company_id",
      "event_id"
    ],
    "queryParameters": [
      "recurrence_target",
      "start_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "deleteExternalUserMapping",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/location/{location_id}/external_user_mappings/{identifier}",
    "summary": "Delete External User Mapping",
    "pathParameters": [
      "company_id",
      "location_id",
      "identifier"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteExternalUserMappings",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/external_user_mappings/{identifier}",
    "summary": "Delete External User Mapping",
    "pathParameters": [
      "company_id",
      "identifier"
    ],
    "queryParameters": [
      "location_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "deleteForecastOverride",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/location/{location_id}/forecast_override",
    "summary": "Sync Daily Projected Forecast Override",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "deleteLocation",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/locations/{location_id}",
    "summary": "Delete Location",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteLocationAssignment",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/users/{user_id}/location_assignments/{location_id}",
    "summary": "Delete Location Assignment",
    "pathParameters": [
      "company_id",
      "user_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteLogBookCategory",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/log_book_categories/{id}",
    "summary": "Delete Log Book Category",
    "pathParameters": [
      "company_id",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteLogBookComment",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/log_book_comments/{id}",
    "summary": "Delete Log Book Comment",
    "pathParameters": [
      "company_id",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteLogBookPost",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/log_book_posts/{id}",
    "summary": "Delete Log Book Post",
    "pathParameters": [
      "company_id",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteRole",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/roles/{role_id}",
    "summary": "Delete Role",
    "pathParameters": [
      "company_id",
      "role_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteRoleAssignment",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/users/{user_id}/role_assignments/{role_id}",
    "summary": "Delete Role Assignment",
    "pathParameters": [
      "company_id",
      "user_id",
      "role_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteShift",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/shifts/{shift_id}",
    "summary": "Delete Shift",
    "pathParameters": [
      "company_id",
      "shift_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteTaskListTemplate",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/task_list_templates/{uuid}",
    "summary": "Delete Task List Template",
    "pathParameters": [
      "company_id",
      "uuid"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteTaskTags",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/task_tags",
    "summary": "Delete Task Tags",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "deleteTimeOff",
    "method": "DELETE",
    "path": "/v2/time_off/{time_off_id}",
    "summary": "Delete Time Off",
    "pathParameters": [
      "time_off_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "deleteTimePunchById",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/time_punches/{time_punch_id}",
    "summary": "Delete Time Punch",
    "pathParameters": [
      "company_id",
      "time_punch_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "editAvailability",
    "method": "PUT",
    "path": "/v2/company/{company_id}/availabilities/{availability_id}",
    "summary": "Update Availability",
    "pathParameters": [
      "company_id",
      "availability_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "editAvailabilityReason",
    "method": "PUT",
    "path": "/v2/company/{company_id}/availability_reasons/{availability_reason_id}",
    "summary": "Update Availability Reason",
    "pathParameters": [
      "company_id",
      "availability_reason_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "editCompanyWebhook",
    "method": "PUT",
    "path": "/v2/company/{company_id}/webhooks/{webhook_id}",
    "summary": "Update Webhook",
    "pathParameters": [
      "company_id",
      "webhook_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "editEvent",
    "method": "PATCH",
    "path": "/v2/company/{company_id}/events/{event_id}",
    "summary": "Update Event",
    "pathParameters": [
      "company_id",
      "event_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "editTaskListTemplate",
    "method": "PUT",
    "path": "/v2/company/{company_id}/task_list_templates/{uuid}",
    "summary": "Update Task List Template",
    "pathParameters": [
      "company_id",
      "uuid"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "editTimeOff",
    "method": "PATCH",
    "path": "/v2/time_off/{time_off_id}",
    "summary": "Update Time Off",
    "pathParameters": [
      "time_off_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "fetchTipPoolManualEntry",
    "method": "GET",
    "path": "/v2/company/{company_id}/tip_pool/{tip_pool_settings_uuid}/manual_entry",
    "summary": "Retrieve Tip Pool Manual Entries",
    "pathParameters": [
      "company_id",
      "tip_pool_settings_uuid"
    ],
    "queryParameters": [
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "findById",
    "method": "GET",
    "path": "/v2/time_off/{time_off_id}",
    "summary": "Retrieve Time Off",
    "pathParameters": [
      "time_off_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getAssignments",
    "method": "GET",
    "path": "/v2/company/{company_id}/users/{user_id}/assignments",
    "summary": "List Assignments",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getAvailabilityById",
    "method": "GET",
    "path": "/v2/company/{company_id}/availabilities/{availability_id}",
    "summary": "Retrieve Availability",
    "pathParameters": [
      "company_id",
      "availability_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getDailySalesAndLabor",
    "method": "GET",
    "path": "/v2/reports/daily_sales_and_labor",
    "summary": "Retrieve Daily Sales and Labor",
    "pathParameters": [],
    "queryParameters": [
      "start_date",
      "end_date",
      "location_id",
      "department_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getEngageOverviewByLocationId",
    "method": "GET",
    "path": "/v2/company/{company_id}/locations/{location_id}/engage_overview",
    "summary": "Retrieve Engagement Overview",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [
      "date",
      "frequency",
      "user_type",
      "permission_template_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getEvent",
    "method": "GET",
    "path": "/v2/company/{company_id}/events/{event_id}",
    "summary": "Retrieve Event",
    "pathParameters": [
      "company_id",
      "event_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getEvents",
    "method": "GET",
    "path": "/v2/company/{company_id}/events",
    "summary": "List Events",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "start_date",
      "end_date",
      "limit",
      "type"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getExternalUserMapping",
    "method": "GET",
    "path": "/v2/company/{company_id}/location/{location_id}/external_user_mappings/{identifier}",
    "summary": "Retrieve User External Mapping",
    "pathParameters": [
      "company_id",
      "location_id",
      "identifier"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getHoursAndWages",
    "method": "GET",
    "path": "/v2/reports/hours_and_wages",
    "summary": "Retrieve Worked Hours and Wages",
    "pathParameters": [],
    "queryParameters": [
      "punches",
      "company_id",
      "from",
      "to",
      "location_id",
      "department_id",
      "role_id",
      "user_id",
      "include_tips",
      "include_qualified_ot"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getLocationById",
    "method": "GET",
    "path": "/v2/company/{company_id}/locations/{location_id}",
    "summary": "Retrieve Location",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getLocationListByCompany",
    "method": "GET",
    "path": "/v2/company/{company_id}/locations",
    "summary": "List Locations",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "modified_since",
      "deleted",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getReceipt",
    "method": "GET",
    "path": "/v2/company/{company_id}/receipts/{receipt_id}",
    "summary": "Retrieve Receipt",
    "pathParameters": [
      "company_id",
      "receipt_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getRoleAssignments",
    "method": "GET",
    "path": "/v2/company/{company_id}/users/{user_id}/role_assignments",
    "summary": "List Role Assignments",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getTaskList",
    "method": "GET",
    "path": "/v2/company/{company_id}/task_lists/{list_id}",
    "summary": "Retrieve Task List",
    "pathParameters": [
      "company_id",
      "list_id"
    ],
    "queryParameters": [
      "user_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getTaskListDailySummary",
    "method": "GET",
    "path": "/v2/company/{company_id}/task_list_daily_summary",
    "summary": "List Task List Daily Summary",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getTaskLists",
    "method": "GET",
    "path": "/v2/company/{company_id}/task_lists",
    "summary": "List Task Lists",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "user_id",
      "location_id",
      "uuid",
      "active_on_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getTaskListTemplate",
    "method": "GET",
    "path": "/v2/company/{company_id}/task_list_templates/{uuid}",
    "summary": "Retrieve Task List Template",
    "pathParameters": [
      "company_id",
      "uuid"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getTaskListTemplates",
    "method": "GET",
    "path": "/v2/company/{company_id}/task_list_templates",
    "summary": "List Task List Templates",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "department_id",
      "role_id",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getTaskManagementSettings",
    "method": "GET",
    "path": "/v2/company/{company_id}/task_management_settings",
    "summary": "Retrieve Task Management Settings",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getTimeClockingPayrollPeriod",
    "method": "GET",
    "path": "/v2/company/{company_id}/payroll_periods/{payroll_period_id}",
    "summary": "Retrieve Payroll Period",
    "pathParameters": [
      "company_id",
      "payroll_period_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getTimeClockingPayrollPeriods",
    "method": "GET",
    "path": "/v2/time_clocking/payroll_periods",
    "summary": "List Payroll Periods",
    "pathParameters": [],
    "queryParameters": [
      "cursor",
      "limit",
      "company_id",
      "include_punches_status"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getTimeOffList",
    "method": "GET",
    "path": "/v2/time_off",
    "summary": "List Time Off",
    "pathParameters": [],
    "queryParameters": [
      "company_id",
      "location_id",
      "user_id",
      "status",
      "category",
      "to_date_gte",
      "sort_by",
      "sort_dir",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getTimeOffSettings",
    "method": "GET",
    "path": "/v2/time_off_settings/{company_id}",
    "summary": "Retrieve Time Off Settings",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getTimePunchById",
    "method": "GET",
    "path": "/v2/company/{company_id}/time_punches/{time_punch_id}",
    "summary": "Retrieve Time Punch",
    "pathParameters": [
      "company_id",
      "time_punch_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getTimePunches",
    "method": "GET",
    "path": "/v2/company/{company_id}/time_punches",
    "summary": "List Time Punches",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "department_id",
      "role_id",
      "user_id",
      "approved",
      "limit",
      "modified_since",
      "clocked_in[lte]",
      "clocked_in[gte]",
      "clocked_out[lte]",
      "clocked_out[gte]",
      "include_deleted",
      "deleted",
      "localize_search_time",
      "flags",
      "employee_approval_statuses",
      "cursor",
      "sort_by",
      "business_date_start",
      "business_date_end"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getTipPoolSettings",
    "method": "GET",
    "path": "/v2/company/{company_id}/tip_pool_settings",
    "summary": "Retrieve Tip Pool Settings",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "getTotalHours",
    "method": "GET",
    "path": "/v2/time_off/total_hours",
    "summary": "Retrieve Time Off Hours",
    "pathParameters": [],
    "queryParameters": [
      "company_id",
      "employee_id",
      "date_start",
      "date_end"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getUser",
    "method": "GET",
    "path": "/v2/company/{company_id}/users/{identifier}",
    "summary": "Retrieve User",
    "pathParameters": [
      "company_id",
      "identifier"
    ],
    "queryParameters": [
      "include_inactive"
    ],
    "bodyAllowed": false
  },
  {
    "id": "getUserWages",
    "method": "GET",
    "path": "/v2/company/{company_id}/users/{user_id}/wages",
    "summary": "List User Wages",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "ListAvailabilities",
    "method": "GET",
    "path": "/v2/company/{company_id}/availabilities",
    "summary": "List Availabilities",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "cursor",
      "limit",
      "location_id",
      "user_id",
      "status",
      "repeating",
      "week_gte",
      "week_to_include_repeating_gte",
      "order_field",
      "order_dir"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listAvailabilityReasons",
    "method": "GET",
    "path": "/v2/company/{company_id}/availability_reasons",
    "summary": "List Availability Reasons",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listCompanies",
    "method": "GET",
    "path": "/v2/companies",
    "summary": "List Companies",
    "pathParameters": [],
    "queryParameters": [
      "modified_since"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listCompanyWebhooks",
    "method": "GET",
    "path": "/v2/company/{company_id}/webhooks",
    "summary": "List Webhooks",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "modified_since",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listDepartmentAssignments",
    "method": "GET",
    "path": "/v2/company/{company_id}/users/{user_id}/department_assignments",
    "summary": "List Department Assignments",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "listDepartments",
    "method": "GET",
    "path": "/v2/company/{company_id}/departments",
    "summary": "List Departments",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "modified_since",
      "cursor",
      "limit",
      "location_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listEmploymentRecord",
    "method": "GET",
    "path": "/v2/company/{company_id}/employment_records",
    "summary": "List Employment Record",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "user_id",
      "user_ids",
      "business_entity_uuid"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listExternalUserMapping",
    "method": "GET",
    "path": "/v2/company/{company_id}/location/{location_id}/external_user_mappings",
    "summary": "List External User Mapping",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [
      "modified_since",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listExternalUserMappings",
    "method": "GET",
    "path": "/v2/company/{company_id}/external_user_mappings",
    "summary": "List External User Mapping",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "user_id",
      "external_user_id",
      "modified_since",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listInactiveReasons",
    "method": "GET",
    "path": "/v2/company/{company_id}/inactive_reasons",
    "summary": "List Inactive Reasons",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "listLocationAssignments",
    "method": "GET",
    "path": "/v2/company/{company_id}/users/{user_id}/location_assignments",
    "summary": "List Location Assignments",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "listLogBookCategories",
    "method": "GET",
    "path": "/v2/company/{company_id}/log_book_categories",
    "summary": "List Log Book Categories",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "listLogBookComments",
    "method": "GET",
    "path": "/v2/company/{company_id}/log_book_comments",
    "summary": "List Log Book Comments",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "log_book_ids"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listLogBookPosts",
    "method": "GET",
    "path": "/v2/company/{company_id}/log_book_posts",
    "summary": "List Log Book Posts",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "log_book_category_id",
      "user_id",
      "date",
      "posted_date_gte",
      "posted_date_lte",
      "message",
      "order_field",
      "order_dir",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listRoles",
    "method": "GET",
    "path": "/v2/company/{company_id}/roles",
    "summary": "List Roles",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "department_id",
      "ids",
      "modified_since",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listSalesReceipts",
    "method": "GET",
    "path": "/v2/company/{company_id}/receipts",
    "summary": "List Receipts",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "receipt_date[gte]",
      "receipt_date[lte]",
      "modified_since",
      "status",
      "external_user_id",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listScheduledShifts",
    "method": "GET",
    "path": "/v2/company/{company_id}/shifts_scheduled/{id}",
    "summary": "List Scheduled Shifts",
    "pathParameters": [
      "company_id",
      "id"
    ],
    "queryParameters": [
      "location_id",
      "grace_period"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listShift",
    "method": "GET",
    "path": "/v2/company/{company_id}/shifts",
    "summary": "List Shifts",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "cursor",
      "limit",
      "location_id",
      "shift_ids",
      "department_id",
      "department_ids",
      "role_id",
      "user_id",
      "start[lte]",
      "start[gte]",
      "end[lte]",
      "end[gte]",
      "deleted",
      "include_deleted",
      "draft",
      "include_draft",
      "open",
      "modified_since",
      "sort_by",
      "sort_dir",
      "consider_tz_in_ranges"
    ],
    "bodyAllowed": false
  },
  {
    "id": "ListShiftFeedback",
    "method": "GET",
    "path": "/v2/company/{company_id}/shift_feedback",
    "summary": "List Shift Feedback",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "start_date",
      "end_date",
      "location_id",
      "user_id",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listUserContacts",
    "method": "GET",
    "path": "/v2/company/{company_id}/contacts",
    "summary": "List User Contacts",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "include_hidden_admins",
      "name",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "listUsersAuthorizedLocations",
    "method": "GET",
    "path": "/v2/company/{company_id}/users/{user_id}/authorized_locations",
    "summary": "List User Authorized Locations",
    "pathParameters": [
      "company_id",
      "user_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "listUsersList",
    "method": "GET",
    "path": "/v2/company/{company_id}/users",
    "summary": "List Users",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "modified_since",
      "location_id",
      "department_id",
      "role_id",
      "status",
      "name",
      "sort_by",
      "cursor",
      "limit"
    ],
    "bodyAllowed": false
  },
  {
    "id": "postShift",
    "method": "POST",
    "path": "/v2/company/{company_id}/shifts",
    "summary": "Create Shift",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "postTimePunch",
    "method": "POST",
    "path": "/v2/company/{company_id}/time_punches",
    "summary": "Create Time Punch",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "postUser",
    "method": "POST",
    "path": "/v2/company/{company_id}/users",
    "summary": "Create User",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "putTimePunch",
    "method": "PUT",
    "path": "/v2/company/{company_id}/time_punches/{time_punch_id}",
    "summary": "Update Time Punch",
    "pathParameters": [
      "company_id",
      "time_punch_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "putUser",
    "method": "PUT",
    "path": "/v2/company/{company_id}/users/{identifier}",
    "summary": "Update User",
    "pathParameters": [
      "company_id",
      "identifier"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "retrieveCompanyLaborSettings",
    "method": "GET",
    "path": "/v2/company/{company_id}/labor_settings",
    "summary": "Retrieve Labor Settings",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "retrieveDailyStats",
    "method": "GET",
    "path": "/v2/company/{company_id}/location/{location_id}/daily_stats",
    "summary": "Retrieve Daily Stats",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [
      "department_id",
      "date",
      "include_future"
    ],
    "bodyAllowed": false
  },
  {
    "id": "retrieveDayPartSettings",
    "method": "GET",
    "path": "/v2/company/{company_id}/day_part/settings",
    "summary": "Retrieve Day Part Settings",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "retrieveDepartment",
    "method": "GET",
    "path": "/v2/company/{company_id}/departments/{department_id}",
    "summary": "Retrieve Department",
    "pathParameters": [
      "company_id",
      "department_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "retrieveExternalUserMapping",
    "method": "GET",
    "path": "/v2/company/{company_id}/external_user_mappings/{identifier}",
    "summary": "Retrieve User External Mapping",
    "pathParameters": [
      "company_id",
      "identifier"
    ],
    "queryParameters": [
      "location_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "retrieveLogBookComment",
    "method": "GET",
    "path": "/v2/company/{company_id}/log_book_comments/{id}",
    "summary": "Retrieve Log Book Comment",
    "pathParameters": [
      "company_id",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "retrieveLogBookPost",
    "method": "GET",
    "path": "/v2/company/{company_id}/log_book_posts/{id}",
    "summary": "Retrieve Log Book Post",
    "pathParameters": [
      "company_id",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "retrieveReceiptsSummary",
    "method": "GET",
    "path": "/v2/company/{company_id}/receipts_summary",
    "summary": "Retrieve Receipts Summary",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "location_id",
      "receipt_date[gte]",
      "receipt_date[lte]",
      "modified_since"
    ],
    "bodyAllowed": false
  },
  {
    "id": "retrieveRole",
    "method": "GET",
    "path": "/v2/company/{company_id}/roles/{role_id}",
    "summary": "Retrieve Role",
    "pathParameters": [
      "company_id",
      "role_id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "retrieveShift",
    "method": "GET",
    "path": "/v2/company/{company_id}/shifts/{shift_id}",
    "summary": "Retrieve Shift",
    "pathParameters": [
      "company_id",
      "shift_id"
    ],
    "queryParameters": [
      "include_deleted"
    ],
    "bodyAllowed": false
  },
  {
    "id": "retrieveTipPoolDetailedReport",
    "method": "GET",
    "path": "/v2/company/{company_id}/locations/{location_id}/tip_pool_detailed_report",
    "summary": "Retrieve Tip Pool Detailed Report",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [
      "tip_pool_uuid",
      "day_part_uuid",
      "start_date",
      "end_date",
      "skip_validation"
    ],
    "bodyAllowed": false
  },
  {
    "id": "retrieveTipPoolSummaryReport",
    "method": "GET",
    "path": "/v2/company/{company_id}/locations/{location_id}/tip_pool_summary_report",
    "summary": "Retrieve Tip Pool Summary Report",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [
      "tip_pool_uuid",
      "day_part_uuid",
      "start_date",
      "end_date"
    ],
    "bodyAllowed": false
  },
  {
    "id": "retrieveUserContact",
    "method": "GET",
    "path": "/v2/company/{company_id}/contacts/{identifier}",
    "summary": "Retrieve User Contact",
    "pathParameters": [
      "company_id",
      "identifier"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "saveTimeOffSettings",
    "method": "POST",
    "path": "/v2/time_off_settings/{company_id}",
    "summary": "Create Time Off Settings",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "saveTipPoolManualEntry",
    "method": "PUT",
    "path": "/v2/company/{company_id}/tip_pool/{tip_pool_settings_uuid}/manual_entry",
    "summary": "Update Tip Pool Manual Entries",
    "pathParameters": [
      "company_id",
      "tip_pool_settings_uuid"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "SyncOverriddenProjectedSalesInterval",
    "method": "DELETE",
    "path": "/v2/company/{company_id}/locations/{location_id}/forecast_override_interval",
    "summary": "Delete Sales Forecast Override Interval",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "testCompanyWebhook",
    "method": "GET",
    "path": "/v2/company/{company_id}/test_webhook",
    "summary": "Test Webhook Notification",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [
      "topic",
      "webhook_id"
    ],
    "bodyAllowed": false
  },
  {
    "id": "updateAvailabilityStatus",
    "method": "PUT",
    "path": "/v2/company/{company_id}/availabilities/{availability_id}/status",
    "summary": "Update Availability Status",
    "pathParameters": [
      "company_id",
      "availability_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateCompany",
    "method": "PATCH",
    "path": "/v2/companies/{id}",
    "summary": "Update Company",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateCompleteReceipt",
    "method": "PUT",
    "path": "/v2/company/{company_id}/receipts/{receipt_id}",
    "summary": "Update Receipt",
    "pathParameters": [
      "company_id",
      "receipt_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateDepartment",
    "method": "PUT",
    "path": "/v2/company/{company_id}/departments/{department_id}",
    "summary": "Update Department",
    "pathParameters": [
      "company_id",
      "department_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateEmploymentRecord",
    "method": "PUT",
    "path": "/v2/company/{company_id}/employment_record/{uuid}",
    "summary": "Update Employment Record",
    "pathParameters": [
      "company_id",
      "uuid"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateExternalUserMapping",
    "method": "PUT",
    "path": "/v2/company/{company_id}/location/{location_id}/external_user_mappings/{identifier}",
    "summary": "Update External User Mapping",
    "pathParameters": [
      "company_id",
      "location_id",
      "identifier"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateExternalUserMappings",
    "method": "PUT",
    "path": "/v2/company/{company_id}/external_user_mappings/{identifier}",
    "summary": "Update External User Mappings",
    "pathParameters": [
      "company_id",
      "identifier"
    ],
    "queryParameters": [
      "location_id"
    ],
    "bodyAllowed": true
  },
  {
    "id": "updateLocation",
    "method": "PUT",
    "path": "/v2/company/{company_id}/locations/{location_id}",
    "summary": "Update Location",
    "pathParameters": [
      "company_id",
      "location_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateLogBookCategory",
    "method": "PATCH",
    "path": "/v2/company/{company_id}/log_book_categories/{id}",
    "summary": "Update Log Book Category",
    "pathParameters": [
      "company_id",
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateRole",
    "method": "PUT",
    "path": "/v2/company/{company_id}/roles/{role_id}",
    "summary": "Update Role",
    "pathParameters": [
      "company_id",
      "role_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateRoleAssignment",
    "method": "PUT",
    "path": "/v2/company/{company_id}/users/{user_id}/role_assignments/{role_id}",
    "summary": "Update Role Assignment",
    "pathParameters": [
      "company_id",
      "user_id",
      "role_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "updateShift",
    "method": "PUT",
    "path": "/v2/company/{company_id}/shifts/{shift_id}",
    "summary": "Update Shift",
    "pathParameters": [
      "company_id",
      "shift_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "upsertBulkEmploymentRecords",
    "method": "POST",
    "path": "/v2/company/{company_id}/bulk_employment_records",
    "summary": "Create Many Employment Records",
    "pathParameters": [
      "company_id"
    ],
    "queryParameters": [],
    "bodyAllowed": true
  },
  {
    "id": "viewCompany",
    "method": "GET",
    "path": "/v2/companies/{id}",
    "summary": "Retrieve Company",
    "pathParameters": [
      "id"
    ],
    "queryParameters": [],
    "bodyAllowed": false
  },
  {
    "id": "whoAmI",
    "method": "GET",
    "path": "/v2/whoami",
    "summary": "Retrieve Identity",
    "pathParameters": [],
    "queryParameters": [],
    "bodyAllowed": false
  }
] as const satisfies readonly SevenShiftsOperation[];

export const SEVEN_SHIFTS_READ_OPERATION_IDS = SEVEN_SHIFTS_OPERATIONS.filter((operation) => operation.method === "GET").map((operation) => operation.id);
export const SEVEN_SHIFTS_MANAGE_OPERATION_IDS = SEVEN_SHIFTS_OPERATIONS.filter((operation) => operation.method !== "GET").map((operation) => operation.id);
export const SEVEN_SHIFTS_OPERATION_BY_ID = new Map<string, SevenShiftsOperation>(SEVEN_SHIFTS_OPERATIONS.map((operation) => [operation.id, operation]));
