import type {
  BoundedRestConnector,
  BoundedRestOperation,
} from "../bounded-rest/bounded-rest-api.adapter";

/** Generated from Little Green Light official dynamic REST documentation on 2026-07-17. */
export const LITTLE_GREEN_LIGHT_OPERATIONS = [
  {
    id: "get_v1_appeals_by_appeal_id_appeal_requests",
    method: "GET",
    path: "/v1/appeals/{appeal_id}/appeal_requests",
    pathParameters: ["appeal_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Appeal Requests for Appeal",
  },
  {
    id: "post_v1_appeals_by_appeal_id_appeal_requests",
    method: "POST",
    path: "/v1/appeals/{appeal_id}/appeal_requests",
    pathParameters: ["appeal_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Appeal Request",
  },
  {
    id: "get_v1_appeal_requests_by_id",
    method: "GET",
    path: "/v1/appeal_requests/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Appeal Request details",
  },
  {
    id: "patch_v1_appeal_requests_by_id",
    method: "PATCH",
    path: "/v1/appeal_requests/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Appeal Request",
  },
  {
    id: "delete_v1_appeal_requests_by_id",
    method: "DELETE",
    path: "/v1/appeal_requests/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Appeal Request",
  },
  {
    id: "post_v1_constituents_by_constituent_id_appeal_requests",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/appeal_requests",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Appeal Request for Constituent",
  },
  {
    id: "get_v1_constituents_by_constituent_id_appeal_requests",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/appeal_requests",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Appeal Requests for Constituent",
  },
  {
    id: "get_v1_appeals",
    method: "GET",
    path: "/v1/appeals",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Appeals",
  },
  {
    id: "post_v1_appeals",
    method: "POST",
    path: "/v1/appeals",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Appeal",
  },
  {
    id: "get_v1_appeals_by_id",
    method: "GET",
    path: "/v1/appeals/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Appeal details",
  },
  {
    id: "patch_v1_appeals_by_id",
    method: "PATCH",
    path: "/v1/appeals/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Appeal",
  },
  {
    id: "delete_v1_appeals_by_id",
    method: "DELETE",
    path: "/v1/appeals/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Appeal",
  },
  {
    id: "get_v1_groups",
    method: "GET",
    path: "/v1/groups",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Groups",
  },
  {
    id: "post_v1_groups",
    method: "POST",
    path: "/v1/groups",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Group",
  },
  {
    id: "get_v1_groups_by_id",
    method: "GET",
    path: "/v1/groups/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Group details",
  },
  {
    id: "patch_v1_groups_by_id",
    method: "PATCH",
    path: "/v1/groups/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Group",
  },
  {
    id: "delete_v1_groups_by_id",
    method: "DELETE",
    path: "/v1/groups/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Group",
  },
  {
    id: "get_v1_group_memberships_by_id",
    method: "GET",
    path: "/v1/group_memberships/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Group Membership details",
  },
  {
    id: "patch_v1_group_memberships_by_id",
    method: "PATCH",
    path: "/v1/group_memberships/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Group Membership",
  },
  {
    id: "delete_v1_group_memberships_by_id",
    method: "DELETE",
    path: "/v1/group_memberships/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Group Membership",
  },
  {
    id: "get_v1_constituents_by_constituent_id_group_memberships",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/group_memberships",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Group Memberships",
  },
  {
    id: "post_v1_constituents_by_constituent_id_group_memberships",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/group_memberships",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Group Membership",
  },
  {
    id: "get_v1_attributes",
    method: "GET",
    path: "/v1/attributes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Custom Attributes",
  },
  {
    id: "get_v1_campaigns",
    method: "GET",
    path: "/v1/campaigns",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Campaigns",
  },
  {
    id: "post_v1_campaigns",
    method: "POST",
    path: "/v1/campaigns",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Campaign",
  },
  {
    id: "get_v1_campaigns_by_id",
    method: "GET",
    path: "/v1/campaigns/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Campaign details",
  },
  {
    id: "patch_v1_campaigns_by_id",
    method: "PATCH",
    path: "/v1/campaigns/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Campaign",
  },
  {
    id: "delete_v1_campaigns_by_id",
    method: "DELETE",
    path: "/v1/campaigns/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Campaign",
  },
  {
    id: "get_v1_categories_by_category_id_keywords",
    method: "GET",
    path: "/v1/categories/{category_id}/keywords",
    pathParameters: ["category_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Keywords",
  },
  {
    id: "post_v1_categories_by_category_id_keywords",
    method: "POST",
    path: "/v1/categories/{category_id}/keywords",
    pathParameters: ["category_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Keyword",
  },
  {
    id: "post_v1_constituents_by_constituent_id_keywords",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/keywords",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Add Keyword",
  },
  {
    id: "delete_v1_constituents_by_constituent_id_keywords_by_id",
    method: "DELETE",
    path: "/v1/constituents/{constituent_id}/keywords/{id}",
    pathParameters: ["id", "constituent_id"],
    mutating: true,
    bodyAllowed: false,
    description: "Remove Keyword",
  },
  {
    id: "get_v1_keywords_by_id",
    method: "GET",
    path: "/v1/keywords/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Keyword details",
  },
  {
    id: "patch_v1_keywords_by_id",
    method: "PATCH",
    path: "/v1/keywords/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Keyword",
  },
  {
    id: "delete_v1_keywords_by_id",
    method: "DELETE",
    path: "/v1/keywords/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Keyword",
  },
  {
    id: "get_v1_categories",
    method: "GET",
    path: "/v1/categories",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Categories for Account",
  },
  {
    id: "post_v1_categories",
    method: "POST",
    path: "/v1/categories",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Category",
  },
  {
    id: "get_v1_categories_by_id",
    method: "GET",
    path: "/v1/categories/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Category details",
  },
  {
    id: "patch_v1_categories_by_id",
    method: "PATCH",
    path: "/v1/categories/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Category",
  },
  {
    id: "delete_v1_categories_by_id",
    method: "DELETE",
    path: "/v1/categories/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Category",
  },
  {
    id: "get_v1_constituents_by_constituent_id_categories",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/categories",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Categories for Constituent",
  },
  {
    id: "get_v1_constituents_search",
    method: "GET",
    path: "/v1/constituents/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Search for Constituents",
  },
  {
    id: "get_v1_constituents",
    method: "GET",
    path: "/v1/constituents",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch all Constituents for an account",
  },
  {
    id: "post_v1_constituents",
    method: "POST",
    path: "/v1/constituents",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Constituent",
  },
  {
    id: "get_v1_constituents_by_id",
    method: "GET",
    path: "/v1/constituents/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Constituent details",
  },
  {
    id: "patch_v1_constituents_by_id",
    method: "PATCH",
    path: "/v1/constituents/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update constituent",
  },
  {
    id: "delete_v1_constituents_by_id",
    method: "DELETE",
    path: "/v1/constituents/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete constituent",
  },
  {
    id: "get_v1_constituents_by_constituent_id_contact_reports",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/contact_reports",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Contact Reports for Constituent",
  },
  {
    id: "post_v1_constituents_by_constituent_id_contact_reports",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/contact_reports",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Contact Report",
  },
  {
    id: "get_v1_contact_reports_search",
    method: "GET",
    path: "/v1/contact_reports/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Search for Contact Reports",
  },
  {
    id: "get_v1_contact_reports",
    method: "GET",
    path: "/v1/contact_reports",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Contact Reports for Account",
  },
  {
    id: "get_v1_contact_reports_by_id",
    method: "GET",
    path: "/v1/contact_reports/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Contact Report details",
  },
  {
    id: "patch_v1_contact_reports_by_id",
    method: "PATCH",
    path: "/v1/contact_reports/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Contact Report",
  },
  {
    id: "delete_v1_contact_reports_by_id",
    method: "DELETE",
    path: "/v1/contact_reports/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Contact Report",
  },
  {
    id: "get_v1_constituents_by_constituent_id_constituent_relationships",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/constituent_relationships",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Constituent Relationships for a Constituent",
  },
  {
    id: "post_v1_constituents_by_constituent_id_constituent_relationships",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/constituent_relationships",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Constituent Relationship",
  },
  {
    id: "get_v1_constituent_relationships_by_id",
    method: "GET",
    path: "/v1/constituent_relationships/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Constituent Relationship details",
  },
  {
    id: "patch_v1_constituent_relationships_by_id",
    method: "PATCH",
    path: "/v1/constituent_relationships/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Constituent Relationship",
  },
  {
    id: "delete_v1_constituent_relationships_by_id",
    method: "DELETE",
    path: "/v1/constituent_relationships/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Constituent Relationship",
  },
  {
    id: "get_v1_constituents_by_constituent_id_email_addresses",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/email_addresses",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Email Addresses",
  },
  {
    id: "post_v1_constituents_by_constituent_id_email_addresses",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/email_addresses",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Email Address",
  },
  {
    id: "get_v1_email_addresses_by_id",
    method: "GET",
    path: "/v1/email_addresses/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Email Address details",
  },
  {
    id: "patch_v1_email_addresses_by_id",
    method: "PATCH",
    path: "/v1/email_addresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Email Address",
  },
  {
    id: "delete_v1_email_addresses_by_id",
    method: "DELETE",
    path: "/v1/email_addresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Email Address",
  },
  {
    id: "get_v1_constituents_by_constituent_id_gifts",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/gifts",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Gifts",
  },
  {
    id: "post_v1_constituents_by_constituent_id_gifts",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/gifts",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Gift",
  },
  {
    id: "get_v1_gifts_search",
    method: "GET",
    path: "/v1/gifts/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Search for Gifts",
  },
  {
    id: "get_v1_gifts_by_id",
    method: "GET",
    path: "/v1/gifts/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Gift details",
  },
  {
    id: "patch_v1_gifts_by_id",
    method: "PATCH",
    path: "/v1/gifts/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Gift",
  },
  {
    id: "delete_v1_gifts_by_id",
    method: "DELETE",
    path: "/v1/gifts/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Gift",
  },
  {
    id: "post_v1_constituents_by_constituent_id_invitations",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/invitations",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Invitation for Constituent",
  },
  {
    id: "get_v1_constituents_by_constituent_id_invitations",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/invitations",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Invitations for Constituent",
  },
  {
    id: "get_v1_events_by_event_id_invitations",
    method: "GET",
    path: "/v1/events/{event_id}/invitations",
    pathParameters: ["event_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Invitations for Event",
  },
  {
    id: "post_v1_events_by_event_id_invitations",
    method: "POST",
    path: "/v1/events/{event_id}/invitations",
    pathParameters: ["event_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Invitation",
  },
  {
    id: "get_v1_invitations_by_id",
    method: "GET",
    path: "/v1/invitations/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Invitation details",
  },
  {
    id: "patch_v1_invitations_by_id",
    method: "PATCH",
    path: "/v1/invitations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Invitation",
  },
  {
    id: "delete_v1_invitations_by_id",
    method: "DELETE",
    path: "/v1/invitations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Invitation",
  },
  {
    id: "get_v1_constituents_by_constituent_id_memberships",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/memberships",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Memberships",
  },
  {
    id: "post_v1_constituents_by_constituent_id_memberships",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/memberships",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Membership",
  },
  {
    id: "get_v1_memberships_by_id",
    method: "GET",
    path: "/v1/memberships/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Membership details",
  },
  {
    id: "patch_v1_memberships_by_id",
    method: "PATCH",
    path: "/v1/memberships/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Membership",
  },
  {
    id: "delete_v1_memberships_by_id",
    method: "DELETE",
    path: "/v1/memberships/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Membership",
  },
  {
    id: "get_v1_constituents_by_constituent_id_notes",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/notes",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Notes for Constituent",
  },
  {
    id: "post_v1_constituents_by_constituent_id_notes",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/notes",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Note",
  },
  {
    id: "get_v1_notes",
    method: "GET",
    path: "/v1/notes",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Notes for Account",
  },
  {
    id: "get_v1_notes_by_id",
    method: "GET",
    path: "/v1/notes/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Note details",
  },
  {
    id: "patch_v1_notes_by_id",
    method: "PATCH",
    path: "/v1/notes/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Note",
  },
  {
    id: "delete_v1_notes_by_id",
    method: "DELETE",
    path: "/v1/notes/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Note",
  },
  {
    id: "get_v1_constituents_by_constituent_id_phone_numbers",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/phone_numbers",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Phone Numbers",
  },
  {
    id: "post_v1_constituents_by_constituent_id_phone_numbers",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/phone_numbers",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Phone Number",
  },
  {
    id: "get_v1_phone_numbers_by_id",
    method: "GET",
    path: "/v1/phone_numbers/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Phone Number details",
  },
  {
    id: "patch_v1_phone_numbers_by_id",
    method: "PATCH",
    path: "/v1/phone_numbers/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Phone Number",
  },
  {
    id: "delete_v1_phone_numbers_by_id",
    method: "DELETE",
    path: "/v1/phone_numbers/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Phone Number",
  },
  {
    id: "get_v1_constituents_by_constituent_id_class_affiliations",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/class_affiliations",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Class Affiliations",
  },
  {
    id: "post_v1_constituents_by_constituent_id_class_affiliations",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/class_affiliations",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Class Affiliation",
  },
  {
    id: "get_v1_class_affiliations_by_id",
    method: "GET",
    path: "/v1/class_affiliations/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Class Affiliation details",
  },
  {
    id: "patch_v1_class_affiliations_by_id",
    method: "PATCH",
    path: "/v1/class_affiliations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Class Affiliation",
  },
  {
    id: "delete_v1_class_affiliations_by_id",
    method: "DELETE",
    path: "/v1/class_affiliations/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Class Affiliation",
  },
  {
    id: "get_v1_constituents_by_constituent_id_street_addresses",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/street_addresses",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Street Addresses",
  },
  {
    id: "post_v1_constituents_by_constituent_id_street_addresses",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/street_addresses",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Street Address",
  },
  {
    id: "get_v1_street_addresses_by_id",
    method: "GET",
    path: "/v1/street_addresses/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Street Address details",
  },
  {
    id: "patch_v1_street_addresses_by_id",
    method: "PATCH",
    path: "/v1/street_addresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Street Address",
  },
  {
    id: "delete_v1_street_addresses_by_id",
    method: "DELETE",
    path: "/v1/street_addresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Street Address",
  },
  {
    id: "get_v1_constituents_by_constituent_id_volunteer_times",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/volunteer_times",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Volunteer Times for Constituent",
  },
  {
    id: "post_v1_constituents_by_constituent_id_volunteer_times",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/volunteer_times",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Volunteer Time",
  },
  {
    id: "get_v1_volunteer_times_search",
    method: "GET",
    path: "/v1/volunteer_times/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Search for Volunteer Times",
  },
  {
    id: "get_v1_volunteer_times",
    method: "GET",
    path: "/v1/volunteer_times",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Volunteer Times for Account",
  },
  {
    id: "get_v1_volunteer_times_by_id",
    method: "GET",
    path: "/v1/volunteer_times/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Volunteer Time details",
  },
  {
    id: "patch_v1_volunteer_times_by_id",
    method: "PATCH",
    path: "/v1/volunteer_times/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Volunteer Time",
  },
  {
    id: "delete_v1_volunteer_times_by_id",
    method: "DELETE",
    path: "/v1/volunteer_times/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Volunteer Time",
  },
  {
    id: "get_v1_constituents_by_constituent_id_web_addresses",
    method: "GET",
    path: "/v1/constituents/{constituent_id}/web_addresses",
    pathParameters: ["constituent_id"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Web Addresses",
  },
  {
    id: "post_v1_constituents_by_constituent_id_web_addresses",
    method: "POST",
    path: "/v1/constituents/{constituent_id}/web_addresses",
    pathParameters: ["constituent_id"],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Web Address",
  },
  {
    id: "get_v1_web_addresses_by_id",
    method: "GET",
    path: "/v1/web_addresses/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Web Address details",
  },
  {
    id: "patch_v1_web_addresses_by_id",
    method: "PATCH",
    path: "/v1/web_addresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Web Address",
  },
  {
    id: "delete_v1_web_addresses_by_id",
    method: "DELETE",
    path: "/v1/web_addresses/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Web Address",
  },
  {
    id: "get_v1_events",
    method: "GET",
    path: "/v1/events",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Events",
  },
  {
    id: "post_v1_events",
    method: "POST",
    path: "/v1/events",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Event",
  },
  {
    id: "get_v1_events_by_id",
    method: "GET",
    path: "/v1/events/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Event details",
  },
  {
    id: "patch_v1_events_by_id",
    method: "PATCH",
    path: "/v1/events/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Event",
  },
  {
    id: "delete_v1_events_by_id",
    method: "DELETE",
    path: "/v1/events/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Event",
  },
  {
    id: "get_v1_funds",
    method: "GET",
    path: "/v1/funds",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Funds",
  },
  {
    id: "post_v1_funds",
    method: "POST",
    path: "/v1/funds",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Fund",
  },
  {
    id: "get_v1_funds_by_id",
    method: "GET",
    path: "/v1/funds/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Fund details",
  },
  {
    id: "patch_v1_funds_by_id",
    method: "PATCH",
    path: "/v1/funds/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Fund",
  },
  {
    id: "delete_v1_funds_by_id",
    method: "DELETE",
    path: "/v1/funds/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Fund",
  },
  {
    id: "get_v1_gift_categories",
    method: "GET",
    path: "/v1/gift_categories",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Gift Categories",
  },
  {
    id: "get_v1_gift_types",
    method: "GET",
    path: "/v1/gift_types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Gift Types",
  },
  {
    id: "get_v1_lists_search",
    method: "GET",
    path: "/v1/lists/search",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Search for Lists",
  },
  {
    id: "get_v1_lists",
    method: "GET",
    path: "/v1/lists",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Lists",
  },
  {
    id: "get_v1_mailing_templates",
    method: "GET",
    path: "/v1/mailing_templates",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Mailing Templates",
  },
  {
    id: "get_v1_membership_levels",
    method: "GET",
    path: "/v1/membership_levels",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Membership Levels",
  },
  {
    id: "post_v1_membership_levels",
    method: "POST",
    path: "/v1/membership_levels",
    pathParameters: [],
    mutating: true,
    bodyAllowed: true,
    description: "Create new Membership Level",
  },
  {
    id: "get_v1_membership_levels_by_id",
    method: "GET",
    path: "/v1/membership_levels/{id}",
    pathParameters: ["id"],
    mutating: false,
    bodyAllowed: false,
    description: "Show Membership Level details",
  },
  {
    id: "patch_v1_membership_levels_by_id",
    method: "PATCH",
    path: "/v1/membership_levels/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: true,
    description: "Update Membership Level",
  },
  {
    id: "delete_v1_membership_levels_by_id",
    method: "DELETE",
    path: "/v1/membership_levels/{id}",
    pathParameters: ["id"],
    mutating: true,
    bodyAllowed: false,
    description: "Delete Membership Level",
  },
  {
    id: "get_v1_payment_types",
    method: "GET",
    path: "/v1/payment_types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Payment Types",
  },
  {
    id: "get_v1_relationship_types",
    method: "GET",
    path: "/v1/relationship_types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Relationship Types",
  },
  {
    id: "get_v1_class_affiliation_types",
    method: "GET",
    path: "/v1/class_affiliation_types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Class Affiliation Types",
  },
  {
    id: "get_v1_types",
    method: "GET",
    path: "/v1/types",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Types for Account",
  },
  {
    id: "get_v1_types_by_type",
    method: "GET",
    path: "/v1/types/{type}",
    pathParameters: ["type"],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Values for Type",
  },
  {
    id: "get_v1_team_members",
    method: "GET",
    path: "/v1/team_members",
    pathParameters: [],
    mutating: false,
    bodyAllowed: false,
    description: "Fetch Team Members",
  },
] as const satisfies readonly BoundedRestOperation[];

export const LITTLE_GREEN_LIGHT_READ_OPERATION_IDS =
  LITTLE_GREEN_LIGHT_OPERATIONS.filter((item) => !item.mutating).map(
    (item) => item.id,
  );
export const LITTLE_GREEN_LIGHT_MANAGE_OPERATION_IDS =
  LITTLE_GREEN_LIGHT_OPERATIONS.filter((item) => item.mutating).map(
    (item) => item.id,
  );

export const LITTLE_GREEN_LIGHT_BOUNDED_REST_CONNECTOR: BoundedRestConnector = {
  slug: "little-green-light",
  name: "Little Green Light",
  baseUrl: "https://api.littlegreenlight.com/api/",
  credentialName: "LITTLE_GREEN_LIGHT_API_KEY",
  authorization: { headerName: "Authorization", prefix: "Bearer " },
  operations: LITTLE_GREEN_LIGHT_OPERATIONS,
  health: { operationId: "get_v1_types" },
};
